### ISSUE TITLE
Custom type containing IFormFile isn't processed by model binder

### ISSUE THREAD

**Issue by svallis** [aspnet/Mvc#5733] opened 2017-01-30 16:04 UTC
I'm trying to extend `IFormFile` with some custom data. I'm using EditorTemplates to render forms and the goal is for a `FileControl` to contain some data which is written out with the form to aid the user in making a file selection. Simplified for brevity:

```
public class FileControl
{
    public IFormFile File { get; set; }
    public string CurrentUrl { get; set; }
}
```

A view model:

```
public class SomeViewModel
{
    public FileControl SomeFile { get; set; }
}
```

And in the EditorTemplate for `FileControl`:

```
<div>@Model.CurrentUrl</div>
<input asp-for="File" />
```

For some reason the model binder is not populating `File` on post - it's null. What seems really strange to me is that if I modify the EditorTemplate to output the `CurrentUrl` as a text box, not only does that property model bind correctly, but it also causes the `File` property to model bind correctly! Is there something wrong within the model binder, or am I missing something obvious?

It feels like the model binder is opting not to process the `FileControl` type entirely when there is only an `IFormFile` in it, but the presence of the `string` property causes both items to be correctly processed.

The EditorTemplate that does bind both properties correctly, but now has a text box that isn't required in it:

```
<input asp-for="File" />
<input asp-for="CurrentUrl" />
```

---

Related to the above, am I taking the right approach here in the first place? I initially looked at implementing the `IFileControl` interface myself, but didn't want to duplicate existing functionality. Trying to derive from `FileControl` itself didn't seem wise either as it's in an internal namespace.

**Comment by Eilon** [comment] 2017-01-30 17:48
Duplicate of https://github.com/aspnet/Mvc/issues/4485.

**Closed by Eilon** 2017-01-30 17:48 UTC
