### ISSUE TITLE
Validation attributes applied to action parameters have no effect

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#1696] opened 2014-12-10 21:10 UTC
This is not a regression from Mvc 5.2. Validation attributes like Range, Regex, Email etc can be applied on method parameters since the attribute allows it. However, parameters aren't used as a source for validation attributes. Consequently, an action such as

``` C#
[HttpGet("/api/department/{id:int}"]
public IActionResult GetDept([Range(0, 100)] int id)
```

would not treat a request to `/api/department/101` as a validation error.

**Comment by tx8821** [comment] 2016-09-18 00:33
Any updates on this topic?

**Comment by rynowak** [comment] 2017-07-18 05:12
We're planning to do this in 2.1. Closing this for now as a dupe of https://github.com/aspnet/Mvc/issues/4603

**Closed by rynowak** 2017-07-18 05:12 UTC
Labels: 0 - Backlog
