### ISSUE TITLE
@Ajax.beginform is missing in MVC 6 

### ISSUE THREAD

**Issue by rahuldhariya01** [aspnet/Mvc#2629] opened 2015-05-29 16:06 UTC
notice that ajax.beginform is missing from MVC 6 , why ?  when I try to write ajax.beginform in a view its seems ajax object is missing. Any help ?

If I write ajax form like below then it works fine but “Onsuccess” event and so many other parameters are missing in it. See below
``` html
 <form asp-controller="PreRegistration" asp-action="Index"  data- ajax="true" 

 data-method="post"  data-ajax-mode="replace" data-ajax-update="#cooldiv">

            <label asp-for="FirstName">FirstName:</label><input asp-for="FirstName" /><br>        

                           <input type="submit" value="Save" />

    </form>
```

**Comment by pranavkm** [comment] 2015-05-29 18:21
Duplicate of https://github.com/aspnet/Mvc/issues/2015

**Closed** 2015-06-03 17:20 UTC
Labels: duplicate
