### ISSUE TITLE
Using page variable in [Route] causes errors

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/Mvc#6800] opened 2017-09-09 00:15 UTC
Moved from https://github.com/aspnet/EntityFrameworkCore/issues/9738 by @isonil

This causes errors:

```C#
[Route("route/{page}")]
public async Task<IActionResult> Index(int page)
{
    return await GetPage(page);
}
````

Errors (which don't even say what's wrong):
```
An unhandled exception occurred while processing the request.

InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Shared/Index.en-US.cshtml
/Views/Shared/Index.en.cshtml
/Views/Shared/Index.cshtml
```

This works fine:
```C#
[Route("route/{page2}")]
public async Task<IActionResult> Index(int page2)
{
    return await GetPage(page2);
}
````

**Comment by rynowak** [comment] 2017-09-11 14:59
@pranavkm is this a duplicate of something we fixed already?

**Comment by Eilon** [comment] 2017-09-11 16:51
Yeah this looks like the reserved `page` token issue, no?

**Comment by pranavkm** [comment] 2017-09-11 17:05
Dup of https://github.com/aspnet/Mvc/issues/6660.

**Closed by pranavkm** 2017-09-11 17:05 UTC
Labels: investigate
