### ISSUE TITLE
Can't create project using VS2015 Community Update 2

### ISSUE THREAD

**Issue by Mr-Binary** [aspnet/Mvc#4771] opened 2016-05-29 22:35 UTC
After install the asp.net core RC2 package for vs2015
Two more options appear in my VS2015-Templates-C#-Web:

- ASP.Net Core Web Application (.NET Core)
- ASP.Net Core Web Application (.NET Framework)

No matter which combination I use (Web Application, Web API, Empty, .Net Core, .Net Framework), 
Create either of them will lead me to such an error:

> 
"The system cannot find the file specified.(Exception from HRESULT:0x80070002)"

How to solve it?

**Comment by ctyar** [comment] 2016-05-30 05:20
duplicate of this?
https://github.com/aspnet/Tooling/issues/540

**Comment by Mr-Binary** [comment] 2016-05-31 04:01
Yes,thanks! @ctyar

**Closed** 2016-05-31 04:01 UTC
