### ISSUE TITLE
DependencyContextJsonReader performance on startup

### ISSUE THREAD

**Issue by Yves57** [aspnet/Mvc#5060] opened 2016-07-22 15:31 UTC
Starting the "MvcSandbox" MVC sample with Kestrel and the Visual Studio Profiler attached (in Release of course).

Here is the top most used functions on my computer.

![image](https://cloud.githubusercontent.com/assets/11701094/17061775/81b24c1c-5030-11e6-9abd-118f7f060ff4.png)

The "deps.json" file loading takes a large part of the startup time.

After analyzing `Microsoft.Extensions.DependencyModel.DependencyContextJsonReader`, I have seen that it uses the Json.Net `JObject.Load()` method.

To compare, I have rewritten the class from scratch by using only the low level `JsonTextReader` class.

For a 330KB file loaded 100 times from a string (to avoid hard disc loading overhead):
- Current implementation: 1557ms
- JsonTextReader implementation: 576ms

**Comment by rynowak** [comment] 2016-07-22 15:42
@Yves57 thanks for providing data! @pakrym was about to start looking at the dependency context, hopefully you two can share some notes.

Would it be possible to upload the .vspx somewhere? I'd like to take a look

**Comment by Yves57** [comment] 2016-07-22 16:08
Maybe I can attach the file to the Github issue (5 MB)? Otherwise I will try with my OneDrive account.
I can give you my implementation source code too (the DependencyContextJsonReader tests from the CLI module are ok).

**Comment by pakrym** [comment] 2016-07-22 16:12
@Yves57 Please open a PR for DependencyContextJsonReader on CLI repo

**Comment by Yves57** [comment] 2016-07-22 16:23
I have tried to get a working CLI solution, but I have several problems specific to this solution (no problem for MVC or FileSystem for example). In particular, the solution does not compile with several mysterious messages "An item with the same key has been already added", an few other problems.

To pass the DependencyContextJsonReader "offical" tests, I had to copy/paste the source code in an other solution. So I cannot be sure that there is no regression otherwise (the code was sometimes tricky to analyze!).

**Comment by rynowak** [comment] 2016-07-22 16:26
If you want to just open a PR on dotnet/CLI, in whatever state the code is in currently, Pavel can take care of the details. We want to be really careful not to introduce regressions in this code.

**Comment by Yves57** [comment] 2016-07-22 16:43
[MvcSandbox.zip](https://github.com/aspnet/Mvc/files/378705/MvcSandbox.zip)

And here is the VSPX.

**Comment by rynowak** [comment] 2016-07-22 18:22
Thanks so much for all of this.

If you're using the VS profiler make sure to turn off "Just My Code" - yes, the profiler has it's own just my code setting
![image](https://cloud.githubusercontent.com/assets/1430011/17066954/4edbc962-4ffe-11e6-83d0-a7da3a24e501.png)

**Show All Code** on the right

This is what I see in the functions window after turning that off:
![image](https://cloud.githubusercontent.com/assets/1430011/17067018/a2c9d686-4ffe-11e6-8fb2-899c5f02ba6e.png)

**Comment by Yves57** [comment] 2016-07-22 20:52
Sorry!
I was surprised too see a so important percentage while my performance tests show about 15ms to load the "deps.json" file.
I propose to improve the performances of 2% of the startup time. Awesome :-).

**Comment by rynowak** [comment] 2016-07-22 20:59
We still definitely care about this :+1: The impact of improving parsing `deps.json` is much larger on sites with more dependencies.

I just wanted to point out a gotcha with the VS profiler.

**Comment by Eilon** [comment] 2016-07-27 20:00
Closing this one because there's a CLI issue for it.

**Closed by Eilon** 2016-07-27 20:00 UTC
Labels: external
