### ISSUE TITLE
View component with optional parameters does not render with tag syntax if the optional parameters are omitted

### ISSUE THREAD

**Issue by nozer** [aspnet/Mvc#6096] opened 2017-04-07 10:29 UTC
Hi

If a view component's InvokeAsync method has optional parameters and if the optional parameters are not specified in the tag,  then the view component won't render. 

For example, given the following `InvokeAsync`:
```
       public async Task<IViewComponentResult> InvokeAsync(
            Question question,
            bool hideComments = false,
            bool hideShare = false)
        {
            
            ViewData["hideComments"] = hideComments;
            ViewData["hideShare"] = hideShare;
           
            return await Task.FromResult(View(question));
        }
```

`@await Component.InvokeAsync("QuestionActions", new {question = Model})` 
and 
`<vc:question-actions question="Model" hide-share="true" hide-comments="true" ></vc:question-actions>`

**will render *but*** 

`<vc:question-actions question="Model"  ></vc:question-actions>` won't render. 

I am using `netcoreapp1.1` and `dotnet info` gives:

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

**Comment by NTaylorMullen** [comment] 2017-04-07 17:18
Duplicate of: https://github.com/aspnet/Mvc/issues/5541

**Closed by NTaylorMullen** 2017-04-07 17:18 UTC
Labels: duplicate
