### ISSUE TITLE
Localize [Required] DataAnnotation

### ISSUE THREAD

**Issue by MateEke** [aspnet/Mvc#8542] opened 2018-10-03 08:45 UTC
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Create a project with this: [https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1#using-one-resource-string-for-multiple-classes](url)

#### Description of the problem:
Translation for `[Required]` annotation doesn't work without providing "ErrorMessage" attribute.
Other DataAnnotation's works properly. 
For example `[EmailAddress]` gets translated with this resx file, without providing "ErrorMessage" attribute to the annotation, but `[Required]` doesn't get translated without providing "ErrorMessage".

```
...
  <data name="The {0} field is required." xml:space="preserve">
    <value>A(z) {0} mező kötelező</value>
    <comment>Required</comment>
  </data>
  <data name="RequiredAttribute_ValidationError" xml:space="preserve">
    <value>A(z) {0} mező kötelező</value>
    <comment>Default Required</comment>
  </data>
  <data name="Invalid username or password!" xml:space="preserve">
    <value>Hibás felhasználónév vagy jelszó!</value>
    <comment>Required</comment>
  </data>
  <data name="The {0} field is not a valid e-mail address." xml:space="preserve">
    <value>Nem megfelelő email formátum.</value>
  </data>
  <data name="The input was not valid." xml:space="preserve">
    <value>Hibás érték.</value>
  </data>
...
```
I have tried this solution from StackOverflow: [https://stackoverflow.com/a/50230263/4690796](url) but the custom `GetAttributeAdapter` function doesn't get called for `[Required]`.

**Comment by mkArtakMSFT** [comment] 2018-10-03 15:46
Thanks for contacting us, @MateEke.
@ryanbrandenburg, can you please look into this? Thanks!

**Comment by ryanbrandenburg** [comment] 2018-10-03 21:31
This is a dupe of aspnet/Mvc#6696. Voicing your opinions there will help us see all the community feedback in one place.

**Closed by ryanbrandenburg** 2018-10-03 21:31 UTC
Labels: investigate
