### ISSUE TITLE
ApiDescriptionProvider doesn't handle task-likes

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#7525] opened 2018-03-22 05:07 UTC
`DefaultApiDescriptionProvider` is responsible for populating the basic API Explorer data based on the method signature. However, we don't handle task-like return types here, and just handle `Task` and `Task<T>`

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ApiExplorer/DefaultApiDescriptionProvider.cs#L487

Arbitrary task-like types are supported by MVC's action invoker, but that doesn't work in API Explorer.

**Comment by rynowak** [comment] 2018-03-22 05:08
This seems low priority, to me, we didn't get any feedback about this in 2.0. However if you did end up using custom task-likes, you'd find the `ActionResult<T>` feature totally busted for your purposes.

**Comment by obayit** [comment] 2018-05-01 12:46
@khellang can you help me understanding the issue:
I created an action that returns ValueTask\<int>, and the Default Api Description Provider output is :
Response Type = System.Threading.Tasks.ValueTask`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]

Is the problem is that the Response Type should be "System.Threading.Tasks.ValueTask<System.Int32>" ?

**Comment by obayit** [comment] 2018-05-01 12:49
btw the media types I got where:

Formatter
Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter
Media Type
text/plain

Formatter
Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter
Media Type
application/json

Formatter
Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter
Media Type
text/json

**Comment by obayit** [comment] 2018-05-01 13:00
I think @rynowak  solved the issue in this commit fc3a815e57376aefa91adf219d64fbc6538821b3

**Comment by pranavkm** [comment] 2018-05-01 13:32
Dup of https://github.com/aspnet/Mvc/issues/7452. Closing this since the other issue is already being tracked for 2.2.0.

**Closed by pranavkm** 2018-05-01 13:32 UTC
Labels: enhancement, up-for-grabs
