### ISSUE TITLE
Make `ApiBehaviorApplicationModelProvider` less aggressive in Über-binding scenarios

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#8135] opened 2018-07-25 04:56 UTC
#### Is this a Bug or Feature request?:
Could be considered a bug. See #8111 for a long thread touching on the subject.

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
1. Add `[ApiController]` to a controller
2. Create a model wit routing attributes on its properties e.g. `[FromRoute]` and `[FromBody]`
2. Use above model as a parameter in an action

#### Description of the problem:
Entire model will be treated as if it were associated with `[FromBody]`

##### Potential fixes
1. Check properties of complex models for `BindingSource` information. Do not infer the `BindingSource` if anything is found.
2. Add an in-box `Attribute` as described in workaround 2.

##### Workarounds
1. Set the `ApiBehaviorOptions.SuppressInferBindingSourcesForParameters` property to `true`.
2. Add an `Attribute` implementing `IBindingSourceMetadata`. Its `BindingSource` property should return `BindingSource.ModelBinding` or a `CompositeBindingSource` combining `BindingSource.Query` and `BindingSource.Path`. (`BindingSource.Body` will override this where necessary.)

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Doesn't matter that much -- anything after `[ApiController]` was introduced

**Comment by mkArtakMSFT** [comment] 2018-07-27 20:43
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment] 2018-07-27 20:53
> Check properties of complex models for BindingSource information. Do not infer the BindingSource if anything is found.

That's expressly a non goal here. Model binding allows specifying a binder at any level and ApiController is meant to keep the inference simple and intuitive. 

> Add an in-box Attribute as described in workaround 2.

Seems like a trivial thing for a user to create and add. I don't see why this needs to be built-in.

**Comment by dougbu** [comment] 2018-07-27 21:07
> That's expressly a non goal here.

This is odd because `[ApiController]` behaviours can't simply be turned off at the model type or action levels. And, we're landing on two highly-touted features that don't seem to work together out of the box.

> Seems like a trivial thing for a user to create and add.

According to the person who reported #8111, this trivial thing doesn't work (it should).

**Comment by pranavkm** [comment] 2018-07-27 21:09
Ok, so is the bug here to investigate why applying `BindingSource = ModelBinder` does not work for ApiControllers?

**Comment by mkArtakMSFT** [comment] 2018-07-27 21:34
Closing this as the behavior here seems to be by design. Thanks @pranavkm  and @danroth27

**Closed by mkArtakMSFT** 2018-07-27 21:34 UTC
Labels: 1 - Ready, PRI: 1 - Required, bug

**Comment by abatishchev** [comment] 2018-07-28 01:06
>Ok, so is the bug here to investigate why applying BindingSource = ModelBinder does not work for ApiControllers?
How the question whether it's by design is equal to statement it's by design?

**Comment by dougbu** [comment] 2018-07-28 04:16
@abatishchev this bug was specifically about the conventions linked to `[ApiController]`. The decision was the conventions work as intended and don't need finer-grained controls than already exist.

If you want to instead use Über binding, don't use `[ApiController]` or disable this particular convention with
``` c#
services.Configure<ApiBehaviorOptions>(options => options.SuppressInferBindingSourcesForParameters = true);
```
in your `Startup.ConfigureServices(IServiceCollection services)` method. And, if Über binding doesn't work in either case, that's separate from this bug.
