### ISSUE TITLE
Problems hosting rc1-final-update1 on IIS

### ISSUE THREAD

**Issue by ghostdlr** [aspnet/Mvc#3829] opened 2015-12-29 21:14 UTC
Works just fine when I run it on my computer from Visual studio ( in IIS express) .  But when I try to host  the website on my server (WS 2012 , IIS 8 ), the page takes forever to load .

I found this error in log:

```
C:\iis\beta\wwwroot>IF "C:\iis\beta\approot\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnx.exe" == "" (SET "DNX_PATH=dnx.exe" ) 
Error: Unable to load application or execute command 'Microsoft.AspNet.Server.Kestrel'. Available commands: web, ef.
System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadFile(String assemblyPath)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func2 factory)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
```

Here's my project.json:

```json
{
  "webroot": "wwwroot",
  "userSecretsId": "aspnet5-gplayweb-11fc9aea-7741-4cff-ba1f-fc74dfb7600b",
  "version": "1.0.0-*",

  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final",
    "Microsoft.AspNet.Session": "1.0.0-rc1-final",
    "MySql.Data": "6.9.8"
  },
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}
```

**Comment by Eilon** [comment] 2015-12-29 23:28
Are you actually trying to use the Kestrel web server or are you trying to run in IIS?

**Comment by ghostdlr** [comment] 2015-12-29 23:29
I'm trying to run on IIS

**Comment by Eilon** [comment] 2015-12-29 23:57
Have you read the docs at https://docs.asp.net/en/latest/publishing/iis.html ? They also cover various common errors.

**Comment by ghostdlr** [comment] 2015-12-30 00:15
Yes, I did read it a couple of times . 

I don't get any errors .  Just "Waiting for ..."  status in chrome  and the page never finishes loading .

**Comment by Eilon** [comment] 2015-12-30 00:30
Hmm definitely weird. @kichalla @Tratcher any idea about this or how to debug it?

@ghostdlr does the Windows Event Log have anything? Or IIS FREB logs?

**Comment by kichalla** [comment] 2015-12-30 00:41
@ghostdlr How are you creating the content for the IIS hosted website? like did you do a local file publish and then pointing your website to the published wwwroot folder?

**Comment by ghostdlr** [comment] 2015-12-30 00:42
It used to work just fine with beta8 . 

I found this in Windows Logs
`The description for Event ID 1000 from source HttpPlatformHandler cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Process '35632' failed to start. Port = 31225, Error Code = '-2147023829'.
`

**Comment by ghostdlr** [comment] 2015-12-30 00:45
Yes, I published the website  Release-x86 , dnx-clr-win-x86.1.0.0-rc1-update1 , then I upload it to my server and point IIS to wwwroot .

**Comment by ghostdlr** [comment] 2015-12-30 09:36
I can start teamviewer, if anyone wants to take a look .

**Comment by Tratcher** [comment] 2016-01-04 22:07
> Self hosting doesn't work either . The console window closes instantly ... I don't have time to read the contents.

Open a console window, navigate to your published output and run `web.cmd`. This should at least let you see the error.

**Comment by ghostdlr** [comment] 2016-01-06 14:22
It shows the same error:
`Error: Unable to load application or execute command 'Microsoft.AspNet.Server.Kestrel'. Available commands: web, ef.
System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadFile(String assemblyPath)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func2 factory)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)`

**Comment by rbjarnason** [comment] 2016-01-07 16:19
We have exactly the same problem with: "The description for Event ID 1000 from source HttpPlatformHandler cannot be found." Any ideas?

**Comment by mikes-gh** [comment] 2016-01-07 21:11
Sounds like a deployment issue.  Is this a virtual directory?
Are you using publish from vs.

**Comment by Tratcher** [comment] 2016-01-07 23:12
@rbjarnason It appears to be an issue with the event log manifest installer. It's harmless, just noisy. We've got the HttpPlatformHandler team looking into it.

**Comment by rbjarnason** [comment] 2016-01-08 12:12
Thanks guys but the problem is fixed now. This was not published through VS and it turned out that some files had not been overwritten since the last version.

**Comment by mikes-gh** [comment] 2016-01-09 00:53
@rbjarnason Can you close please.

**Comment by ghostdlr** [comment] 2016-01-09 01:08
@mikes-gh I publish with visual studio .   
I just point IIS to a folder on the server hdd where the website is uploaded .

**Comment by ghostdlr** [comment] 2016-01-10 16:18
I fixed the problem by deleting global.json from approot\src\website\

**Closed** 2016-01-10 17:08 UTC
