### ISSUE TITLE
Broken method File() in ASP.NET Core MVC

### ISSUE THREAD

**Issue by igorgiovannini** [aspnet/Mvc#8508] opened 2018-09-28 11:51 UTC
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Inside an action method of your controller, return a file using the following method:

`return File("filepath", "media type");`

This throws a System.IO.FileNotFoundException.
Example: https://github.com/igorgiovannini/aspnet-mvc-issue8508

#### Description of the problem:
A System.IO.FileNotFoundException is been thrown.
File permissions are OK, even owner.

It's possible to bypass the problem by reading first the bytes and then returning them.

`return File(System.IO.File.ReadAllBytes("filepath"), "media type");`

Detailed exception:

`2018-09-27 18:42:03,416 ERROR Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware - An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not find file: **my path**
File name: '**my path**'
   at Microsoft.AspNetCore.Mvc.Infrastructure.VirtualFileResultExecutor.ExecuteAsync(ActionContext context, VirtualFileResult result)
   at Microsoft.AspNetCore.Mvc.VirtualFileResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)`

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.4

**Comment by khellang** [comment] 2018-09-28 12:18
I think you need to provide a repro here. This sounds like a mismatch between the content root and the current directory.

What's the output of `Directory.GetCurrentDirectory()`/`Path.GetFullPath("filepath")`?

If you inject `IHostingEnvironment` into your controller, what's the value of the `ContentRootPath` and `WebRootPath` properties?

Are you copying the file to output?

**Comment by igorgiovannini** [comment] 2018-09-28 12:33
`Directory.GetCurrentDirectory()` returns the path where the project is located.
`Path.GetFullPath("filepath")` returns the path where the "filepath" is located (preceded by `Directory.GetCurrentDirectory()`)

For IHostingEnvironment:
`ContentRootPath` => same as  `Directory.GetCurrentDirectory()`
`WebRootPath` => like  `Directory.GetCurrentDirectory()`, but with /wwwroot appended.

The files are copied and are accessible (I can open them with Preview/...).
The path I get in the Exception is **real!**.

As soon as I can I provide you an example.

**Comment by igorgiovannini** [comment] 2018-09-28 15:59
Example is now available: https://github.com/igorgiovannini/aspnet-mvc-issue8508

**Comment by igorgiovannini** [comment] 2018-09-28 16:11
LOL. Forgive me, I'm an as****e!
The comments on the method tell "virtual path", not physical path.
It works.

However I don't understand why it throws an exception giving also the full path (and the file exists and is there...). I have to take a look to the source code 😄 

Shall I keep the issue open? In the latest MVC 5.2 (.NET Framework) the method works differently...

**Comment by mkArtakMSFT** [comment] 2018-09-28 18:31
Thanks for contacting us, @igorgiovannini.
We're closing this issue as the behavior discussed seems to be by design.

**Closed by mkArtakMSFT** 2018-09-28 18:31 UTC
