### ISSUE TITLE
Enable PartialTagHelper to take in constructed model types.

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#7374] opened 2018-02-14 22:54 UTC
```html
<partial name="_Order" asp-for="@(new PartialsModel.Order { Total = 12 })" />
```

Throws an exception. This is possible with
```csharp
Html.Partial
```

so its a gap in the current `<partial>` tag helper.
The workaround is to put the expression in a temporary variable and do `asp-for=@variable`

**Comment by NTaylorMullen** [comment] 2018-02-15 00:02
Duplicate of https://github.com/aspnet/Razor/issues/2065

**Comment by javiercn** [comment] 2018-02-15 05:29
Reopening because I want a decision from triage on whether we fix asp-for or we add an asp-model property to support these cases.

**Comment by pranavkm** [comment] 2018-02-15 16:08
cc @DamianEdwards , thoughts on this?

**Comment by DamianEdwards** [comment] 2018-02-15 16:31
Is this true for all ModelExpression properties? I see the linked bug says we regressed this from 1.x which makes me inclined to investigate a fix.

**Comment by pranavkm** [comment] 2018-02-15 16:36
It wasn't a regression, I tried a 1.1 application and the problem was the same there. It's a bug \ limitation of the parser, but not a regression.

**Comment by pranavkm** [comment] 2018-02-15 16:39
To add to my previous comment, the question here is - do we need to add a `object Model` property to `PartialTagHelper` that lets you workaround the parser bug until we address it?

**Comment by DamianEdwards** [comment] 2018-02-15 17:15
Is this uniquely an issue with the PartialTagHelper? If so, we could add a model property to allow setting directly, or we could fix the parser bug. I'm slightly concerned about having two ways to set the partial model that folks have to decipher.

**Comment by pranavkm** [comment] 2018-02-15 17:38
The parser issue isn't unique to partials, but passing a  `new PartialModelType` is a partial-ism. @NTaylorMullen said the Razor issue was assigned to the 2.2.0 milestone, so it might not be a very long wait to get this resolved.

**Comment by DamianEdwards** [comment] 2018-02-15 17:50
Ok, I think we need to add the other property then. Not being able to simply pass a new instance of a type to the partial is bad. Also, while we're at it, the attribute should be 'for' not 'asp-for' as this is a custom element.

**Comment by pranavkm** [comment] 2018-02-15 18:11
So that I understood the asks correctly:

* Rename `asp-for` -> `for`. Does this need to go in to preview1?
* Add a new `object model` property on `PartialTagHelper`. We'll only allow setting, one of the `for` attribute or the `model` attribute.

**Comment by NTaylorMullen** [comment] 2018-02-15 18:56
> Ok, I think we need to add the other property then. Not being able to simply pass a new instance of a type to the partial is bad.

Why not just re-prioritize the general `ModelExpression` issue? I'm strongly against adding a `model` attribute to work around a bug.

**Comment by NTaylorMullen** [comment] 2018-02-15 19:15
Ok talked a lot offline and @dougbu enlightened us that having `for` support `new XYZ` could never work (even if parsing allowed it). Therefore, we'll need to have both. Pranav's listing of the asks is what we'll need to do; not as a workaround but in order to fully support all scenarios.

```
from @pranavkm
- Rename asp-for -> for. Does this need to go in to preview1?
- Add a new object model property on PartialTagHelper. We'll only allow setting, one of the for attribute or the model attribute.
```

**Comment by javiercn** [comment] 2018-02-15 20:38
@NTaylorMullen why will asp-for never work for random expressions?

**Comment by NTaylorMullen** [comment] 2018-02-15 23:16
> @NTaylorMullen why will asp-for never work for random expressions?

Because `asp-for` dives the lambda expression tree looking for a name to use. In the case of `new XYZ()` there's no name to consume (which is why when saving it to a variable it uses the variables name as the "name"). @dougbu said it's a restriction that's been there for even Html helpers in the past for expression based methods.

**Comment by javiercn** [comment] 2018-02-16 00:16
@NTaylorMullen Can't the name just fallback to ""? Maybe not by default, but at least when we tell the underlying system to do so? There are cases in which it would be useful, like this one.

**Comment by NTaylorMullen** [comment] 2018-02-16 00:30
> Can't the name just fallback to ""? Maybe not by default, but at least when we tell the underlying system to do so? There are cases in which it would be useful, like this one.

@dougbu ?

**Comment by dougbu** [comment] 2018-02-16 00:39
@javiercn I mixed up two places we restrict lambda expression nodes. Your issue is likely about an inability to get `ModelMetadata` for the expression, not about expression names. Put another way, I was thinking about (1) but your issue is (2).
1. `ExpressionHelper` is the one that recurses through the entire expression tree and deals with expression names. It just shortens the name when it hits an unsupported lambda expression node. So, *does* come up with `string.Empty` when the top node is unsupported.
    - There's still a potential `Exception` because the empty string is not a valid HTML `name` or `id` attribute value. Many of the HTML generation methods check this requirement and `throw` when it's violated.
2. `ExpressionMetadataProvider` only looks at the top node in the lambda expression tree. But, it `throw`s when that node is unsupported. If the `Exception` you saw was an `InvalidOperationException`, `ExpressionMetadataProvider` threw it. There is no workaround since `ExpressionMetadataProvider` is an `internal static class`.

We could perhaps add more expression nodes to the supported set. Not sure we've received requests for anything like that.

For the general issue with `<partial>`, @NTaylorMullen [described](https://github.com/aspnet/Mvc/issues/7374#issuecomment-366031737) a much quicker and more general fix.

**Comment by mkArtakMSFT** [comment] 2018-02-28 22:15
@DamianEdwards, we need your input on this one. What should the user experience be here? The options we've discussed are:
1. Have two tag helpers: `Partial` and `Partial-For`
2. Add the `model` attribute (as was already proposed), and use another attribute (i.e. `fieldName`) with it to provide the missing metadata - the prefix.

**Comment by mkArtakMSFT** [comment] 2018-02-28 23:00
From @DamianEdwards: go with an additional parameter for the existing tag helper.

**Comment by dougbu** [comment] 2018-02-28 23:37
Why do we need `fieldName`? `Html.PartialAsync(...)` handles the `Model` case just fine and doesn't muck with `TemplateInfo.HtmlFieldPrefix`. Adding this attribute also seems confusing and adds error and override cases between three attributes, not just two (`for` conflicts with `model` and now `fieldName`)

**Comment by NTaylorMullen** [comment] 2018-03-15 00:30
Ya I'm not sold on having a `fieldName` property. Going to leave that out.

**Comment by NTaylorMullen** [comment] 2018-03-23 23:37
e94d77c47f15facd7e1394c942190cb9d49e2c59

**Closed by NTaylorMullen** 2018-03-23 23:37 UTC
Labels: 3 - Done, cost: M, enhancement
