### ISSUE TITLE
WebApplicationFactory initialization is not thread safe causing multiple TestServer instances being created

### ISSUE THREAD

**Issue by Suremaker** [aspnet/Mvc#8629] opened 2018-10-21 11:30 UTC
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Please see the https://github.com/Suremaker/WebApplicationFactoryTests repository.

#### Description of the problem:
The `WebApplicationFactory<T>` initialization process is not thread-safe, making multiple instances of `TestServer` created if `CreateDefaultClient()` is called from different threads.

The problem has been described on the https://github.com/Suremaker/WebApplicationFactoryTests repository Readme and the repository contains tests recreating that issue.

The side question here is how to enforce/ensure the `WebApplicationFactory<T>` is initialized, as there is no explicit method for it?

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

Microsoft.AspNetCore.Mvc.Testing version 2.1.3

**Comment by javiercn** [comment] 2018-10-22 03:19
Thanks for contacting us.

This class doesn’t claim to be thread safe, so the behavior you are experiencing is expected.

If you need to use it on multithreaded environments you are responsible for wrapping its usage in lock statements as aprropriate.

**Comment by Suremaker** [comment] 2018-10-22 19:46
Hello @mkArtakMSFT, @javiercn,

Thank you for the fast response. I have checked the documentation on the `WebApplicationFactory` and it does not mention being thread-safe indeed.

In all the projects so far we have been using the `TestServer` class explicitly, instantiated once and shared between all the tests that have been running in parallel - mainly to speed up the integration tests execution and do not waste the time on costly initialization time of the TestServer on every test.  
With that approach we have never encounter any issues with `TestServer` itself being accessed by multiple threads.

As I started playing with ASP.NET Core 2.1, I found that `WebApplicationFactory` has been introduced to make testing even simpler, so I tried it and found this problem.

The brief analysis of the code shows that the issue lays in [void EnsureServer()](https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Testing/WebApplicationFactory.cs#L113) which allows race condition with current implementation but it could be easily fixed with code like:
```c#
private readonly object _lockObject = new object();
private void EnsureServer()
{
    if (_server != null)
        return;

    lock (_lockObject)
    {
        if (_server != null)
            return;

        EnsureDepsFile();

        var builder = CreateWebHostBuilder();
        SetContentRoot(builder);
        _configuration(builder);
        _server = CreateServer(builder);
    }
}
```
or other simple code making it thread safe.

If that rather a small fix gets implemented, other users won't have to guard all the usage places with locks and the behavior of the class would be consistent.

I wonder if there is any chance to get it fixed here?

**Comment by javiercn** [comment] 2018-10-22 21:56
@Suremaker That alone is not enough, WAF keeps lists of clients and child WAFs in order to dispose them later. Making WAF thread safe implies looking at the entire class and protecting access to all the shared state.

If you want to share the WAF across threads I would recommend simply wrapping it in a static class, exposing a method or two to create the clients you need and protecting shared access to the WAF inside the wrapper class.

**Comment by mkArtakMSFT** [comment] 2018-10-23 17:21
Thank you for your feedback.
We're closing this issue as the behavior discussed seems to be by design.

**Closed by mkArtakMSFT** 2018-10-23 17:21 UTC
Labels: investigate
