### ISSUE TITLE
StatusCode always return OK

### ISSUE THREAD

**Issue by bigfi** [aspnet/Mvc#6077] opened 2017-04-05 13:30 UTC
I have a problem with the function "StatusCode()" and others.

Here is the method :
```c#
public async Task<IActionResult> Login([FromBody] MobilLoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                result = await _signInManager.PasswordSignInAsync(model.UserName, model.Password, model.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation(1, "User logged in.");
                    return Ok();
                }
                else
                {
                    return StatusCode(StatusCodes.Status401Unauthorized);
                }
            }
            return StatusCode(StatusCodes.Status400BadRequest);
        }
```

It's basicaly the login method from the Identity in the MVC controller. But I made it for an app in Xamarin to call it.
So if the login went well, it returns the OK response and if not, it returns the StatusCode 401.

But on my App side, even if I send a 401 status, it received a 200 response.
I tried to use 
- StatusCode(StatusCodes.Status400BadRequest)
- new StatusCodeResult(401)
- Unauthorized()

I always receive a 200 response on my client side. 

The only method that does not send a 200 is the Badrequest() one. With this one, I receive a 400 on my client side.

Is there a bug or did I do Something wrong?

**Comment by Eilon** [comment] 2017-04-11 17:23
Have you set a breakpoint or maybe logged from the line that says `return StatusCode(StatusCodes.Status401Unauthorized);` to see if it runs?

If you do see it running, it could be that another middleware component is changing the status code from 401 to a 200.

@Tratcher / @HaoK - in ASP.NET Core 1.x what circumstances would the AuthN middleware change the status code from 401 to 200?

**Comment by Tratcher** [comment] 2017-04-11 17:29
Some middleware can react to 401s and issue challenges, but none of ours would change the status to 200.

Note Unauthorized would be the preferred response here since that will directly invoke the auth middleware to issue a challenge.

**Comment by bigfi** [comment] 2017-04-11 19:22
Thank you for your answers.

Yes, I set a breakpoint on my return code. The return is executed and the next step is the end } of the method. Everything looks good on server side.

**Comment by Eilon** [comment] 2017-04-12 01:50
@bigfi can you show what your Startup.cs file looks like? Presumably there's some middleware component that's changing the status code.

**Comment by bigfi** [comment] 2017-04-12 06:48
Here it is

`
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using nurseryBackupServer.Data;
using nurseryBackupServer.Models;
using nurseryBackupServer.Services;
using nurseryBackupServer.Controllers;

public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

            if (env.IsDevelopment())
            {
                // For more details on using the user secret store see http://go.microsoft.com/fwlink/?LinkID=532709
                //builder.AddUserSecrets();
                builder.AddUserSecrets(TOKEN);

                // This will push telemetry data through Application Insights pipeline faster, allowing you to view results immediately.
                builder.AddApplicationInsightsSettings(developerMode: true);
            }

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddApplicationInsightsTelemetry(Configuration);

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            services.AddMvc();

            services.AddAuthorization(options =>
            {
                options.AddPolicy(
                    "AllUsers",
                    policy => policy.RequireRole("Admin", "Director", "Educ"));
                options.AddPolicy(
                    "PowerUser",
                    policy => policy.RequireRole("Director", "Admin"));
                options.AddPolicy(
                    "Administration",
                    policy => policy.RequireRole("Admin"));
            });

            // Add application services.
            services.AddTransient<IEmailSender, AuthMessageSender>();
            services.AddTransient<ISmsSender, AuthMessageSender>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            //app.UseApplicationInsightsRequestTelemetry();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            //app.UseApplicationInsightsExceptionTelemetry();

            app.UseStaticFiles();

            app.UseIdentity();

            ApplicationSeedData.SeedData(app.ApplicationServices).Wait();

            // Add external authentication middleware below. To configure them please see http://go.microsoft.com/fwlink/?LinkID=532715

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }`

**Comment by Eilon** [comment] 2017-06-07 21:56
Unfortunately we don't see anything above that would indicate what would cause this. Can you post a complete application that demonstrates the problem?

**Comment by Eilon** [comment] 2017-08-04 17:57
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2017-08-04 17:57 UTC
