### ISSUE TITLE
upgrade asp.net core targeting framework 4.6.1 from vs2015 to vs2017 - One or more compilation references are missing

### ISSUE THREAD

**Issue by ErezSavir** [aspnet/Mvc#5926] opened 2017-03-08 15:17 UTC
I opened it on the SDK repo as well- https://github.com/dotnet/sdk/issues/958 as I'm not sure where it supposed to be.

 have upgraded my asp.net core,using project.json and targeting .net framework 4.6.1 on visual studio 2015 to visual studio 2017.

I have multiple projects in the solution where the main application is referencing them by project reference(all of them target net461).

When running the application I get

`One or more compilation references are missing. Possible causes include a missing 'preserveCompilationContext' property under 'buildOptions' in the application's project.json.`
Screenshot:
![11](https://cloud.githubusercontent.com/assets/6003926/23704391/55508f08-040d-11e7-9cdf-88532fa2965d.png)

And my csproj:
[webapp.txt](https://github.com/dotnet/sdk/files/827601/webapp.txt)

I'll try to create a project to see if I can reproduce.

**Comment by Eilon** [comment] 2017-03-09 17:53
Closing this because it looks like the right set of people are looking at https://github.com/dotnet/sdk/issues/958. We can move the discussion back here if it looks like the issue is with MVC.

**Closed by Eilon** 2017-03-09 17:53 UTC
