### ISSUE TITLE
ViewComponent partial view searching outside component folder

### ISSUE THREAD

**Issue by joshua-mng** [aspnet/Mvc#6285] opened 2017-05-17 13:41 UTC
Let's say I'm calling view component named 'NavigationViewComponent' from Index.cshtml view of controller named 'HomeController'. (tested on ASP.NET Core MVC 1.1.3)

~/Views/Home/Index.cshtml

`@Component.Invoke("Menu")`

now, inside the component's view

~/Views/Home/Components/Navigation/Menu.cshtml

```
<div class="menu">
    Html.Partial("SubMenu")
</div>
```

it seems razor view engine is searching SubMenu inside ~/Views/Home/ and ~/Views/Shared/ folders.

Logically, it should search inside the current view component's folder first. Like following?

~/Views/Home/Components/Navigaiton/SubMenu.cshtml
~/Views/Shared/Components/Navigation/SubMenu.cshtml

Is it bug or by design?

**Comment by rynowak** [comment] 2017-05-17 14:44
> Logically, it should search inside the current view component's folder first. 

`@Html.Partial("SubMenu")` does a search for `SubMenu.cshtml` based on the search paths defined by the view engine. The fact that you're calling `@Html.Partial` from inside a VC's view does not change the search paths.

If you want to run the partial from the currently executing view's folder you can use a filename `@Html.Partial("SubMenu.cshtml")` see https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial

**Comment by joshua-mng** [comment] 2017-05-18 04:43
In fact, I tried calling `@Html.Partial("SubMenu.cshtml")` and it still does not search inside current VC's folder. It searches only inside current controller's view folder.

**Comment by rynowak** [comment] 2017-05-18 21:53
Hmm, I thought that would work. @dougbu any ideas here?

**Comment by dougbu** [comment] 2017-05-18 22:12
Sounds like a bug in how we're setting `ViewContext.ExecutingFilePath` when executing a view component view. Must be a case where that isn't updated.

**Comment by dougbu** [comment] 2017-05-18 22:27
Could happen iff `IRazorPage.Path` were set incorrectly. But, only tests, `DefaultPageFactory` and `DefaultRazorPageFactoryProvider` set that property. `DefaultPageFactory` is more likely to get confused but shouldn't be used in this context.

**Comment by mkArtakMSFT** [comment] 2018-01-04 20:56
@dougbu, can you please handle this during preview2 timeframe? Thanks!

**Comment by dougbu** [comment] 2018-02-21 21:22
Thank you for your feedback. We're closing this issue as the behaviour discussed is by design in one case  (the original question) and not reproducible in the other.

If `@Html.Partial("SubMenu.cshtml")` is not working as described below in your particular application, please provide us with a minimal repro project that illustrates the problem, preferably hosted in a GitHub repo. I recommend opening a new issue and leaving this one to your question about the view engine search paths.
> it seems razor view engine is searching SubMenu inside `~/Views/Home/` and `~/Views/Shared/` folders.

As @rynowak said [above](https://github.com/aspnet/Mvc/issues/6285#issuecomment-302113313) this is by design.
> In fact, I tried calling `@Html.Partial("SubMenu.cshtml")` and it still does not search inside current VC's folder. It searches only inside current controller's view folder.

I cannot reproduce this behaviour. With `@Html.Partial("SubMenu.cshtml")` in the default view for a `"Menu"` component invoked from the `"Home"` controller i.e. in `~/Views/Home/Components/Menu/Default.cshtml`, the view engine just looks for `~/Views/Home/Components/Menu/SubMenu.cshtml`.

If the component calls `View("~/Views/Home/Components/Navigation/Menu.cshtml")` instead of `View()` and `~/Views/Home/Components/Navigation/Menu.cshtml` contains `@Html.Partial("SubMenu.cshtml")`, the view engine just looks for `~Views/Home/Components/Navigation/SubMenu.cshtml`.

----
Issue #7143 is currently in the 3.0 milestone, indicating we may consider revisiting the default view engine search paths in the future.

**Closed by dougbu** 2018-02-21 21:22 UTC
Labels: 2 - Working, bug
