### ISSUE TITLE
ApiExplorer: ProducesResponseType hides ActionResult<T>

### ISSUE THREAD

**Issue by lecoque** [aspnet/Mvc#7972] opened 2018-06-26 13:37 UTC
#### Description of the problem:
```csharp
[HttpGet("{id}")]
[ProducesResponseType(StatusCodes.Status404NotFound)]
public async Task<ActionResult<Book> GetByIdAsync(int id)
{
    //
}
```

Now when using `ApiDescription.SupportedResponseTypes` the only supported response type is `void` but when I remove `ProducesResponseType` attribute I get the correct response type.

Is this by design?

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.0

**Comment by pranavkm** [comment] 2018-06-26 16:16
> Is this by design?

Yup. The moment you specify a `ProducesResponseType` \ `Produces` attribute, MVC assumes the application developer will provide all valid response codes. We are making a small change to the behavior of `ActionResult<T>` + some success status codes - https://github.com/aspnet/Mvc/issues/7871 - but that still requires you to specify all possible status codes from the action.

**Comment by lecoque** [comment] 2018-06-26 18:00
I see thanks.

**Comment by pranavkm** [comment] 2018-06-28 16:28
Closing since this is by design. For 2.2, we plan on using [API Conventions](https://github.com/aspnet/Announcements/issues/307) to remove some of the boiler attributes required for producing good swagger.

**Closed by pranavkm** 2018-06-28 16:28 UTC
