### ISSUE TITLE
return BadRequest() doesn't short-circuit middleware flow

### ISSUE THREAD

**Issue by GVG** [aspnet/Mvc#7726] opened 2018-05-02 21:26 UTC
I have 2 similar web projects with common code base and I have an issue with _return BadRequest()_ when returning it without any data as _BadRequestResult_.

First project's _Configure_ method in _Startup_ ends with following code:
`app.Run(async (context) => // Handle everything else
{
	context.Response.ContentType = "text/html";
	await context.Response.SendFileAsync(Path.Combine(env.WebRootPath, "index.html")); // For HTML5 routing
});`

Second project's _Configure_ method ends with this:
`app.Run(async (context) => // Handle everything else
{
	context.Response.Redirect("https://somewhere.com");
});`

Now the issue itself is following behavior:
In first project I can call _return BadRequest()_ or _return BadRequest("text")_ in any controller and the result will be status 400 with or without text/object respectively. That delegate with _SendFileAsync()_ is not reached and this is correct/expected behavior. No issues here.
In second project if I call _return BadRequest()_ without arguments the delegate with _Redirect()_ function is reached for some reason and I get status 302 instead of expected status 400 without content. _return BadRequest("text")_ works correctly. Why _return BadRequest()_ doesn't short-circuit middleware execution flow like in first project? My _Redirect()_ delegate should be called only when MVC and other middleware couldn't process the request. Did I miss something?

ASP .NET Core 2.0.2 and MVC 2.0.3

**Comment by khellang** [comment] 2018-05-02 22:18
I guess `BadRequest("text")` ends up writing to the body, which forces the headers to be flushed. After that, it's too late for the redirect to do anything useful so it just fails silently.

**Comment by kichalla** [comment] 2018-05-02 22:31
@GVG Even in case of the second project, I would not expect the last middleware to be executed if you are a BadRequest (with or without a text)

Do you have a repro project? (Have you looked at the issue template before creating this issue?)

**Comment by GVG** [comment] 2018-05-02 22:38
Yes, it's kind of expected behavior. But why last middleware is executed only in second project after BadRequesting without text? First one doesn't execute it in this case.

I don't have repro project right now. Thought it's something obvious. I can try to reproduce it if needed.

**Comment by GVG** [comment] 2018-05-03 00:26
After digging MVC source code I've found what caused this behavior.
`app.UseStatusCodePagesWithReExecute("/Error/{0}");` caused it.
The flow is following:
1. RouterMiddleware is invoked with correct HttpContext.Request.Path and `if (context.Handler == null)` is false
2. return BadRequest();
3. StatusCodePagesMiddleware is invoked with HttpContext.Response.StatusCode = 400, ContentLength = null and ContentType = null
4. Skips conditional `return;` on line 42 in StatusCodePagesMiddleware.cs (due to status 400 and nulls )
5. `app.UseStatusCodePages(async context =>` delegate in StatusCodePagesExtensions.cs is called (line 173)
6. It changes HttpContext.Request.Path to "/Error/400" generated from my template above.
7. RouterMiddleware is invoked again with changed path and `if (context.Handler == null)` becomes true
8. My last redirect middleware is invoked

https://github.com/aspnet/Diagnostics/blob/rel/2.0.0/src/Microsoft.AspNetCore.Diagnostics/StatusCodePage/StatusCodePagesExtensions.cs

Is this correct behavior for StatusCodePages middleware? Was it designed to work this way?
The comment above this condition in step 3 says `// Do nothing if a response body has already been provided.`. This is ok for MVC controllers because you must always return a view, but if you use REST API at same time this doesn't allow you to return simple bad request response for AJAX request.
Now I'm not sure what repository this issue belongs to.

**Comment by khellang** [comment] 2018-05-03 10:04
> Is this correct behavior for StatusCodePages middleware? Was it designed to work this way?

It sounds like it's doing exactly what it's supposed to do. You've told it to re-exectue the pipeline with `/Error/{0}` as the path if it gets back an error response, and that's what it's doing. If you don't have anything to handle `/Error/400`, then it'll fall through to the redirect MW.

> This is ok for MVC controllers because you must always return a view, but if you use REST API at same time this doesn't allow you to return simple bad request response for AJAX request.

Then don't use `StatusCodePages` 😉 As the name suggests, it's meant to return a status code *page*. If you want to return plain, empty error responses from your API, you should just remove that middleware.

**Comment by kichalla** [comment] 2018-05-03 10:26
@khellang the scenario seems a bit interesting if you have MVC and api in the same app, in which case there needs to be a way for `UseStatusCodePagesWithReExecute` to no-op in case of let's say all request urls starting with '/api'. 
Probably there should be an overload which accepts a predicate taking in httpcontext to decide whether this middleware should no-op or not? cc @Tratcher

**Comment by khellang** [comment] 2018-05-03 10:45
> the scenario seems a bit interesting if you have MVC and api in the same app, in which case there needs to be a way for UseStatusCodePagesWithReExecute to no-op in case of let's say all request urls starting with '/api'.

But what's the point of re-executing the pipeline when you don't have anything that can handle the re-execution?

> Probably there should be an overload which accepts a predicate taking in httpcontext to decide whether this middleware should no-op or not?

`UseStatusCodePages` already has an overload taking `Func<StatusCodeContext, Task>`. It should be pretty easy to no-op for API calls using that.

**Comment by GVG** [comment] 2018-05-03 10:58
@kichalla or maybe mark controllers and/or actions with special attribute if this will work.
An attribute which defines action/controller type would be useful. Then you can make entire controller an MVC controller and one action in it as an API action (this is my case). This will allow to handle them in different ways. I.e. for MVC method we can return page `/Error/400` and for API it will be JSON or text response or even empty response.

@khellang for API empty BadRequest is perfectly fine response, but for MVC it's not really a valid response and UseStatusCodePages is meant to handle such cases. The issue is that this middleware works fine within MVC logic, but it intercepts correct API responses too.

**Comment by khellang** [comment] 2018-05-03 11:30
> for API empty BadRequest is perfectly fine response, but for MVC it's not really a valid response and UseStatusCodePages is meant to handle such cases. The issue is that this middleware works fine within MVC logic, but it intercepts correct API responses too.

Yes, `UseStatusCodePages` is meant to produce an error page for a status code, which doesn't work for APIs.

The question is; why are you using it in your API?

> \- Doctor, it hurts when I do this.
> \- Don't do that.

> or maybe mark controllers and/or actions with special attribute if this will work.

No matter what you do inside MVC, it still won't prevent whatever middleware you have in your pipeline from executing. If you don't want to produce status code pages in your API, you need to make sure the status code page middleware doesn't get executed.

**Comment by GVG** [comment] 2018-05-03 11:33
@khellang I'm not using UseStatusCodePages for API. I'm using it for MVC.

**Comment by khellang** [comment] 2018-05-03 11:46
> I'm not using UseStatusCodePages for API. I'm using it for MVC.

Then why is this even an issue? 😝

**Comment by GVG** [comment] 2018-05-03 11:51
@khellang did you read what I wrote? Please stop leaving useless comments and wasting everyone's time.

**Comment by khellang** [comment] 2018-05-03 11:55
> did you read what I wrote? Please stop leaving useless comments and wasting everyone's time.

Sorry, I was just trying to help. I'll see myself out. Good luck with your MVC/API app.

**Comment by GVG** [comment] 2018-05-03 12:00
Thank you. That's very kind.

**Comment by Tratcher** [comment] 2018-05-03 17:16
UseStatusCodePages doesn't have any knowledge of what framework was used to generate the response, be it MVC, API, etc.. It's very customizable, but not very smart by itself. Its job is to provide response bodies if you didn't. There are a few different ways of dealing with your mixed use scenario.

A) Teach your "/Error/" route to respond appropriately for both API and MVC requests. It can examine the original request path and react accordingly:
https://github.com/aspnet/Diagnostics/blob/88db534e42a49eade81611b04c0adc04e4684b2c/test/Microsoft.AspNetCore.Diagnostics.Tests/ExceptionHandlerTest.cs#L259-L265
B) There's an override feature you can set in your API controllers. https://github.com/aspnet/Diagnostics/blob/3a868d87a2458fd025ca71e2538b3a72f67c7c50/samples/StatusCodePagesSample/Startup.cs#L45-L49
C) Conditionally exclude the middleware from the pipeline using UseWhen.
https://github.com/aspnet/HttpAbstractions/blob/87cd79d6fc54bb4abf07c1e380cd7a9498a78612/src/Microsoft.AspNetCore.Http.Abstractions/Extensions/UseWhenExtensions.cs#L23
https://weblogs.asp.net/imranbaloch/conditional-middleware-in-aspnet-core

**Comment by GVG** [comment] 2018-05-03 20:05
@Tratcher Thank you very much! This is exactly what I wanted to know.
So this behavior is considered correct? If so, can you add a note about this to the documentation? Because it was unclear until I ran entire pipeline with debugger.

**Comment by Tratcher** [comment] 2018-05-03 21:17
Yes, it's correct. What doc were you referencing, this one? https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.1#configuring-status-code-pages

The only thing I see missing from that doc is the override feature.

**Comment by mkArtakMSFT** [comment] 2018-05-07 23:31
@Tratcher, who should handle the requested docs change here? Or should we just have a new docs issue created for this?
As I understand, there is no other action here, is there?

**Comment by Tratcher** [comment] 2018-05-07 23:38
We haven't identified any concrete changes for the docs so far. Do the comments at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.1#configuring-status-code-pages make sense to you in this context?

**Comment by mkArtakMSFT** [comment] 2018-05-08 20:01
@Tratcher, this is specifically what I've referred to above:

>In my opinion there should be a note about conditions which trigger StatusCodePage handler (line 42) and regarding prevent HTML status code responses from showing up to an API client (line 37) which means that BadRequest() and BadRequest(object) will be handled in 2 different ways when this middleware is used as is out-of-the-box. It's not obvious for people who didn't dig the source code.

**Comment by mkArtakMSFT** [comment] 2018-05-09 15:55
Thank you for your feedback, @GVG.
We're closing this issue as the behavior discussed seems to be by design.

Also, I'm not sure when, but it seems that the `UseStatusCodePagesWithReExecute` method is already pointed out in the docs @Tratcher referred to.

**Closed by mkArtakMSFT** 2018-05-09 15:55 UTC
Labels: docs
