### ISSUE TITLE
Web API Template with Windows Authentication in .NET Core SDK 2.1.302 does not generate a Windows Authentication template

### ISSUE THREAD

**Issue by gortok** [aspnet/Mvc#8269] opened 2018-08-14 17:03 UTC
#### Is this a Bug or Feature request?:

Bug.

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
1.  run the following command with .NET Core SDK 3.1.302 from Mac OS or select New Project -> ASP.NET Core Web Application -> Authentication -> Windows Authentication in VS 2017 15.7.6
```
 dotnet new webapi --auth Windows
```
2. Observe that no Authentication controller or Authentication attributes are attached to the default template; and the only controller present is the `ValuesController` with no authorization.

3. Observe that appsettings.json has Windows Authentication set to `false`.

#### Description of the problem:

The SDK template with the `--auth` option set to `Windows` (either in Visual Studio or through the command line on Mac OS) does not generate a project with any authentication options set up (let alone the expected Windows Authentication additions).

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

2.1? (unclear; the template does not put a version in the .csproj for the generated project.

**Comment by javiercn** [comment] 2018-08-14 17:39
@gortok I think you might be using an older version of the templates. (Not sure how or why). This was fixed as part of https://github.com/aspnet/Templating/commit/74883b2cf035ae0a05d99cc125ce352eade66d40 and I've validated that it's fixed in the current SDK.

Maybe @natemcmaster can shed some light on what's going on here?

**Comment by javiercn** [comment] 2018-08-14 17:51
@gortok I chatted with @natemcmaster and he can't reproduce the issue either. We've also confirmed that the fix was on more than one patched version (2.1.1 and so on) so I think something is likely wrong on your setup.

I would recommend you download the latest version of the SDK and repair your installation. After that try again and if it still reproduces for you. Remove the folder in "%userprofile%\.templateengine" and try again.

Closing this issue as there's no more action to be taken here at the moment. If you still have issues after performing the steps described above, feel free to reopen it and let us know. We'll loop other people in to help.

**Comment by gortok** [comment] 2018-08-14 18:27
I get the desire to close this quickly; but it seems jarring. Especially since I *Just* (today, right before filing this bug) updated both my .NET Core MacOS and the Visual Studio tooling for .NET Core (by updating visual studio).

**Comment by gortok** [comment] 2018-08-14 18:30
.NET Core --info (MacOS):
```
 georgestocker@vae-lt373  ~/src/nextgen/authentication   NEX-4981 ●  dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.0.0-preview2-1-003177 [/usr/local/share/dotnet/sdk]
  1.0.3 [/usr/local/share/dotnet/sdk]
  1.0.4 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.300-preview1-008174 [/usr/local/share/dotnet/sdk]
  2.1.300-rc1-008673 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

This is the version available for download from: https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.302-macos-x64-installer

Visual Studio version:

15.7.6 (again, updated today).

**Comment by javiercn** [comment] 2018-08-14 19:10
@mlorbetske @natemcmaster  Can you help out here?

For comparison, this is the output from my installed dotnet --info
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.400
 Commit:    8642e60a0f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400-preview-009197 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

I think your machine has an older version of the SDK. Not sure why.

**Comment by gortok** [comment] 2018-08-14 19:12
Yes, my SDK was installed today, from the Mac OS link on the dotnet core download SDK.

**Comment by javiercn** [comment] 2018-08-14 19:25
@gortok Have you tried removing the .templateengine folder from the user profile? (It should autorepair).

You should be seeing 2.1.400 if you had the latest bits, either something went wrong on the installation or the link on the download page is not correct.

In any case, this is not really an MVC issue but a templating engine issue, as you are likely seeing an older version of the templates even though your bits contain a newer version.

**Comment by natemcmaster** [comment] 2018-08-14 19:43
@javiercn 2.1.400 is part of the [VS 15.8](https://blogs.msdn.microsoft.com/visualstudio/2018/08/14/visual-studio-2017-version-15-8/) which was just announced a few hours ago. I wouldn't expect this to make a difference as it contains the same templates as the 2.1.302 SDK.

**Comment by javiercn** [comment] 2018-08-14 20:28
@gortok Don't worry. We'll move it when we have to. We have looped in the right people.

**Comment by gortok** [comment] 2018-08-14 20:37
Outside of ensuring Visual Studio was up to date; I also manually installed the .NET Core CLI for Windows and tried again; same result as above.  Here's the `dotnet --info` from that:

```
C:\Users\georgestocker\ad-auth>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17723
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-1-003177 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Users\georgestocker\ad-auth>
```

**Comment by gortok** [comment] 2018-08-14 21:53
I also rm -rf’d The template engine directory on Mac, to no effect. Will try with the windows side and see if that works.

**Comment by javiercn** [comment] 2018-08-22 22:33
Closing this issue in favor of https://github.com/aspnet/Mvc/issues/8270

**Closed by javiercn** 2018-08-22 22:33 UTC
Labels: investigate
