### ISSUE TITLE
WebApplicationTestFixture should provide a default WebHostBuilder

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#7038] opened 2017-11-09 09:42 UTC
According to the [announcement](https://github.com/aspnet/Announcements/issues/275) `WebApplicationTestFixture` tries to look for a function with the signature `public static IWebHostBuilder CreateWebHostBuilder(string [] args)` in the assembly where the `Startup` class is located.

That sounds really strange to me. My `CreateWebHostBuilder` method in my `Program` class is for use in production. I don't want my tests to be reading configuration from environment variables and would prefer to avoid writing test code in my application.

I think the `WebApplicationTestFixture` should provide a basic default `WebHostBuilder` (example below) instead of or in addition to looking in the `Program` class for an implementation of some method.

```
var builder = new WebHostBuilder()
    .ConfigureAppConfiguration((hostingContext, config) =>
        config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true))
    .UseDefaultServiceProvider((context, options) => options.ValidateScopes = true)
    .UseStartup<T>();
```

As it is, `WebApplicationTestFixture` will definately require me to override it to make it useful. With some sensible defaults, it could be made useful without doing so. 

See also [WebApplicationTestFixture Should Find the Project under Test](https://github.com/aspnet/Mvc/issues/7037)

**Comment by Eilon** [comment] 2017-11-27 20:09
@RehanSaeed I believe the idea here is that if you have a custom scenario, you can override one of the virtual methods on `WebApplicationTestFixture` to suit your needs:

https://github.com/aspnet/Mvc/blob/008a562bf5b1ab89e4b83c60faaabd1d12ffcb82/src/Microsoft.AspNetCore.Mvc.Testing/WebApplicationTestFixture.cs#L122

In general the app's startup code should be aware of multiple environments and use conditional logic to enable/disable certain parts as needed. The reason the test fixture calls the default method is that in any non-trivial scenario there are many services that need to be configured, so having two copies of that code seems less than ideal.

@javiercn do you have additional thoughts on this?

**Comment by javiercn** [comment] 2017-11-28 01:35
@Eilon is exactly right. Things like setting up application configuration etc will not work properly with just doing new WebHostBuilder().

By default the tests reflects the config of your application as close as possible, that's the starting point. You can always override CreateWebHostBuilder and setup dependencies and anything else you need for your tests

**Comment by javiercn** [comment] 2017-12-22 18:42
I'm closing this as by design.

The solution is simply to extend WebApplicationTestFixture and override CreateWebHostBuilder to create the builder yourself (and depend on this class for your tests)

**Closed by javiercn** 2017-12-22 18:42 UTC
Labels: investigate
