### ISSUE TITLE
Why DataAnnotationLocalizerProvider lambda is called for model type?

### ISSUE THREAD

**Issue by amityagov** [aspnet/Mvc#5636] opened 2016-12-22 21:05 UTC
Why not for attribute which i want localize? 
Later, in `IStringLocalizer.this[string name, params object[] arguments]` i can't get attribute type or any info about it, so i can't properly get localized string for attribute localization.

Mvc Code: 
DataAnnotationsModelValidatorProvider.CreateValidators
```
stringLocalizer = this._options.Value.DataAnnotationLocalizerProvider(context.ModelMetadata.ContainerType ?? context.ModelMetadata.ModelType, this._stringLocalizerFactory);
```

StringLocalizer is created for model but not for attribute.

My Code:
```
AddDataAnnotationsLocalization(options =>
{
	options.DataAnnotationLocalizerProvider = (type, factory) => factory.Create(type); 
        // type is typeof(MyModelType)
})
```

Mvc version: 1.1.0

**Comment by frankabbruzzese** [comment] 2016-12-25 11:14
What's the problem with it? Everything is as explained in the [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization). localizers are created from types (however you may create them also from string that have no type associated with them). 
Pls explain clearly the supposed issue, possibly referring to mismatches between documentation and actual behavior.

**Comment by Eilon** [comment] 2016-12-27 18:28
@ryanbrandenburg thoughts on this?

**Comment by ryanbrandenburg** [comment] 2017-01-17 19:47
@amityagov a reminder to tell us more about your scenario by answering the questions from the people above. Otherwise we'll close this since we don't have enough information to act on.

**Comment by amityagov** [comment] 2017-01-18 18:44
It is reasonable to pass the attribute type during the localization process rather than model type.
There is no prerequisites to pass the useless model type.

I want to create IStringLocalizerFactory implementation which will use json-based dictionary to store the localization data.
Or it will use the database to store localized values.
e.g.

```
{
	"System.ComponentModel.DataAnnotations.RequiredAttribute.ErrorMessage": "Error: field {0} is required."
}
```

So i need to pass the localization key to IStringLocalizer method to get localized value.

Current behavior does not allow to do it.

IStringLocalizerFactory default implementation - ResourceManagerStringLocalizerFactory.
It looks like leaked abstraction. Because ResourceManagerStringLocalizerFactory implementation uses resources in form of `"String Value": "Localized String Value"` as localization source. And IStringLocalizer gets value like "String Value" to localize with some other parameters but not any useful info about localizable value.

IStringLocalizerFactory and IStringLocalizer depend from one implementation - ResourceManagerStringLocalizerFactory.

Sorry for my english.)

**Comment by ryanbrandenburg** [comment] 2017-01-18 20:03
If I'm understanding your correctly you have the same basic thoughts as #302. You would like to remove the Type overload of `IStringLocalizerFactory.Create` because you think it's too narrow and not useful to your use case. My reply to that is the same as @Eilon's was, the interface must be broad enough to accomodate many different implementations of `IStringLocalizerFactory`, but I would also like to point out that creating an `IStringLocalizer` based off of a type is not specific to `ResourceManagerStringLocalizerFactory`, but to the style of organizing resource by the types to which they pertain, which could be applied to most all implementations (EF might filter through a table by Type, JSON might have multiple files the way we do for resources etc.).

I'm closing this as a duplicate of #302. If we've misunderstood your request/feedback then I think the best way to proceed would be to create an example of the situation you would like to address as a minimal github repo so that we can better understand your goals.

**Closed by ryanbrandenburg** 2017-01-18 20:03 UTC

**Comment by amityagov** [comment] 2017-01-18 20:45
@ryanbrandenburg

This issue is not duplicate of #302.

I DO NOT want to remove anything. I just want it to be fixed for being usable.

This is example repo: https://github.com/amityagov/data-annotations-localization-ex
`HomePageModel` model with attribute.
`JsonBasedStringLocalizerFactory` factory implementation.
`StringLocalizer::IStringLocalizer.this[string name, params object[] arguments]` called with error text  value and some args. 

I just want to 
* change DataAnnotationLocalizerProvider behavior to use attribute type. 
* ValidationAttributeAdapter<>::GetErrorMessage call _stringLocalizer even if this.Attribute.ErrorMessage is empty or null
* pass some data to IStringLocalizer.this[string name, params object[] arguments] about attribute, so i can use this.

Based on the current state of things i need to completely rewrite DataAnnotationsClientModelValidatorProvider and some other classes. So sad.

I completely disagree this issue is dup of anything.

**Comment by dougbu** [comment] 2017-01-18 21:52
@amityagov I asked earlier for more details about your scenario and the above description helps. But what drives your need for validation adapters to have _both_ the corresponding attribute and an `IStringLocalizer` created with information about the attribute?

Separately,
> ValidationAttributeAdapter<>::GetErrorMessage call _stringLocalizer even if this.Attribute.ErrorMessage is empty or null. currently it is not called.

This is by design. To do otherwise would both override the existing .NET localization of the default `ValidationAttribute` error messages and create an unmanageable situation where the `IStringLocalizer` implementation must recognize the default error messages in every language the system supports.

**Comment by amityagov** [comment] 2017-01-19 07:30
@dougbu 
1) `ValidationAttributeAdapter<>` currently receive attribute instance and IStringLocalizer instance, but later in `GetErrorMessage`? the adapter does not pass any info about attribute to localizer.
2) `ValidationAttributeAdapter<>` class is base class for 8 classes. So if i want to change behavior i need to create approx NINE classes and replace default ValidationAttributeAdapterProvider which contains stairway of attribute type checks with my own impl. So currently where is no any extension point for changing `ValidationAttributeAdapter::GetErrorMessage` behavior. Maybe you can add some interface what can support extensibility and which will be called from `GetErrorMessage`. Like `IClientModelValidatorLocalizer::GetErrorMessage(IStringLocalizer localizerForModelType, Attribute attribute)`. Implementation of this may be replace in IOC. So `public API` users can get more flexible and extensible api).

**Comment by frankabbruzzese** [comment] 2017-01-19 10:40
@amityagov ,
You have chosen the wrong extension point. Also if you succeed in customizing `ValidationAttributeAdapter `messages the way you want, you have done 50% of the job, since `ValidationAttributeAdapter `is responsible just for client side validation, so you would need to change also server side messages.

If your final purpose is just providing default messages that depend just on the attribute and not on where they are placed the right way is to add those messages to all attributes having ErrorMessage=null and ErrorMessageResourceName=null (ie to all the ones with no other message already set).

The simplest way to achieve your goal is by setting `ErrorMessageResourceName`, and  and by providing a standard full resource file(ie one that creates a type) in the project root.

More specifically you may implement `IValidationMetadataProvider `and in its `CreateValidationMetadata` method just loop through the already added validation attributes and add the proper `ErrorMessageResourceName `and `ErrorMessageResourceType `to the ones with no other message already set.

Then you may add this provider to the MvcOptions in the Configure section with:
`options.ModelMetadataDetailsProviders.Add(new MyCustomValidationMetadataProvider());`

This way you retain the possibility to specify a message that is specific for a ViewModel, and at the same time you have overall defaults.

You can do this inn 20 minutes. Let me know if you need more details.

**Comment by amityagov** [comment] 2017-01-19 11:01
@frankabbruzzese

So if i need to provide localized messages for attributes not depend on where they placed i need to fill ErrorMessage property in model where the attribute placed? I am right?

**Comment by frankabbruzzese** [comment] 2017-01-19 11:20
@amityagov ,
No if you set `ErrorMessage `the string is localized in a way that depends on the ViewModel it is placed in.
A resource file will be searched in a file path that contains the ViewModel type name as explained in the [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization). 

If you **dont want this** you need to use `ErrorMessageResourceName` and `ErrorMessageResourceType` instead. You may also fill them automatically by writing a `IValidationMetadataProvider`, as I explained above.

**Comment by CGollhardt** [comment] 2017-11-09 00:06
For reference, @frankabbruzzese  has blogged about his approach:

https://blogs.msdn.microsoft.com/mvpawardprogram/2017/05/09/aspnetcore-mvc-error-message/

Thank you by the way :)
