### ISSUE TITLE
ValidateAntiForgery Attribute Breaks with Cookies Disabled and More

### ISSUE THREAD

**Issue by Bojanema** [aspnet/Mvc#7086] opened 2017-11-25 23:16 UTC
I have 2 scenarios where this attribute is giving me a headache. 

Scenario 1:  I disable browser cookies, I try to do a post to login via external provider and then I get a blank page. No Errors, no nothing. However, if I remove my attribute then I get redirected to Google as expected.

I tried putting break points but they don't get hit. My URL indicates I am on the page of my action: mysite/Login/ExternalLogin. I am trying to graciously handle if cookies are disabled but this is preventing me from doing that.

Scenario 2: I login to my site, then I logout using `_signInManager.SignOutAsync();` and then I return the page, please keep in mind I do not redirect, I just return a view saying you are logged out. Then I click on Login button again and I get the same result. White page, no errors, no breakpoints hit. Url in the browser is correct. If I remove the attribute, everything works fine.

My theory is that the generated token doesn't match when it tries to check. This results in somehow giving me a blank page, not even my global catchall filter that I have doesn't get triggered.

**Comment by mkArtakMSFT** [comment] 2018-04-24 17:29
Thanks for contacting us, @Bojanema.
@javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment] 2018-04-24 17:57
Hi,

Scenario 1: Antiforgery requires cookies to work, this is by design.
Scenario 2: We require/recommend you redirect after _signInManager.SignOutAsync(). Login in or login out doesn't change the identity of the user for the current request but for the next request. The recommended pattern to use for these operations is Post-Redirect-Get.

You are getting a blank page most likely because you are receiving a 400 response given that:
In scenario 1 there is no cookie token.
In scenario 2 the antiforgery token doesn't match the identity of the current user.

Closing this as there's no action to be done here.

Thanks.

**Closed by javiercn** 2018-04-24 17:57 UTC
Labels: investigate
