### ISSUE TITLE
anchor TagHelper ingores Class

### ISSUE THREAD

**Issue by ralfbalzer** [aspnet/Mvc#5401] opened 2016-10-12 10:28 UTC
I am using the achor Tag helper to create a link as follows:

`<a asp-controller="Haus" asp-action="Details" asp-route-hausTyp="@item.HausCat.NameLocalized" asp-route-HausName="@item.Name" asp-route-id="@item.Id" class="haus-link">.`

The output however ignores the class I set inside the tag:

`<a href="/de/Haus/Gruppenhaus/Les_Bosquets/Details/458">Gruppenhaus Les Bosquets</a>`

Is this by design or a bug?

**Comment by dougbu** [comment] 2016-10-12 16:59
@ralfbalzer something is strange here and it's definitely not by design. But I can't reproduce your issue in a quick attempt.

Do you have a more complete repro of this scenario, preferably a small GitHub repo we could look at?

**Comment by ralfbalzer** [comment] 2016-10-12 18:18
@dougbu I have given you access to my project.
Let me know if you have any questions.

**Comment by dougbu** [comment] 2016-10-12 18:52
Sorry, I can't see an accessible project. Please either make a public repository in your GitHub profile or (if the project contains proprietary info) send an email to `{my GitHub alias}@microsoft.com`.

**Comment by dougbu** [comment] 2016-10-12 19:27
Got it now. Was looking in the wrong place.

**Comment by Eilon** [comment] 2016-10-12 21:16
@dougbu can you see if this repros on 1.0.0 RTM as well?

**Comment by dougbu** [comment] 2016-10-17 17:01
@ralfbalzer when using your application with somewhat-random but sufficient data in the various tables, I am unable to reproduce this issue. The `AnchorTagHelper` generates
``` html
<a class="haus-link" href="/en/Haus/0/1/Details/13">
    <img style="width: 220px; display: block;" src="/images/haus/13/">
</a>
```
and
``` html
<a class="haus-link" href="/en/Haus/1/2/Details/14">
    <img style="width: 220px; display: block;" src="/images/haus/14/">
</a>
```

Is it possible I'm using a slightly different version of the code than you were when the problem was visible?

**Comment by dougbu** [comment] 2016-10-17 17:57
The other possibility is you're looking at the HTML generated for the second `<a>` element in `_accomodation.cshtml`. That one lacks a `class` attribute but has the same `asp-*` attributes in the source.

Note the `<img>` element in the first `<a>`, the text in the second, and the text in your generated HTML.

**Comment by dougbu** [comment] 2016-10-17 18:56
Closing. @ralfbalzer please reopen if I'm misreading something.

**Closed by dougbu** 2016-10-17 18:56 UTC
Labels: investigate
