### ISSUE TITLE
HttpDelete passed array by route or query doesn't parse properly

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/Mvc#8077] opened 2018-07-13 19:04 UTC
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Add an api endpoint like so:

        [HttpDelete("DeleteByIds/{id}")]
        public virtual async Task<ActionResult> DeleteByIds([FromRoute] int[] id)

id will always be empty

Also 
        [HttpDelete("DeleteById")]
        public virtual async Task<ActionResult> DeleteByIds([FromQuery] int[] id)

will always be empty

Also using IEnumerable<int> like classic WebApi also is empty.

#### Description of the problem:
HttpDelete should parse the array of params properly. In the case of /DeleteById/12,10,11 it should put those values in with the comma separated listed.

In the case of query it should do the same with /DeleteById?Id=10&Id=12&Id=11

None of these work.

Also the documentation isn't at all clear if Delete with a body works either so there really is no way to use proper REST and do a delete of multiple objects at the same time.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

2.1.2

**Comment by mkArtakMSFT** [comment] 2018-07-16 18:15
Thanks for contacting us, @JohnGalt1717.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment] 2018-07-16 21:52
@JohnGalt1717 thank you for your feedback. We're closing this issue as the behaviour discussed is by design.

Route values may only be atomic values and collections or complex types are not supported. A good indication of this is the list of available route constraints: https://github.com/aspnet/Routing/tree/release/2.2/src/Microsoft.AspNetCore.Routing/Constraints

Separately, the Delete method is normally used to delete a single resource and not an arbitrary set of resources.

**Closed by dougbu** 2018-07-16 21:52 UTC
Labels: investigate

**Comment by JohnGalt1717** [comment] 2018-07-16 22:13
Reasons you should strongly reconsider:

1.  You're breaking compatibility with asp.nwt web api for no reason causing major bugs and requiring rewrites of client code for all of those people you're encouraging to Port their code.

2. The http standard doesn't say that this is not allowed nor wrong.

3. I checked 15 other rest frameworks. They all support this.

4.  You're forcing people to write either syntactically incorrect code using Post or being inefficient multiple calls thus undermining the message that .net core is one of the fastest frameworks there is.

5. You're not throwing or doing anything useful, just not parsing anything even the first value.  That's the definition of bad coding even if you insist on not following what everyone else does, what is supported by the standard, is faster than your method and supports porting existing code.
