### ISSUE TITLE
Missing content-type header when content length 0 despite specifying Produces attribute on action

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/Mvc#7231] opened 2018-01-11 14:42 UTC
When using `[Produces("text/plain")]` and the body content length is 0 the content-type header is suppressed.

If the URL ends with something like ".png" Firefox and other browsers display an error similar to `The image “http://example.com/example.png” cannot be displayed because it contains errors.`

Could this be changed so that the header is output when the ProducesAttribute class is used?

This is mainly an issue when returning `Ok()` in an action.

**Comment by mkArtakMSFT** [comment] 2018-01-11 17:49
Thank you for contacting us.
To evaluate this feature request, we'd like to understand more about your scenario. Could you please elaborate on the scenario and the problem you're trying to solve? Specifically, how do you expect a browser to behave in case of a 0 length image?

**Comment by Matthew-Bonner** [comment] 2018-01-11 21:14
It isn't an image, just an empty response for when no response other than a 200 status code is acceptable.

Consider the following code:

    using ImageServer.Application;
    using Microsoft.AspNetCore.Mvc;

    namespace ImageServer.Controllers
    {
        public class CacheController : Controller
        {
            private readonly ICacheService _cacheService;

            public CacheController(ICacheService cacheService)
            {
                _cacheService = cacheService;
            }

            public IActionResult Flush(string id)
            {
                if (string.IsNullOrEmpty(id))
                {
                    _cacheService.Flush();
                }
                else
                {
                    _cacheService.Flush(id);
                }
            
                return Ok();
            }
        }
    }

The route:
{controller}/{action}/{id?}

And the requested URL:
http://example.com/cache/flush/example.png

Which in the context of this code is informing the cache to flush the file "example.png".

So I'm not requesting an image, I'm flushing the cache for that file, but because the URL ends in ".png" the browser assumes, because there is no content-type header when there should be, that I'm requesting an image.

So if I use the ProducesAttribute like so:
    using ImageServer.Application;
    using Microsoft.AspNetCore.Mvc;

    namespace ImageServer.Controllers
    {
        public class CacheController : Controller
        {
            private readonly ICacheService _cacheService;

            public CacheController(ICacheService cacheService)
            {
                _cacheService = cacheService;
            }

            [Produces("text/plain")]
            public IActionResult Flush(string id)
            {
                if (string.IsNullOrEmpty(id))
                {
                    _cacheService.Flush();
                }
                else
                {
                    _cacheService.Flush(id);
                }
            
                return Ok();
            }
        }
    }

I would expect the error to go away, but it doesn't because despite using the ProducesAttribute, no content-type is included in the response.

**Comment by mkArtakMSFT** [comment] 2018-01-12 17:42
Thanks for reporting this issue. We agree that this seems to be a minor bug and we've assigned one of our team members to look into this based on its priority.

**Comment by mkArtakMSFT** [comment] 2018-01-12 17:45
Actually, this may be something by design. We'll investigate this first.

**Comment by mkArtakMSFT** [comment] 2018-01-12 17:46
@rynowak, any thoughts? Is the ProducesAttribute meant to work only with ObjectResult-s?

**Comment by rynowak** [comment] 2018-01-12 19:10
Yes, that's correct. Those attributes only apply when you have some data to via objectresult. As a workaround for this, you could do something like:
```
return Content(string.Empty, "text/plain");
```

**Comment by mkArtakMSFT** [comment] 2018-01-12 21:39
Thank you for your feedback.
We're closing this issue as the behavior discussed seems to be by design.

**Closed by mkArtakMSFT** 2018-01-12 21:39 UTC
Labels: investigate
