### ISSUE TITLE
Change the checkbox fork in InputTagHelper to work with other TagHelpers

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#5983] opened 2017-03-17 18:19 UTC
Today the `GenerateCheckbox` method in our `InputTagHelper` is inserted into the body of the `TagHelperOutput`. Functionally this works but it prevents other TagHelpers from acting on the current TagHelperOutput's tagname, attributes etc. We originally built the `GenerateCheckbox` impl as is because we'd always generate a hidden input tag inline; now, we have access to PostElement AND we have a separate TagHelper that renders the hidden input tag.

**Comment by dougbu** [comment] 2017-04-05 15:33
Think this is a dupe of #5902. As I mentioned in response to that bug, need to handle the `!ViewContext.FormContext.CanRenderAtEndOfForm` case. Guess we could instead find a way to require end of `<form>` rendering support.

**Closed** 2017-05-05 18:54 UTC
