### ISSUE TITLE
Performance Issues with Html.DisplayFor()

### ISSUE THREAD

**Issue by mitchelsellers** [aspnet/Mvc#6796] opened 2017-09-08 14:45 UTC
Default project scaffolding for "List" views will result in a scaffolded display that will use your model with Html.DisplayFor() being used to output each of the individual values on the view.  An example of one of these is below.

```
<tbody>
    @foreach (var item in Model)
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegionName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegionDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BranchCount)
            </td>
            <td>
                <a asp-controller="Region" asp-action="Edit" asp-route-id="@item.RegionId" class="btn btn-primary">Edit</a>
            </td>
        </tr>
}
</tbody>
```
This example was pulled from a simple ViewModel that contained 4 properties, an int RegionId and BranchCount, as well as two string fields, max length of 250 chars.

Removing all other factors, including EF queries, if this view was rendered using the scaffolded code with 150-200 records the UI render was taking between 2.3 and 4.5 seconds to complete.  Changing the view display process to simply have the following layout, resulted in near instant rendering of the UI.

```
<tbody>
    @foreach (var item in Model)
{
        <tr>
            <td>
                @item.RegionName
            </td>
            <td>
                @item.RegionDescription
            </td>
            <td>
                @item.BranchCount
            </td>
            <td>
                <a asp-controller="Region" asp-action="Edit" asp-route-id="@item.RegionId" class="btn btn-primary">Edit</a>
            </td>
        </tr>
}
</tbody>
```
Initial diagnostic validation appear to show that the lookup of the display template when using DisplayFor might not be cached.  

## Environment Information
Initially confirmed using a .NET Core 1.1 application, validated as still an issue with a test project using .NET Core 2.0.  VS 2017 15.3 was used for all development.

Issue was still apparent when published in release mode and deployed to a server as well.

**Comment by Eilon** [comment] 2017-09-13 20:41
@mitchelsellers thanks for the report. This definitely sounds quite slow.

@pranavkm - can you profile this at least in 2.0 and see where the slowdown is? I would have thought that just about everything is super-duper cached, so rendering a total of ~1000 fields w/ DisplayFor should not take 2 - 4 seconds...

**Comment by Xeio** [comment] 2017-12-01 04:06
I'm seeing pretty large performance changes from a similar change to my own project using .Net Core 2.0, though not as bad as 2-4 seconds for 100 fields.

Using DisplayFor with around 1400 fields has a ~1.4s response time from the server for the full render, and using Razer inline syntax is ~300ms.

Not sure if that could be caching or what, I tried running a profiler against it and it wasn't particularly helpful other than pointing out that 50% of the CPU time was being spent inside the Html.DisplayFor method. I would not have expected such a method to be a huge performance hit.

**Comment by mitchelsellers** [comment] 2017-12-02 00:08
Just another update on this from my side as well.  I see similar results to what @Xeio reported, it is "better" but still very, very poor performance.

I also tried to profile but didn't get very far.

**Comment by merccat** [comment] 2018-02-21 18:11
I see the same issue using DisplayFor in an MVC project under .Net Framework (4.5.2).  The EF query completes and I have my enumerated collection for the view in less than a ms, yet when using DisplayFor the view takes about 6 seconds to render (2000 records containing 7 fields).  Worse, subsequent reloads of the page can result in out of memory exceptions occurring.  I also tried an overload, specifying which display template to use but the result was the same.  

Changing the view to simply display the values as @mitchelsellers did results in near instant page loads and no exceptions.

**Comment by mkArtakMSFT** [comment] 2018-02-23 21:50
@pranavkm, can you please look into this? Thanks

**Comment by pranavkm** [comment] 2018-02-23 21:59
I think @rynowak might have some investigating in to some of this already - see https://github.com/aspnet/Mvc/issues/6111. I'll sync up with next week to see if there's something actionable we could do for preview2

**Comment by mkArtakMSFT** [comment] 2018-03-06 01:45
@pranavkm, please work with @rynowak to get costs for this one.

**Comment by mkArtakMSFT** [comment] 2018-04-10 17:15
Pushed this out to `2.2.0`.

**Comment by DamianEdwards** [comment] 2018-04-16 04:34
This is concerning. Would be good to get this looked at sooner rather than later given the related report is a year old now.

**Comment by rickparrish** [comment] 2018-04-22 01:26
I ran into this today -- not sure if it's helpful, but I thought I'd add that when dealing with child objects the penalty is a significant problem.

Default scaffolded code = 20 seconds to display 250 records.  Example:
@Html.DisplayFor(modelItem => item.Project.Id)

Eliminate access of child object = 1.5 seconds.  Example:
@Html.DisplayFor(modelItem => item.ProjectId)

Eliminate @Html.DisplayFor instead = 80 milliseconds.  Example:
@item.Project.Id

This is using .NET Core 2.0. VS 2017 15.3

**Comment by kichalla** [comment] 2018-04-23 12:04
I tried this scenario with a new ASP.NET Core 2.0 & 2.1 MVC template based project and wasn't seeing the slowness being described here. I tried with 500 - 1500 records. Just to be sure, could any of you give us a simple repro project? Even better, if you could share the Perf profile results of what you are seeing.

**Comment by mitchelsellers** [comment] 2018-04-23 12:10
I would have to create a new sample for you given that this was a while back that I had this issue.  I can try to whip something up, but really it was nothing more than the initial example and comparing rendering times of both methods using the same data retrieval process.

**Comment by rickparrish** [comment] 2018-04-23 13:31
After submitting my last post I played around a bit more, and I found the 20 second penalty was only associated with nullable properties.  So for example in my class I have int? ProjectId, and accessing item.Project.Id via @Html.DisplayFor is incredibly slow.  I also have a non-nullable int ActivityId, and accessing item.Activity.Id does not result in a 20 second delay via @Html.DisplayFor.

In my case ProjectId is null probably 80% of the time.  I didn't think to test to see what would happen if it was only null 10% of the time, and I'm not in a position where I can test that right now.

So if you try again and still can't replicate the results with nullable properties let me know and I can probably put a new demo project together later tonight.

**Comment by mitchelsellers** [comment] 2018-04-23 14:10
Ah @rickparrish great observation, in my example one of the properties was a nullable int as well.

**Comment by kichalla** [comment] 2018-04-23 16:59
Sorry but I am still unable to see the kind of delay you guys are seeing. I have shared my repro project over here: https://github.com/kichalla/DisplayForSlow (Main files: [CustomersController](https://github.com/kichalla/DisplayForSlow/blob/master/DisplayForSlow/Controllers/CustomersController.cs), [View](https://github.com/kichalla/DisplayForSlow/blob/master/DisplayForSlow/Views/Customers/Index.cshtml))
You can take a look at it and see if I am missing anything.
Could you give us more details about the kind of environment where you are seeing this? like OS, Debug/Release, Kestrel/IIS, if inside a container, like Docker etc.

**Comment by rickparrish** [comment] 2018-04-23 18:00
Thanks for the starter project.  I don't have 2.1 installed so I downgraded to 2.0 and your project did not have the noticeable delay I experienced.  (The Address class was missing, so based on your code I added one with a nullable Zipcode.)

This wasn't quite the same setup as me though -- in your case a Customer always has an Address, but sometimes the Address does not have a Zipcode.  In my case it's more like my Customers only have an Address 20% of the time, so I modified your project by adding a new property that I only populate 20% of the time, and now I'm experiencing the slowness.

In the Index.cshtml file I've added a couple comments indicating how each of the options perform.

https://github.com/rickparrish/DisplayForSlow
[Index.cshtml comments](https://github.com/rickparrish/DisplayForSlow/blob/8a4b9dec77e1224af538f9f203e8dfbc843fe623/DisplayForSlow/Views/Customers/Index.cshtml#L60)

**Comment by pranavkm** [comment] 2018-05-01 17:04
The underlying issue seems to be https://github.com/aspnet/Mvc/issues/6928. Resolving the value for each of `@Html.DisplayFor(modelItem => item.TestNullable.Name)` results in a null ref (`TestNullable` is intended to be always null) and consequently, Mvc is try-catching 500 null refs (the sample is looping over a set of 500 items) which adds up. Using a bespoke `@item.TestNullable?.Name` doesn't have this issue. We've taken stabs at this in the past (https://github.com/aspnet/Mvc/pull/7181) without getting too far. 

@rickparrish  to answer your code comment `<!-- Convert all to @@item.FirstName syntax takes 50 milliseconds -->`, DisplayFor and EditorFor do a lot more work than writing an object out, so it's expected to be slower. However, I agree, 10+ seconds makes it pretty unusable.

cc @rynowak \ @dougbu since you have more context.

**Comment by rynowak** [comment] 2018-05-01 17:50
I thought the decision before was to try and fix the common cases of #6928 even though we'd never be able to solve all of them.

**Comment by pranavkm** [comment] 2018-05-01 18:07
@mkArtakMSFT  here's my suggestion for the issue:

*  Revive #6298 for 2.2.0 
* consider taking PR https://github.com/aspnet/Mvc/pull/7181 as is (assuming there's enough test coverage). There's also https://github.com/aspnet/Mvc/pull/7395 that we could consider in addition that touches some of these common areas.
* File a separate issue to track additional scenarios listed in https://github.com/aspnet/Mvc/pull/7181#issuecomment-362754479

It's a fairly small amount of work to do to address some very common scenarios.

**Comment by dougbu** [comment] 2018-05-01 20:13
@pranavkm when we decided not to take #7181, it led to large numbers of test failures. IOW it wasn't ready. The following comment in https://github.com/aspnet/Mvc/pull/7181#issuecomment-362754479 also means #7181 _undoes_ an existing optimization.
> the existing captured local variable case doesn't work together with the new rewriter

#7395 appears to have significant correctness issues. It assumes the only property on a view is `Model`.

And, no, we don't have enough test coverage of this area.

That said, would likely be beneficial to spend some time to rewrite Linq expressions to use `?.` / `?[`-equivalent nodes or to skip evaluation when `Model == null` and the expression is `m => m`, `m => Model.Property` and similar. My main point is that work should start from scratch.

**Comment by pranavkm** [comment] 2018-05-12 02:35
Tracking further work using https://github.com/aspnet/Mvc/issues/6928

**Closed by pranavkm** 2018-05-12 02:35 UTC
Labels: 2 - Working, Perf, investigate

**Comment by dougbu** [comment] 2018-05-13 02:25
@pranavkm we normally close a later issue as a duplicate of an earlier report. Your choice here reverses that. Suggest keeping this issue open instead. (It also contains more details about user scenarios where performance issues are visible.)
