### ISSUE TITLE
Add a way to identify top level model to the ModelBindingContext.

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#2425] opened 2015-04-21 22:32 UTC
We rely on the ContainerType to be null to determine if a object is top level. 
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ModelBinding/Binders/MutableObjectModelBinder.cs#L57

This logic is flawed as we create sub models while binding collections where the ContainerType is null. 

A fix for this would be to make ModelBindingContext aware of if it is a top level model.

**Comment by dougbu** [comment] 2015-04-21 22:44
dupe of #2203.  both are low-priority because we haven't come up with scenario where the "bug" (found through code inspection) makes any difference.

**Closed** 2015-04-22 21:34 UTC
Labels: duplicate
