### ISSUE TITLE
_ViewImports using clause not finding libraries...

### ISSUE THREAD

**Issue by adrianlmm** [aspnet/Mvc#4206] opened 2016-03-02 18:41 UTC
Greetings.

The type or namespace name 'Microsoft' could not be found (are you missing a using directive or an assembly reference?)

@using Microsoft.AspNetCore.Mvc;

I get this error, I'm using 1.0.0-rc2-16551

This worked fine before I updated, I was using 1.0.0-rc2-16357, I updated and renamed AspNet to AspNetCore.

**Comment by ajaybhargavb** [comment] 2016-03-14 23:42
@adrianlmm, I am unable to reproduce this error with the latest bits. Could you use the latest version and check if the problem still exists? If it does, it would be great if you can push a repro sample somewhere.

**Comment by pranavkm** [comment] 2016-03-15 00:02
Does your `project.json` have `"preserveCompilationContext": true`?

**Comment by SkyKnight** [comment] 2016-03-15 14:59
@ajaybhargavb I also have this issue with MusicStore example. I updated packages to rc2-20219 and changed runtime to rc2-16595 and there is still problem with _ViewImports usings.

**Comment by adrianlmm** [comment] 2016-03-15 15:21
@ajaybhargavb 

This is my Project.json

```
{
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "version": "1.0.0",

  "webroot": "wwwroot",

  "sources": [ "src" ],

  "frameworks": {
    "dnx451": {
      "frameworkAssemblies": {
        "System.Data": "",
        "System.Collections": "",
        "System.Drawing": "4.0.0.0"
      }
    }
  },

  "dependencies": {
    "Microsoft.AspNetCore.IISPlatformHandler": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "FirebirdSql.Data.FirebirdClient": "4.7.0.0",
    "Microsoft.Framework.Configuration.Json": "1.0.0-*",
    "Microsoft.AspNetCore.Session": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "jQuery.Validation": "1.14.0",
    "Aspose.Cells.dll": "1.0.1",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-*"
  },

  "commands": {
    "web": "grole"
  }
}


```

The Project is quite big to attach it here, but I'll make an small example.

**Comment by adrianlmm** [comment] 2016-03-15 15:37
I ran "dnu restore" and now I have a new error:

 'IServiceCollection' does not contain a definition for 'AddCaching' and no extension method 'AddCaching' accepting a first argument of type 'IServiceCollection'

So I can't make a simple test Project now.

**Comment by ajaybhargavb** [comment] 2016-03-17 18:11
@adrianlmm, Are you using `dnx` to run your app?
We recently moved away from `dnx` over to `dotnet`. If you are still using `dnx` to run, you might be hitting this https://github.com/aspnet/Announcements/issues/154. If so you need to add `Microsoft.AspNetCore.Mvc.Dnx` to your `project.json`.

Note that `dnu/dnx` is being deprecated. We recommend using `dotnet` (http://dotnet.github.io/) instead. [Here](http://www.hanselman.com/blog/ExploringTheNewNETDotnetCommandLineInterfaceCLI.aspx) is a blog post to help you get started.

**Comment by SkyKnight** [comment] 2016-03-20 11:51
@ajaybhargavb moving to dotnet command works for me :) Music store example still has some internal issues, but my private project render razor views without problems. Thanks!

**Comment by ajaybhargavb** [comment] 2016-03-21 19:04
Closing this issue. Please re-open if the issue still exists.

**Closed by ajaybhargavb** 2016-03-21 19:04 UTC
Labels: 2 - Working, bug
