### ISSUE TITLE
Flags enum property not being properly bound in some scenarios

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#2073] opened 2015-02-24 19:27 UTC
I came across the following question in SO today
http://stackoverflow.com/questions/28548607/mvc6-custom-model-binder-for-an-enum-with-the-flags-attribute

I was able to repro this issue. Should this scenario be supported by default? I think yes?

``` c#
public Person CreatePerson(Person person)
{
    return person;
}

public class Person
{
    public int Id { get; set; }

    public string Name { get; set; }

    public CarType CarType { get; set; }
}

[Flags]
public enum CarType
{
    None = 0,
    Coupe = 1,
    Sedan = 2,
    Limo = 4
}
```

Following input works(i.e the value of CarType property is Coupe | Sedan):
`person.CarType=Coupe,Sedan`

Does not work(i.e the value of CarType property is only Coupe ):
`person.CarType=Coupe&person.CarType=Sedan`

Code of interest for this issue:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ModelBinding/ValueProviders/ValueProviderResult.cs#L105

**Comment by rynowak** [comment] 2015-02-24 21:56
@kichalla what was the behavior in MVC5?

**Comment by rynowak** [comment] 2015-02-24 21:58
Possible regression? https://github.com/aspnet/Mvc/issues/165

**Comment by kichalla** [comment] 2015-02-24 22:34
Good questions, @rynowak ...this was `not` supported in MVC 5 too...

In the bug you referenced, the scenario seems to be similar to mine(except that the data is coming from uri). The tests as part of this commit do not seem to have be covering the scenario that the bug mentions but tests the comma separated scenario.

**Comment by rynowak** [comment] 2015-02-24 23:36
If you think that we're missing tests for an **already supported scenario** then please just add them if it's quick, otherwise open a separate issue.

**Comment by danroth27** [comment] 2016-08-19 04:32
@kichalla @Eilon Is this a duplicate of #3977?

**Comment by Eilon** [comment] 2016-11-15 18:54
Closing because we have no plans to support this.

**Closed by Eilon** 2016-11-15 18:54 UTC
Labels: 0 - Backlog, enhancement, wontfix
