### ISSUE TITLE
Last registered mvc configuration override to all mvc services

### ISSUE THREAD

**Issue by oguzhaneren** [aspnet/Mvc#5138] opened 2016-08-12 22:59 UTC
Here my code, 

I want to create branch base service provider so my code here:

When I set mvc configs for "b1/{*path}" branch, its apply this settings to other branches.

I except when I go /b1/api/values it must be return result as xml format
I except when I go /b2/api/items it must be return result as json format (default format) 

but two result are same, xml format.

```

     public class Startup2
    {

        private IServiceCollection _services;

        public Startup2(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            _services = services;
            services.AddRouting();
        }


        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            CreateBranch(app, "b2/{*path}",
                options =>
                {

                });

             CreateBranch(app, "b1/{*path}",
                options =>
                {
                    options.OutputFormatters.Clear();
                    options.OutputFormatters.Add(new XmlSerializerOutputFormatter());
                });

        }

        private void CreateBranch(IApplicationBuilder app, string path, Action<MvcOptions> mvcConfigure = null)
        {
            var routeBuilder = new RouteBuilder(app);
            var routeTemplate = path;

            routeBuilder.MapRoute(routeTemplate, (IApplicationBuilder branch) =>
            {
                var ss = _services;
                IServiceCollection serviceCollection = new ServiceCollection();
                foreach (ServiceDescriptor service in ss)
                {
                    serviceCollection.Add(service);
                }
                serviceCollection.AddMvc(c => mvcConfigure?.Invoke(c));
                serviceCollection.AddScoped<IQueryService, DummyQueryService>();
                serviceCollection.AddScoped<IConnectionStringFactory>((sp) => new DummyConnectionStringFactory(""));
                serviceCollection.AddScoped<INotificationService, LogNotificationService>();
                branch.ApplicationServices = serviceCollection.BuildServiceProvider();

                branch.UseMvc().ApplicationServices = branch.ApplicationServices;

            });


            var router = routeBuilder.Build();
            app.UseRouter(router);
        }
    }
```

**Comment by Eilon** [comment] 2016-08-13 00:34
@sebastienros any ideas?

**Comment by danroth27** [comment] 2016-08-15 17:05
Please note that If all you really want to do is control which formatter gets used for a particular endpoint, you could do that with the `ProducesAttribute`. See https://docs.asp.net/en/latest/mvc/models/formatting.html#forcing-a-particular-format.

**Comment by sebastienros** [comment] 2016-08-15 17:46
@oguzhaneren what you are describing is called multi-tenancy, even though you could think it is not (https://twitter.com/oguzhannet/status/762702383185100800)

But you don't just need multi-tenancy, it's MT with custom services for each tenant which is harder. I know you are already looking at SaasKit as suggested in order to accomplish it (https://github.com/saaskit/saaskit/issues/41).
Another way is to either use or reproduce what https://github.com/OrchardCMS/Orchard2 is doing as it supports this already.

The general idea we apply in Orchard is to create an many containers as there are tenants, and have a middleware that switches the current container in a request, based on the selected tenant. Each tenant gets it's own midleware pipeline. There can also be common middlewares.

In the end there is no issue with regards to registering configuration and services. it's working as advertised, but solving your issue requires custom plumbing for tenants and probably modules management, which both SaasKit and Orchard2 provide sample implementations for.

**Comment by oguzhaneren** [comment] 2016-08-19 18:00
@sebastienros 

> it's MT with custom services for each tenant

yes, that's I need.

I implemented containers each tenant (branch) but I need extra services (mvc,nancy,signalr,ef) and configuration for that tenants.

Above example works like buggy (maybe last registered mvc set a static variable)

**Comment by oguzhaneren** [comment] 2016-08-20 13:17
finally I implemented it: https://github.com/oguzhaneren/AspNetCoreComposition

**Comment by davidfowl** [comment] 2016-08-20 14:43
https://github.com/oguzhaneren/AspNetCoreComposition/blob/master/Shared/BranchBuilder.cs#L29

That line isn't right. You need to get an `IServiceScopeFactory` and to make and dispose a scope per request for e.g https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/RequestServicesContainerMiddleware.cs

**Comment by oguzhaneren** [comment] 2016-08-21 11:19
@davidfowl why I need to another scope? (scope in scope) Main request already creates a scope

**Comment by davidfowl** [comment] 2016-08-21 15:29
> @davidfowl why I need to another scope? (scope in scope) Main request already creates a scope

You're overwriting the main request's service provider in your middleware with a non-scoped service provider. 

Take a look at aspnet-contrib, it has some hosting extensions that are useful for this scenario https://github.com/aspnet-contrib/AspNet.Hosting.Extensions/blob/dev/src/AspNet.Hosting.Extensions/HostingExtensions.cs#L144.

**Comment by Eilon** [comment] 2017-06-09 22:10
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by Eilon** 2017-06-09 22:10 UTC
Labels: question
