### ISSUE TITLE
ModelBinding does not like setter only properties

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Mvc#4646] opened 2016-05-16 14:54 UTC
Hi Guys, 

It's me again, trying to do things with modelbinding that I thought should be possible but are not.
This time it's trying to modelbind to an object like this  that has shadowed properties.

``` cs
public class Query: BaseQuery {
   [CsvConverter]
   public new ICollection<string, string> Status {set { base.Status = value; }}

   public new string AnotherProp {set { base.AnotherProp = value; }}
}
```

This should work just fine but modelbinding decides that any shadowed property is no longer a property of the model and it completely disappears in the ModelMetadata.Properties.

Why have I created it like this? Separation of concerns, I have a few Query objects in another project with handlers that get called via MediatR and I do not want to decorate these with attributes for MVC concerns, I also don't want to make everything virtual for the sake of "maybe I need to override these in another project". 

EDIT: Just tried this with virtual properties as I want to continue in the meantime, exactly the same problem. That shadows don't work alright, but no virtuals is kind of shocking.

**Comment by Eilon** [comment] 2016-05-16 18:55
@rynowak / @dougbu I recall some discussions a looooooong time ago about not supporting `new` properties - do you remember anything about this?

The `virtual` property thing is indeed surprising...

**Comment by rynowak** [comment] 2016-05-16 19:27
Decision long back was that we would explicitly not support shadowed properties. Virtual properties not working would be a big surprise and a serious bug.

@NinoFloris can you post a sample of your model class that isn't working with virtual properties and the input data that you expect to be bound?

**Comment by Eilon** [comment] 2016-05-20 05:27
@NinoFloris any chance you can share more details about the virtual properties on your model types?

**Comment by Eilon** [comment] 2016-05-24 23:57
@NTaylorMullen can you try to repro this issue with virtual properties? And/or check if we have a unit test for this (and if not, add one).

**Comment by NTaylorMullen** [comment] 2016-05-26 00:18
@NinoFloris I'm trying out a scenario with virtual/overridden properties with a custom `ModelBinder` and all seems to work fine. Could you provide a simple repro project for me to take a look at?

**Comment by NTaylorMullen** [comment] 2016-05-26 18:51
Closing until we're able to get a repro to investigate the issue.

**Comment by NinoFloris** [comment] 2016-05-31 17:08
Ok sorry guys, it was all smoke and mirrors but I have found out the root cause.

https://github.com/aspnet/Common/blob/dev/src/Microsoft.Extensions.PropertyHelper.Sources/PropertyHelper.cs#L507

This property helper class gets called in the DefaultModelMetadataProvider and weeds out all the 'interesting properties' based on this little predicate.

The problem is however, that for modelbinding there should be no reason why I could not have a setter only property.

There is even separate branching in the code for the getters and setters of properties. https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Metadata/DefaultModelMetadataProvider.cs#L160

Would you consider fixing this?

P.S. On the upside because the PropertyHelper is used, shadowed properties are working great though!

**Comment by dougbu** [comment] 2016-05-31 18:09
The getter requirement is intentional. One set of rules just makes sense for most end-to-end scenarios. For example though model binding might be able to handle setter-only properties, HTML generation and output formatting could not.

**Comment by NinoFloris** [comment] 2016-05-31 18:54
Ah so intentional that everyone could within minutes point me to the issue with my example.
So intentional that it almost sounds like "We don't want to put in the effort even though the behaviour is not logical for ModelBinding".
And finally great that three layers away from this public api it was decided to restrict all things related to properties to a silly subset.

I know I'm being condescending but I don't believe it was really 'designed' this way. Rather this is now an issue after the fact and being waved away as intentional. As is clearly visible in the DefaultModelMetadataProvider code where there is a branch for getters and one for setters.

**Comment by dougbu** [comment] 2016-05-31 19:08
I'm sorry you're annoyed but please note the decision was not made from an implementation perspective. Different rules for different parts of the system would be complicated _for users_ and a major compatibility break with earlier MVC releases. Feel free to reopen this issue if you feel strongly about it.

What do you mean by "one for setters" in `DefaultModelMetadataProvider`? That class has about the same amount of code for the `ModelMetadata.PropertyGetter` and `PropertySetter` properties.

**Comment by NinoFloris** [comment] 2016-05-31 19:13
Ok I'm sorry for my tone, that was not constructive.

I mean that the DefaultModelMetadataProvider already does the check if a property's getter is public and only then sets the propertyEntry.propertyGetter. 

So it is too bad that the properties it gets from the PropertyHelper wil never have any need for this check, as they will always have a public getter.

That is what I mean with, it seems that it used to work with setter only (by that I mean no public getter) properties.

**Comment by dougbu** [comment] 2016-05-31 19:20
> it seems that it used to work with setter only (by that I mean no public getter) properties.

If you're correct, not supporting get-only properties would be a regression from MVC 5.x. Let us know if  you've tested this and definitely reopen the issue if so.

**Comment by NinoFloris** [comment] 2016-05-31 19:24
> If you're correct, not supporting get-only properties would be a regression from MVC 5.x. Let us know if you've tested this and definitely reopen the issue if so.

set-only you mean right?

**Comment by dougbu** [comment] 2016-05-31 19:26
Ooops, yup.

**Comment by NinoFloris** [comment] 2016-05-31 19:49
Actually it sort of is a regression, as seen below.

I don't have good access to your commit history before you opensourced but following the trail it lead me to this old web api version of the PropertyHelper, found in multiple places with the same contents.

> http://sourcebrowser.io/Browse/ASP-NET-MVC/aspnetwebstack/src/Common/PropertyHelper.cs#170
> https://github.com/ASP-NET-MVC/aspnetwebstack/blob/master/OData/src/Common/PropertyHelper.cs
> 

It has the check inside the GetProperties function at line 170, where it does check if the getter is not null but it does not check if the getter is public, which in most modelbinding cases is the same, as you cannot call a private getter from inside a ModelBinder.

This corresponds to the fact that at this commit:

> https://github.com/aspnet/Mvc/blob/90cef3b9ca86f56bd49700f632474e7db068816a/src/Microsoft.AspNet.Mvc.ModelBinding/Metadata/DefaultModelMetadataProvider.cs#L107

DefaultModelMetadataProvider still calls GetProperties, not GetVisibleProperties as it does now, because it was not there in the previous versions of the PropertyHelper.

**Comment by dougbu** [comment] 2016-05-31 22:00
I was thinking about testing more than source changes. For one thing MVC 5 doesn't use `PropertyHelper` in its [`DefaultModelBinder`](http://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Web.Mvc/DefaultModelBinder.cs). Would also be good to know the Web API 3.x behaviour.

I bet we intentionally removed support for model binding non-`public` properties. Can't find the issue at the moment though.

FYI all of the previous Web API 3.x / MVC 5 code is available at http://aspnetwebstack.codeplex.com/

**Comment by Eilon** [comment] 2016-06-08 21:26
Moving to Backlog as we are not planning to make any changes here at this time. We urge apps to not use set-only properties or non-public properties for model binding or rendering.

**Comment by Eilon** [comment] 2016-11-15 21:04
Closing because we have no plans to support this.

**Closed by Eilon** 2016-11-15 21:04 UTC
Labels: wontfix
