### ISSUE TITLE
ValidationSummary tag helper should not render the tag if there are not items to render

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#5209] opened 2016-08-31 18:45 UTC
With `<div asp-validation-summary="ModelOnly"></div>`:

On `GET`
![image](https://cloud.githubusercontent.com/assets/1165805/18141863/04e1e652-6f70-11e6-848f-56670663b6d0.png)

On `POST` with errors
![image](https://cloud.githubusercontent.com/assets/1165805/18141887/181a3ad0-6f70-11e6-8116-5876d193e4b3.png)

On `POST` without errors in the model
![image](https://cloud.githubusercontent.com/assets/1165805/18141937/414dd696-6f70-11e6-813e-4398299b9b26.png)

In this last screenshot, there are no model errors, however there are non-model errors. The div should not be rendered.

**Comment by dougbu** [comment] 2016-09-01 02:42
@sebastienros is this a dupe of #2372?

Or are you requesting a behaviour change for the "client-side validation enabled but `ModelOnly` requested case" from checking `IsValid` to checking whether `ModelState` includes errors for the current `Model`?

I ask in part because "model errors" versus "non-model errors" doesn't align with the meaning of `ModelOnly`. To make that more clear, consider a template view for a POCO class somewhere in the model tree. `<div asp-validation-summary="ModelOnly"</div>` in that view will list errors in the `ModelState[ViewData.TemplateInfo.HtmlFieldPrefix]` key but nothing else. On the other hand, `<div asp-validation-summary="All"></div>` will list _every_ error in `ModelState` i.e. for properties of the POCO class, the current instance of that class, everything above it, and so on.

**Comment by dougbu** [comment] 2016-09-03 00:07
Talked offline w/ @sebastienros and the #2372 may be useful for his scenarios. But the change in behaviour I described above fixes the particular bug he hit here.

**Comment by dougbu** [comment] 2016-09-08 23:12
eee1a9f

**Closed by dougbu** 2016-09-08 23:12 UTC
Labels: 2 - Working, bug
