### ISSUE TITLE
Error in UseOpenIdConnectAuthentication middleware!

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Mvc#3195] opened 2015-09-24 08:37 UTC
I ran my web application with web command :
` "web": "Microsoft.AspNet.Hosting --ASPNET_ENV development --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:49102"`
This is the error that shown in console:

```
System.MissingMethodException: Method not found: 'Void Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.set_RequireState(Boolean)'
.
   at Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectOptions..ctor(String authenticationScheme)
   at Microsoft.AspNet.Builder.OpenIdConnectExtensions.UseOpenIdConnectAuthentication(IApplicationBuilder app, Action`1 configureOptions)`
```

I try to use this code but not worked:
```c#
app.UseOpenIdConnectAuthentication(options =>
            {
                options.ProtocolValidator =new OpenIdConnectProtocolValidator
                    {
                        RequireStateValidation=false
                    };
...
```

**Comment by rynowak** [comment] 2015-09-24 15:09
A `MethodMissingException` is almost always a binary mismatch. Can you please double check that you're not mixing releases of packages/dnx - look at your dnx version, project.json and output of `dnu list` at the commandline.

**Comment by mikeandersun** [comment] 2015-09-24 15:54
After many time restoring of packages. I get the following error when run it with Kestrel:
System.InvalidOperationException: This application requires DNX version 1.0.0-beta8-15665 or newer to run.
I stop my work and wait for next nightly build, maybe will solve this issue. :(

**Comment by Eilon** [comment] 2015-09-24 17:57
Closing for now because this is definitely a build mismatch. Ensure you're using either a nuget.org release (beta7), or the latest of all the packages (beta8-*).

**Comment by Eilon** [comment] 2015-09-24 17:58
If you're still seeing an issue please share a repro project on GitHub (or wherever).

**Comment by mikeandersun** [comment] 2015-09-25 12:50
I have the issue yet. [This](https://github.com/mikeandersun/experimental) is an Experimental repo.
Thanks a loat for your time.

**Comment by Eilon** [comment] 2015-09-25 17:11
@NTaylorMullen can you have a look and see what the issue is?

**Comment by NTaylorMullen** [comment] 2015-09-25 17:33
Will do

**Comment by NTaylorMullen** [comment] 2015-09-25 18:23
Investigated and it's a binary mismatch of `Microsoft.IdentityModel.Protocols.OpenIdConnect`. You specify this in your `project.json`:
![image](https://cloud.githubusercontent.com/assets/2008729/10108673/22cf84c2-6377-11e5-83a7-fc2652be145f.png)

Which results in the following version of the package being brought in:
![image](https://cloud.githubusercontent.com/assets/2008729/10108689/38b2894c-6377-11e5-8ae1-eff6d58d7250.png)

This conflicts with the version that `Microsoft.AspNet.Authentication.OpenIdConnect` brings in. It brings in [2.0.0-beta7-*](https://github.com/aspnet/Security/blob/852f44a3691c02c379b586fe7ef3dc0cb4cea6ab/src/Microsoft.AspNet.Authentication.OpenIdConnect/project.json#L11).

So if you remove your `project.json` dependency and rely on the version we bring in you end up with:
![image](https://cloud.githubusercontent.com/assets/2008729/10108747/988d15da-6377-11e5-997b-35823bc661fd.png)

This results in your `Startup.cs` breaking when you try to do [this](https://github.com/mikeandersun/experimental/blob/6d9c807621e7399e2638b9801e3d795420214800/source/OpenIdExperinces/Startup.cs#L93). You can fix it by doing `RequireState = false` instead.

**Closed by NTaylorMullen** 2015-09-25 18:23 UTC
Labels: invalid
