### ISSUE TITLE
Changing `RazorViewEngineOptions` or `RazorPagesOptions` breaks view searches within dependencies

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7346] opened 2018-02-10 20:40 UTC
For example, in an application based on a template using Individual Accounts, changing `RazorPagesOptions.RootDirectory` to `/` makes all Identity-related pages return 404s. This is not (yet) a bug in Microsoft.AspNetCore.Identity.UI because MVC provides no independent way to control page location formats in libraries.

Because we intend to support 3rd party libraries containing pages and views, this problem is not specific to Microsoft.AspNetCore.Identity.UI.

Some possibilities:
1. Remove all view and page location format-related options
  Yeah, an egregious breaking change
1. Ignore the view and page location format-related options when retrieving pages and views in external (non-application) assemblies
1. Fall back to the default view and page location formats when overridden locations find nothing
  This will of course result in extra I/O and unexpected success cases
1. Support `assembly:` attributes controlling the view and page locations in an assembly
  Logged warnings when these attributes are *not* used in an application that overrides view and page location format-related options may help if we go this route

**Comment by mkArtakMSFT** [comment] 2018-03-15 21:02
Pushing this to the next milestone so we can collect more data. If we hear many customers asking for these customizations we'll reconsider our decision. For now the current approach is by design.

**Comment by mkArtakMSFT** [comment] 2018-05-14 21:18
Closing as there were no community involvement at all.

**Closed by mkArtakMSFT** 2018-05-14 21:18 UTC
Labels: investigate
