### ISSUE TITLE
MSB4018 The “GenerateEmbeddedResourcesManifest” task failed unexpectedly

### ISSUE THREAD

**Issue by dudedev** [aspnet/Mvc#8121] opened 2018-07-20 09:06 UTC
#### Description of the problem:
I am trying to add localization to my web app(using Aspnetcore 2.1.1 and Razor pages). However, the moment I add more than one .resx file, it fails to compile with following error.

```
Error	MSB4018	The "GenerateEmbeddedResourcesManifest" task failed unexpectedly.
System.InvalidOperationException: An item with the name '' already exists.
   at Microsoft.Extensions.FileProviders.Embedded.Manifest.Task.Internal.Entry.AddChild(Entry child)
   at Microsoft.Extensions.FileProviders.Embedded.Manifest.Task.Manifest.AddElement(String originalPath, String assemblyResourceName)
   at Microsoft.Extensions.FileProviders.Embedded.Manifest.Task.GenerateEmbeddedResourcesManifest.BuildManifest(EmbeddedItem[] processedItems)
   at Microsoft.Extensions.FileProviders.Embedded.Manifest.Task.GenerateEmbeddedResourcesManifest.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Service	C:\Users\.nuget\packages\microsoft.extensions.fileproviders.embedded\2.1.1\build\netstandard2.0\Microsoft.Extensions.FileProviders.Embedded.targets	65	
```

#### Possible cause of the issue
Problem is the content of generated manifest file "Microsoft.Extensions.FileProviders.Embedded.Manifest.xml". The manifest file generator adds this line for one *.resx file.
`<File Name=""><ResourcePath></ResourcePath></File>`.  When the generator finds another *.resx file, it tries to add the same line to the manifest xml, and fails saying "An item with the name '' already exists."

**Comment by ryanbrandenburg** [comment] 2018-07-27 22:17
@dudedev could you create a minimal reproduction app which displays this behavior? This guarantees that we're looking at the same problem you're having.

**Comment by dudedev** [comment] 2018-07-31 11:26
@ryanbrandenburg I have created a sample app with the problem. How do you want me to share the source code?

**Comment by dudedev** [comment] 2018-07-31 11:34
@ryanbrandenburg Steps to reproduce:
1. Create a wepapp using template "ASP.NET Core Web Application"
2. Edit .csproj file to include `<GenerateEmbeddedFilesManifest>True</GenerateEmbeddedFilesManifest>` under `<PropertyGroup>`.
3. Add two resources files e.g. Resources.en.resx and Resources.de.resx
4. Build the project, you should see the build error

**Comment by mkArtakMSFT** [comment] 2018-07-31 17:40
@dudedev, please share it as a public repo in GitHub?

**Comment by dudedev** [comment] 2018-07-31 17:58
https://github.com/dudedev/MSB4018

**Comment by mkArtakMSFT** [comment] 2018-08-01 16:55
Thanks @dudedev.
@ryanbrandenburg, its all yours now!

**Comment by ryanbrandenburg** [comment] 2018-08-02 23:59
Thanks @dudedev, this did end up replicating. I was able to track the failure down to [this area](https://github.com/aspnet/FileSystem/blob/release/2.2/src/FS.Embedded.Manifest.Task/GenerateEmbeddedResourcesManifest.cs#L93) in aspnet/FileSystem. It seems that that task is not very robust, and makes the assumption that EmbeddedResource.LogicalName will always have a value. This is not the case for the default EmbeddedResources created for .resx files.

@mkArtakMSFT who knows that area the best? It looks like @javiercn did some work in there but I don't know if he's a SME who would be best situated to fix this.

@dudedev, in the mean time it's not ideal, but you can both generate your embedded files manifest and have these resx files embedded by setting `<EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>` in your propertyGroup and doing something like
```
<ItemGroup>
    <EmbeddedResource Include="Resources/Resource.de-DE.resx">
      <LogicalName>Resources/Resource.de-DE.resx</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources/Resource.en-US.resx">
      <LogicalName>Resources/Resource.en-US.resx</LogicalName>
    </EmbeddedResource>
</ItemGroup>
```

to manually embed the resources.

**Comment by javiercn** [comment] 2018-08-03 02:12
I’m the right person to look at this. This is a patch candidate I think. @natemcmaster sorry for ruining your day :(

**Comment by mkArtakMSFT** [comment] 2018-08-03 16:59
Thanks @ryanbrandenburg.
@javiercn, can you please look into this further and confirm whether this will be a patch candidate or not.

**Comment by javiercn** [comment] 2018-08-03 17:47
@dudedev I can't reproduce this with my version of the SDK. I think this was caused by a change in the definition of the EmbeddedResource made in the SDK (which change, I don't know for sure). In any case, I think this is a transient issue. You can exclude the resource files from the manifest as exemplified below and that should fix the problem:

```xml
<ItemGroup>
    <EmbeddedResource Include="Resources/Resource.de-DE.resx">
      <LogicalName>Resources/Resource.de-DE.resx</LogicalName>
      <ExcludeFromManifest>true</ExcludeFromManifest>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources/Resource.en-US.resx">
      <LogicalName>Resources/Resource.en-US.resx</LogicalName>
      <ExcludeFromManifest>true</ExcludeFromManifest>
    </EmbeddedResource>
</ItemGroup>
```

I'm closing the issue as there no more action to take from us at this point.
@dudedev If this doesn't solve your issue let us know.

Thanks for bringing this up.

**Closed by javiercn** 2018-08-03 17:47 UTC
Labels: investigate
