### ISSUE TITLE
Razor Views do not recompile when directories with large numbers of files are present in the project tree

### ISSUE THREAD

**Issue by nlowe** [aspnet/Mvc#7028] opened 2017-11-06 04:43 UTC
First off, I've been tearing my hair out for the past few hours trying to figure out what's causing this so if this isn't the right repo to report this in, feel free to move it.

## Problem

If the `material-design-icons` package from npm is present in the `node_modules` directory, Razor templates do not get compiled on subsequent requests. This seems to be some limit with the number of files in the project tree. This package has 89,814 files in it. I was able to reproduce this by creating 10,000 empty files in a directory:

```powershell
1..10000 | ForEach-Object { New-Item -ItemType File -Path foo -Name ([Guid]::NewGuid().Guid.ToString()) | Out-Null }
```

Removing this package (and my test folder if I created it) causes views to be recompiled on new requests after they are modified on disk.

### Steps to Reproduce

1. Create a new MVC project: `dotnet new mvc`
2. Create `10000` empty files in a folder in the project:
    * `mkdir foo`
    * `1..10000 | ForEach-Object { New-Item -ItemType File -Path foo -Name ([Guid]::NewGuid().Guid.ToString()) | Out-Null }`
        * linux: `for i in {1..10000}; do mktemp -p foo > /dev/null; done`
3. `dotnet run`
4. Open `http://localhost:5000` in a browser
5. Modify `Views/Home/Index.cshtml` and reload the page in the browser

**Expected Result**: The view is recompiled and updated after the page reloads

**Actual Result**: The request returns almost instantly and is not updated. No warnings are printed in the console with the standard project template.

### Attempted Workaround

After removing my test folder, I tried the following to exclude the `node_modules` folder from consideration in hopes that it would be ignored when views should be recompiled:

```xml
  <ItemGroup>
    <Compile Remove="node_modules\**" />
    <Content Remove="node_modules\**" />
    <EmbeddedResource Remove="node_modules\**" />
    <None Remove="node_modules\**" />
  </ItemGroup>

  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);node_modules\**\*.*</DefaultItemExcludes>
  </PropertyGroup>
```

This had no effect: after modifying views on disk, I had to `ctrl+c` and run `dotnet run` again for the view to update.

## Question

Is there a way to exclude the entire `node_modules` folder from the system? I am using `webpack` and don't need access to it at runtime. This seems like a really easy limit to hit on any project that uses a decent amount of frontend packages from `npm`.

**Comment by pranavkm** [comment] 2017-11-06 17:10
@nlowe what OS \ platform did you see this issue in? We had report of an issue on CentOS where the FileSystemWatcher was getting overwhelmed when the app had a large number of files and stopped reporting changes. One workaround to unblock you in the meanwhile is to enable polling to detect file system changes. Set this environment variable `DOTNET_USE_POLLING_FILE_WATCHER=1` and run the app. Perhaps that might help.

The work to investigate here is to figure out if we're adding a watcher that listens to the node_modules directory at runtime and see if there's a reasonable solution that avoids doing this.

**Comment by nlowe** [comment] 2017-11-06 17:14
I'm on Arch Linux. I don't have access to my machine right now but I'll test that out and get back to you.

**Comment by nlowe** [comment] 2017-11-06 22:59
@pranavkm setting that environment variable seems to work for my use case. Would this be a bad thing to set in a bash profile so I don't have to remember to set it every time?

**Comment by pranavkm** [comment] 2017-11-06 23:21
@nlowe there's a small amount of extra I/O involved when you request a view. I would avoid using this in a production environment, but it's entirely harmless locally. In fact, setting this flag up is a staple of container based development workflows.

**Comment by nlowe** [comment] 2017-11-07 02:59
Good to know.

> The work to investigate here is to figure out if we're adding a watcher that listens to the node_modules directory at runtime and see if there's a reasonable solution that avoids doing this.

Is there anything you need me to try regarding this?

**Comment by pranavkm** [comment] 2017-11-07 05:07
@nlowe not at this point. We'll bother you if we are unable to reproduce the issue. I'll leave the issue open so we can track the work.

**Comment by mkArtakMSFT** [comment] 2018-04-25 17:45
@pranavkm, was there any investigation done here?

**Comment by pranavkm** [comment] 2018-05-01 18:55
I tried this on Ubuntu 16.04 back in December, but I couldn't reproduce the issue. At least it didn't seem like the issue was inherent to the way xplat does file system watching. 

* @stephentoub would you know if there's a hard limit on the number of files that can be present in a directory on Centos \ ArchLinux for the FileSystemWatcher stops producing change events?
* More generally, only relying on FileSystemWatcher to work out changes is kinda problematic since it is limited by things like buffer sizes - https://msdn.microsoft.com/en-us/library/system.io.filesystemwatcher(v=vs.110).aspx#Anchor_6. We should consider baking in polling alongside events from FSW. It's the only way to guarantee eventual consistency.

**Comment by rynowak** [comment] 2018-05-01 18:59
>We should consider baking in polling alongside events from FSW. It's the only way to guarantee eventual consistency.

This a million times.

If you're in a dev environment, it's ok if the filewatcher approach works 99.9% of the time. 

If you're using this production then you will have problems, and I don't think we should spend time trying to make it foolproof.

**Comment by pranavkm** [comment] 2018-05-01 22:59
> If you're using this production then you will have problems

This would play well with https://github.com/aspnet/Mvc/issues/6643 feature. Have it be off for users that don't care about reloading views in production, but have a setting that turns it on.

**Comment by stephentoub** [comment] 2018-05-09 00:35
> would you know if there's a hard limit on the number of files that can be present in a directory on Centos \ ArchLinux for the FileSystemWatcher stops producing change events?

FileSystemWatcher uses `inotify` on Linux.  I'm not aware of any limit on the number of files, but there are several other limits, which you can both see and set via procfs:
- http://linuxinsight.com/proc_sys_fs_inotify_max_queued_events.html
- http://linuxinsight.com/proc_sys_fs_inotify_max_user_instances.html
- http://linuxinsight.com/proc_sys_fs_inotify_max_user_watches.html

**Comment by rynowak** [comment] 2018-05-09 03:37
The following is not directed at @nlowe  .... 😆 

--- 

I feel like we need a standard response to these issues, or documentation, or to make the polling file-watcher the default. We know that file watching is a best-effort mechanism. We (MVC) also don't directly control any of these things and we can't react to them. 

I think we should set the expectation that you shouldn't rely on the filewatcher in production.

**Comment by mkArtakMSFT** [comment] 2018-05-11 21:34
Closing this issue in favor of https://github.com/aspnet/Home/issues/3135

**Closed by mkArtakMSFT** 2018-05-11 21:34 UTC
Labels: investigate
