### ISSUE TITLE
Global exception handling no longer works in ASP.NET Core 2.0

### ISSUE THREAD

**Issue by sebastianbk** [aspnet/Mvc#6690] opened 2017-08-21 10:15 UTC
I recently upgraded my ASP.NET Core 1.1 project to 2.0 and, as a result, my way of handling exceptions globally no longer works. A couple of months ago I implemented [Scott Sauber's suggestion](https://scottsauber.com/2017/04/03/adding-global-error-handling-and-logging-in-asp-net-core/) for handling exceptions, which basically involves calling `app.UseExceptionHandler("/Home/Error")` in `Startup.cs` and then running this code in the Error action of the Home controller:

```csharp
var exceptionFeature = HttpContext.Features.Get<IExceptionHandlerPathFeature>();

if (exceptionFeature != null)
{
    var dict = new Dictionary<string, string>();
    dict.Add("Path", exceptionFeature.Path);

    Exception exceptionThatOccurred = exceptionFeature.Error;
    _telemetryClient.TrackException(exceptionThatOccurred, dict);
}
```

This worked perfectly in 1.1, but in 2.0 the user is no longer being redirected to the Error action when an exception is thrown somewhere in my app.

I then tried to implement [Paul Hiles' suggestion](https://www.devtrends.co.uk/blog/handling-errors-in-asp.net-core-web-api), which involves developing a piece of middleware to handle exceptions and render the Error view. You can see my code for the middleware [here](https://gist.github.com/sebastianbk/a7da03bffb8fcea02595f51baf43c11c). My middleware makes use of an interface called `IViewRenderService`, which I copied from [Paris Polyzos' blog](https://ppolyzos.com/2016/09/09/asp-net-core-render-view-to-string/).

Rather than catching the exception, logging it with Application Insights and rendering the Error page, I now get an HTTP 500 response with an empty body:

```
HTTP/1.1 500 Internal Server Error
Content-Length: 0
Server: Kestrel
X-Powered-By: ASP.NET
Date: Mon, 21 Aug 2017 10:04:12 GMT
```

Why are my exceptions no longer being catched gracefully in 2.0?

**Comment by halter73** [comment] 2017-08-22 00:33
@sebastianbk What does your [log output](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging?tabs=aspnetcore2x#how-to-add-providers) look like when you get these 500 responses?

This usually means something in the request pipeline is throwing an uncaught exception. It could even be the error handling code itself that's doing this. The logs should give you exceptions details including a stack trace.

**Comment by Eilon** [comment] 2017-09-08 03:49
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2017-09-08 03:49 UTC

**Comment by jayeshdshah** [comment] 2017-11-27 06:03
@sebastianbk  Initially I also faced the same issue as you mentioned above.. But I found that I was working in Development environment so Error action code wasn't executing. Below is the case,

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Base/Error");
            }
After changing environment to **production**, Error action was properly handled. 

and just a suggestion, I created  a **BaseController :  Controller** and transferred my Error action method into that base controller. Now I inherit every controller from this BaseController so, I get this error handler in every page...

Happy coding...

**Comment by alexsorokoletov** [comment] 2018-02-22 04:15
What we found for ourselves is that we added `[HttpGet]` on our exception handler page and POST requests were not reaching it.
Docs from the post above clearly state:
```
In an MVC app, don't explicitly decorate the error handler action method with HTTP method attributes, such as HttpGet. Using explicit verbs could prevent some requests from reaching the method.
```
