### ISSUE TITLE
Razor Pages does not map query parameter if it is called `page`

### ISSUE THREAD

**Issue by gyankov** [aspnet/Mvc#8676] opened 2018-10-31 15:24 UTC
#### Description of the problem:

Currently sending a query parameter called `page` is not possible in a Razor Pages project. I am aware that the framework does not bind it correctly as `page` is a keyword. However, is there any workaround to send a query parameter called `page`?

**Comment by poke** [comment] 2018-10-31 15:48
Duplicate of #7876. Unfortunately, there’s no workaround for this. You will have to choose a different parameter name (e.g. `p`) or switch to controllers to make this work.

**Closed** 2018-10-31 17:23 UTC
