### ISSUE TITLE
Custom JsonConverter breaks recursive validation

### ISSUE THREAD

**Issue by markusbrueckner** [aspnet/Mvc#6466] opened 2017-06-29 12:02 UTC
For a polymorphic endpoint in a JSON API we implemented a custom JsonConverter, that deserializes certain object properties based on the value of a `type` field in the JSON representation (basically this is a generic container object, which contains a `type` field as the discriminator and a `data` field containing the actual data.)

An example of such a (stripped down) class hierarchy looks like this:
```csharp
public interface IContainer
{
   IProperty GenericProperty { get; set; }
}

[JsonConverter(typeof(CustomConverter))]
public class Container<TProperty> : IContainer
   where TProperty : IProperty
{
     [Required]
     public TProperty Property { get; set; }

     public IProperty GenericProperty
     {
         get
         {
             return Property;
         }
         set { Property = (TProperty) value; }
     }
}

public interface IProperty
{
}

public class Property : IProperty
{
    public string Id { get; set; }

    [Required]
    public string Test { get; set; }
}
```

The CustomConverter looks like this (stripped down, to isolate the issue. In the original code, it deserializes different types derived from a common interface):
```csharp
public class CustomConverter : JsonConverter
{
    public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
    {
        throw new System.NotImplementedException();
    }

    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
    {
        var prop = JObject.Load(reader);
        var cont = Activator.CreateInstance(objectType) as IContainer;
        cont.GenericProperty = serializer.Deserialize(prop["Property"].CreateReader(), typeof(Property)) as IProperty;
        return cont;
    }

    public override bool CanWrite => false;

    public override bool CanConvert(Type objectType)
    {
        return true;
    }
}
```

I have two different controller endpoints to test the behavior:
```csharp
[HttpPost("/interface")]
public IActionResult PostInterface([FromBody]Container<Property> value)
{

}
```
This version works (i.e. any validation errors in the `Property` object cause the ModelState to be invalid).

```csharp
[HttpPost("/direct")]
public IActionResult PostDirect([FromBody]Container<IProperty> value)
{

}
```
This doesn't. As far as I can see, no validation of the Property object takes place and no errors are reported. The only difference being that the type parameter for the `Container< >` class is the base interface this time.

Explicitly retrieving the `Property` object from the container and validating it via
```csharp
Validator.TryValidateObject(container.Property, new ValidationContext(container.Property), results, true)
```
works correctly in both situations. It looks, as if the interface prevents the validation from recursing down into the property.

From my understanding the validation takes place after deserialization. If so, how does the extra step with the custom JsonConverter break the validation? Or is my understanding wrong and the JsonConverter has to do something in order to enable correct deserialization?

**Comment by Eilon** [comment] 2017-07-03 17:17
@rynowak / @dougbu - thoughts?

**Comment by dougbu** [comment] 2017-07-03 17:49
Validation does indeed take place after deserialization. However, it's intentionally based on the _declared_ type of the model and its properties.

Put another way, this behaviour will occur for any subclass created during deserialization. You'd see the same thing with a custom model binder instead of a custom type converter. However, the custom model binder has an opportunity to update the `ValidationStateEntry` for the `GenericProperty`. A custom model binder could e.g. use the `ModelMetadata` for the `Property` type instead.

**Comment by Eilon** [comment] 2017-08-31 04:41
Closing because there are no plans to implement this. The current behavior is by design.

**Closed by Eilon** 2017-08-31 04:41 UTC
