### ISSUE TITLE
2.1-Preview 1: IsBindingRequired and IsRequired still false with RequiredAttribute on controller parameter.

### ISSUE THREAD

**Issue by nphmuller** [aspnet/Mvc#7435] opened 2018-03-04 15:03 UTC
Say I have to following controller:
``` c#
[Route("My")]
public class MyController : ControllerBase
{
    [HttpGet]
    public void MyAction([BindRequired, Required] string queryParm)
    {

    }
}
```
And the following code:
``` c#
var apiDescriptionsProvider = app.ApplicationServices.GetRequiredService<IApiDescriptionGroupCollectionProvider>();
var parameterDescription = apiDescriptionsProvider.ApiDescriptionGroups.Items.Single().Items.Single().ParameterDescriptions.Single();
var isBindingRequired = parameterDescription.ModelMetadata.IsBindingRequired;
var isRequired = parameterDescription.ModelMetadata.IsRequired;
```

I'd expect both `isBindingRequired` and `isRequired` to be true. Both are however false.
I also inspected `ModelMetadata.MetadataKind` which had a value of `Type` instead of `Parameter` which I expect is the underlying cause.

Am I doing something wrong, or is this a bug? When I call the API from my browser without supplying `queryParm`, the model state is invalid. So that part is going right.

**Comment by mkArtakMSFT** [comment] 2018-03-05 18:02
Thanks for contacting us. @dougbu, can you please look into this?

**Comment by dougbu** [comment] 2018-03-05 20:48
@nphmuller are you seeing an issue with `[Required]` on an action parameter i.e. are `ModelState` errors added when the `string` parameter isn't provided? If yes, I can't reproduce the problem. Your application likely has additional customizations beyond what you've described. Does it for example use a custom `IModelMetadataProvider`?

If your issue is specifically with the `IApiDescriptionGroupCollectionProvider` results, I suspect the `ApiDescriptionGroups` will frequently be incomplete (in my test app, it's empty) and will rarely contain complete information about action parameters. Is this your issue?

**Comment by dougbu** [comment] 2018-03-05 21:14
> I suspect the `ApiDescriptionGroups` will frequently be incomplete (in my test app, it's empty) and will rarely contain complete information about action parameters. Is this your issue?

Never mind this part. I forgot to opt into API Explorer for my controller. I can now reproduce your issue even though MVC will require a value for `queryParm`.

I suspect API Explorer needs to be made aware of the `ModelMetadataProvider` enhancements over what `IModelMetadataProvider` alone enables.

Separately,
> I'd expect both `isBindingRequired` and `isRequired` to be `true`.

There's no `[BindRequired]` attribute in the code you provided. `ModelMetadata.IsBindingRequired` should be `false`.

**Comment by dougbu** [comment] 2018-03-05 21:29
Problem is at https://github.com/aspnet/Mvc/blob/3517ecda2f7eee421159d4e3206f937264f5b56b/src/Microsoft.AspNetCore.Mvc.ApiExplorer/DefaultApiDescriptionProvider.cs#L165
That code needs to handle the case where `_modelMetadataProvider` is a `ModelMetadataProvider` and use `GetMetadataForParameter(...)` then.

**Comment by dougbu** [comment] 2018-03-05 21:35
Should also check MVC for other places it calls `IModelMetadataProvider.GetMetadataForType(...)` where it may be dealing with an action or page handler parameter.

**Comment by nphmuller** [comment] 2018-03-06 09:30
> There's no [BindRequired] attribute in the code you provided. ModelMetadata.IsBindingRequired should be false.

Ah, sorry about that. Was still a bit confused about when `IsBindingRequired` is set to true. Guess it's easier than I though: it's only set when a `BindingBehaviorAttribute` is set with `BindingBehavior.Required`.

I'll update the example in my first post. Because even when `[BindRequired]` is set, `isBindingRequired` is still false.

**Comment by mkArtakMSFT** [comment] 2018-03-12 17:11
@dougbu, I think you already have some fixes for this area. If this one, however, is self contained, feel free to reassign to @kichalla. Please also assign the cost, whoever will be handling it.

**Comment by dougbu** [comment] 2018-03-12 17:25
Reassigning because I did not experiment with my recommendations. On the other hand, I did a bit of the search for `IModelMetadataProvider.GetMetadataForType(...)` uses and suspect there be dragons -- though likely baby dragons (corner cases).

I would cost this as S but will leave it to @kichalla to make his own determination and assign the label.

**Closed** 2018-03-19 19:06 UTC
Labels: 2 - Working, bug, cost: M
