### ISSUE TITLE
Localization Resource Not Found if Path to View contains "./"

### ISSUE THREAD

**Issue by cdwlighting** [aspnet/Mvc#6099] opened 2017-04-07 14:40 UTC
This one had me scratching my head for 2 and 3/4 days!

I have a view that included a partial from the path ./Partials/_viewname.cshtml.

I have the translation that was /resourcePath/views/controller_name/partials/_viewname.culture.resx

I could not figure out why the translations from my resource were not being applied, even after checking the pathing, Resource Keys, etc.  I didn't find the issue until I started recreating how the path to the resource was being created...

I noticed that the path was being generated as resourcePath.views.controller_name[..].partials._viewname. In the debugger I had seen the '...',   however; I had thought that the debugger was placing ellipses in the string to make it easier to read. 

I did not find any other references related to this.  Let me know if you need anything from me, and I will provide what I can.

I do think an easy fix will be to add another Replace to the Resource Path string that replaces '...' with '.'.

The other thought I had is, if you are not supposed to do './' in your @Html.RenderPartial(Async) calls, why does Razor load the file and render it?

Thanks.  
Chris

**Comment by Eilon** [comment] 2017-04-19 22:42
Hmm this is weird, I'm not sure the right way to handle this. We don't really want to do our own canonicalization here - that is usually a path to other bugs. The Replace("...", ".") also has its own set of errors.

But perhaps we can detect some common cases (such as this) that have "known-correct" solutions and make those work.

**Comment by ryanbrandenburg** [comment] 2018-02-26 23:37
Do the changes in [this](https://github.com/aspnet/Mvc/commit/665c767af663f2ef804db7eb6a2a66b949102efd) commit reflect your scenario? If so it seems like this might have been solved in the meantime. If not could you give us a bit more detail, preferably with a reproduction app?

**Comment by ryanbrandenburg** [comment] 2018-02-28 23:16
I'm closing this for now since we couldn't get a repro. If you're still having trouble feel free to re-open with more information.

**Closed by ryanbrandenburg** 2018-02-28 23:16 UTC
Labels: 2 - Working, bug
