### ISSUE TITLE
Antiforgery sets headers after the response body has started

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Mvc#7040] opened 2017-11-09 17:46 UTC
This was found when we changed TestServer to behave more like a real server and lock headers after the body starts. See https://github.com/aspnet/Hosting/pull/1256

```
  at Microsoft.AspNetCore.Http.HeaderDictionary.ThrowIfReadOnly()
     at Microsoft.AspNetCore.Http.HeaderDictionary.set_Item(String key, StringValues value)
     at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.SetDoNotCacheHeaders(HttpContext httpContext)
     at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetAndStoreTokens(HttpContext httpContext)
     at Microsoft.AspNetCore.Mvc.ViewFeatures.AntiforgeryExtensions.GetHtml(IAntiforgery antiforgery, HttpContext httpContext)
     at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateAntiforgery(ViewContext viewContext)
     at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.GenerateForm(String actionName, String controllerName, Object routeValues, FormMethod method, Nullable`1 antiforgery, Object htmlAttributes)
     at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.BeginForm(String actionName, String controllerName, Object routeValues, FormMethod method, Nullable`1 antiforgery, Object htmlAttributes)
     at Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperFormExtensions.BeginForm(IHtmlHelper htmlHelper, String actionName, String controllerName, FormMethod method, Object htmlAttributes)
     at AspNetCore._Views_Antiforgery_FlushAsyncLogin_cshtml.<<ExecuteAsync>b__0_0>d.MoveNext() in D:\github\AspNet\Universe\modules\Mvc\test\WebSites\BasicWebSite\Views\Antiforgery\FlushAsyncLogin.cshtml:line 14
```

These tests are being disabled until this is fixed:
SetCookieAndHeaderBeforeFlushAsync_GeneratesCookieTokenAndHeader
SetCookieAndHeaderBeforeFlushAsync_PostToForm

**Comment by Eilon** [comment] 2017-11-27 20:05
@javiercn can you take a look?

**Comment by javiercn** [comment] 2018-01-14 23:33
I think I'm running into this while writing functional tests for Identity as a library. I'm marking it as working cause i'm investigating and its blocking me.

**Comment by rynowak** [comment] 2018-01-15 00:04
What's caused the body to start sending? Antiforgery **can't** function if you don't set the cookie before writing to the body. Blowing up is a reasonable behaviour in that case.

**Comment by javiercn** [comment] 2018-01-15 00:41
It turned out to be something different. The antiforgery cookie wan't marked essential so it wasn't being written in my tests. Kiran made the change, but hasn't propagated yet to the latest and greatest version.

**Comment by javiercn** [comment] 2018-01-15 02:02
I found the issue anyways, as I was already here. It's caused by 
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/HtmlHelper.cs#L879
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L194
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/AntiforgeryExtensions.cs#L40
https://github.com/aspnet/Antiforgery/blob/dev/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgery.cs#L43

IMO there are two valid solutions:
Make GetAndStoreTokens idempotent (do not try to serialize the tokens again if they are already on the feature and are the same as in the cookie)
Make GetHtml check the antiforgery feature for the cookie token.
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/AntiforgeryExtensions.cs#L40

**Comment by mkArtakMSFT** [comment] 2018-01-23 06:23
Here is the PR fixing the issue: https://github.com/aspnet/Antiforgery/pull/179

**Closed** 2018-01-23 06:24 UTC
Labels: 3 - Done, bug

**Comment by mkArtakMSFT** [comment] 2018-01-24 01:29
Here is the PR re-enabling the disabled tests: https://github.com/aspnet/Mvc/pull/7286
