### ISSUE TITLE
Adjusting BindRequired semantics / alternatives?

### ISSUE THREAD

**Issue by drauch** [aspnet/Mvc#7511] opened 2018-03-20 12:01 UTC
We want to give our REST API users feedback:
* if they provided no value for a required property -> we can use the BindRequired attribute in this scenario
* if they provided an ill-formatted / non-convertible value
** for a required property -> how to improve the BindRequired error message in this scenario, which simply states that no value has been provided which confuses the caller, because he has indeed provided a value, it is simply of the wrong data format.
** for a non-required property -> ? What attribute to use in this scenario?

Note: we are using ASP.NET Core 1.1.x

**Comment by mkArtakMSFT** [comment] 2018-03-21 16:54
Thanks for contacting us.
@dougbu, do you have any suggestions regarding the ask? Thanks!

**Comment by dougbu** [comment] 2018-03-21 17:45
`[BindRequired]` means binding a property must succeed. It can't succeed if the submitted value is poorly formatted. But, errors about the formatting should also be in the `ModelState`.
1. In what scenario does that _not_ occur?
2. Or, is your concern the sparseness of the `The value '{0}' is not valid.` or `The value '{0}' is not valid for {1}.` error messages? Those messages can be changed on a per-parameter, property or type basis in an `IMetadataDetailsProvider` implementation.

If you're combining `[BindRequired]` with `ValidationAttribute`s e.g. `[RegularExpression]`, the `ValidationAttribute`s will not execute unless the `[BindRequired]` passes. That's intentional because we don't validate something already determined to be invalid.

But, some of the above might have changed in subtle ways since 1.1. I'm looking at current behaviour i.e. 2.1-Preview1.

**Comment by drauch** [comment] 2018-03-21 21:12
I'm pretty sure you are talking about news for 2.1-preview1 here. Maybe the output is even better in 2.0. But in 1.1 the output is NOT `The value '{0}' is not valid.`, it is something along the lines of `No value provided`, which is confusing.

1) But you are probably not going to backport that to 1.1.x, or am I wrong?

2) Still, even with 2.1-preview1 - does a wrong data type for an optional model property result in a "The value is not valid for" message or in a silent ignore?

**Comment by dougbu** [comment] 2018-03-21 22:38
> it is something along the lines of `No value provided`, which is confusing.

I was saying there should be at least two error messages. Do you have a small repro showing a case where only the `No value provided` error is added when model binding fails due to a formatting issue?

**Comment by drauch** [comment] 2018-03-22 07:49
https://www.dropbox.com/s/d6wj84v4i7wedlj/BindRequiredRepro.zip?dl=0

Use Postman to send a GET request with param "Prop=LOL" to the Home/Test action. The error returned is "No value provided" and not "The value is not valid".

However, if this is fixed in 2.1-preview1, I'm okay with it. Please answer my question 2 above though, it'd really help :-)

**Comment by drauch** [comment] 2018-03-26 11:08
1) You're right. My bad, the repro is not exactly what I've actually done. Sorry for the inconveniences!

If the action is POST and you use Postman to send a *text* body parameter with the wrong type => it works. If you try to send a *file* body parameter instead of a text body parameter => it doesn't work.

2) What about the second question about BindRequired for *optional* parameters?

**Comment by dougbu** [comment] 2018-03-26 16:21
> Still, even with 2.1-preview1 - does a wrong data type for an optional model property result in a "The value is not valid for" message or in a silent ignore?

Incorrectly-formatted data e.g. `"LOL"` for an `int` property results in a message like `"The value 'LOL' is not valid for Prop."`. This occurs whether or not the property is required (in any sense of "required").

**Comment by drauch** [comment] 2018-03-28 06:13
OK. This sounds great. Thanks for the clarification!

We derailed a bit, we thought that all this is not implemented because we always tried to send a file instead of text and vice versa (a scenario in which the logic doesn't work). Do you know anything about that as well? Is there a way to support the "nice error response" in this scenario as well? You can try it yourself easily by using Postman and setting the type of a body parameter to file instead of a text.

**Comment by dougbu** [comment] 2018-03-28 15:36
> Do you know anything about that as well?

I believe you're talking about posting a multipart body to an MVC action and attempting to bind one of the segments to something other than an `IFormFile` parameter. If I've got that right, it's not a supported scenario: `IFormFile` and collections of `IFormFile` are the only supported parameter types when binding from multipart segments.

**Comment by mkArtakMSFT** [comment] 2018-04-02 21:27
Thank you for your feedback.
We're closing this issue as the behavior discussed seems to be by design.

**Closed by mkArtakMSFT** 2018-04-02 21:27 UTC
Labels: question
