### ISSUE TITLE
RedirectToActionResult doesn't honor current area.

### ISSUE THREAD

**Issue by B-Esmaili** [aspnet/Mvc#3833] opened 2015-12-30 12:27 UTC
When i use `RedirectToAction` with no area provided , it omits area in the redirected url.from the `RedirectToActionResult.cs` class :

```
if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }
            var loggerFactory = context.HttpContext.RequestServices.GetRequiredService<ILoggerFactory>();
            var logger = loggerFactory.CreateLogger<RedirectToActionResult>();

            var urlHelper = GetUrlHelper(context);

            var destinationUrl = urlHelper.Action(ActionName, ControllerName, RouteValues);
            if (string.IsNullOrEmpty(destinationUrl))
            {
                throw new InvalidOperationException(Resources.NoRoutesMatched);
            }

            logger.RedirectToActionResultExecuting(destinationUrl);
            context.HttpContext.Response.Redirect(destinationUrl, Permanent);
```

here i can't see any fallback value for `area` if not one provided by the `RedirectToAction` method.between i have a question related to this issue, and that is when we use `TagHlepers` like `form` & `a` tags they generate `area` as parameter (eg: `/Controller/Action?area=somearea`) not as part of url (eg: `SomeArea/Controller/Action`) , could you clarify intention behind this decision?
thanks for support!

**Comment by Muchiachio** [comment] 2015-12-30 14:34
It should work, could you provide your route configuration?

**Comment by Eilon** [comment] 2016-01-22 23:58
@javiercn can you try to repro this?

**Comment by javiercn** [comment] 2016-02-01 20:35
@B-Esmaili There are a couple of explanations of why you are seeing that behavior. If your current request is not within the area to the action you are generating the link to, you need to specify the value of the area manually as part of the route values. (For redirecting within the same area is not required, but for moving to/from an area to another area or to an action without area it is required)

For the case in which you are seeing the area as a parameter of the action, its most likely caused by the order of your routes, you can see the example 1 of the following announcement for more details: https://github.com/aspnet/Announcements/issues/120

If are still having issues with this, you can provide us with your route configuration, action, etc on this issue so that we can help you out.

**Closed** 2016-02-05 23:03 UTC
Labels: 2 - Working, investigate
