### ISSUE TITLE
Segfaults under Ubuntu when the ViewModel is null for a View

### ISSUE THREAD

**Issue by BenjiZombie** [aspnet/Mvc#6724] opened 2017-08-29 15:28 UTC
(This is more of an FYI for others who might encounter the same issue. )

Under Ubuntu-16.04, if I omit to provide an instance of the `ViewModel` to a View, I get `segfaults` or `illegal instructions` errors and the application abruptly stops. This does not happen in my development Windows 10 environment.

It is really simple to reproduce.

Controller:
```
[AllowAnonymous]
[HttpGet]
public IActionResult Login(string returnUrl = null)
{
	ViewData["ReturnUrl"] = returnUrl;
	return View();
}
```

View (basic Login form):
```
@model LoginViewModel

<form ....>
    <input asp-for="Username" />
    <input asp-for="Password" />
    ...
</form>
```

Result:
```
Segmentation fault (core dumped)
```

Or sometimes

```
Illegal instructions (core dumped)
```

This happens either after the very first request to that action, or after a few refreshes of the page.

To resolve this, simply pass a new instance of the `ViewModel` to the view:

```
[AllowAnonymous]
[HttpGet]
public IActionResult Login(string returnUrl = null)
{
	ViewData["ReturnUrl"] = returnUrl;
	return View(new CreateViewModel());  
}
```

This makes sense, however I was expecting a `NullReferenceException` instead of segfaults. Under Windows, I noticed this first chance exception in the logs.

`dotnet --info`

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by Eilon** [comment] 2017-08-29 16:47
Hmm this definitely doesn't sound good. The process shouldn't crash because of something fairly trivial.

@kichalla - can you try to repro and we can file a new bug on https://github.com/dotnet/coreclr ?

**Comment by kichalla** [comment] 2017-08-29 22:58
I have tried to reproduce it many times but I am unable to. @BenjiZombie I suppose you created the application starting with something like `dotnet new --auth Individual`?

**Comment by BenjiZombie** [comment] 2017-08-30 12:33
@kichalla I created the project on my Windows 10 dev env using VS 2017, and have since then upgrade to 2.0 and VS 15.3. The project is quite large now; I will try and create a smaller application to reproduce the issue and report back here.

Thanks

**Comment by kichalla** [comment] 2017-08-30 17:16
Thanks @BenjiZombie I will close this issue for now. Feel free to re-open it with more information. Thanks

**Closed by kichalla** 2017-08-30 17:16 UTC
Labels: 2 - Working, investigate
