### ISSUE TITLE
Precompile razor views from code

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [aspnet/Mvc#7272] opened 2018-01-22 07:21 UTC
We are struggling with slow first usage of our razor views. Is there any way to force recompile of razor views from code?
We do not have access to our pipelines, so changing build or deploy is not an option for us.

**Comment by mkArtakMSFT** [comment] 2018-01-22 18:02
@rynowak, any suggestions here?

**Comment by rynowak** [comment] 2018-01-22 18:20
@FenrisWolfAtMiddleEarth could you please clarify the following points?

> We are struggling with slow first usage of our razor views. 

What does this mean? Are you saying that the first request is too slow? How slow? How did you measure this, and how did you arrive at the conclusion that view compilation is the problem?

> Is there any way to force recompile of razor views from code?

I assume by this that you mean that you want to re-trigger compilation of an already-compiled Razor view from code. If you mean something else please clarify. I don't understand how this is related to the first point, so it's likely that I am confused.

We have no support for triggering recompilation from code. MVC creates a filewatcher on application startup and will recompile based on file changes on disk.

>We do not have access to our pipelines, so changing build or deploy is not an option for us.

What does this mean? Do you not have access to the project file? Anything meaningful for build configuration should be in the project file already.


----------

MVC Core 2.0 supports view compilation during publish https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?tabs=aspnetcore2x

This feature is getting some enhancements and a facelift in 2.1. If you feel like the capabilities we have are not a good fit for your needs please let us know.

**Comment by FenrisWolfAtMiddleEarth** [comment] 2018-01-22 20:02
Thanks for your input. I will try to elaborate

- Yes the first request is too slow. I would say 5-7 seconds measured with the naked eye. After reading of similar experiences from other users, my best guess is due to compilation of the view. Any requests after the first are lightning fast.

- As I understand it will not be a re-compilation but a first compilation, as it is also stated in the first sentence on the page which you link to (Razor views are compiled at runtime). 

- I'm sorry to hear you do not support compilation at startup. That was what I was looking for.

- I have access to the project file and all other source code files. However I don't have access to / can change the build and deploy pipeline which grabs the source, compiles, tests and deploys. So from your article I have nowhere to perform the command "dotnet publish -c Release"

Hopefully this clarifies my question.

**Comment by mkArtakMSFT** [comment] 2018-01-24 22:52
Thank you for your feedback.
We're closing this issue as the behavior discussed seems to be by design.
The right way to publish an app requires you to run `dotnet publish`, which will create a portable bits of your application that can then be deployed. Running `dotnet publish` will automatically compile the views and improve the startup performance.

**Closed by mkArtakMSFT** 2018-01-24 22:52 UTC
