### ISSUE TITLE
Range Requests support

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#480] opened 2014-05-10 00:01 UTC
https://aspnet.codeplex.com/SourceControl/latest#Samples/WebApi/HttpRangeRequestSample/ReadMe.txt

| 92 | 10188 | Reported By: Kiran Challa |

**Comment by danroth27** [comment] 2016-08-18 20:09
@Eilon I think we can close this as a duplicate of #4786. I believe the main scenario for range requests is partial file downloads.

**Comment by danroth27** [comment] 2016-08-18 20:24
We can revisit adding more general support for range requests based on customer feedback.

**Closed by danroth27** 2016-08-18 20:24 UTC
Labels: 0 - Backlog, enhancement, feature
