### ISSUE TITLE
Razor views cannot use typed base class with typed models

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#6291] opened 2017-05-18 16:18 UTC
Based on https://github.com/aspnet/Mvc/issues/5397#issuecomment-278992344

Consider a Razor file with an `@inherits` with a closed generic base type: e.g.  `@inherits Microsoft.AspNetCore.Mvc.Razor.RazorPage<MyModel>`. This fails to compile with 
```C#
Property 'ViewData' is of type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary`1[[MyModel]]', but this method requires a value of type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
 Parameter name: viewContext
```

The issue here is that in the absence of an `@model` keyword, the HtmlHelper is injected with the default model viz `dynamic`:

```C#
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
```

**Comment by pranavkm** [comment] 2017-05-18 16:21
> Original comment from @YetaWF

It's unclear based on this, and the fact that the issue is closed, what the future direction is.

The inability to have custom Razor Views inherit from RazorPage\<T\> is severely limiting.
Admittedly I am converting some huge MVC5 apps and overall this is fairly simple, but not being able to inherit RazorPage\<T\> with types other than object is a complete roadblock.

While I understand the use of _ViewImports.cshtml and model, and I confirmed that it works, it is at best a workaround. And may be usable for trivial or average MVC apps.

MVC5 was able to inherit from WebViewPage\<T\> as in:

    public class MyRazorView<TModule, TModel> : WebViewPage<TModel>
        where TModule : ModuleDefinition
        where TModel : class {

        public RazorView();

        ...
        public TModel Model { get; }
        public TModule Module { get; }
        ...
    }

The corresponding view would look like this (note, no model required (or even allowed)).

    @inherits MyRazorView<TextModule, TextModelDisplay>
    @Html.DisplayFor(m => Module.Contents)

This custom class MyRazorView\<TModule, TModel\> used in MVC5 provides TYPED properties (like the Module property). I looked into using a service on MVC6 using IViewContextAware to inject these. While I confirmed that this works, this is impractical for 1000+ classes derived from RazorPage\<T\>.
The difficulty in providing TYPED properties (which are different for each class) in MVC6 is where the lack of derived custom RazorViews is causing problems.


MVC6's lack of support for inheriting from RazorPage\<T\> (which "replaces" WebViewPage\<TModel\>) forces the use of _ViewImports.cshtml.
Clearly with this approach all views in the same folder must use the same _ViewImports.cshtml, which means they are all based on the same class. (Not good).
And the model must now be explicitly listed in the view. So now we define the class outside the view in _ViewImports.cshtml and the model in the view. (ugly?).

Obviously it's not possible to use inherits and model both in the same view. (Error: The 'inherits' keyword is not allowed when a 'model' keyword is used.)
This was correct in MVC5 because WebViewPage\<TModel\> correctly determined the model type and a model keyword was not necessary and correctly rejected.
MVC6 also doesn't allow inherits and model in the same view. This must be a left-over from MVC5 because MVC6 makes no use whatsoever of the inherits keyword to determine the model type.
Allowing inherits and model in the same view in MVC6 would seem an OK solution, although somewhat hacky... as both the inherits and model would specify the model type. At least it would eliminate the unnecessarily awkward separation of class and model definition.

Further, in MVC5 the Html property was a properly typed HtmlHelper\<TModel\>.
In MVC6 only a model keyword results in a property typed HtmlHelper\<TModel\>. Without model (but with inherits in the view), you'll get HtmlHelper\<dynamic\>, which results in the dreaded

    Property 'ViewData' is of type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary`1[[YetaWF.Modules.Text.Controllers.TextModuleController+TextModelDisplay, YetaWF.Text, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null]]', but this method requires a value of type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'.
    Parameter name: viewContext

While I appreciate the new features and enhancements in MVC6, this is an area that was severely clipped in MVC6 and makes upgrading to MVC6 really unnecessarily difficult.

Maybe there is a solution to somehow add typed properties to a view and my inexperience with MVC6 is preventing me from finding another solution, other than custom RazorPage\<T\>-derived classes. As I mentioned, while injection works, it doesn't seem impractical for 1000+ derived classes.

**Comment by YetaWF** [comment] 2017-05-18 17:01
I have developed a viable (although somewhat hacky) workaround for 2.0. Even using classes such as this 
`@inherits MyRazorView<TextModule, TextModelDisplay>`
The approach is to override ModelDirective and extract the type correctly. This would be super simple if ModelDirective were exposed (it isn't, hence the hackiness).
This means in startup I have to do something like this (and override a ton of classes, just to get a hold of ModelDirective. But it does work (at least until preview1 switched to netcoreapp2.0, another story):

```
            // We need to handle ModelDirective to derive the Model type (otherwise we'll end up with "dynamic") for all our views
            // This is most likely going to change as we're using an unreleased version of MVC
            // Such a hack... TODO: Research if there is a cleaner way in ModelDirective
            services.AddSingleton(typeof(RazorEngine), s => {
                return RazorEngine.Create(builder => {
                    YetaWFInjectDirective.Register(builder);//<<<
                    YetaWFModelDirective.Register(builder);//<<<
                    NamespaceDirective.Register(builder);
                    PageDirective.Register(builder);

                    builder.AddTargetExtension(new InjectDirectiveTargetExtension());

                    builder.Features.Add(new ModelExpressionPass());
                    builder.Features.Add(new YetaWFPagesPropertyInjectionPass());//<<<
                    builder.Features.Add(new ViewComponentTagHelperPass());
                    builder.Features.Add(new RazorPageDocumentClassifierPass());
                    builder.Features.Add(new MvcViewDocumentClassifierPass());

                    builder.Features.Add(new Microsoft.CodeAnalysis.Razor.DefaultTagHelperFeature());

                    if (!builder.DesignTime) 
                    {
                        builder.Features.Add(new DefaultInstrumentationPass());
                    }

                    builder.Features.Add(new Microsoft.CodeAnalysis.Razor.DefaultTagHelperFeature());

                    var metadataReferenceFeature = s.GetRequiredService<LazyMetadataReferenceFeature>();
                    builder.Features.Add(metadataReferenceFeature);
                });
            });
```

This code is a little outdated as I have been unable to keep up since I need .NET support. All the code in its hackiness is at https://github.com/YetaWF/YetaWF-Solution2/blob/master/Website/Startup6.cs

**Comment by rynowak** [comment] 2017-05-30 19:31
@pranavkm is this a regression from 1.1.X?

**Comment by pranavkm** [comment] 2017-05-31 14:38
Nope - this is a regression from Mvc <= 5

**Comment by mkArtakMSFT** [comment] 2018-05-02 22:01
Closing this as there wasn't much feedback regarding this as well as this is not a priority at the moment. /cc @DamianEdwards

**Closed by mkArtakMSFT** 2018-05-02 22:01 UTC
