### ISSUE TITLE
Validation design

### ISSUE THREAD

**Issue by JeremySkinner** [aspnet/Mvc#1260] opened 2014-10-07 10:49 UTC
Hi

I'm the author of the FluentValidation library, and am looking at getting this to work with MVC6 with the help of @kanchanm 

Historically, it's always been a pain to get FluentValidation to work with MVC's validation infrastructure:
- MVC expects the validation provider to validate each value, and then if it passes the value is set on the property (as per the DataAnnotations validator)
- FluentValidation works by setting all the properties first, and then validating the entire object in one go

I've been able to get the two to work together with some messy hacks with previous versions of MVC (and to a lesser extent, WebAPI), but I was wondering if there are any plans to change this with vnext?

Specifically, I'd love to see a way for authors of validation libraries to take control of the *entire validation process* without having to create a custom model binder (with MVC5 and before, not all validation takes place in the model validator - some is still done by the binder).

**Comment by rynowak** [comment] 2015-03-13 21:44
Triage: This is a follow-on to the model-metadata change, and also is churn to the public API for validators. Would like to do for RC.

**Comment by JeremySkinner** [comment] 2015-03-16 10:57
Thanks...any initial thoughts on what the API might look like?

**Comment by rynowak** [comment] 2015-03-16 20:30
History: We used to have two validation systems.
-------------
1). One that ran during model binding of things like query-string/form-data/route-values. This is the one you're describing above, which validates a property-at-a-time
2). One that runs on the result of a formatter, which reads json or xml from the request body. 

We're keeping number 2 and getting rid of number 1. This means that validation will run after-the-fact on the fully-constructed model. There is also the capability for model-binding/formatters will add validation errors for missing values, which we will keep because once model-binding/de-serialization is over we can't tell the difference between an explicit-null and a value that wasn't provided.


Extensibility: We have two kinds of validation extensibility
--------------------
1). One that handles an individual property
2). One that takes full-control and is responsible for all validation for a model-object-graph

We're planning on supporting **both** kinds of validation extensibility. Current names are placeholders (`IObjectModelValidator` and `IModelValidator` I believe).

`IObjectModelValidator` is a replaceable service. If you swap it out, you're responsible for all validation other than what comes from the model-binders/formatters. If it's interesting to you we could factor this out into an  abstract-visitor + implementation.

`IModelValidator` is a little tricky. You will be able to register multiple providers in `MvcOptions`, but for the kinds of extensibility most users do that won't be necessary. In general the approach is that model-metadata will carry a set of validator-metadata -- this metadata might just be attributes that's used by a provider, or it might be a validator itself. In the case of the latter, the default validator provider will just do a conditional cast. This puts the burden of caching on the model-metadata system and not on extensibility code.


Other: Random thoughts
---------------
I don't like that client validation rules have to implement `IModelValidator` - this seems like a big layering violation in that most client rules are stateless, and by definition don't care about the actual model value. Expect these to be decoupled (not sure if that has any impact on fluent-validation).

I'm still looking for a way to get rid of `IModelValidator.IsRequired`. I really don't like that we make required validators first-class because it contorts the implementation code in all kinds of ways.

@JeremySkinner anything on your wishlist that we should think about?

/cc @harshgMSFT in case he wants to add anything

**Comment by JeremySkinner** [comment] 2015-03-17 11:07
This looks great - thanks for the detailed reply. A few questions...

> There is also the capability for model-binding/formatters to add validation errors for missing values, which we will keep because once model-binding/de-serialization is over we can't tell the difference between an explicit-null and a value that wasn't provided.

Will it be possible to globally take control of this process if the value wasn't provided, without having to implement a custom binder/formatter? This was probably the biggest pain when dealing with MVC integration in the past. 

> IObjectModelValidator is a replaceable service. If you swap it out, you're responsible for all validation other than what comes from the model-binders/formatters. If it's interesting to you we could factor this out into an abstract-visitor + implementation.

I'll try and have a play with this to see whether being a visitor would make things easier - I'll let you know.

> I don't like that client validation rules have to implement IModelValidator

Agreed. Will the mechanism for registering new client-side rules be similar as with MVC5 and earlier? 

Once I've had a play with it, I'll get back to you if there's anything else that I think would be useful. Thanks again for putting the work into this.

**Comment by rynowak** [comment] 2015-03-17 18:09
> Will it be possible to globally take control of this process if the value wasn't provided, without having to implement a custom binder/formatter? This was probably the biggest pain when dealing with MVC integration in the past.

Any example of what you'd want to do? Current design is that we look for an `IModelValidator` where `IModelValidator.IsRequired == true`. We're looking to improve on the current design. Maybe we'll record a breadcrumb in modelstate that validators can look for later.

> Agreed. Will the mechanism for registering new client-side rules be similar as with MVC5 and earlier?

Adding new rules should be as simple as some combination of:
1). Create an attribute that implements some TBD interface, put it on properties/types.
2). Create an `IlValidationMetadataProvider` which can annotate `ModelMetadata` with any information you need
3). Create and register (in `MvcOptions`) an `IModelValidatorProvider` that does what you want (possibly looking at data provided by number 2) - based on your criteria.

**Comment by JeremySkinner** [comment] 2015-03-18 08:46
> Any example of what you'd want to do? Current design is that we look for an IModelValidator where IModelValidator.IsRequired == true and then run it.... 

I think this is fine, but what will happen if either you can't find a IsRequired validator, or the required validator returns valid? I'm particularly thinking of the following scenario:

- Data type is non-nullable value-type
- No value was specified
- No validator could be found (or it says valid)

With MVC5 and previous, the binder would then generate the generic "A value is required" message, which couldn't be overriden. I'd like it if the IModelValidator to be the one making the decision about whether this should be allowed or not. 

This is probably one of the most frequent questions I get asked with FluentValidation - where someone wants a non-nullable value type to simply keep its default value if no value was specified (rather than being an error condition). Whilst FluentValidation itself can support this, you can't do this when using the MVC integration points because of the binder.

> Maybe we'll record a breadcrumb in modelstate that validators can look for later.

This sounds interesting...how would you imagine this would work? Just a placeholder is added to the modelstate that the validator could fill in later? What would happen if a validator didn't fill it in?

> Adding new rules should be as simple as some combination of... 

Sounds good.

**Comment by rynowak** [comment] 2015-03-18 18:56
> With MVC5 and previous, the binder would then generate the generic "A value is required" message, which couldn't be overriden. I'd like it if the IModelValidator to be the one making the decision about whether this should be allowed or not.

Good feedback. We'll have to look into improving this as that is the current behavior. The problem is distinguishing between a `null` that was provided on the wire and a lack of data. Do you feel like this distinction is important to your users?

**Comment by rynowak** [comment] 2015-03-18 18:57
> This is probably one of the most frequent questions I get asked with FluentValidation - where someone wants a non-nullable value type to simply keep its default value if no value was specified (rather than being an error condition).

In the new system you can change this in model-metadata. By default a non-nullable value type is considered required, but you can configure it.

**Comment by JeremySkinner** [comment] 2015-03-19 12:28
>  The problem is distinguishing between a null that was provided on the wire and a lack of data. Do you feel like this distinction is important to your users?

Yes, I think the distinction is important, but it should be up to the user to decide how they want to handle it. 

> In the new system you can change this in model-metadata. By default a non-nullable value type is considered required, but you can configure it.

Great, that sounds perfect.

**Comment by rynowak** [comment] 2015-03-20 22:34
Part 1 of this is here: f5e7a69693e517666766517cd64e4d4e77e00659

Still to come:
- renames
- refactor of client rules
- addressing some of @JeremySkinner specific concerns pointed out here.

**Comment by rynowak** [comment] 2015-03-31 21:11
Hi @JeremySkinner - I'm going to close this massive bug and open some more targeted ones based on our discussion. If you run into new issues, or you don't think I've captured all of the feedback, please open separate issues.

See #2303
See #2304

**Closed by rynowak** 2015-03-31 21:11 UTC
Labels: 1 - Ready, enhancement
