### ISSUE TITLE
Label Inside EditorTemplate Disappears During Validation

### ISSUE THREAD

**Issue by Reafidy** [aspnet/Mvc#2778] opened 2015-07-02 22:16 UTC
I am using ASP.net MVC 6 and the following EditorTemplate:

    <div class="form-group">        
        @Html.LabelFor(m => m, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue,  htmlAttributes)
            @Html.ValidationMessageFor(m => m, null, new { @class = "help-block" })
        </div>
    </div>

When attempting to save the form with a deliberate error, the page refreshes and correctly shows the validation error but the label completely disappears.   It is not hidden it is completely gone from the html source.

Here is my EditorFor:

     @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })

A bug?

**Comment by danroth27** [comment] 2015-07-06 16:52
@ajaybhargavb Please try to reproduce this

**Comment by Reafidy** [comment] 2015-07-06 21:14
New to Github and At the risk of sounding completely dumb, what does the '2- working' label mean?

**Comment by danroth27** [comment] 2015-07-07 16:31
@Reafidy It just means that the person assigned to the issue is now working on the issue.

**Comment by Reafidy** [comment] 2015-07-08 06:01
Thanks.

**Comment by ajaybhargavb** [comment] 2015-07-16 23:50
92f3e21fe62ea40342f2eb462ee8a92361ad591b

**Closed by ajaybhargavb** 2015-07-16 23:50 UTC
Labels: 2 - Working, bug
