### ISSUE TITLE
Exception Handling MVC Service

### ISSUE THREAD

**Issue by jackryu** [aspnet/Mvc#6454] opened 2017-06-27 21:40 UTC
Hello,

I am try to throw error from MVC service for AJAX callback but my error not track in AJAX code below.

Services

 ```
[AllowAnonymous]
        [HttpGet]
        public JsonResult SendOTP(string keyin)
        {
            try
            {
                return Json("Success", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
               throw ex;
            }
```
      
AJAX Call Back

```

 $.ajax({
            type: "GET",
            url: WEB_SERVICES.SendOTP,
            contentType: "application/json; charset=utf-8",
            data: filter1,
            dataType: "json",
        }).done(function(data){ alert("Success") }).fail(function (xhr, status, err){

alert (XMLHttpRequest.responseText);
});

```

Note : I need to convert Exception  object in JSON or provide any other best approach. 

Please help.

**Comment by Eilon** [comment] 2017-07-03 17:43
@jackryu - what data do you see coming back from the request?

Please note that if the server already started writing the response, there's no way to cancel that. All the server can do is abort/reset the connection, and it's not possible to send other/additional information back to the client.

**Comment by Eilon** [comment] 2017-08-31 04:40
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2017-08-31 04:40 UTC
