### ISSUE TITLE
ObjectResult executor should log the type of the value being written out

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#4604] opened 2016-05-09 21:48 UTC
We log here https://github.com/aspnet/Mvc/blob/release/src/Microsoft.AspNetCore.Mvc.Core/Internal/ObjectResultExecutor.cs#L139

and it shows up like `Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.` in the log

Related :
- return Json("this is a json string");
  Executing JsonResult, writing value this is a json string.
- return Json(null);
  Executing JsonResult, writing value .
- return Json(new Account() { MyProperty = "pr1", MyProperty2 = "pr2" });
  Executing JsonResult, writing value RoutingMiddleware.Controllers.Account.

**Comment by javiercn** [comment] 2016-05-10 03:00
We should never do the first case. We don't have a way of knowing if the information is confidential, so we shouldn't add it to logs by default.

**Comment by Eilon** [comment] 2016-05-10 17:06
There isn't a *huge* security concern here because we log a ton of stuff already anyway, any of which might already have security concerns. E.g. even a URL might have some secret code in it.

The bigger concern is that anything related to live data values is unbounded in terms of length, and thus might bloat log files.

So, logging just the type is probably all we would do.

**Comment by rynowak** [comment] 2016-05-10 22:31
We log the `Convert.ToString(...)` output of the parameters/models. This will generally be the model typ e name, but allows you to customize it if desired.

**Comment by rynowak** [comment] 2017-07-14 18:42
We really have no excuse not to fix this for 2.1

**Comment by mistakenot** [comment] 2017-09-04 09:51
I've had a stab at fixing this. First attempt at a contribution to this project, so please be forgiving of anything I've missed :) You can see my diff at https://github.com/mistakenot/Mvc/commit/25019a0b2d78813cc2abaf065f26edba6678efce.

Let me know if it is any help.

**Comment by Eilon** [comment] 2017-09-05 04:20
@mistakenot thanks for taking a crack at this! If you send a PR it will probably make it easier for us to review. Thanks!

**Comment by Eilon** [comment] 2017-09-13 21:42
@rynowak there's a PR for this that I assigned to you to review.

**Comment by rynowak** [comment] 2017-09-14 06:40
9db92dc6a7bfc22a62ff12053244201c38390da5 and db2d9ee56f9a7ca0f1a264821e0608b70047337c

**Comment by oofpez** [comment] 2018-01-30 09:08
Seems related:  I am having an issue where my entire api response body is logged!

> Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor: Information: Executing JsonResult, writing value { ... }

{ ... } containing the entire json model.

how can I turn this off?  It only seems to happen in the one controller method, where they response is returned like this:
`return Json(JsonConvert.DeserializeObject(stringValue));`

as opposed to `return  Json( object)` which outputs the type.

**Comment by Eilon** [comment] 2018-01-30 17:49
@oofpez hmm that certainly sounds odd. Can you log a new issue with detailed steps to reproduce this?

**Comment by kichalla** [comment] 2018-01-30 18:07
I was able to repro this issue in 2.0.5 version of MVC, but it is fixed in latest version (dev) though

**Comment by pranavkm** [comment] 2018-02-13 00:00
Doesn't look like this is resolved. Testing with `2.1.0-preview1-28257`, here's what I see: 

```
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ControllerContext'.
```

Reopening so we can track this for preview2.

**Comment by rynowak** [comment] 2018-03-16 05:03
```
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ControllerContext'.
```

@pranavkm This logs the **TYPE** of the value, which is what expect. What am I missing??? 
https://github.com/aspnet/Mvc/blob/930664de6ef5b6fe1d547ded61745962253774eb/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcCoreLoggerExtensions.cs#L936

**Comment by pranavkm** [comment] 2018-03-16 16:09
The problem's here - https://github.com/aspnet/Mvc/blob/930664de6ef5b6fe1d547ded61745962253774eb/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/ObjectResultExecutor.cs#L128

**Closed** 2018-03-19 15:06 UTC
Labels: 1 - Ready, bug
