### ISSUE TITLE
Redirecting to non-ASCII URL

### ISSUE THREAD

**Issue by miloush** [aspnet/Mvc#6609] opened 2017-07-30 10:24 UTC
```C#
public IAction Index()
{
    return Redirect(Url.Content("~/ů"));
}
```

throws _InvalidOperationException: Invalid non-ASCII or control character in header: 0x016F_ with no user code on stack.

The framework decided to put that URL into HTTP header which changed its encoding requirements, so I would expect it to fulfil them. Users might not know or care how the redirect is done and it is not clear what header is the error about.

**Comment by Eilon** [comment] 2017-08-04 17:32
Duplicate of https://github.com/aspnet/HttpAbstractions/issues/907.

**Closed** 2017-08-04 17:32 UTC
Labels: duplicate
