### ISSUE TITLE
ActionDescription.BoundProperties not working as expected for FromQuery

### ISSUE THREAD

**Issue by Mardoxx** [aspnet/Mvc#7465] opened 2018-03-09 22:25 UTC
```cs
[Route("api/values")]
public class ValuesController : Controller
{
    [HttpGet]
    [CustomMethodSelector]
    public IActionResult Get([FromQuery] int? number)
    {
        return Ok(number);
    }
}

public class CustomMethodSelectorAttribute : ActionMethodSelectorAttribute
{
    public CustomMethodSelectorAttribute()
    {
    }

    public override bool IsValidForRequest(RouteContext routeContext, ActionDescriptor action)
    {
        var boundProps = action.BoundProperties
            .Select(x => x.Name)
            .ToList();

        Console.WriteLine($"[{String.Join(",", boundProps)}]");

        return true;
    }
}
```

`GET api/values`
\> []

`GET api/values?number`
\> []

`GET api/values?number=`
\> []

`GET api/values?number=1`
\> []

I'd expect it to be [], [number], [number], [number] respectively, or at least [number] on the last one judging how ASP.Net handles empty query values.

Does this only work for FromBody/FromForm?

**Comment by pranavkm** [comment] 2018-03-09 22:30
You likely need `ActionDescriptor.Parameters`

**Comment by Mardoxx** [comment] 2018-03-09 22:37
Oh hmm.. Props vs Parameters!

I wanted a list of bound parameters. But I don't suppose this is possible? This is too early in the pipeline isn't it?

What is the BoundProperties property for?

**Comment by pranavkm** [comment] 2018-03-09 22:38
All action parameters are typically model bound, so that should meet your requirement. BoundProperties are properties on the declaring type that get bound. Mvc supports this - e.g. `[FromBody] public Person Person { get; set; }`

**Comment by Mardoxx** [comment] 2018-03-09 22:43
Ok, so what about value types/primitives?

`ActionDescriptor.BoundProperties` is empty, and also is `.Properties` for my example!

**Comment by pranavkm** [comment] 2018-03-09 22:51
`int? number`  is a parameter. Is it located in `ActionDescriptor.Parameters`?

**Comment by Mardoxx** [comment] 2018-03-09 23:36
Why have you closed this... 👎

**Comment by Mardoxx** [comment] 2018-03-09 23:37
If you misunderstood my question, ask for clarification -- don't just prematurely close it.

**Comment by mkArtakMSFT** [comment] 2018-03-10 04:05
Hi Mardoxx. Can you please clarify what is your question? /cc @pranavkm

**Comment by tchelidze** [comment] 2018-03-10 11:18
Well, it seems to be little bit different.

Observing [ControllerActionDescriptorBuilderTest.cs](https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/test/Microsoft.AspNetCore.Mvc.Core.Test/Internal/ControllerActionDescriptorBuilderTest.cs) and in fact `BoundProperties` represent the **properties of Controller** (not an action parameter) which get bound from the current request.

Suppose following example

```C# 
public class HomeController : Controller
{
    [FromQuery(Name = "number")]
    public string number { get; set; }

    [HttpGet]
    [CustomMethodSelector]
    [Route("index")]
    public IActionResult Index([FromQuery] ActionViewModel model) => Ok(number);
}
```

If we invoke `Index` action, then inside `ActionDescriptor.BoundProperties`  will be 1 element, info of `number` property.

**Comment by Mardoxx** [comment] 2018-03-12 10:52
@mkArtakMSFT The question should be "How can I retrieve a list of bound parameters of an Action?" It would seem there is not a way, at least not with `ActionDescription`!

@tchelidze Checking the tests! Now why didn't I think of that! 😄  Thanks for the writeup

**Comment by mkArtakMSFT** [comment] 2018-03-13 17:01
@Mardoxx, you already confirmed that @pranavkm 's suggestion regarding `ActionDescriptor.Parameters` contained the data you were looking for - bound parameter info. Closing this thread as there seems to be no other question here.

**Comment by Mardoxx** [comment] 2018-03-13 17:16
No it doesn't.

**Comment by Mardoxx** [comment] 2018-03-13 17:16
`ActionDescriptor.Parameters` contains a list of all parameters, regardless of if they have a value bound to them or not.

**Comment by Mardoxx** [comment] 2018-03-13 17:19
I was under the assumption that @pranavkm was asking for this information for further diagnostic.

**Comment by pranavkm** [comment] 2018-03-13 17:31
Seems like we're talking past each other, let's go over this again:

* A controller or a Razor page handler may have bound properties indicated by `ActionDescription.BoundParameters`. An action also has parameters listed by `ActionDescription.Parameters`. Parameters are always model bound.
* Both BoundProperties and parameters may be annotated with specific attributes that disallows binding. `ModelMetadata.IsBindingAllowed` indicates if binding is allowed on parameters or bound properties. Note: for most parts, this only works correctly in 2.1.0.  See https://github.com/aspnet/Mvc/issues/6790 and it's PR https://github.com/aspnet/Mvc/pull/6842 for further details on what this entails.

Does this answer your question?

**Comment by mkArtakMSFT** [comment] 2018-03-19 18:26
Hi. We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by mkArtakMSFT** 2018-03-19 18:26 UTC
Labels: question
