### ISSUE TITLE
Model binding sometimes gives NREs

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Mvc#3676] opened 2015-12-02 15:21 UTC
I'm not sure what I'm seeing here, but my code definitely hasn't been reached yet.

I have the following Action defined on a controller:
```csharp
[HttpPost("UploadForm")]
public async Task<IActionResult> UploadForm([FromBody] JObject json)
```

With rc1-final on Linux, my application can reach two states
- Every request to this method succeeds
- Every request to this method fails with
```
      An unhandled exception has occurred while executing the request
      System.NullReferenceException: Object reference not set to an instance of an object
        at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultComplexObjectValidationStrategy+Enumerator.MoveNext () [0x00000] in <filename unknown>:0
        at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren (IValidationStrategy strategy) [0x00000] in <filename unknown>:0
        at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType () [0x00000] in <filename unknown>:0
        at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.Visit (Microsoft.AspNet.Mvc.ModelBinding.ModelMetadata metadata, System.String key, System.Object model) [0x00000] in <filename unknown>:0
        at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren (IValidationStrategy strategy) [0x00000] in <filename unknown>:0
        at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.VisitEnumerableType () [0x00000] in <filename unknown>:0
        at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.Visit (Microsoft.AspNet.Mvc.ModelBinding.ModelMetadata metadata, System.String key, System.Object model) [0x00000] in <filename unknown>:0
        at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.Validate (Microsoft.AspNet.Mvc.ModelBinding.ModelMetadata metadata, System.String key, System.Object model) [0x00000] in <filename unknown>:0
        at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.Validate (IModelValidatorProvider validatorProvider, Microsoft.AspNet.Mvc.ModelBinding.ModelStateDictionary modelState, Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationStateDictionary validationState, System.String prefix, System.Object model) [0x00000] in <filename unknown>:0
        at Microsoft.AspNet.Mvc.Controllers.DefaultControllerActionArgumentBinder+<BindModelAsync>d__6.MoveNext () [0x00000] in <filename unknown>:0
[…unreadable async stack trace through the request pipeline]
```

**Comment by rynowak** [comment] 2015-12-02 22:17
What version of mono?

**Comment by Tragetaschen** [comment] 2015-12-03 08:01
4.0.1 on my embedded ARM platform.

I've been using this version since May without problems.

**Comment by rynowak** [comment] 2015-12-07 21:03
@Tragetaschen can you share an example of the model code that's causing this issue so I can try to reproduce it?

**Comment by Tragetaschen** [comment] 2015-12-08 09:56
The request is an XHR from an angular2 SPA to the above action with the following request data. I restart the web server and just send it again to get the differing results.

```
Host: localhost:2226
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Content-Type: application/json; charset=UTF-8
Referer: http://localhost:2226/Settings/Expert
Content-Length: 1709
Cookie: CookieService={"TargetEnergyScaling":0,"TargetEnergyColor":0}
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache

{"RealTimePreset":"00:00:00","PersonalHazard":0.8,"NeutronNotification":false,"IdentificationStatistics":1,"GrossCountsPreset":0,"FinderFalseAlarmTime":10,"DoseRateAlarmThreshold":0.8,"Zinc-65":{"Severity":"Innocent","Usage":"NORM"},"Thallium-201":{"Severity":"Innocent","Usage":"MED"},"Thorium-232":{"Severity":"Innocent","Usage":"NORM"},"Technetium-99m":{"Severity":"Innocent","Usage":"MED"},"Radium-226":{"Severity":"Innocent","Usage":"NORM"},"Plutonium":{"Severity":"Threatening","Usage":"SNM"},"Neptunium-237":{"Severity":"Threatening","Usage":"SNM"},"Sodium-22":{"Severity":"Innocent","Usage":"IND"},"Manganese-54":{"Severity":"Innocent","Usage":"MED"},"Lutetium-176":{"Severity":"Innocent","Usage":"MED"},"Potassium-40":{"Severity":"Innocent","Usage":"MED"},"Iridium-192":{"Severity":"Innocent","Usage":"MED"},"Iodine-131":{"Severity":"Innocent","Usage":"MED"},"Iodine-125":{"Severity":"Innocent","Usage":"MED"},"Iodine-123":{"Severity":"Innocent","Usage":"MED"},"Europium-155":{"Severity":"Innocent","Usage":"IND"},"Europium-152":{"Severity":"Innocent","Usage":"IND"},"Uranium":{"Severity":"Threatening","Usage":"SNM"},"Cesium-137":{"Severity":"Innocent","Usage":"IND"},"Cesium-134":{"Severity":"Innocent","Usage":"IND"},"Cobalt-60":{"Severity":"Innocent","Usage":"IND"},"Cobalt-57":{"Severity":"Innocent","Usage":"IND"},"Cadmium-109":{"Severity":"Innocent","Usage":"IND"},"Barium-133":{"Severity":"Innocent","Usage":"IND"},"Americium-241":{"Severity":"Threatening","Usage":"IND"},"SaveGpsPosition":true,"Language":"en-US","DisplayBrightness":25,"BluetoothFunctions":1,"AutomaticClock":true,"ShowUsage":true,"ShowSeverity":true,"ShowConfidence":true,"KeyFeedback":3,"DoseRateUnit":0,"AlarmFeedback":3}
```

**Comment by Tragetaschen** [comment] 2015-12-08 11:12
I integrated the source code of MVC `rc1-final` and looked [at the offending method](https://github.com/aspnet/Mvc/blob/eef6c3883a7e27b8387b0925f0b6a88df0a484c5/src/Microsoft.AspNet.Mvc.Core/ModelBinding/Validation/DefaultComplexObjectValidationStrategy.cs#L97). It's that call to `GetRuntimeProperty()` that might return `null` depending on some unknown state most likely within Mono. This specific call tries to access the `Key` property of the first `Newtonsoft.Json.Linq.JProperty` ("RealTimePreset") in the JSON payload.

Can you share the bug that's referenced at the top of this mono-specific code path? (https://github.com/aspnet/External/issues/44)

**Comment by Tragetaschen** [comment] 2015-12-08 11:25
Found it in the PR (#3221): https://bugzilla.xamarin.com/show_bug.cgi?id=25717

**Comment by Tragetaschen** [comment] 2015-12-08 13:15
On further inspection (because `JProperty` doesn't have a `Key` property):

When the code succeeds, this is the validation chain:
```
validation visitor (visit): Newtonsoft.Json.Linq.JObject
validation visitor (enumerable): Newtonsoft.Json.Linq.JObject
validation visitor (children): Newtonsoft.Json.Linq.JObject
validation visitor (visit): Newtonsoft.Json.Linq.JProperty
validation visitor (enumerable): Newtonsoft.Json.Linq.JProperty
validation visitor (children): Newtonsoft.Json.Linq.JProperty
```
`JProperty` and `JObject` are both recognized as enumerable things, because they are.

When things fail, the `JProperty` suddenly is a complex type:
```
validation visitor (visit): Newtonsoft.Json.Linq.JObject
validation visitor (enumerable): Newtonsoft.Json.Linq.JObject
validation visitor (children): Newtonsoft.Json.Linq.JObject
validation visitor (visit): Newtonsoft.Json.Linq.JProperty
validation visitor (complex): Newtonsoft.Json.Linq.JProperty
validation visitor (children): Newtonsoft.Json.Linq.JProperty
```
And visiting the children tries to find a non-existing `Key` Property

But that means [`typeof(IEnumerable).IsAssignableFrom(ModelType)`](https://github.com/aspnet/Mvc/blob/9342cb0ab78add8c527edcbc4c0988edc96f01e3/src/Microsoft.AspNet.Mvc.Abstractions/ModelBinding/ModelMetadata.cs#L365) sometimes returns true and sometimes false for the same actual type.

:tired_face:

**Comment by Tragetaschen** [comment] 2015-12-08 13:50
Ok, it's a runtime ordering issue of the reflection metadata, because `JObject` implements various `IEnumerable<>` variants and the way the validation handles this.

Notably, everything works when the last `FirstOrDefault()` call in `ClosedGenericMatcher.ExtractGenericInterface` returns `IEnumerable<JToken>` and it doesn't when it returns `IEnumerable<KeyValuePair<string, JToken>>`.

That becomes a problem because the non-generic call to `_model.GetEnumerator()` in the `DefaultCollectionValidationStrategy.Enumerator` chooses an enumerator over a different type and then things blow up.


There is a missing link between the generated enumerator and the detected ElementMetadata.

**Comment by rynowak** [comment] 2015-12-08 16:31
Thanks @Tragetaschen for the analysis, this is a big help!

It looks like you're right, we definitely have a bug with `ExtractGenericInterface` that needs to be addressed.

Also, we really shouldn't be trying to deeply validate `JObject` and friends anyway. I think we need the check here: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinding/Validation/ValidationVisitor.cs#L213 to apply to `JObject` and the other related types.

**Comment by rynowak** [comment] 2015-12-08 18:33
@Tragetaschen 

@dougbu and I spent some time looking into this and we came up with 4 issues that need to addressed. I've also been working with another customer via mail, who's hitting similar problems, so their issues are reflected here too.

Problems:
 1). In your case, we shouldn't be getting here at all. It's not intended that we deeply validate `JObject` or any related types because there's no validation metadata there. It's just wasted work.

The logic that we use to `IExcludeTypeFilter` should apply to collections as well as complex types.

2). `ModelMetadata.ElementMetadata` is non-deterministic based on reflection order when a type implements `IEnumerable<>` twice.

In the example you provided, my hypothesis is that the failure case is like this:
```
validation visitor (visit): Newtonsoft.Json.Linq.JObject
validation visitor (enumerable): Newtonsoft.Json.Linq.JObject
validation visitor (children): Newtonsoft.Json.Linq.JObject
validation visitor (visit): KeyValuePair<string, Newtonsoft.Json.Linq.JProperty>
validation visitor (complex): KeyValuePair<string, Newtonsoft.Json.Linq.JProperty>
validation visitor (children): KeyValuePair<string, Newtonsoft.Json.Linq.JProperty>
```

This causes a problem because of 4).


3). `ModelMetadata.ElementMetadata` has a race condition here: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinding/Metadata/DefaultModelMetadata.cs#L253

This is non-atomic. It's possible to for a thread to see `_haveCalculatedElementMetadata` as true, but get a null value for `_elementMetadata`.

4). `DefaultCollectionValidationStrategy` assumes that the `IEnumerable` implementation of type will yield elements of the type corresponding to `ModelMetadata.ElementMetadata`. This isn't a safe guarantee.

In the example of `JObject`, the `IEnumerable` implementation returns instances of `JToken` not of `KeyValuePair<string, JToken>`


@Tragetaschen - can you do me a favor? Can you try pasting something like this into the startup code of your app, and tell me what you see on a few run-throughs? I just want to confirm that the non-determinism in 2). is really what we're seeing.

```
 var provider = app.ApplicationServices.GetRequiredService<IModelMetadataProvider>();
var metadata = provider.GetMetadataForType(JObject));
Console.WriteLine(metadata.ElementMetadata.ModelType);
```

**Comment by Tragetaschen** [comment] 2015-12-09 13:46
I had already further `Console.WriteLine`d my way through the validation chain and saw the discrepancy between `model.GetType()` (which I showed in my example) and the associated metadata. That's why I came to my conclusion.

Nontheless, I integrated your snippet in my Startup class and as expected, that yields different results on consecutive runs:
```
Newtonsoft.Json.Linq.JToken
```
and then the POST request works,
```
System.Collections.Generic.KeyValuePair`2[System.String,Newtonsoft.Json.Linq.JToken]
```
and then the POST request doesn't.

**Comment by rynowak** [comment] 2015-12-09 21:16
@Tragetaschen - I've checked in changes for issues 1, 3, and 4 described above. We'll no longer be trying to validate `JObject` and pals, which should resolve your issue. 

This is available in MVC builds >= rc2-16599

**Comment by rynowak** [comment] 2015-12-14 17:04
I've corrected all of the issues called out here: https://github.com/aspnet/Mvc/issues/3676#issuecomment-162972683

cf6662d0c3f7d764089a3938f9fb3a21bf25f55d
96de1dbe4b914734cfe97f271230ff6c6ddcfa11
b82deb7d186c980d5bbfe12357715a69f7fd362f
ee6ef3f25fbd2a0f5a6215c6f98c1df0912d6090

Please reopen if you're seeing any similar issues.

**Closed by rynowak** 2015-12-14 17:04 UTC
Labels: 2 - Working, bug
