### ISSUE TITLE
ModelState Validation doesn't work as expected

### ISSUE THREAD

**Issue by Samvrie** [aspnet/Mvc#2198] opened 2015-03-18 08:16 UTC
Hi,

EDIT : I'm on the beta3 packages, VS CTP 6

I'm actually making some test on the validation of my Model.
I have a class with different property
```C#
    public abstract class User
    {
        public string Id { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required, MaxLength(100)]
        public string FirstName { get; set; }
        [Required, MaxLength(100)]
        public string LastName { get; set; }
        [Required, MaxLength(255)]
        public string Address { get; set; }
 
        public DateTime Birthday { get; set; }
        [Required]
        [EnumDataType(typeof(CountryIso))]
        public object CountryOfResidence { get; set; }
        [Required]
        [EnumDataType(typeof(CountryIso))]
        public object Nationality { get; set; }
    }
```

Everything is working fine for the Required, but the EnumDataType and EmailAddress doesn't work as expected.

I wrote a simple test 

```c#
        [Fact]
        public void PostNatural_UnknowCountryIso_PropertyNameIsInList()
        {
            var user = new UserNatural {
                FirstName = "a",
                LastName = "a",
                Email = "a",
                Address = "a",
                Nationality = 250,
                CountryOfResidence = 250
            };
            var results = new List<ValidationResult>();

            ValidationHelper.TryValidate(user, results);

            Assert.True(results.Any(r => r.MemberNames.Any(memberName => memberName == nameof(UserNatural.Nationality))));
        }
```

To see if the Enum is properly found (The last value is 249)
```C#
public enum CountryIso 
{
       ...
        ZM = 248,
        ZW = 249
}
```

But the model State is always Valid.
Am i missing something?
I've tried to Switch the object Type of the properties to string(Which doesn't compile) and int (Which doesn't find an error when the input isn't inserted).
Same with EmailAdresss the "a" value is accepted.

Here is code of The ValidationHelper
```C#
    internal static class ValidationHelper
    {
        internal static bool TryValidate(object @object, ICollection<ValidationResult> results)
        {
            var context = new ValidationContext(@object, serviceProvider: null, items: null);

            var isValid = Validator.TryValidateObject(@object, context, results);
            return isValid;
        }
    }
```

**Comment by danroth27** [comment] 2015-03-18 16:38
@rynowak @dougbu Where are we at with support for these data annotations?

**Comment by dougbu** [comment] 2015-03-18 16:59
see #327.

the basic answer is that we have adapters that _could_ support `[Validation]` and any subclass.  instead we register only a few subclasses.  so we support `[EmailAddress]` but not `[EnumDataType]`.

@Samvrie `[EmailAddress]` has very permissive validation.  "a" is valid.  you could try to find something the following regular expression would reject:
``` c#
"^((([a-z]|\\d|[!#\\$%&'\\*\\+\\-\\/=\\?\\^_`{\\|}~]|[\\u00A0-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFEF])+(\\.([a-z]|\\d|[!#\\$%&'\\*\\+\\-\\/=\\?\\^_`{\\|}~]|[\\u00A0-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFEF])+)*)|((\\x22)((((\\x20|\\x09)*(\\x0d\\x0a))?(\\x20|\\x09)+)?(([\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x7f]|\\x21|[\\x23-\\x5b]|[\\x5d-\\x7e]|[\\u00A0-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFEF])|(\\\\([\\x01-\\x09\\x0b\\x0c\\x0d-\\x7f]|[\\u00A0-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFEF]))))*(((\\x20|\\x09)*(\\x0d\\x0a))?(\\x20|\\x09)+)?(\\x22)))@((([a-z]|\\d|[\\u00A0-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFEF])|(([a-z]|\\d|[\\u00A0-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFEF])([a-z]|\\d|-|\\.|_|~|[\\u00A0-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFEF])*([a-z]|\\d|[\\u00A0-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFEF])))\\.)+(([a-z]|[\\u00A0-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFEF])|(([a-z]|[\\u00A0-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFEF])([a-z]|\\d|-|\\.|_|~|[\\u00A0-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFEF])*([a-z]|[\\u00A0-\\uD7FF\\uF900-\\uFDCF\\uFDF0-\\uFFEF])))\\.?$"
```

**Comment by Samvrie** [comment] 2015-03-18 19:15
@dougbu Thanks for the answer i will try a RegExp for my Email checking.
Is there a way to actually add my own DataAnnotations validations?

**Comment by rynowak** [comment] 2015-03-18 19:17
@Samvrie the simplest way would be to subclass `ValidationAttribute`. Nothing much should have changed here so any public docs you find for `DataAnnotations` should be valid for creating your own.

**Comment by Samvrie** [comment] 2015-03-18 19:41
Thanks! I will look into that!

**Comment by Samvrie** [comment] 2015-03-19 08:58
Well i'm facing an other problems. I've implemented my own class for *EnumValidation*, my attributes is properly created, but the **IsValid** method is never called.

**Comment by dougbu** [comment] 2015-03-19 14:34
@Samvrie please file a separate issue for your new concern.  include information about how your `enum` validator is being used.

do you agree with closing this issue as a duplicate of #327?

btw the regular expression I provided earlier is from at least one version of `[EmailAddress]`. my suggestion was to reverse-engineer that to find a string that would result in validation failures.

**Comment by Samvrie** [comment] 2015-03-19 18:03
Yes sure, we can close this issue, i will open a new one more appropriate to the case

**Comment by dougbu** [comment] 2015-03-19 18:27
thx

**Closed by dougbu** 2015-03-19 18:27 UTC
Labels: 1 - Ready, investigate
