### ISSUE TITLE
Mvc binds all posted fields to IDictionary

### ISSUE THREAD

**Issue by stephtr** [aspnet/Mvc#6744] opened 2017-09-01 07:48 UTC
When extending the mvc template (`dotnet new mvc`) by the following code:

```
public IActionResult Test()
{
    var model = new Dictionary<string, string>();
    model.Add("test", "abc");
    return View(model);
}

[HttpPost]
public IActionResult Test(IDictionary<string, string> parameters)
{
    return View(parameters);
}
```

```
@model IDictionary<string, string>

<table>
    <tr>
        <td>Key</td>
        <td>Value</td>
    </tr>
    @foreach (var data in Model)
    {
        <tr>
            <td>@data.Key</td>
            <td>@data.Value</td>
        </tr>
    }
</table>

<form method="post">
    <p>
        Test: <input asp-for="@Model["test"]" />
    </p>
    <p>
        <input type="submit" />
    </p>
</form>
```

the following fields are posted (antiforgery is enabled by default):
```
[test]: abc
__RequestVerificationToken: ...
```

Mvc includes both fields in the `IDictionary` argument, but in my opinion only the `test` field should be included. I could wrap the `IDictionary` in its own class, but I thought that my method should either also work or at least throw an error (since for example replacing the `IDictionary` by a `string` fails with `The name of an HTML field cannot be null or empty.`).

While the problem resulting in using an `IDictionary<string, string>` is not that large the situation gets more complicated when using an `IDictionary<int, string>` since converting `__RequestVerificationToken` to an `int` throws a middleware exception.

**Comment by Eilon** [comment] 2017-09-01 18:24
Well, I can certainly repro this, and it interestingly gets values only for the form (not query string, not route data, etc.).

From a discussion with @dougbu , this appears to be by design regarding the form.

As far as hiding the `__RequestVerificationToken`, I'm not sure if that's a good idea, because ultimately the model binding info being used is perfectly valid.

I think the recommended solution to this is to use a common prefix for all the posted data, for example:

This is the controller action:

```c#
        [HttpPost]
        public IActionResult Index(IDictionary<string, string> x)
        {
            return Ok(x);
        }
```

And this is the view:

```html
<form method="post">
    <input type="text" name="x.k1" value="v1" />
    <input type="text" name="x.k2" value="v2" />
    <input type="submit" value="Submit" />
</form>
```

And when I post the form, I get only this data returned:

![image](https://user-images.githubusercontent.com/202643/29982783-f5d8da68-8f07-11e7-8f1e-5d9ef3536ece.png)

Note that only the values that have the `x.` prefix are in the `x` dictionary.

Otherwise there's really no way to guarantee that "other stuff" won't show up in the dictionary. Today it's the request verification token, but tomorrow it could be any other data that's posted.

For these reasons, I'm closing the issue.

cc @rynowak in case he has further thoughts.

**Closed by Eilon** 2017-09-01 18:24 UTC

**Comment by dougbu** [comment] 2017-09-01 19:20
@stephtr you can also change `ViewData.TemplateInfo.HtmlFieldPrefix` to "x" around the `<input/>` elements that correspond to your dictionary.
