### ISSUE TITLE
FileVersionProvider should be replaceable

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#6371] opened 2017-06-07 00:34 UTC
Either though DI or an option so that devs can decide to use their own file eviction logic (timestamp for instance) or a faster hash.

**Comment by markrendle** [comment] 2017-07-24 10:13
Should `FileVersionProvider` be replaceable, or would adding a `IFileVersionHashProvider` or `IFileVersionTokenProvider` interface that can be replaced work just as well? Most of the logic in `FileVersionProvider` looks standard.

**Comment by mistakenot** [comment] 2017-09-21 20:12
Could there be an arguement for putting a `IFileInfoHashProvider` in the [FileSystem](https://github.com/aspnet/FileSystem) project so that it lives with the IFileInfo interface instead of the TagHelper project?

**Comment by mkArtakMSFT** [comment] 2018-01-04 20:47
@sebastienros, what is the status of this?

**Comment by sebastienros** [comment] 2018-02-16 21:51
@mkArtakMSFT yeah, what's the status of this?

**Comment by Eilon** [comment] 2018-02-16 21:56
Hey what's the status of this?

Just kidding. @sebastienros , is this something you want to contribute so you can consume for Orchard Core? We're open to that. But otherwise it won't happen in 2.1.

**Comment by sebastienros** [comment] 2018-02-16 21:58
Fair enough, I'll ask my manager if I can work on it.

**Comment by q42jaap** [comment] 2018-05-09 08:28
We are running into an issue (see #7735) where we want to verify version hashes in the static files middleware. I'd be willing to contribute.

**Comment by pranavkm** [comment] 2018-05-09 17:25
Here's my suggestion for what this could look like:

```C#
public class FileVersionProvider
{
    public abstract string GetFileVersion(IFileInfo fileInfo);
}

internal class DefaultFileVersionProvider : FileVersionProvider
{
    private MemoryCache _cache;
    
    public override string GetFileVersion(string path)
    {
        if (!_cache.TryGetValue(path, out value))
        {
            var fileInfo = GetFileInfo();
            value = GetHashForFile(path);
            _cache.Set(path, value, fileSystem.Watch(path));
        }
    }
}

internal class FileVersionUtility
{
    private ConcurrentDictionary<string, (string versionedPath, string version)> _fileVersionLookup;
    
    public string AddFileVersionToPath(string path)
    {
        var currentVersion = _fileVersionProvider.GetFileVersion(path);
        if (!_fileVersionLookup.TryGetValue(path, out var result) || !string.Equals(result.version, currentVersion))
        {
            var versionedPath = QueryHelpers.AddQueryString(path, VersionKey, currentVersion);
            result = _fileVersionProvider.GetOrAdd(path, (versionedPath, currentVersion));
        }
        
        return result.versionedPath;
    }
}
```

**Comment by pranavkm** [comment] 2018-05-11 14:55
The current API contract is string -> string. I'd rather not change it and let the default implementation assume the string is a file in the IFileProvider.

**Comment by pranavkm** [comment] 2018-06-12 22:36
@q42jaap are you still interested in submitting a PR for this?

**Comment by q42jaap** [comment] 2018-06-13 15:49
Hi Pranavkm, I've been pondering this and then I was moved onto another project :( So I'm not going to be able to contribute atm 😢

**Comment by pranavkm** [comment] 2018-06-13 16:28
That's unfortunate. @mkArtakMSFT moving this out to backlog. The issue is still up-for-grabs, so other contributors are welcome to give this a shot.

**Closed** 2018-09-14 16:17 UTC
Labels: 2 - Working, PRI: 3 - Optional, cost: S, enhancement, up-for-grabs
