### ISSUE TITLE
Cannot render correctly DisplayFor interface ViewModel

### ISSUE THREAD

**Issue by lucacelenza** [aspnet/Mvc#8083] opened 2018-07-13 22:55 UTC
#### Is this a Bug or Feature request?
Bug **`Microsoft.AspNetCore.All` v2.0.8**

#### Description of the problem:
I'm currently working on a simple project to get the grasp of the new ASP.NET framework. I have a ViewModel which has an interface property. Actually, this is a thing I often come across whenever laying out ViewModels for any of my projects.

Let's suppose I have this situation:

```
public class FamilyViewModel 
{
    public string Name { get; set; }
    public IChildrenViewModel Children { get; set; }
}

public interface IChildrenViewModel 
{
    //this is just a marker interface
}

public class NoChildrenViewModel
{
    //as the name implies, no children here
}

public class ChildrenViewModel
{
    public IEnumerable<string> Children { get; set; }
}

```
If I try rendering the IChildrenViewModel property of FamilyViewModel with a `@Html.DisplayFor(m => m.Children)` **and** no IChildrenViewModel.cshtml template is found, ASP.NET Core tries a _dummy rendering_ of the ViewModel.

Instead of searching for the DisplayTemplate related to the implementation provided in the model, ASP.NET Core outputs:

- property name and property value of the primitive type properties;
- no output at all for complex objects.

#### Steps to reproduce:
I created a [github repo](https://github.com/lucacelenza/aspnet-mvc-interfaceviewmodel) to show the problem and the difference with ASP.NET MVC 5.

**Comment by mkArtakMSFT** [comment] 2018-07-16 16:30
Thanks for contacting us, @lucacelenza.
@NTaylorMullen, can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment] 2018-07-16 23:13
Hi @lucacelenza, first off I want to say that your repro was fantastic! Very simple, easy to reproduce and informative; thank you!

So in regards to this issue it's actually by design. When moving to Core we found that in legacy ASP.NET we had a bad habit of oversharing (using view model templates that were unintended). To combat this we removed that capability and required users to be explicit in the types that they use when working with display templates. Sorry I don't have a better answer for you!

**Closed by NTaylorMullen** 2018-07-16 23:13 UTC
Labels: by design, investigate

**Comment by lucacelenza** [comment] 2018-07-23 08:29
Thank you for your answer and your feedback, @NTaylorMullen. However I still don't get how to handle this situation without piling up the .cshtml view code with **if** statements, depending on the complexity of the ViewModel. 

```
//ViewModel
public class FamilyViewModel 
{
    public string Name { get; set; }
    public IEnumerable<string> Children { get; set; }
}

//.chstml
@if (Model.Children.Any())
{
 ...
}
else
{
 ...
}
```

Isn't it something that should _also_ be avoided?

**Comment by NTaylorMullen** [comment] 2018-07-25 17:49
Not sure I entirely get your snippet code but I'm assuming in your View you need to type check the children and then render them under the proper type?

This is indeed a side effect of our decision to require explicit types to be declared. I'd recommend writing some helper methods to aid in the workings of your own types 😄
