### ISSUE TITLE
Can you make it possible to stop swallowing model binding exceptions?

### ISSUE THREAD

**Issue by joshmouch** [aspnet/Mvc#3898] opened 2016-01-10 19:53 UTC
When trying to deserialize JSON into an Action argument during a Post, when an exception occurs during the deserialization, the default behavior of MVC is to swallow the exception and pass in a null value for the argument.  

This causes all sorts of problems because:
1. It allows actions to be called without the expected model being there.
2. In production, any automated exception logging tools (like Microsoft Azure Application Insights) will never catch the problem because the exception was swallowed up and ignored.
3. It also makes debugging difficult because in order to see what the problem was with deserialization, you have to attach to the process with Visual Studio and add the following cod to your Startup.cs.  Before DNX this wasn't an issue, but with support for Edit and Continue removed and the general new debugging paradigm DNX brings (code is compiled after every save), this becomes cumbersome.

````
services.AddMvc()
				.AddJsonOptions(options =>
				{
					options.SerializerSettings.Error = (sender, args) =>
					{
						// Exceptions are being eaten up and ignored right now.  Set breakpoint here in order to debug theproblem.
						throw new Exception("There was an error during deserialization.");
					};
				});
````

I'd prefer it the exception stopped the entire pipeline and returned a 500 (along with the Developer Exception page) just like if an exception is throw inside the Action method.

Here's my example Action for clarity:
````
[HttpPost("{id}")]
public IActionResult Post([FromBody]MyModel value)
{}
````

Is there a way to do this?

**Comment by dougbu** [comment] 2016-01-10 20:37
As-is, your action will ignore _any_ error during model binding or validation. It should check `ModelState.IsValid`.

For this particular error, an `Exception` thrown during JSON deserialization is added to the `ModelStateDictionary`.

**Comment by joshmouch** [comment] 2016-01-10 21:13
Sorry, but this doesn't really answer my question.
BTW, I am checking ModelState.IsValid.
If I'm to understand your direction, you think I should re-throw any exceptions in ModelState.Exception... correct?
If that's the way to go, there's still potential for a programmer to forget to re-throw in some action somewhere and swallow up the error.

**Comment by davidfowl** [comment] 2016-01-10 21:33
> 1. It allows actions to be called without the expected model being there.

Would you want to control that on a global basis or on a per action basis? That's how MVC has worked since forever. 

> 2. In production, any automated exception logging tools (like Microsoft Azure Application Insights) will never catch the problem because the exception was swallowed up and ignored.

That's not true, errors are still logged: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Formatters.Json/JsonInputFormatter.cs#L127

> It also makes debugging difficult because in order to see what the problem was with deserialization, you have to attach to the process with Visual Studio and add the following cod to your Startup.cs. Before DNX this wasn't an issue, but with support for Edit and Continue removed and the general new debugging paradigm DNX brings (code is compiled after every save), this becomes cumbersome.

Can you elaborate some more? If you're debugging nothing is recompiled until you detach. What is harder to debug?

/cc @Eilon

**Comment by joshmouch** [comment] 2016-01-10 22:05
It's good to know that the exception is logged.  That means it will be caught in production.

It sounds like there isn't really a way to do what I want...

As far as making development more difficult, here is the current workflow:

1. Ctrl+F5 in Visual Studio. Browser window is open and stays open.
2. Make changes in code.  DNX automatically recompiles.
3. View changes in existing browser window.
4. If there is an exception, a 500 is returned and the Developer Exception page gives you a stack trace.

However, if you have a model binding error, you have to jump out of the workflow and:
1. Hit F5 in Visual Studio to run attached to IIS Express.  A new browser window is open.
2. Set breakpoint in the Error handler I created in Startup.cs.
3. View changes in existing browser window.  (this may take a while if you are deep into the application)
4. Breakpoint is hit... figure out the problem.
5. Stop the application.  Fix problem.
6. Repeat #1 through #5 until binding works correctly (keep in mind it may take a while to get back to the error condition).
7. Hit Ctrl-F5 again to enter "DNX-watch" mode.  Close the extra browser window that was opened.
8. Jump back to the regular workflow, above.

**Comment by davidfowl** [comment] 2016-01-10 22:51
@joshmouch How is that different from the workflow with MVC 5.x and ASP.NET 4.x or even WebAPI? I'm just trying to understand if you're comparing something old how it used to work or just generally complaining about the behavior?

**Comment by joshmouch** [comment] 2016-01-11 00:18
It's different because of Edit and Continue.
In MVC 5.x you could enable Edit and Continue and stick to the first workflow (except use F5 instead of ctrl-F5).
In MVC 6.x you "emulate" Edit and Continue by using Ctrl-F5 (which I believe uses dnx-watch).

However, in MVC 6.x you have to switch back and forth in order to just see what the exception is.  But this is *only* the case for model binding errors.  It's sometimes as much as 5 minutes extra time just to see what the error was.

You've offered me two solutions.
A. Re-throw the error in the action.
B. Subscribe to the log somehow while developing (I'll have to research this).

Option A is better because I consider this to be an exception and don't think it should be ignored.

**Comment by davidfowl** [comment] 2016-01-11 02:02
How does edit and continue let you see the exception for model binding errors on Mvc 5?

**Comment by joshmouch** [comment] 2016-01-11 02:21
With the first piece of code a pasted or else, I suppose, with the ModelBinding.Exception you mentioned earlier.

**Comment by danroth27** [comment] 2016-01-11 17:43
Returning a 500 when there is a serialization issue is probably not what you want. In most cases, these exceptions will get caused by a bad request from the client (ex. the client sends you malformed JSON). Typically you would respond to the client with a 4xx error and let them know what was wrong with the request. The current behavior let's you handle these cases and return the appropriate error.

**Comment by joshmouch** [comment] 2016-01-11 17:53
@danroth27 True.  A 4xx exception would be fine... (e.g. throw new HttpException(400, "Bad Request");

**Comment by danroth27** [comment] 2016-01-11 18:38
Well, what I'm trying to say is that this really isn't an exceptional case. The server is behaving as expected. It's the client that did something wrong and the server just needs to let the client know. You wouldn't throw an exception for this case - you would just return a 4xx level response.

**Comment by joshmouch** [comment] 2016-01-11 19:13
@danroth27  Hmm... difference of opinion, I guess.  As a whole application (server + client), the user is in an exceptional state that would be considered a showstopping bug.

**Comment by danroth27** [comment] 2016-01-13 17:22
You can log the error on the server, but in general you probably don't want to be throwing exceptions on the server for misbehaving clients. You don't in general have control over which clients are sending your requests.

Closing as we don't plan to change the current behavior.

**Closed by danroth27** 2016-01-13 17:22 UTC
