### ISSUE TITLE
After calling SignInAsync, the IsAuthenticated function still returns false

### ISSUE THREAD

**Issue by jamesgurung** [aspnet/Mvc#6478] opened 2017-07-02 10:29 UTC
**Problem:**

After calling `SignInAsync`, the `IsAuthenticated` function still returns `false`.

This is a regression from ASP.NET Core 2 Preview 1 in which the same code worked as expected.

**Repro:**

New project:
```
dotnet --version
2.0.0-preview2-006497
dotnet new mvc
```

Add in startup.cs:

```
public void ConfigureServices(IServiceCollection services)
{
  services.AddCookieAuthentication(o => {
    o.LoginPath = "/login";
  });
  services.AddMvc();
}
```

Modify HomeController.cs:
```
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace SignInDemo.Controllers
{
  public class HomeController : Controller
  {
    public IActionResult Index()
    {
      return Content(User.Identity.IsAuthenticated.ToString());
    }

    [Route("/login")]
    public async Task<IActionResult> Login()
    {
      var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
      identity.AddClaim(new Claim(ClaimTypes.Name, "testuser"));
      await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));
      return Redirect("/");
    }
  }
}
```

**Expected result:**

The homepage displays "False". After navigating to /login an auth cookie is set and it redirects to the homepage which now displays "True".

**Actual result:**

The homepage displays "False". After navigating to /login a cookie is set (".AspNetCore.Cookies") and it redirects to the homepage however this still displays "False".

**Comment by davidfowl** [comment] 2017-07-03 06:53
@jamesgurung What does your `Configure` method look like?

**Comment by jamesgurung** [comment] 2017-07-03 19:59
@davidfowl I had previously (wrongly) used the default implementation of `Configure` in my repro. I've now added `app.UseAuthentication()` but this does not fix the problem:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
  app.UseAuthentication();

  if (env.IsDevelopment()) {
    app.UseDeveloperExceptionPage();
  } else {
    app.UseExceptionHandler("/Home/Error");
  }

  app.UseStaticFiles();

  app.UseMvc(routes => {
    routes.MapRoute(
        name: "default",
        template: "{controller=Home}/{action=Index}/{id?}");
  });
}
```

**Comment by davidfowl** [comment] 2017-07-03 20:01
@jamesgurung Can you post your minimal sample to github so we can run it? Based on what you described, it sounds like you were missing the `UseAuthentication` middleware.

**Comment by Eilon** [comment] 2017-07-03 20:03
Also maybe enable the console logger w/ full output?

**Comment by jamesgurung** [comment] 2017-07-03 20:20
I've put the minimal repro on GitHub: https://github.com/jamesgurung/SignInDemo

Also, here are the console logs:

**Run the app...**
```
SignInDemo> info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
SignInDemo>       User profile is available. Using 'C:\Users\James\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
SignInDemo> dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
SignInDemo>       Hosting starting
SignInDemo> dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[4]
SignInDemo>       Hosting started
SignInDemo> dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[0]
SignInDemo>       Loaded hosting startup assembly SignInDemo
SignInDemo> dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[0]
SignInDemo>       Loaded hosting startup assembly Microsoft.AspNetCore.ApplicationInsights.HostingStartup
SignInDemo> dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[0]
SignInDemo>       Loaded hosting startup assembly Microsoft.AspNetCore.Server.IISIntegration
SignInDemo> Hosting environment: Development
SignInDemo> Content root path: D:\Documents\Visual Studio 2017\Projects\SignInDemo
SignInDemo> Now listening on: http://localhost:18728
SignInDemo> Application started. Press Ctrl+C to shut down.
SignInDemo> dbug: Microsoft.AspNetCore.Server.Kestrel[1]
SignInDemo>       Connection id "0HL62A0MG0A1D" started.
SignInDemo> dbug: Microsoft.AspNetCore.Server.Kestrel[1]
SignInDemo>       Connection id "0HL62A0MG0A1C" started.
SignInDemo> dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[19]
SignInDemo>       Connection id "0HL62A0MG0A1C" reset.
SignInDemo> dbug: Microsoft.AspNetCore.Server.Kestrel[10]
SignInDemo>       Connection id "0HL62A0MG0A1C" disconnecting.
SignInDemo> dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[7]
SignInDemo>       Connection id "0HL62A0MG0A1C" sending FIN.
SignInDemo> dbug: Microsoft.AspNetCore.Server.Kestrel[2]
SignInDemo>       Connection id "0HL62A0MG0A1C" stopped.
SignInDemo> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
SignInDemo>       Request starting HTTP/1.1 GET http://localhost:56469/  
SignInDemo> dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
SignInDemo>       The request path / does not match a supported file type
SignInDemo> dbug: Microsoft.AspNetCore.Routing.RouteBase[1]
SignInDemo>       Request successfully matched the route with name 'default' and template '{controller=Home}/{action=Index}/{id?}'.
SignInDemo> dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
SignInDemo>       Executing action SignInDemo.Controllers.HomeController.Index (SignInDemo)
SignInDemo> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
SignInDemo>       Executing action method SignInDemo.Controllers.HomeController.Index (SignInDemo) with arguments ((null)) - ModelState is Valid
SignInDemo> dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
SignInDemo>       Executed action method SignInDemo.Controllers.HomeController.Index (SignInDemo), returned result Microsoft.AspNetCore.Mvc.ContentResult.
SignInDemo> info: Microsoft.AspNetCore.Mvc.Internal.ContentResultExecutor[1]
SignInDemo>       Executing ContentResult with HTTP Response ContentType of text/plain; charset=utf-8
SignInDemo> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
SignInDemo>       Executed action SignInDemo.Controllers.HomeController.Index (SignInDemo) in 39.7352ms
SignInDemo> dbug: Microsoft.AspNetCore.Server.Kestrel[9]
SignInDemo>       Connection id "0HL62A0MG0A1D" completed keep alive response.
SignInDemo> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
SignInDemo>       Request finished in 227.8668ms 200 text/plain; charset=utf-8
```

**Navigate to /login...**
```
SignInDemo> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
SignInDemo>       Request starting HTTP/1.1 GET http://localhost:56469/login  
SignInDemo> dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
SignInDemo>       The request path /login does not match a supported file type
SignInDemo> dbug: Microsoft.AspNetCore.Routing.Tree.TreeRouter[1]
SignInDemo>       Request successfully matched the route with name '(null)' and template 'login'.
SignInDemo> dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
SignInDemo>       Executing action SignInDemo.Controllers.HomeController.Login (SignInDemo)
SignInDemo> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
SignInDemo>       Executing action method SignInDemo.Controllers.HomeController.Login (SignInDemo) with arguments ((null)) - ModelState is Valid
SignInDemo> dbug: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[37]
SignInDemo>       Reading data from file 'C:\Users\James\AppData\Local\ASP.NET\DataProtection-Keys\key-ccde4c71-1c73-4d8d-8dea-7a7213eebaac.xml'.
SignInDemo> dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[18]
SignInDemo>       Found key {ccde4c71-1c73-4d8d-8dea-7a7213eebaac}.
SignInDemo> dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver[13]
SignInDemo>       Considering key {ccde4c71-1c73-4d8d-8dea-7a7213eebaac} with expiration date 2017-08-29 20:24:48Z as default key.
SignInDemo> dbug: Microsoft.AspNetCore.DataProtection.TypeForwardingActivator[0]
SignInDemo>       Forwarded activator type request from Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
SignInDemo> dbug: Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor[51]
SignInDemo>       Decrypting secret element using Windows DPAPI.
SignInDemo> dbug: Microsoft.AspNetCore.DataProtection.TypeForwardingActivator[0]
SignInDemo>       Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
SignInDemo> dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory[4]
SignInDemo>       Opening CNG algorithm 'AES' from provider '(null)' with chaining mode CBC.
SignInDemo> dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory[3]
SignInDemo>       Opening CNG algorithm 'SHA256' from provider '(null)' with HMAC.
SignInDemo> dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider[2]
SignInDemo>       Using key {ccde4c71-1c73-4d8d-8dea-7a7213eebaac} as the default key.
SignInDemo> trce: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector[31]
SignInDemo>       Performing protect operation to key {ccde4c71-1c73-4d8d-8dea-7a7213eebaac} with purposes ('D:\Documents\Visual Studio 2017\Projects\SignInDemo', 'Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware', 'Cookies', 'v2').
SignInDemo> info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[10]
SignInDemo>       AuthenticationScheme: Cookies signed in.
SignInDemo> dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
SignInDemo>       Executed action method SignInDemo.Controllers.HomeController.Login (SignInDemo), returned result Microsoft.AspNetCore.Mvc.RedirectResult.
SignInDemo> info: Microsoft.AspNetCore.Mvc.Internal.RedirectResultExecutor[1]
SignInDemo>       Executing RedirectResult, redirecting to /.
SignInDemo> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
SignInDemo>       Executed action SignInDemo.Controllers.HomeController.Login (SignInDemo) in 111.255ms
SignInDemo> dbug: Microsoft.AspNetCore.Server.Kestrel[9]
SignInDemo>       Connection id "0HL62A0MG0A1D" completed keep alive response.
SignInDemo> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
SignInDemo>       Request finished in 141.4457ms 302 
SignInDemo> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
SignInDemo>       Request starting HTTP/1.1 GET http://localhost:56469/  
SignInDemo> dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
SignInDemo>       The request path / does not match a supported file type
SignInDemo> dbug: Microsoft.AspNetCore.Routing.RouteBase[1]
SignInDemo>       Request successfully matched the route with name 'default' and template '{controller=Home}/{action=Index}/{id?}'.
SignInDemo> dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
SignInDemo>       Executing action SignInDemo.Controllers.HomeController.Index (SignInDemo)
SignInDemo> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
SignInDemo>       Executing action method SignInDemo.Controllers.HomeController.Index (SignInDemo) with arguments ((null)) - ModelState is Valid
SignInDemo> dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
SignInDemo>       Executed action method SignInDemo.Controllers.HomeController.Index (SignInDemo), returned result Microsoft.AspNetCore.Mvc.ContentResult.
SignInDemo> info: Microsoft.AspNetCore.Mvc.Internal.ContentResultExecutor[1]
SignInDemo>       Executing ContentResult with HTTP Response ContentType of text/plain; charset=utf-8
SignInDemo> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
SignInDemo>       Executed action SignInDemo.Controllers.HomeController.Index (SignInDemo) in 9.7245ms
SignInDemo> dbug: Microsoft.AspNetCore.Server.Kestrel[9]
SignInDemo>       Connection id "0HL62A0MG0A1D" completed keep alive response.
SignInDemo> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
SignInDemo>       Request finished in 31.4121ms 200 text/plain; charset=utf-8
```

**Comment by davidfowl** [comment] 2017-07-03 20:26
I just ran it and it worked. Here's what I did:
- Cloned the repo
- Ran `dotnet restore`
- Ran `dotnet run`
- Navigated to the root saw "false"
- Changed the url to {basepath}/login
- Saw "true"

**Comment by jamesgurung** [comment] 2017-07-03 20:35
Ok, just tried it. That works for me too!

It **doesn't** work on IIS Express. I've been using the following steps:

* Opened the project in VS 15.3 Preview 3
* Pressed the "IIS Express" play button (F5)
* Navigated to the root saw "False"
* Changed the url to {basepath}/login
* Saw "False"

**Comment by davidfowl** [comment] 2017-07-03 21:40
I can reproduce this too and the behavior is bizarre and hard to explain. You need to add this to make it work:

```C#
services.AddAuthentication(o =>
{
    o.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
});
```

Disclaimer: Authz is complicated... This is by no means and excuse but this is how things current are. 

When you don't specify a default authentication scheme, it will use the only registered scheme (in this case cookies) by default. Now the problem is that when you add IIS into the picture, it adds another scheme, and now you don't have a single unambiguous default so the middleware does nothing. By explicitly setting the `DefaultAuthenticateScheme` in AddAuthentication, you're telling it to use that scheme to get the principal on incoming requests. 

/cc @blowdart @Tratcher @HaoK

**Comment by blowdart** [comment] 2017-07-03 21:44
Yup, this is a compat limitation. .NET has always been like this, if you don't specify a scheme when creating a principal, then the identity is unauthenticated. Nothing asp.net can do about it unfortunately.

**Comment by davidfowl** [comment] 2017-07-03 21:58
It's not that @blowdart, it's because the auth system
no longer has a single scheme registered. It has nothing to do with the claims identity being created.

**Comment by jamesgurung** [comment] 2017-07-03 22:10
Thanks @davidfowl, got it working :+1:

Is it worth adding a debug warning when the Auth middleware doesn't have a default authentication scheme set?

**Comment by blowdart** [comment] 2017-07-03 22:16
This is strange, [the workshop](https://github.com/blowdart/AspNetAuthorizationWorkshop/tree/core2) doesn't set a default authentication scheme anywhere and works just fine, and IIS integration is loaded there too. So it's _not_ adding IIS into the picture that is the problem here.

**Comment by davidfowl** [comment] 2017-07-03 22:37
Ok well if you run the repro, you'll see into works without IIS and when you add IIS it doesn't work. I'm like 96% sure it's what I said but I'll wait for another dev to chime in and confirm.

**Comment by HaoK** [comment] 2017-07-03 23:22
Yes what @davidfowl fowler said is correct, DefaultAuthenticateScheme falls back to a single auth handler by default.  But IISExpress adds its own auth handler, so it becomes null...

Somewhat related, I opened a PR https://github.com/aspnet/HttpAbstractions/pull/885 today adding a new AutomaticAuthentication option explicitly for the UseAuthentication middleware so we have something that explicitly targets the middleware scenario. (It still fallsback to DefaultAuthenticateScheme , but at least it has a first class option now)

**Comment by HaoK** [comment] 2017-07-03 23:24
Its fine for the AuthenticationMiddleware to not attempt to set the user when DefaultAuthenticateScheme is not set, since the middleware is also responsible handling remote authentication requests..  This is the often the case for apps that only use JwtBearer auth.

**Comment by PinpointTownes** [comment] 2017-07-03 23:54
Speaking of oddities caused by the IIS integration, here's another one: https://github.com/aspnet/IISIntegration/issues/390 :sweat_smile:

**Comment by blowdart** [comment] 2017-07-05 16:54
@HaoK if that were the case the auth workshop wouldn't work, or am I behind in versions where that happens?

**Comment by HaoK** [comment] 2017-07-05 16:57
You are probably behind versions yes...

**Comment by HaoK** [comment] 2017-07-05 16:58
Hosts weren't done in preview1, so the hosts only started adding their own handlers in preview2, so your workshops are probably broken then.

**Comment by PinpointTownes** [comment] 2017-07-05 16:59
It's also worth noting that the IIS integration stuff uses some voodoo sorcery and only registers the "native" handler if a non-anonymous authentication type was configured in the IIS settings (which is likely not the case if you use IIS Express).

**Comment by blowdart** [comment] 2017-07-05 18:22
Ah, yea, it's preview 1.

Ok that seriously sucks.

**Comment by Tratcher** [comment] 2017-07-05 19:33
See https://github.com/aspnet/IISIntegration/pull/377 that cleans this up post preview2.

**Comment by Eilon** [comment] 2017-07-05 23:31
Gonna play naive here... have we determined that there's still an issue in 2.0.0 RTM? If so, what?

**Comment by Tratcher** [comment] 2017-07-06 03:45
This issue is mitigated for RTM, IISIntegration won't register a second middleware to muddle things up unless you actually enable Windows Auth in IIS. @davidfowl still doesn't like the defaults design, but that's a longer discussion.

**Comment by Eilon** [comment] 2017-07-06 18:44
Ok. Is there anything at all left in MVC to do? If so, what (or is that the longer discussion)? Or is all future work in other places (e.g. IISIntegration)?

**Comment by davidfowl** [comment] 2017-07-06 23:38
We decided to make the default authentication scheme required.

**Comment by PinpointTownes** [comment] 2017-07-06 23:53
@davidfowl what about the other schemes? (signin, signout, forbidden, challenge?)

**Comment by davidfowl** [comment] 2017-07-07 00:00
I mean to say, by default without setting a DefaultScheme, nothing is assumed and will throw. We're going to add a new property called DefaultScheme that needs to be set if you use any of the overloads that don't pass a scheme in directly.

**Comment by HaoK** [comment] 2017-07-07 00:06
You guys can move this discussion to the PR :) https://github.com/aspnet/HttpAbstractions/pull/891

**Comment by PinpointTownes** [comment] 2017-07-07 00:10
Woo, that's an extremely audacious plan! I like it, but please consider updating `AuthenticationService` to point to the appropriate documentation when the parameterless overloads are called when no authentication scheme is explicitly registered so folks know how to make the right decision :+1:

**Comment by HaoK** [comment] 2017-07-07 00:12
This isn't any different than today when there was more than one handler, and DefaultAuthenticateScheme wasn't set.

**Comment by PinpointTownes** [comment] 2017-07-07 00:15
Well, the logic is now way much simpler, and far more deterministic. The current bits use too much sorcery: is there a single handler register? Is the handler a signout handler? Is it a signout handler? Etc. etc.

**Comment by PinpointTownes** [comment] 2017-07-07 00:16
Oh and BTW, we can know reunify `IAuthenticationHandler` and `IAuthenticationSignInHandler`/`IAuthenticationSignOutHandler` and revert all the logging madness! Booowayyyy :man_dancing:

**Comment by HaoK** [comment] 2017-07-07 00:24
Doubt that's happening at this point, I like how things are currently where handlers only implement the interfaces they support, instead of throwing NotSupportedException on SignIn/SignOut everywhere.  Certainly need a real benefit other than internal logging code organization...

**Comment by PinpointTownes** [comment] 2017-07-07 00:31
> instead of throwing NotSupportedException on SignIn/SignOut everywhere. 

That's what happens when the handler doesn't implement `IAuthenticationSignIn/OutHandler`, except it's a very misleading `InvalidOperationException` that requires a cast: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationService.cs#L161

I can't see any avantage with having separated interfaces, now. Specially since it's not consistent with `ChallengeAsync`/`ForbidAsync`, that don't need separate interfaces.

**Comment by HaoK** [comment] 2017-07-07 02:52
Its consistent with IAuthenticationRequestHandler, all AuthenticationHandlers implement Authenticate/Challenge/Forbid.  We have one handler that implements SignIn, and two that implement SignOut.

**Comment by Tratcher** [comment] 2017-07-07 05:14
Closing this as there's no MVC work. Any further discussion can go to aspnet/HttpAbstractions#891 or aspnet/Security#1287

**Closed by Tratcher** 2017-07-07 05:14 UTC
