### ISSUE TITLE
FromBody valuetuple to have both stream and formal-binding 

### ISSUE THREAD

**Issue by fabiomaulo** [aspnet/Mvc#6227] opened 2017-05-03 11:31 UTC
Currently the `[FromBody]` can be used just one time and that is correct for various reasons.
In my scenario (WebHook callback) I have a "formal" model (the payload) and also the need to read the request-body as a stream to validate the hash.
What I'm thinking is something like this:
`[FromBody] (MyModel, byte[])`
`[FromBody] (MyModel, string)`
`[FromBody(Encoding = Encoding.UTF8)] (MyModel, string[])`

The implementation should bind the first value of the tuple as normal (current behavior). The second tuple value can be just of type byte[] or string and its value represents the "naked-body".

**Comment by frankabbruzzese** [comment] 2017-05-03 13:25
Not clear what your intentions are. However, if the request body contains various parts, since body is not organized as name-value pairs, the onlly way to recognize the various parts is writing a custom formatter. Otherwise you have to process everything as a sequence of bytes in the Controller itself or in an ActionFilter

**Comment by fabiomaulo** [comment] 2017-05-03 13:55
The case is the a receiver of a webhook.
The webhook (a POST to my app) has a payload (a model) and some headers.
One of the headers is the "Notification-Signature" that is basically an hash (HMACSHA256) calculated on the whole request-content plus some headers.

Inside my action I need the payload, which contains a JSON, with all needed information about the notification but, before trust the POST, I have to check (recalculate) the "Notification-Signature".

For sure I can implement a custom binder, a middleware, maybe an ActionFilter... the quick-dirty solution is avoid to specify any kind of binding, for the Request.Body, and manage everything from inside the action.

Would be useful to have an OOTB solution for something that is not so strange nowadays.

**Comment by fabiomaulo** [comment] 2017-05-03 17:47
I know... its a shame!! but, so far, it pay the bill
```		
		private (T, byte[]) FromRequestBody<T>() where T: class
		{
			if (Request?.Body == null)
			{
				return (null, null);
			}
			byte[] content;
			using (var contentStream = new MemoryStream())
			{
				Request.Body.CopyTo(contentStream);
				contentStream.Flush();
				contentStream.Seek(0, SeekOrigin.Begin);
				content = contentStream.ToArray();
			}
			var data = JsonConvert.DeserializeObject<T>(Encoding.UTF8.GetString(content));
			ModelState.Clear();
			TryValidateModel(data);
			return (data, content);
		}
```

**Comment by frankabbruzzese** [comment] 2017-05-03 20:07
If the pronlem is "validating the payload" I think the right place is a Mddleware that check for the specific headers, and when it recognize a request for valifation performs the hash verification (or any other kind of verification requested by the header). In case validation fails it should immediately return a client error result breaking the pipeline.

Controllers don't need to know anything about body validation, they must just process the payload

**Comment by fabiomaulo** [comment] 2017-05-03 21:04
Perhaps.... even if the "normal" usage of validation is inside the action :
```
if(!ModelState.IsValid)
{
return BadRequest(ModelState);
}
```
In my case, even if it is a webhook, I have to validate the payload, the headers managed by a specific action and the signature.
For sure I can distribute the validation in various places but I prefer to have an all-in-one without use something that sound automagical to my colleagues,

Grazie per la collaborazione Franco.

**Comment by frankabbruzzese** [comment] 2017-05-03 21:45
It is something similar to authentication, or to Antiforgery token. You should validate it either in a controller filter or in a Middleware. The easiest place where to process the Raw Request is a Middleware but you may process it also in an Action Filters or in the Action Method itself. 


I don't like the validation code be in the action method...Consider you might need the same validation logic in other controllers. So you should factor out the whole validation routine. 
If you dont like also Action Filters consider using a generic controller that implements this protocol, other controllers might inherit from.

I suggest the following path:
 1, Your action method uses [FromBody] and if you don want to use ActionFilters of Miffleware, has also parameters for your headers (using FromHeader).
2. Then call a protected method that performs the validation (possibly inherited from a base controller), and just pass it all needed headers. The validation routine may take the body from he Controller and use both raw body and header to perform validation. In case of error the routine add error nessages to the ModelState.
3. After the call to the validation routine, the action method either uses the model contained in the [FromBody] parameter, or returns the error.

**Comment by fabiomaulo** [comment] 2017-05-04 03:31
Franco, have you tried to read the Request.Body before or after Action binding [FromBody] in the current release of aspnetcore mvc ?
I'm asking because the reason of my request is not about where put the code (13 code lines) I have already working.
BTW, this is the signature of the action
```
		[HttpPost()]
		public async Task<IActionResult> DayChanged(SellerDayStatsChanged data
			, [FromHeader(Name = "Notification-Topic")] string topic
			, [FromHeader(Name = "Notification-Type")] string notificationType
			, [FromHeader(Name = "Notification-Hook-ID")] string hookIdtopic
			, [FromHeader(Name = "Notification-URI")] string acknowledgedUri
			, [FromHeader(Name = "Notification-Signature")] string signature
			)
		{
			(SellerDayStatsChanged data, byte[] content) fromRequestBody = InfoFromRequest<SellerDayStatsChanged>();
			if(fromRequestBody.data != null)
			{
				data = fromRequestBody.data;
			}
```
This Action, with `[FromBody]` in the signature, works perfectly in tests and even in "integration" tests using the `TestServer`; but when you try to use it in production it fails because you can't read the `Request.Body` multiple times and you can't `Seek` it. To make it work you need a very ugly, and IMO dangerous, trick using a middleware to swap the `Request.Body` stream with a `MemoryStream`... or something like that.
If there is no intention to implement this feature OOTB there is no problem, as proposal is just a proposal.

Nuovamente grazie per la collaborazione Franco.

**Comment by frankabbruzzese** [comment] 2017-05-04 17:07
@fabiomaulo ,
If the problem is Request.Body being not stored, but read directly from the request stream so it can be read just once, then allowing several parameters match the same content would not solve the problem. Since a similar feature would nead the request body be read several times, in any case, which in turns implies the request body must be stored somehow.

So I see just 3 possible solutions:

1. Writing a new formatter for the content type used by the WebHook. That is a formatter, that is able to do the whole job by processing both headers and body when this content type is encountered (May you recognize your WebHook pattern from its content-type? If yes a new formatter for that content type may be written ).
2. Writing a middleware that enables a storing logic for the body when some conditions are met. This way one may read Request body several time. Stream rewind may be enabled by calling **Request.EnableRewind()**, BEFORE its first read. Thus you have to implement a middleware that performs this call when your WebHook is recognized somehow. **You cant call it all the times**, otherwise you might experience performance problems when you send big files to the servers.(images, videos, etc.) 
3. Wait the WebHooks library is implemented for Asp.Net core too (see [here](https://github.com/aspnet/WebHooks/issues/5)).

**Comment by fabiomaulo** [comment] 2017-05-04 18:21
Franco,
>If the problem is Request.Body being not stored, but read directly from the request stream so it can be read just once, then allowing several parameters match the same content would not solve the problem.

**As you can see in my proposal, and in my solution, because the parameter is just one (the ValueTuple) there is no need to read the `Request.Body` more than one.** In that 13 code-lines there is no magic.

Grazie molte per la collaborazione Franco.
P.S. I hope you will need and you will use that library to produce webhooks.

**Comment by Eilon** [comment] 2017-06-07 21:43
Closing because there are no plans to implement this.

**Closed by Eilon** 2017-06-07 21:43 UTC
