### ISSUE TITLE
Integration tests always use development environment

### ISSUE THREAD

**Issue by henrik-olsson-valtech** [aspnet/Mvc#7976] opened 2018-06-27 08:38 UTC
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
https://github.com/henrik-olsson-valtech/EnvironmentRepro

#### Description of the problem:
ASP.NET Core 2.1 web API reads environment from environment variable ASPNETCORE_ENVIRONMENT with "normal" Kestrel hosting but not when hosted in a test. Was this changed with https://github.com/aspnet/Mvc/commit/ced377d89b2208cddce3a3157925a1d4fb0c0113? It doesn't work for us, becuase we're running integration tests as part of our build in an integration test environment.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.0

**Comment by khellang** [comment] 2018-06-27 12:35
I doubt anyone thought people would use environment variables in their test setup 😄 

You could work around it pretty easily though:

```diff
diff --git a/EnvironmentRepro.IntegrationTests/WebApplicationFactory.cs b/EnvironmentRepro.IntegrationTests/WebApplicationFactory.cs
new file mode 100644
index 0000000..21790db
+++ b/EnvironmentRepro.IntegrationTests/WebApplicationFactory.cs
@@ -0,0 +1,20 @@
+using System;
+using Microsoft.AspNetCore.Hosting;
+
+namespace EnvironmentRepro.IntegrationTests
+{
+    public class WebApplicationFactory<TEntryPoint> : Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory<TEntryPoint>
+        where TEntryPoint : class
+    {
+        protected override void ConfigureWebHost(IWebHostBuilder builder)
+        {
+            base.ConfigureWebHost(builder);
+
+            var environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
+
+            if (!string.IsNullOrEmpty(environment))
+            {
+                builder.UseEnvironment(environment);
+            }
+        }
+    }
+}
```

**Comment by henrik-olsson-valtech** [comment] 2018-06-28 07:17
Yes, I already had a workaround similar to that one (although yours is better). But I spent several hours to understand the problem and implement a workaround.

> I doubt anyone thought people would use environment variables in their test setup

What do you mean? We have the following:
1. We want to run integration tests in multiple environments (development and test/staging).
2. We have different configurations in different environments, so the web API must load appsettings.Development.json or appsettings.Staging.json etc.
I thought that the ASPNETCORE_ENVIRONMENT environment variable is the way to tell ASP.NET Core which environment it is running in. Do you have an alternative solution?

**Comment by khellang** [comment] 2018-06-28 08:06
> What do you mean?

I'm just guessing that this is a scenario that didn't come up when the bug fix/feature was put in place. TBH, it's the first time I've heard of this.

> Do you have an alternative solution?

My alternative solution would be to make your tests environment-agnostic (unless you have environment-specific code in your app). I.e. start out with a clean environment each time you run the tests. It's hard to say whether this would work for you without knowing more details about the environment.

**Comment by henrik-olsson-valtech** [comment] 2018-06-28 11:04
We don't have environment specific code, but the environments contain databases that have different connection strings.

**Comment by mkArtakMSFT** [comment] 2018-07-09 17:52
@javiercn, would like to get your opinion about this? I've requested your review on the associated PR also.

**Comment by javiercn** [comment] 2018-07-09 18:35
@henrik-olsson-valtech This is by design, so that apps in functional tests work so long as they work when you F5 or `dotnet run` the app. We expect people to write tests this way first and then `productionize` their tests to run on the CI, etc. Ideally with an environment specifically designed for running integration tests.

**Comment by javiercn** [comment] 2018-07-09 21:21
I might not have been super clear.
What @khellang is proposing is the expected way to do this.
If you need to run the tests against multiple environments with multiple setups the recommendation is that you override ConfigureWebHostBuilder and add the appropiate setups in there.

I'm closing the issue as this is by design and there's no further action to take in here.

**Closed by javiercn** 2018-07-09 21:21 UTC
Labels: investigate
