### ISSUE TITLE
Performance problems?Is there an updated way to achieve it?

### ISSUE THREAD

**Issue by qibucloud** [aspnet/Mvc#6049] opened 2017-03-30 05:47 UTC
Mainly want to replace ViewComponent more than one method call data

```html
<ul>
    @foreach (var item in await Contents.GetListAsync(Data, 1, "products", 10))
    {
        <li><a href="/@(item.RoutingUrl).html" title="@(item.ContentName)">@(item.ContentName)<span></span></a></li>
    }
</ul>
<ul>
    @foreach (var item in await Contents.GetListAsync(Data, 1, "news", 10))
    {
        <li><a href="/@(item.RoutingUrl).html" title="@(item.ContentName)">@(item.ContentName)<span></span></a></li>
    }
</ul>
```

**Comment by Eilon** [comment] 2017-06-07 21:57
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2017-06-07 21:57 UTC
