### ISSUE TITLE
All attribute validations triggered with string property

### ISSUE THREAD

**Issue by kvriel** [aspnet/Mvc#5115] opened 2016-08-04 22:57 UTC
Using a string next to other types in a model, will always trigger all attribute validations on the string property, by submitting the form.

```
public class Model
{
	/// <summary>
	/// Verification day
	/// </summary>
	[Required]
	[DataType(DataType.Text)]        
	public int Day { get; set; }

	/// <summary>
	/// Verification month
	/// </summary>
	[Required]
	[DataType(DataType.Text)]
	public string Month { get; set; }
}
```
In the view there are two forms defined with both one of the properties.
```
<style>
.input-validation-error {
    border: 1px solid #ff0000;
}
</style>

<div class="row">
	<div class="col-md-6">
		<div class="panel one-panel">
			<form asp-controller="Home" asp-action="Verification">

				<input asp-for="Day" class="form-control verification-day dateinput" placeholder="DD" autocomplete="off" maxlength="2" pattern="\d*"/>
				
				<input type="submit" value="One" class="btn btn-success" />
			</form>
		</div>
	</div>
	<div class="col-md-6">
		<div class="panel two-panel">
			<form asp-controller="Home" asp-action="Verification">
				
				<input asp-for="Month" class="form-control verification-day dateinput" placeholder="DD" autocomplete="off" maxlength="2" pattern="\d*"/>
				
				<input type="submit" value="Two" class="btn btn-success" />
			</form>
		</div>
	</div>
</div>
```
By submitting the from in two-panel, the validation error will only be applied to the Month input. By submitting the form in one-pannel, the validation error will not only be applied to the Day input, but also to the Month input.

If you change the model to only work with interger properties this senario will work fine. Changing it all to sting properties, all input field will get a validation error.

**Comment by Eilon** [comment] 2016-08-05 17:23
@dougbu ideas?

**Comment by dougbu** [comment] 2016-08-05 17:33
@kvriel what are the exact validation errors that show up? MVC only deals with in the scenario you've described is `[Required]` on the two properties. If you're seeing issues related to the `maxlength` or `pattern` attributes, this is about your browser.

The other possibility is the `verification-day` or `dateinput` classes are causing odd behaviour.

A small repro project e.g. in a GitHub repo would help in any case. I'd like to see exactly what's happening when.

**Comment by Eilon** [comment] 2016-08-05 17:50
@dougbu I think the repro has enough in it, no?

**Comment by dougbu** [comment] 2016-08-05 17:51
Just hoping to save a small amount of time if @kvriel already has a repro project. But you're right, it's a very small amount of time :smiley_cat:

**Comment by dougbu** [comment] 2016-08-07 03:05
The repro covers different server-side model binding and validation errors. `[Required]` has no effect on non-`Nullable` value types but the `SimpleTypeModelBinder` detects invalid conversions, rejecting `string.Empty` when submitted for an `int` property. `[Required]` works later, as part of the validation phase, and the (`string`) `Month` property in Scenario 1 is _always_ invalid since you're binding the entire `ViewModel1` class.

For more consistent behaviour between value and reference types, suggest enabling client-side validation e.g. the following in both `ScenarioX.cshtml` files:
``` html
@section scripts
{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}
```

Probably also best to remove `[Required]` where .NET ignores it -- on all `int` properties in this case.

**Comment by Eilon** [comment] 2016-08-08 02:45
@dougbu so is this an app bug? Or an MVC bug? Or something else?

**Comment by dougbu** [comment] 2016-08-08 03:50
It's an app bug though one we see frequently.

Details: MVC is working as designed. So is .NET but `[Required]` semantics confuse everyone.

**Comment by Eilon** [comment] 2016-08-08 04:18
@dougbu is there a suggestion on something we can improve here? Or is it ultimately a design limitation of the system?

**Comment by dougbu** [comment] 2016-08-08 04:37
This is ultimately a design limitation of the system.

Haven't looked at our model binding or validation docs lately but perhaps we could dedicate a section to `[Required]` and when it is enforced?

**Comment by Eilon** [comment] 2016-08-08 17:19
@dougbu feel free to file a doc bug on that. I'm closing this issue for now.

**Closed by Eilon** 2016-08-08 17:19 UTC
