### ISSUE TITLE
Duplicate assemblies cause AddMvc to throw an exception

### ISSUE THREAD

**Issue by keflem** [aspnet/Mvc#5289] opened 2016-09-16 23:37 UTC
The constructor to CandidateResolver (lines 76-77) does not take into account case sensitivity and thus causes an exception to be thrown when the same assembly is referenced with just a different case.

To repo this bug, create two projects that will be dependencies of a ASP.Net Core projects, one that has a project.json referencing a dependency with lowercase and the other project referencing the same dependency with different case.  It will cause AddMvc to fail.

Example 1 project.json:
"Microsoft.Net.Http":  "2.2.22"

Example 2 project.json:
"microsoft.net.http":  "2.2.22"

In the ASP.Net Core project, calling services.AddMvc() in Startup.ConfigureServices will cause a Key already added exception to be thrown.

**Comment by javiercn** [comment] 2016-09-17 02:18
@rynowak This is dependencycontext giving us bad data @pakrym

**Comment by Eilon** [comment] 2016-10-24 21:00
@jbagga can you see if this repros with the latest bits?

**Comment by jbagga** [comment] 2016-10-31 23:58
@Eilon @javiercn @rynowak 
Package restore fails when trying to add the same package reference in two different projects' project.json files with different cases, when they are dependencies of the same project (as explained above). For the example I used, it complains about a dependency of the referenced package to be already added.

For package `Microsoft.IdentityModel.Protocols` reference:
`An item with the same key has already been added. Key: Microsoft.CSharp Unspecified`

**Comment by Eilon** [comment] 2016-11-01 02:45
@jbagga thanks.

@keflem do you have any more info about this? If you can upload a repro project to GitHub we can take another look.

**Comment by jbagga** [comment] 2016-11-07 19:17
@Eilon Modified exception message for duplicate runtime library names in CandidateResolver.

**Comment by jbagga** [comment] 2016-11-07 19:54
Marking as closed because we cannot reproduce this issue, but we improved the exception message for better diagnostics in case it happens again

**Closed by jbagga** 2016-11-07 19:54 UTC
Labels: 3 - Done, bug
