### ISSUE TITLE
Performance JsonResult

### ISSUE THREAD

**Issue by AlesDo** [aspnet/Mvc#5364] opened 2016-10-04 22:56 UTC
Hello,

I have noticed a strange issue when doing some preliminary performance tests on an application I'm developing. I noticed that when returning objects as JsonResult the requests take quite a long time to complete on the client side even if i just return an Object directly without any processing. I have looked at the source for the JsonResultExecutor and i see you write the serialization directly to the body stream. Does this cause the message to be sent in parts and this causes the additional delay?
To test i have created my own StringJsonResult object where i instead first serialize the object to a string and the write the output by using the WriteAsync method on the response at once. This significantly reduces the time of the request to about 150ms compared to 600ms.
Can you give some insight on what might be going on here or if I am not using something correctly.
I have attached a sample solution that demonstrates this behavior.
[WebApiPerformance.zip](https://github.com/aspnet/Mvc/files/509675/WebApiPerformance.zip)

**Comment by danroth27** [comment] 2016-10-05 16:41
@ajaybhargavb please sync with @rynowak

**Comment by ajaybhargavb** [comment] 2016-10-07 23:45
The difference here is because of logging. https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/Internal/JsonResultExecutor.cs#L120

Perf data: (loadtest -k -n 10000 -c 32 --rps 1000)
Mvc JsonResult implementation (does logging)
![image](https://cloud.githubusercontent.com/assets/1579269/19208178/e1ab86ee-8cab-11e6-8d44-df43aee1a61e.png)

Custom JsonResult implementation (no logging)
![image](https://cloud.githubusercontent.com/assets/1579269/19208216/6ef9094a-8cac-11e6-8abe-f29ec9aa5246.png)

**Comment by ajaybhargavb** [comment] 2016-10-07 23:48
@AlesDo, try doing your performance tests with logging disabled and see if the issue still persists.

**Comment by AlesDo** [comment] 2016-10-08 18:04
I have tried again with the setting LogLevel.None and I still see the issue. Is this the correct way to disable the logging? I have tried also to comment out the logger configuration and the result is the same. The requests with JsonResult take almost twice the time see attached image. I have now also added another custom result where I write to the stream similar to the JsonResultExecutor and the time is only slightly bigger compared to the string output. I have attached again my sample project with the changes. In the sample i have increased the size of the object so the difference in time is more visible.
![results](https://cloud.githubusercontent.com/assets/13190278/19215013/561ec2e0-8d9a-11e6-9f31-e996d1f58cdd.PNG)
[WebApiPerformance.zip](https://github.com/aspnet/Mvc/files/517852/WebApiPerformance.zip)

**Comment by ajaybhargavb** [comment] 2016-10-08 20:04
@AlesDo, try commenting out the below two lines in your `Startup.cs`.
```c#
loggerFactory.AddConsole(LogLevel.None);
loggerFactory.AddDebug(LogLevel.None);
```

**Comment by AlesDo** [comment] 2016-10-08 20:19
I did that and I still get the same behavior. If you run my sample you don't see the difference?

![results02](https://cloud.githubusercontent.com/assets/13190278/19215682/5bd4a69c-8dad-11e6-8006-432610847cc9.PNG)

**Comment by davidfowl** [comment] 2016-10-08 22:00
What sort of logging is wired up? Just delete the 2 loggerFactory statements all up and see if it still happens. I'd be surprised if loggging was that big of an issue. Are you testing perf testing in debug or release?

**Comment by AlesDo** [comment] 2016-10-08 23:26
For the logging I use the default that is built in. The application i'm using now is just a default ASP.NET core application as it is created by VisualStudio with WebApi enabled. I first noticed this in the application I develop but then went back to a basic application to verify that it was not my code that was affecting this.
I did delete the logging statements and they do not change my results. All the tests were run with debug builds. I tried now also with release and the performance is better. The response times are smaller in some cases almost half of the times in debug which is very good but I still see the same pattern that the JsonResult response in almost all of the cases takes around double the time of my custom JsonResults. The difference is not a big issue when the objects returned are small but once they grow bigger it becomes a significant difference.
Here are sample results:
Release running inside IISExpress (same settings than previous post):
![results03](https://cloud.githubusercontent.com/assets/13190278/19216475/e8de7230-8dc5-11e6-8dab-273622c08c89.PNG)
Release running standalone (same settings than previous post):
![results04](https://cloud.githubusercontent.com/assets/13190278/19216476/f4004080-8dc5-11e6-8712-eb9f8c176f29.PNG)
Release running standalone with 10 times bigger object as previously:
![results05](https://cloud.githubusercontent.com/assets/13190278/19216483/19e7351a-8dc6-11e6-8e34-8ac15b4913bd.PNG)
Release running standalone with 100 times bigger object as previously: 
![results06](https://cloud.githubusercontent.com/assets/13190278/19216487/2f486f78-8dc6-11e6-9a78-60466143b172.PNG)

**Comment by davidfowl** [comment] 2016-10-09 00:33
It's probably because JSON.NET is synchronous and Kestrel + libuv doesn't do synchronous writes. There's a response buffering threshold where you can write up to 64K (not configurable right now) and after that threads will start blocking after you hit that limit. Do you know how big your objects are? (size in bytes after you convert to the JSON string)

**Comment by AlesDo** [comment] 2016-10-09 13:31
The size of the objects I used in the tests from the images were 390039 bytes except for the last two where I mention I increased the size even more. This means they were bigger than 64K in all cases.
To me this does not explain the difference in times for the different result objects. I assume this response buffering threshold is not specific just to the JsonResult and applies also to my custom result objects. So it still looks like the JsonResult is doing also something else than just writing the output.
If I make the object smaller than 64K the responses are very fast (1ms) and the difference is not visible.

**Comment by halter73** [comment] 2016-10-10 21:05
@davidfowl is partly right. The cause of the performance difference between JsonResult and StringJsonResult for objects over 64KB is the minimal amount of buffering in JsonResult. For responses less than 64KB, Kestrel basically does all the buffering for you. But for responses larger than that, you need to think about buffering yourself. There's a risk if you buffer too much, your web application will run into memory pressure, but it generally will reduce response times given small load.

@davidfowl also mentions that JSON.NET does synchronous writes. While that is an issue for when there are a lot of parallel requests, your test does one request at a time so it doesn't really make a difference here.

The buffering is best illustrated by this modification to your StringJsonResult class:

```c#
using System;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebApiPerformance.Controllers
{
    internal class StringJsonResult : ActionResult
   {
      private JObject dataObject;

      public StringJsonResult(JObject dataObject)
      {
         this.dataObject = dataObject;
      }

      public override async Task ExecuteResultAsync(ActionContext context)
      {
         HttpResponse response = context.HttpContext.Response;
         string outputString = JsonConvert.SerializeObject(dataObject);
         response.StatusCode = StatusCodes.Status200OK;
         response.ContentType = "application/json";

         const int maxWriteSize = 1024;

         var outputBytes = new byte[maxWriteSize];
         for (var i = 0; i < outputString.Length; i += maxWriteSize)
         {
            var count = Math.Min(maxWriteSize, outputString.Length - i);
            Encoding.ASCII.GetBytes(outputString, i, count, outputBytes, 0);
            await response.Body.WriteAsync(outputBytes, 0, count);
         }
      }
   }
}
```

If you take this and modify `maxWriteSize`, you'll see what a big difference it has on request duration. At a 1024 `maxWriteSize`, StringJsonResult performs about as poorly as JsonResult which makes sense since JsonResult uses [HttpResponseStreamWriter which has a default buffer size of 1024 bytes](https://github.com/aspnet/HttpAbstractions/blob/87cd79d6fc54bb4abf07c1e380cd7a9498a78612/src/Microsoft.AspNetCore.WebUtilities/HttpResponseStreamWriter.cs#L23).

![image](https://cloud.githubusercontent.com/assets/54385/19250958/cda4b68c-8ef1-11e6-8e3e-a22f6c54d67c.png)

At a 4096 `maxWriteSize`, StringJsonResult performs about as poorly as your StreamJsonResult which again make sense considering the following line in StreamJsonResult.ExecuteAsync `using (StreamWriter streamWriter = new StreamWriter(response.Body, Encoding.UTF8, 4096, true))`.

![image](https://cloud.githubusercontent.com/assets/54385/19250910/961d9012-8ef1-11e6-8a31-62ab5574bc35.png)

And of course at a 1024 * 1024 `maxSize`, StringJsonResult performs about as well as your original version.

![image](https://cloud.githubusercontent.com/assets/54385/19251009/179ed8f8-8ef2-11e6-8d0d-6b75fc5133af.png)

Kestrel's 64 KB [MaxResponseBufferSize will be configurable starting in 1.1.0](https://github.com/aspnet/KestrelHttpServer/blob/3177ba0aaeb775e8347ebdc103b12c37f5e6cf44/src/Microsoft.AspNetCore.Server.Kestrel/KestrelServerLimits.cs#L31). Be careful increasing this though, because while it will definitely reduce response times in tests like these, it can lead to higher memory usage per connection.

**Comment by AlesDo** [comment] 2016-10-10 21:25
Thank you for your in depth explanation. Now I understand what is going on.
I think it is good that this will be configurable so it can be fine tuned if needed.

**Comment by rynowak** [comment] 2016-10-14 21:42
@AlesDo - I also want to mention that if you're working with JSON responses on the order of 64+kb, be very careful about implementing your own buffering as a string > 80kb will go to the large object heap. 

As @halter73 mentioned, we're making some improvements in Kestrel to make scenarios like this better, we'll also be looking at improvements from MVC, which is why we've left this issue open for now.

**Comment by halter73** [comment] 2016-10-14 22:05
@rynowak do you want to leave *this* issue open or the new one I made in HttpAbstractions? This issue is still closed...

**Comment by rynowak** [comment] 2016-10-14 23:17
Both

**Comment by Eilon** [comment] 2017-07-05 21:43
We've updated the buffer sizes for these scenarios that should help the performance of this issue, so I'm closing this.

**Closed by Eilon** 2017-07-05 21:43 UTC
Labels: investigate, Perf
