### ISSUE TITLE
Controller.Json First row only then getting data from model with self-reference

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/Mvc#5393] opened 2016-10-10 21:41 UTC
Copying from https://github.com/aspnet/EntityFramework/issues/6723, reported by @dvdobrovolskiy

I have 2 pretty similar models 
Company and Category

Category has self-reference eg 
public int CategoryId { get; set; }
public int? ParentCategoryId { get; set; }
public Category ParentCategory { get; set; }

So then I get data from Company  (by _context.Companies;) and send it to client via JsonResult I got all row in Json as usual buy then I try to do same with Category I get first row only.

Models
```
public class Category
    {
        [Key]
        [ScaffoldColumn(false)]
        public int CategoryId { get; set; }
        [Display(Name = "Название")]
        public string Title { get; set; }
        public int? ParentCategoryId { get; set; }
        public Category ParentCategory { get; set; }
    }

public class Company
    {
        [Key]
        [ScaffoldColumn(false)]
        public int CompanyId { get; set; }
        public string Title { get; set; }
        public string MainPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string TertiaryPhone { get; set; }
    }
```

Code
```
        public JsonResult Read2([DataSourceRequest] DataSourceRequest request)
        {
            var result = _context.Companies;

            return Json(result);
        }
 ```
Returns 
 ```
[{"CompanyId":1,"Title":"Comany1","MainPhone":"Comany1","SecondaryPhone":"Comany1","TertiaryPhone":"Comany1"},{"CompanyId":2,"Title":"Comany2","MainPhone":"Comany2","SecondaryPhone":"Comany2","TertiaryPhone":"Comany2"}]
 ```

but same 
 ```
        public JsonResult Read2([DataSourceRequest] DataSourceRequest request)
        {
            var result = _context.Categories;

            return Json(result);
        }
 ```
returns
[{"CategoryId":3,"Title":"First","ParentCategoryId":null}]

But I have 3 row in Category table.

I am totally unsure that is going wrong and where is a problem. In debug I see jsonresult with 3 objects before it send to client. 

here is data
https://1drv.ms/i/s!AvdtTGXIWO4bg-4rElK7y75gOSox3A

have to admit removing
public Category ParentCategory { get; set; }
from model gives me 3 records now

[{"CategoryId":3,"Title":"First","ParentCategoryId":null},{"CategoryId":4,"Title":"Second","ParentCategoryId":null},{"CategoryId":5,"Title":"Third","ParentCategoryId":null}]

**Comment by rowanmiller** [comment] 2016-10-10 21:41
Moving this one to MVC since the data is correctly returned by EF and the serialization is handled within Controller.Json

**Comment by divega** [comment] 2016-10-10 23:04
Possibly related to https://github.com/aspnet/IISIntegration/issues/39.

**Comment by jbagga** [comment] 2016-10-19 00:46
@dvdobrovolskiy Are you using EF or Kendo UI (since you have DataSourceRequest in your params) for scaffolding? I am unable to repro your issue using EF. 

Also my result includes the ParentCategory in the returned value (looks like yours does not). 

Using your class definitions and code to read from the database, I get:
[{"categoryId":3,"title":"First","parentCategoryId":null,"parentCategory":null},{"categoryId":4,"title":"Second","parentCategoryId":null,"parentCategory":null},{"categoryId":5,"title":"Third","parentCategoryId":null,"parentCategory":null}]

Is it possible that you added ParentCategory to the class after applying EF migrations? In that case you will need to update the database.

**Comment by dvdobrovolskiy** [comment] 2016-10-20 18:22
EF
I do not use Kendo data access

I user Kendo controls in view

**Comment by jbagga** [comment] 2016-10-20 23:59
@dvdobrovolskiy Are you able to share your project with me through github or any other method? I'd like to take a look at that as I am unable to reproduce the issue in my development environment.

**Comment by dvdobrovolskiy** [comment] 2016-10-21 00:04
I think I can make test project for you with such a behaviour 

give me day or two I am out of office now

**Comment by jbagga** [comment] 2016-10-26 21:48
Closing the issue because it cannot be reproduced with the information provided

**Closed by jbagga** 2016-10-26 21:48 UTC
Labels: 2 - Working, investigate

**Comment by pranavkm** [comment] 2016-10-26 22:32
@dvdobrovolskiy feel free to reopen this issue once you have a repro app for us to verify this.
