### ISSUE TITLE
Why LocalizedHtmlString doesn't override ToString()?

### ISSUE THREAD

**Issue by Remleo** [aspnet/Mvc#6938] opened 2017-10-11 09:14 UTC
This sample:
```html
<img tag-helper-string-attribute="@Ls["localized string"]"/>
```
rendered as:
```html
<img alt="Microsoft.AspNetCore.Mvc.Localization.LocalizedHtmlString"/>
```

Why LocalizedHtmlString doesn't override ToString() like LocalizedString for example?

Overriding method ToString() would solve this problem:
```cs
    public override string ToString()
    {
      return Value;
    }
```

The similar problem:
https://stackoverflow.com/questions/39792066/net-core-localization-view-iviewlocalizer-inside-linq-expression/39796425

**Comment by Eilon** [comment] 2017-10-11 18:58
This certainly sounds interesting...

@ryanbrandenburg / @dougbu / @DamianEdwards - thoughts on this? Any reason not to do this?

**Comment by dougbu** [comment] 2017-10-11 19:52
This sounds like a dupe of aspnet/Razor#1679. Put another way, `LocalizedHtmlString` doesn't override `ToString()` because the result /should/ vary depending on the HTML encoder used to render it.

**Comment by Eilon** [comment] 2017-10-11 20:39
Ah, so we need an extra parameter, which ToString() doesn't have, so we don't do it?

**Comment by dougbu** [comment] 2017-10-11 23:31
@Eilon More that the helpers discussed in aspnet/Razor#1679 should avoid the need for `ToString(...)` implementations in every `IHtmlContent` implementation, regardless of the parameters.

**Comment by Remleo** [comment] 2017-10-12 08:49
@Eilon @dougbu 
For accurate data processing within the `LocalizedHtmlString` must be used `WriteTo()` of implemented interface `IHtmlContent`. Razor always uses `IHtmlContent` interface for writing and Razor decides encode or not raw value (`Write()` or `WriteAttributeValue()`)

My case:
```html
<foo-tag-helper some-attr="@Ls["<b>Html sample</b>"]" />
```
```cs
public class FooTagHelper : TagHelper
{
   public string SomeAttr { get; set; }
   ....
}
```
The `FooTagHelper` decide how to use value of `SomeAttr`: `output.Content.AppendHtml()` or `output.Content.Append()`. This decision must be made on TagHelper's side, not `LocalizedHtmlString`'s.

In which scenario you may need encoded value of `LocalizedHtmlString`? I think always is needed raw value.

In a worst case scenario if the raw value gets to Razor it will encode it by default.

**Comment by Remleo** [comment] 2017-10-12 08:59
This sample cause wrong render:
In view:
```html
<img alt="@Ls["a\"b"]"/>
```
rendered not valid html:
```html
<img alt="a"b"/>
```
Quotes not enconded.

The view compiled as:
```cs
WriteAttributeValue("", 393, Ls["a\"b"], 393, 17, false);
```

If change to
```html
<img alt="@Ls["a\"b"].Value"/>
```
redened correct:
```html
<img alt="a&quot;b"/>
```

Seem to Razor must encode quotes in `WriteAttributeValue()` in any case is it `IHtmlContent` or not.

**Comment by dougbu** [comment] 2017-10-12 22:50
We may be straying from `ToString()`.

The distinction between `LocalizedString` and `LocalizedHtmlString` is HTML encoding. ``LocalizedHtmlString` resources, including the resource name (which is used as the fallback value), are assumed to be HTML encoded. If `"a\"b"` were an argument, e.g. `@Ls["MyResource", "a\"b"]`, its value would be encoded.

**Comment by mkArtakMSFT** [comment] 2018-04-25 18:06
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by mkArtakMSFT** 2018-04-25 18:06 UTC

**Comment by hikalkan** [comment] 2018-05-01 08:17
I agree with @Remleo 

````xml
<img tag-helper-string-attribute="@Ls["localized string"]"/>
````

should work as it's very intiutive. This works (added `.Value`):

````xml
<img tag-helper-string-attribute="@Ls["localized string"].Value"/>
````

but it's easy to forget it for a developer.

I believe that `LocalizedHtmlString` should just override `ToString()` and return the `Value`.

**Comment by hikalkan** [comment] 2018-10-06 19:10
Hi @mkArtakMSFT can you check my response?
