### ISSUE TITLE
ViewComponent inside form and Model Biding

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8625] opened 2018-10-19 16:31 UTC
_From @ciacco85 on Friday, 19 October 2018 07:32:34_

Using a Model like
```c#
class A
{
B b {get; set;}
}
class B
{
string testString{get;set;}
}
```

and passing the b property to the viewcomponent

```html
<form aspAction='testMethod'>
<vc:myModel model="@(Model.b)"></vc:myModel>
</form>
```

when posting the form, the model property testString is alwayse null.
I've found a workaround, after a long experience with MVC, inside the viewcomponent, adding the "b" inside name

`<input asp-for="testString" name="b.testString" class="form-control" />`

but in this situation, a ViewComponent should know something about the class in wich the model is placed...two object coupled with no relationship is not that good
Should I use the editor template o change the approch?? ViewComponent are so powerful.
Thanks for your great work!!!

_Copied from original issue: aspnet/AspNetCore#3673_

**Comment by mkArtakMSFT** [comment] 2018-10-22 16:00
Thanks for contacting us, @ciacco85.
@dougbu, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment] 2018-10-22 16:38
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by dougbu** [comment] 2018-10-31 19:35
@ciacco85 thank-you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue, please add a new reply and re-open the issue.

In particular,
> to the viewcomponent
Please provide the view component source, both C# and the `.cshtml` file (if any)

>  the model property testString is alwayse null.

Where?
> Should I use the editor template o change the approch??

That's a good approach if I'm understanding the issue (guessing at the moment). View component invocations pass values but do not change the `TemplateInfo.HtmlFieldPrefix`. That's by design.

**Closed** 2018-10-31 19:35 UTC
Labels: question
