### ISSUE TITLE
Circular reference JsonResult causes response to hang indefinitely

### ISSUE THREAD

**Issue by corruptmem** [aspnet/Mvc#6115] opened 2017-04-11 15:13 UTC
### Code
```csharp
    public sealed class TestController : Controller
    {
        class TestCls
        {
            public string Foo { get; set; }

            public TestCls Bar { get; set; }
        }

        public ActionResult Test()
        {
            var test = new TestCls { Foo = "Baz"};
            test.Bar = test;

            return Json(new { test, qux = "Fred"});

        }
    }
```

### Expected behaviour
One of:
- 500 server error returned to client 
- JSON writer to reach a recursion limit, but continue to serialize the rest of the JSON object (e.g. ``` {"test": {"Foo": "Baz", "Bar": null}, "qux": "Fred"}```

### Actual behaviour (MVC 1.1.2, .NET Core 1.1.1)
Some JSON is serialized to the response: ```{"test":{"Foo":"Baz"}}```

The response then hangs indefinitely without further output or finishing the response. A JSON recursion error is produced in the console, followed by an error saying it can't write an error because the response has already started.

### Actual behaviour (MVC 1.0, .NET Core 1.0)

The response is written until it encounters the property with infinite recursion, at which point the response is terminated without serializing rest of object.

**Comment by Eilon** [comment] 2017-04-11 16:17
@kichalla can you investigate this difference in behavior?

cc @JamesNK in case you have any thoughts on this.

**Comment by kichalla** [comment] 2017-04-11 21:29
@corruptmem What kind of client are you using? is it Chrome browser?

**Comment by corruptmem** [comment] 2017-04-12 08:19
@kichalla Sorry yes, should have mentioned. The client is Chrome 57 on Windows 10.

Additionally, I was hosting the web application directly from Kestrel (running in a console window). I was not going through IIS or IIS Express. 

The original system I was using for the test is no longer available because the VS2015 installation I was using broke. However, I have just performed this test again on another computer with .NET Core / MVC 1.0.1 and VS2015.

In this test environment, using Kestrel:
- Chrome hangs after request
- Edge hangs after request
- Postman says "Could not get any response" (but Kestrel logs that it did send a response)
- Internet Explorer successfully saves a file named Test.json

Using IIS Express, all browsers return ```{"test":{"foo":"Baz"}}``` and terminate the request. However, Postman still says "Could not get any response". 

If I comment out the ```test.Bar = test;``` line, in all cases, including Postman, the response is ```{ "test": {    "foo": "Baz", "bar": null  }, "qux": "Fred" }``` and the request terminates successfully.

Later today, I will try the test on the original machine, this time with a fresh VS2017 / .NET Core 1.1 installation.

**Comment by corruptmem** [comment] 2017-04-12 10:47
With .NET Core 1.1, MVC 1.1.2, latest VS2017 freshly installed, using Kestrel/console launch config:

- Chrome hangs after request
- Edge successfully completes request
- Postman says "Could not get any response" 
- Internet Explorer successfully saves a file named Test.json

With same environment, but IIS Express launch config:

- Chrome sometimes successfully completes request, sometimes hangs after request, sometimes returns nothing.
- Edge sometimes successfully completes request, sometimes says "Can't reach this page"
- Postman says "Could not get any response"
- Internet explorer sometimes saves a file named Test.json, sometimes says "Page could not be displayed"

As you can see with IIS Express in this test, it appears to be acting inconsistently. Sometimes it becomes entirely unresponsive and stops servicing any requests including the default home page until I restart it. Other times it manages to return the home page but won't respond to the test action. At one point I got an IIS HTTP 502.5 Process Failure message, but could not replicate that. 

It's likely this inconsistency is affecting some of my previous tests.

I'm using the template ASP.NET Core Web Application (.NET Core) -> Web Application with No Authentication and Docker disabled, then pasting the code above into a TestController.cs

**Comment by kichalla** [comment] 2017-04-13 17:34
I was able to repro this issue Chrome browser and in all versions of MVC, including the latest...the issue seems to be chunked response not being ended properly. I found this through Fiddler.

**Comment by kichalla** [comment] 2017-04-13 17:50
So basically this is not a recursion issue and does repro for any exception that happens when the formatter is writing out the response.

cc @Tratcher @halter73

**Comment by Tratcher** [comment] 2017-04-13 18:15
By design. If app code throws an exception after starting the body then the connection must be ungracefully terminated. After the headers have been sent there's no other way to communicate the error to the client.

The workaround is to buffer / front load operations that are likely to fail prior to writing to the response.

**Comment by Eilon** [comment] 2017-04-13 18:23
@Tratcher so this is more about certain clients/browsers not responding well to a terminated request?

**Comment by Tratcher** [comment] 2017-04-13 18:28
There's not really a good way for client s to respond, they can only retry.

**Comment by rynowak** [comment] 2017-04-13 19:02
> the connection must be ungracefully terminated

Does it terminate the connection?

**Comment by kichalla** [comment] 2017-04-14 16:57
Discussed with @halter73 and @pakrym and it seems we terminate the connection and do not send the final 0-size chunk on purpose, so its the Chrome browser which is behaving different here.

**Comment by kichalla** [comment] 2017-04-17 12:36
Since there is no action item from our side for this, I am closing this issue.

**Closed by kichalla** 2017-04-17 12:36 UTC
Labels: external, investigate
