### ISSUE TITLE
Wrong Model Binding

### ISSUE THREAD

**Issue by toben** [aspnet/Mvc#6614] opened 2017-08-01 08:35 UTC
Hello,

I tried to find my issues on this repository but I didn't find it so I hope it is a real issue.
I have a View Edit.cshtml who takes a Model which contains a property named "Id".

In this view, I have a ViewComponent which contains a property named "Id" and this view component contains another ViewComponent which also contains a property named "Id".

There is a form in the last view component. When I put a Tag Helper : `<input type="hidden" asp-for="Id" />`. The value is the id of the model of View.cshtml.

I don't know why but maybe I misunderstood the ViewComponent system...

**Comment by Eilon** [comment] 2017-08-02 02:10
@toben - sorry you're running into this issue. It would be helpful if you could share an app (on GitHub) that demonstrates this problem. There are sometimes issues when multiple "levels" of the views and models have elements with the same id, and each case is a bit different.

**Comment by toben** [comment] 2017-08-03 12:24
Unfortunately, I can't do that because it is a project from my company. I tried to find a jsfiddle like for asp.net core (where we can put multiple files) but I don't find it...

**Comment by Eilon** [comment] 2017-08-03 23:33
@toben - any chance you could make a simplified version that demonstrates the problem?

**Comment by Eilon** [comment] 2017-08-16 00:13
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2017-08-16 00:13 UTC
