### ISSUE TITLE
RC2 Label TagHelper NotImplementedException

### ISSUE THREAD

**Issue by goldenalfer** [aspnet/Mvc#4779] opened 2016-05-31 05:08 UTC
After update to RC2 we got NotImplementedException for this code

    <label asp-for="Test"><input asp-for="Test" onchange="alert('x');" /> Test</label>

ViewModel

    public class TestViewModel
    {
        public bool Test { get; set; }
    }

Something wrong with parameters values (e.g. onchange)

Exception:
    
    NotImplementedException: The method or operation is not implemented.

    Microsoft.AspNetCore.Razor.TagHelpers.DefaultTagHelperContent.EmptyOrWhiteSpaceWriter.Write(Char value)
    System.Text.Encodings.Web.TextEncoder.Encode(TextWriter output, String value, Int32 startIndex, Int32 characterCount)
    Microsoft.AspNetCore.Mvc.Rendering.TagBuilder.AppendAttributes(TextWriter writer, HtmlEncoder encoder)
    Microsoft.AspNetCore.Mvc.Rendering.TagBuilder.WriteTo(TextWriter writer, HtmlEncoder encoder)
    Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBuffer.WriteTo(TextWriter writer, HtmlEncoder encoder)
    Microsoft.AspNetCore.Razor.TagHelpers.DefaultTagHelperContent.IsEmptyOrWhiteSpaceCore(Object entry, EmptyOrWhiteSpaceWriter writer)
    Microsoft.AspNetCore.Razor.TagHelpers.DefaultTagHelperContent.get_IsEmptyOrWhiteSpace()
    Microsoft.AspNetCore.Mvc.TagHelpers.LabelTagHelper.<ProcessAsync>d__15.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    Asp._Views_Home_Test_cshtml.<ExecuteAsync>d__24.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---

**Comment by dougbu** [comment] 2016-05-31 05:16
This is a dupe of aspnet/Razor#760.

**Comment by Eilon** [comment] 2016-06-06 17:28
Yup.

**Closed by Eilon** 2016-06-06 17:28 UTC
