### ISSUE TITLE
Different markup state for empty/no errors validation summary between server and client implementations

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Mvc#3377] opened 2015-10-21 20:40 UTC
I'm not sure why there is a need to render empty list element ('HiddenListItem ') in validation summary tag:
https://github.com/aspnet/Mvc/blob/538cd9c19121f8d3171cbfddd5d842cbb756df3e/src/Microsoft.AspNet.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L26
https://github.com/aspnet/Mvc/blob/538cd9c19121f8d3171cbfddd5d842cbb756df3e/src/Microsoft.AspNet.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L703-L707
When there is no errors the resulting html is:

``` cshtml
<div class="text-danger validation-summary-valid" data-valmsg-summary="true">
<ul>
<li style="display:none"></li>
</ul>
</div>
```

The client side implementation does not care about elements of the list itself, they are always cleared:
https://github.com/aspnet/jquery-validation-unobtrusive/blob/master/jquery.validate.unobtrusive.js#L58-L70

The reason I noticed this is that screen readers/crawlers see that list, even if empty (empty list just adds noise to markup):

![image](https://cloud.githubusercontent.com/assets/14539/10649436/79cc7c58-7844-11e5-8ac4-0bdd9e17023f.png)

It would be better to just not render that empty element on server:

``` cshtml
<div class="text-danger validation-summary-valid" data-valmsg-summary="true">
<ul></ul>
</div>
```

Just a little detail.
Thanks!

**Comment by dougbu** [comment] 2015-10-21 21:27
@peterblazejewicz looks like your report is a dupe of #2372. Do you agree?

**Comment by peterblazejewicz** [comment] 2015-10-21 21:45
@dougbu 
The #2372 seems to be more general discussion about rendering validaiton summary container, not only its content.
I'm not sure, I just point that rendering empty 'li' is kind of pointless from both server and client side implementation and I think removing it will not have side effects, while clearing rendered markup. Just '<li style="display:none;"></li>'
Thanks!

**Comment by dougbu** [comment] 2015-10-21 22:02
Hmm, the empty `<li>` element exists to avoid warnings about an empty list (`<ul>` in this case) and remain compliant with the [HTML 4.01](http://www.w3.org/TR/html4/struct/lists.html#h-10.2) specification.

**Comment by peterblazejewicz** [comment] 2015-10-22 18:54
> Hmm, the empty <li> element exists to avoid warnings about an empty list (<ul> in this case) and remain compliant with the HTML 4.01 specification.
The data attributes are either not compliant with 4.01 (December 1999)
If older specs are to be supported, then I would opt to close this one and I'll join discussion  to #2372.
Thanks!

**Comment by dougbu** [comment] 2015-10-22 19:33
> The data attributes for validation are either not compliant with 4.01 (December 1999)

I'm curious: In what way are additional attributes non-compliant? The spec doesn't limit the attributes services can include.

> I'll join discussion to #2372

You're correct this issue is somewhat separate. Let's leave this open so that I can check w/ others whether the 4.01 spec remains interesting. A few people are out this week.

**Comment by peterblazejewicz** [comment] 2015-10-22 19:38
> I'm curious: In what way are additional attributes non-compliant? The spec doesn't limit the attributes services can include.

The validation data attributes won't pass W3C 4.01 validators, just like empty UL tags with 'there is no attribute "DATA-VALMSG-SUMMARY' error

**Comment by Eilon** [comment] 2016-01-15 21:32
Moving to backlog, we will revisit again next time.

**Comment by MrJoe** [comment] 2017-06-16 09:03
An unwanted side effect is when using a strict  `Content-Security-Policy: default-src 'self'; frame-ancestors 'none'; style-src 'self' ` causes a security violation due to the inline style rendering.

**Comment by mkArtakMSFT** [comment] 2018-09-19 21:19
Closing this issue as there was no community involvement for quite a while now.

**Closed by mkArtakMSFT** 2018-09-19 21:19 UTC
