### ISSUE TITLE
Discussion: Startup Code changes in MVC

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3083] opened 2015-09-02 05:09 UTC
#### This is the place for all feedback and discussion related to aspnet/Announcements#62
# 
##### Part 1:

Both the `AddMvc(...)` and `AddMvcCore(...)` extension methods now return a builder API, which can be chained to additional setup methods:

```
services.AddMvc(options =>
{
    options.Filters.Add(...);
})
.AddXmlDataContractSerializerFormatters()
.AddViewLocalization(LanguageViewLocationExpanderFormat.SubFolder);
```

Or used as local variable:

```
var mvc = services.AddMvc(options =>
{
    options.Filters.Add(...);
})
mvc.AddXmlDataContractSerializerFormatters()
mvc.AddViewLocalization(LanguageViewLocationExpanderFormat.SubFolder);
```

The purpose of this change (beyond consistency) is to make the intellisense experience more targeted. Now MVC methods that require you to register MVC can't be called without doing so. Also MVC's various features are more discoverable if you're looking at intellisense for the builder.
##### Part 2:

We removed additional extension methods that we had off of `IServiceCollection` or `MvcOptions` and made them into extensions methods targeting one of the MVC builders (`IMvcCoreBuilder` or `IMvcBuilder`).
###### Old:

```
services.AddMvc();
services.ConfigureMvc(options =>
{
    options.AddXmlDataContractSerializerFormatters();
})
```
###### New:

```
services.AddMvc().AddXmlDataContractSerializerFormatters();
```
#### Part 3:

We removed variations on `ConfigureMvcXyz(...)` and replaced them with extension methods targeting one of the builders.

All of our `AddXyzFeature(...)` methods that have an associated options type, we provide an overload that takes an `Action<T>` for configuring options. 

Where there's no obvious `AddXyzFeature(...)` we provide an `AddXyzOptions(...)` method instead.
###### Old:

```
services.ConfigureMvcJson(...);
```
###### New:

```
services.AddMvc().AddJsonOptions(...);
```

**Comment by NeelBhatt** [comment] 2015-09-02 05:39
Awesome! I knew something like this is coming shortly and it is here! Personally :+1: for this

**Comment by leosvelperez** [comment] 2015-09-02 17:40
That's great! :+1:

**Comment by Flavien** [comment] 2015-09-03 23:21
Not sure if this is related but I have this in my Startup class:

            services
                .AddMvcCore()
                .AddCors()
                .AddJsonFormatters();

This used to work in beta 6, and now in beta 7, whenever a request comes in, I get an error 500 in response instead, and the action method is not called (no exception logged).

Is there a change in what I should do if I use AddMvcCore?

**Comment by rynowak** [comment] 2015-09-03 23:26
@Flavien If this is compiling successfully then it doesn't sound like you're affected by breaking changes to the startup APIs. Would it be possible to attach a debugger and see what's being thrown?

You could also add the error page `app.UseErrorPage();` for local dev troubleshooting.

**Comment by Flavien** [comment] 2015-09-03 23:39
Thanks, I used `UseErrorPage`, and it seems the exception is:

    InvalidOperationException: No service for type 'Microsoft.AspNet.Mvc.ITempDataDictionary' has been registered.

How do I resolve this?

By the way, this can be easily reproduced on the default project template by replacing `services.AddMvc()` with `services.AddMvcCore()`.

**Comment by Flavien** [comment] 2015-09-03 23:43
`.AddViews()` solved the problem.

**Comment by rynowak** [comment] 2015-09-03 23:46
Yep, tempdata is bucketed as a view feature. Are you using it outside of a view, would it be helpful to have an `AddTempData()` shortcut?

**Comment by Flavien** [comment] 2015-09-03 23:50
Yes, I don't use views at all since this is an ASP.NET Web API website. My controllers return directly a `JsonResult` instance.

`AddTempData` would not be very clear as to when you need it, but something with a more obvious name would be useful.

**Comment by rynowak** [comment] 2015-09-03 23:59
So, you're not using TempData? Are you using `Controller` as a base-class?

**Comment by Flavien** [comment] 2015-09-04 16:32
I'm not using TempData explicitly. I'm using `Controller` as the base class, so I suppose `Controller` requires it. I get an exception if I don't call `AddViews`.

**Comment by rynowak** [comment] 2015-09-04 16:33
@Flavien - thanks for confirming, that's what I expected.

**Comment by djanosik** [comment] 2015-09-07 09:43
It's not clear how to access other properties that were available through the `.ConfigureMvc(a)` method. Eg. the following code is no longer working:
```c#
services.ConfigureMvc(o =>
{
    o.ModelMetadataDetailsProviders.Add(new ValidationMetadataProvider(textProvider));
});
```
And the only alternative is:
```c#
services.Configure<MvcOptions>(o =>
{
    o.ModelMetadataDetailsProviders.Add(new ValidationMetadataProvider(textProvider));
});
```
I think there is an `.AddMvcOptions(a)` method missing on the `IMvcBuilder` interface.

**Comment by NeelBhatt** [comment] 2015-09-07 10:20
@djanosik I guess you require ```AddDataAnnotations(...)``` which adds model metadata and validation support for data annotations attributes.

**Comment by djanosik** [comment] 2015-09-07 10:22
@NeelBhatt Nope, these are my own providers that make validation attributes localizable. The `AddDataAnnotations` method is called earlier.

**Comment by rynowak** [comment] 2015-09-07 19:49
@djanosik 

You can just inline any setup actions for `MvcOptions` into `AddMvc(...)`.
```
services.AddMvc(o =>
{
    o.ModelMetadataDetailsProviders.Add(new ValidationMetadataProvider(textProvider));
});
```

If this doesn't do what you want, could you post a more complete sample of what you need to do?

**Comment by djanosik** [comment] 2015-09-07 20:03
@rynowak Yes, but it makes no sense to call `AddMvc` inside an extension method of `IMvcBuilder`. This is what I need:
```c#
services.AddMvc()
    .AddSomethingElse();

public static IMvcBuilder AddSomethingElse(this IMvcBuilder builder) 
{
    builder.AddMvcOptions(o =>
    {
        o.ModelMetadataDetailsProviders.Add(new ValidationMetadataProvider(textProvider));
    });
}
```
I know I can use `builder.Services.Configure<MvcOptions>`, but it's not consistent.

**Comment by rynowak** [comment] 2015-09-07 20:11
@djanosik - makes more sense now, thanks!

Do you care about having your options setup code be idempotent? Inside the framework, we do something like this:

```
public class MyOptionsSetup : IConfigureOptions<MvcOptions>
{
...
}

public static IMvcBuilder AddFeatureXyz(this IMvcBuilder builder)
{
    builder.Services.TryAddEnumerable(ServiceDescriptor.Transient<IConfigureOptions<MvcOptions>, MyOptionsSetup>());
    return builder;
}
```

This makes it so that if you're called multiple times then you only update options once. This is important inside the framework because we don't know if third party code is calling us in addition to the user-authored startup code. May not matter for what you want to accomplish.

**Comment by djanosik** [comment] 2015-09-07 20:15
Yes, that might be useful. I will take a look, thank you!

**Comment by andrewm1986** [comment] 2015-09-13 00:47
Can I suggest a prefix of With for any extension methods? Might read better

```
services.AddMvc().WithXmlDataContractSerializerFormatters();
```

**Comment by rajeshparbat** [comment] 2015-09-13 15:49
Nice One

**Comment by pebezo** [comment] 2015-09-30 03:29
+1 on andrewm1986's suggestion. Not only does it read better, but it's also immediately clear that you can't use the With* methods directly off services.

**Comment by newsash** [comment] 2015-10-07 15:33
+1 on adrewm1986's suggestion and I have another suggestion - all builders can implement IServiceCollection directly:
````c#
services.AddIdentity<User,Role>()
        .AddMvc()
            .WithXmlDataContractSerializerFormatters()
        .AddSingleton<IMyService, MyService>();
````

**Comment by newsash** [comment] 2015-11-04 20:05
@rynowak, could you please comment on the andrewm1986's suggestion?

**Comment by tuespetre** [comment] 2015-12-16 04:49
Just my opinion, it would be nice if the 'AddMvc' extension method would take an 'Action<IMvcBuilder>' so all of the MVC-related setup could be contained within its own block. More aesthetic than anything.

**Comment by Eilon** [comment] 2017-06-09 22:06
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by Eilon** 2017-06-09 22:06 UTC
