### ISSUE TITLE
FromForm inherit doc is empty.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#2663] opened 2015-06-07 08:24 UTC
Looking at a definition of FromForm on Visual Studio I found that the documentation is empty. Looking at the source file I found it has inheritdoc. 

```
    /// <summary>
    /// Specifies that a parameter or property should be bound using form-data in the request body.
    /// </summary>
    [AttributeUsage(AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class FromFormAttribute : Attribute, IBindingSourceMetadata, IModelNameProvider
    {
        /// <inheritdoc />
        public BindingSource BindingSource { get { return BindingSource.Form; } }

        /// <inheritdoc />
        public string Name { get; set; }
    }
```

[FromFormAttribute.cs](https://github.com/aspnet/Mvc/blob/64e726d2b26422c5452475627e4afaba307edec3/src/Microsoft.AspNet.Mvc.Core/FromFormAttribute.cs)

![image](https://cloud.githubusercontent.com/assets/3386797/8023175/3ebf4a12-0cd5-11e5-9a92-f5e606cd0b7d.png)

**Comment by NTaylorMullen** [comment] 2015-06-07 17:39
We have yet to implement `<inheritdoc />`. As of right now we continue to place `<inheritdoc />` on our bits in preparation for it to one day light up :smile:

**Comment by dougbu** [comment] 2015-06-07 17:53
This is a duplicate of #928.  In addition the Roslyn team is tracking this feature at dotnet/roslyn#67.

**Closed by dougbu** 2015-06-07 17:53 UTC
