### ISSUE TITLE
Absolute URL generation includes the wrong port

### ISSUE THREAD

**Issue by strohhut** [aspnet/Mvc#5790] opened 2017-02-11 18:18 UTC
I have links from a http page to a https page.

I create them like this:

```
<a asp-action="Login" asp-controller="Account" asp-protocol="https">Link</a>
<a href="@Url.RouteUrl(someRouteNameVariable, null, "https")">Link 2</a>
```

In Startup.cs I have `options.SslPort = 44301` and I use `[RequireHttps]` on the actions the links point to. 

If I leave out the protocol for the link generation I get a relative path which is wrong obviously. If I specify "https" I still get wrong URLs like `https://localhost.dev:1507/account/login`.

Setting the port [manually](https://github.com/aspnet/Mvc/issues/5565) is not very convenient. Why can't link generation honor the `SslPort` option?

**Comment by SilverioMiranda** [comment] 2017-02-12 17:26
Probably the port in launchSettings.json is 1507
You changed that file?

**Comment by Eilon** [comment] 2017-02-17 21:49
It seems like perhaps the URL generation helpers in MVC could look up the SslPort option if `https` is used and a custom port isn't specified.

**Comment by rocifier** [comment] 2017-03-20 07:15
> It seems like perhaps the URL generation helpers in MVC could look up the SslPort option if https is used and a custom port isn't specified.

Do you mean if a custom port IS specified?

**Comment by Eilon** [comment] 2017-03-20 16:49
@rocifier actually I think maybe in both cases? I guess the key is to check the current scheme, and if it's `https`, use SslPort if it's specified, and remove the port completely if it's not specified.

The reason for this is that I think the current behavior of the helper is that if the port is specified on the "current request" that it will use that port unless you explicitly specify a new port. But when you change schemes, it's a bit trickier because different schemes have different default ports.

**Comment by cod7alex** [comment] 2017-03-24 18:08
Hi guys,

I am trying to reproduce this issue and can't get how to properly set MvcSettings for my unit test.
Code below that i've found in some tests doesn`t seem to work.

```
//setting
IOptions<MvcOptions> options = <some options>;
var services = new ServiceCollection();
services.AddSingleton<IOptions<MvcOptions>>(options);

//getting
var mvcOptions = HttpContext.RequestServices.GetRequiredService<IOptions<MvcOptions>>();
```

**Comment by Eilon** [comment] 2017-03-24 22:15
@cod7alex can you show how you're setting the service provider on the HttpContext? (Is there any code missing in the middle there?)

**Comment by cod7alex** [comment] 2017-03-25 20:34
@Eilon thanks for replying. While looking at code one more time i think i figured it out by myself.
I set services for Router but not for UrlHelper itself )

**Comment by mkArtakMSFT** [comment] 2018-09-11 22:27
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.

**Closed by mkArtakMSFT** 2018-09-11 22:27 UTC
Labels: 1 - Ready, bug, up-for-grabs
