### ISSUE TITLE
WebApplicationTestFixture missing  when preview1 => preview2

### ISSUE THREAD

**Issue by tbertenshaw** [aspnet/Mvc#7634] opened 2018-04-12 08:24 UTC
after updating to preview2  I now get type or namespace not found `WebApplicationTestFixture` Has it been moved, renamed or deprecated?

**Comment by martincostello** [comment] 2018-04-12 10:54
It's been renamed to `WebApplicationFactory<T>`.

**Comment by tbertenshaw** [comment] 2018-04-12 14:33
presumably the Interface has changed then as all tests break now with razor compilation exceptions. Were there any notes on the change as not spotted any sofar.

**Comment by martincostello** [comment] 2018-04-12 15:47
It's _supposed_ to be able to find them by itself now, but I've gone one application where it keeps getting it wrong and I've been struggling to get it to use the right path with how the tests were originally written.

Depending on how I get on I might open an issue about it as either there's a bug in the code to find the app, or there's a missing extensibility point.

**Comment by mkArtakMSFT** [comment] 2018-04-12 18:49
FYI: @javiercn @danroth27

**Comment by javiercn** [comment] 2018-04-12 21:46
@martincostello Can you provide more details (or a repro) on it?

If your app for some reason is struggling to find the content root automatically (we do so by looking at an attribute stamped on the test assembly) you can do two things.

Override ConfigureWebHost on WebApplicationFactory and just call SetContentRoot (WebHost.UseSolutionRelativeContentRoot is still available)

Do the same thing by calling WithWebHostBuilder and creating a customized factory.

It's also important to note that T in WebApplicationFactory must point to the type holding the entry point of your app. It might be that this bug you are running into is caused by a bug we discovered recently related to Microsoft.AspNetCore.App.

In any case, it would be super helpful if you could provide more information about your scenario, or even better a repro project for us to investigate.

Thanks!

**Comment by martincostello** [comment] 2018-04-13 10:33
@javiercn I'm on holiday from work until Wednesday, but once I'm back in the office I'll have another go at trying to get things working correctly. Some of the issues might just be from the way the code is factored to support testability before this fixture was available and the host-builder in `Program` pattern was introduced.

**Comment by martincostello** [comment] 2018-04-19 08:40
@mkArtakMSFT I'll try and look into this today.

**Comment by martincostello** [comment] 2018-04-19 18:15
Having looked into this my issues were related to:
  1. I was using a custom `TestStartup` class before, which is defined in the test assembly, which caused it to fail to find the builder method as the auto-generated `Program` class in the test assembly doesn't contain one. I fixed this by using `Startup` as `T` and then updating it in `CreateWebHost()`. I'll refactor this to remove the need for it and use `ConfigureAppConfiguration()` instead.
  1. The factory was failing to find the right content root (it was duplicating the application name in the path, so it came out as the equivalent of `Application/Application` instead of `src/Application`). I'd tried to fix this by changing the solution root in `CreateWebHost()` with the code above, but this seemed to take no effect. Digging around in the code I found this to be because it was then immediately overwritten upon returning from the method, so the code effectively had no effect.

I resolved these issues by overriding `ConfigureWebHost()` instead.

**Comment by javiercn** [comment] 2018-04-19 21:40
@martincostello Thanks for looking into it!

That sounds about right.

The expected configuration for the fixture is to call CreateWebHostBuilder in your Program.cs and then figure out the content root based on typeof(TProgram).Assembly if you want to use a different Startup (like one in your test assembly) the right thing to do is set it up in ConfigureWebHost.

I'm closing this as there's no action to be taken here.

**Closed by javiercn** 2018-04-19 21:40 UTC
Labels: question
