### ISSUE TITLE
ApiControllerActionSelector equivalent in Asp .net MVC core

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#6256] opened 2017-05-11 21:27 UTC
_From @ankgupta067 on April 21, 2017 10:43_

hi,
we are migrating from web api to asp .net mvc core , i had an action selector in web api , in which if anyware in url "$" symbol exist we used to invoke a specific method in controller.
this functionality we achieved in web api using ApiControllerActionSelector  below was the code to do same in web api - 

 ```
public override HttpActionDescriptor SelectAction(HttpControllerContext controllerContext) {
            string urlDecode = HttpUtility.UrlDecode(
                controllerContext.Request.RequestUri.ToString());
            if (urlDecode != null && urlDecode.Contains("$")) {
                if (controllerContext.Request.Method == HttpMethod.Post) {
                    MethodInfo method = controllerContext.ControllerDescriptor.ControllerType
                        .GetMethod(
                            "PostCustomOperation");
                    return
                        new ReflectedHttpActionDescriptor(
                            controllerContext.ControllerDescriptor, method);
                }
                if (controllerContext.Request.Method == HttpMethod.Get) {
                    MethodInfo method = controllerContext.ControllerDescriptor.ControllerType
                        .GetMethod(
                            "GetCustomOperation");
                    return
                        new ReflectedHttpActionDescriptor(
                            controllerContext.ControllerDescriptor, method);
                }
            }
            HttpActionDescriptor result = base.SelectAction(controllerContext);
            return result;
        }
```
I am not able to find an equivalent way to do same in Asp .net mvc core , i tried implementing IRouter but in that we have to specify controller as well but that is not known to me.
Any suggestion on how to achieve same or is i not possible to do in Asp.net MVC core?

_Copied from original issue: aspnet/Routing#400_

**Comment by rynowak** [comment] 2018-01-08 01:38
Dupe of https://github.com/aspnet/Mvc/issues/6193

**Closed by rynowak** 2018-01-08 01:38 UTC
