### ISSUE TITLE
PageContext.ViewData and ViewContext.ViewData are different instances in Razor Pages

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Mvc#7675] opened 2018-04-17 23:21 UTC
Original issue was discovered in Identity UI and is linked below:

### Details

1. PageActionInvoker creates a `ViewContext` instance using PageContext.ViewData. At this point, `ViewContext.ViewData` = `PageContext.ViewData`  =`ViewData<MyPageModel>`.
2. If the Page has an associated _ViewStart.cshtml,  the page execution results in a `ViewContext.ViewData = new ViewDataDictionary<object>(ViewContext.ViewData)`. 
3. When the page executes, we initialize an instance of `RazorPageAdapter` to avoid double initialization. `RazorPageAdapter` does not have a model property and ends up producing yet another `ViewContext.ViewData = new ViewDataDictionary<object>(ViewContext.ViewData)`
4. The `ViewData` property on the actual Page keys off of `PageContext`: 
`public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<TestModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<TestModel>)PageContext?.ViewData;`

To recap, at this point, in cshtml,

`this.ViewData`  -> `ViewData<MyPageModel>`
`ViewContext.ViewData` -> `new ViewData<object>(new ViewData<object>(this.ViewData));`

5. `ViewContext.ViewData` is what gets passed to Layout, partials etc.

### Why this works:

The  🎩  ✋ 🐰 magic of `CopyOnWriteDictionary`. If the `_ViewStart` or any other component, does not write to `ViewData`, `ViewContext.ViewData` has effectively the same backing store as `this.ViewData`. Any writes to it show up in `ViewContext.ViewData`. This obviously breaks if something expressly writes to `ViewContext.ViewData`. In the Identity UI case, this is the filter that we broke detailed in https://github.com/aspnet/Mvc/issues/7665.

----------------------------
### Original issue

_From @kichalla on April 6, 2018 0:8_

For example, when we go to `Manage` page, we should see the title of the html page to be like `Profile - <application-name>` but we only get ` - <application-name>`.

@pranavkm and I debugged through this and think that the cause of this issue could be with how Identity UI uses a model type(abstract) on the view versus the actual type(implementation). Following line of code is a suspect:
https://github.com/aspnet/Mvc/commit/7127bb5dbbb07eb325a2852ac9a91be0cf443205#diff-0901f55a5e636aeef89b9663dafcb625R171

_Copied from original issue: aspnet/Identity#1737_

**Comment by javiercn** [comment] 2018-04-18 03:43
Are we planning to do something here for 2.1? Is this a patch candidate?  Is this caused by us writing to the viewdata in the filter? (Will this get fixed as part of the other issue?)

**Comment by mkArtakMSFT** [comment] 2018-04-18 16:54
@javiercn, please evaluate how big of a change is this?

**Comment by pranavkm** [comment] 2018-04-18 17:36
I think this warrants further investigation. It wasn't super obvious what a fix for this is and there could be other things that were broken as a result of activating `RazorPageAdapter` rather than the actual page. I don't feel confident in rushing a fix for this in the next couple of days. My suggestion would be 

a) to address this in a patch (or 2.2.0). For the time being, there's a trivial workaround viz to use `ViewContext.ViewData` in the Razor Page to avoid losing values.
b) Fix Identity to either use `HttpContext.Items` or use `ViewContext.ViewData` in the page to workaround the original reported issue - https://github.com/aspnet/Identity/issues/1737

**Comment by rynowak** [comment] 2018-04-18 19:17
Can we evaluate what identity UI is doing as a feature request? 

This is an implementation detail. And there are workarounds.

**Comment by javiercn** [comment] 2018-04-18 19:42
@rynowak This has nothing to do with Identity UI. According to @pranavkm there is something broken here in a more fundamental level. I just happened to trigger it.

I think this is just a bug and we should look into fixing it, when we deem it appropriate. It does not make sense to me to turn this in into a "feature request".

I can likely workaround this by writing stuff to the HttpContext instance instead of the view data, but that's not the point.

**Comment by pranavkm** [comment] 2018-05-09 23:34
Another scenario listed here - https://github.com/aspnet/Mvc/issues/7408

**Comment by pranavkm** [comment] 2018-07-16 18:24
Fixed in https://github.com/aspnet/Mvc/commit/b62499e02c274db162151556318b0a5fae85360e

**Closed** 2018-07-16 18:24 UTC
Labels: 3 - Done, PRI: 2 - Preferred, bug, cost: M

**Comment by dougbu** [comment] 2018-08-15 06:06
@mkArtakMSFT I just hit this issue when writing up aspnet/Razor#2539 and using 2.1.2. One impact is that changing `ViewData.TemplateInfo.HtmlFieldPrefix` in a Razor Page has no impact on the `name`, `id` or `for` attributes that HTML and tag helpers in the page generate. All of this works fine in MVC views.

Put another way, after applying the aspnet/Razor#2539 workaround, the Razor Page version of the repro still fails to generate correct names while the MVC View version works perfectly.

Suggest we port this fix to 2.1.x.

**Comment by mkArtakMSFT** [comment] 2018-08-15 18:29
Per our offline discussion we won't be patching this. The reason is that there is no enough usage of this scenario.
