### ISSUE TITLE
ModelExpression equivalent of m => m?

### ISSUE THREAD

**Issue by newsash** [aspnet/Mvc#3978] opened 2016-01-23 10:05 UTC
How to use label tag helper in the following scenario in a display template? `asp-for="@Model"` leads to invalid label text ("Model").
``` c#
@Html.LabelFor(m => m, new { @class = "control-label col-md-2" })
```

**Comment by NTaylorMullen** [comment] 2016-01-24 05:04
`<label asp-for="@Model" class="control-label col-md-2"></label>`

**Comment by newsash** [comment] 2016-01-24 10:27
In a display template (e.g. `@Html.DisplayFor(m => m.UserName`):
* `<label asp-for="@Model"></label>` results in <code>&lt;label for="UserName"&gt;**Model**&lt;/label&gt;</code>
* `@Html.LabelFor(m => m)` results in <code>&lt;label for="UserName"&gt;**UserName**&lt;/label&gt;</code>

**Comment by dougbu** [comment] 2016-01-24 20:42
I'm able to reproduce this as well. Haven't debugged what is going South but it does look strange, especially given the `for` attribute has the correct value.

**Comment by dougbu** [comment] 2016-01-24 22:46
FYI problem relates to how the `ModelMetadata` for the property is found. In the `@Html.LabelFor(m => m)` case, `PropertyName` is `"UserName"`. But in the `<label asp-for="@Model"></label>` case, `PropertyName` is `"Model"`. Looking a bit deeper...

**Comment by dougbu** [comment] 2016-01-24 23:14
:ok: the issue here is that `ExpressionMetadataProvider.FromLambdaExpression()` correctly handles `m => m` and other identity expressions (`ExpressionType.Parameter`) but does not understand that `m => {generated class}.Model` needs special handling. That is, `@Html.LabelFor(m => Model)` hits exactly the same naming issue.

Unfortunately tag helpers do not support lambda identity expressions and _always_ hit this issue if the `@Model` "fallback" is used. We probably didn't see this before because (a) the `ModelMetadata.PropertyName` property isn't used extensively in HTML generation and (b) `@Model.UserName`, `@Model[i].UserName`, and other lambda RHS that start with `@Model` work fine.

One caveat on (a): `string`s generated for client-side validation rules can be messed up when `PropertyName` is incorrect e.g. `data-val-required="The Model field is required."`.

**Comment by dougbu** [comment] 2016-01-24 23:14
And, no, I don't know of an RC1 workaround other than to use HTML helpers for this case.

**Comment by dougbu** [comment] 2016-04-16 20:08
`release`: 7a1ac03
also merged into `dev`

**Closed by dougbu** 2016-04-16 20:08 UTC
Labels: 3 - Done, bug

**Comment by seraphx2** [comment] 2017-12-17 04:36
So we can, or we cannot, use asp-for tag helpers in Display/Edit templates?
Because it's now almost 2018 and these asp-for's are not working in my template.
