### ISSUE TITLE
Wrong output @Url.Action with route values and Action empty or null

### ISSUE THREAD

**Issue by Boglen** [aspnet/Mvc#2077] opened 2015-02-25 10:05 UTC
Microsoft.AspNet.Mvc.Core version 6.0.0-beta4-12872

Code in View:

@Url.Action(subItem.Action, subItem.Controller, subItem.LinkProperties)

LinkProperties = new Dictionary&lt;string,object&gt;() { id = 1, sortOrder = "desc", pageNum = 1};

Generates:
![1234](https://cloud.githubusercontent.com/assets/10594440/6368604/0ccd1ca2-bd00-11e4-9e59-c48b638a0178.JPG)

with wrong amp

/Page/GetPage/3?pageNum=1& amp;amp;...

**Comment by Boglen** [comment] 2015-02-25 18:44
One more problem:

Let me try to explain the idea.
1) I have entity with controller,action, parameters fields. Controller and action is a string fields, and parameters = Dictionary&lt;string,object&gt;() {}
2) In view i have @Url.Action(item.Action, item.Controller, item.Parameters)
3) Routes:

                   routes.MapRoute(
                        name: "default",
                        template: "{controller}/{action}/{id?}",
                        defaults: new { controller = "Page", action = "Index", id = 2 },
                        constraints: new { id = @"\d+" }
                        );

                   routes.MapRoute(
                         name: "defaultWithoutAction",
                         template: "{controller}/{id?}",
                         defaults: new { action = "Index" },
                         constraints: new { id = @"\d+" }
                       );

1. In the first case i have Controller = "Page", Action = "Index", Parameters = new {id = 1}.
@Url.Action generates "/Page/Index/1"

2. (Bug) In the second case i have Controller = "Page", Action = String.Empty, Parameters = new {id = 1}.
@Url.Action duplicate all patameters from current page route values

3. (Bug) In the third case  i have Controller = "Page", Action = null, Parameters = new {id = 1}.
From http://localhost/Page/Index/5 site page @Url.Action generates "/Page/Index/1"
From http://localhost/Page/AwesomePage/5 @Url.Action generates "/Page/AwesomePage/1"



It would be nice if the second and third case, the helper has generated such url:
 "/Page/1" - if we have route with default action defined.(This link works, by the way. If i have pre-defined route that uses default defined action, I do not need this action in the link)


"/Page/Index/1" - This result is also nice, but looks a little less beautiful.


Microsoft.AspNet.Mvc.Core version - 6.0.0-beta4-12872

**Comment by Eilon** [comment] 2015-02-25 20:49
What's the relationship between this issue and https://github.com/aspnet/Mvc/issues/2029?

**Comment by danroth27** [comment] 2015-02-25 22:56
@ianhong Please try to repro the double encoding issue.

**Comment by ianhong** [comment] 2015-03-02 17:17
@danroth27 I can repro this, and I'm looking into the product code to find the root cause.

**Comment by ianhong** [comment] 2015-03-02 18:10
I think this happens because it calls WriteTo instead of WriteLiteralTo in the following code:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorPage.cs#L391-L394

I think I should talk to @dougbu and @NTaylorMullen before making any fix.

**Comment by ianhong** [comment] 2015-03-02 18:44
@rynowak 
MVC5 has the same behavior. Users should use Html.Raw to avoid this  in this case.

**Comment by ianhong** [comment] 2015-03-02 18:50
@Boglen 
I'm closing this issue. This behavior hasn't been changed since MVC5. I think you can use Html.Raw as follows in this scenario. 
<A href="@Html.Raw(Url.Action("About", new { Id = 1, PageNum = 2, Sol = 3}))">Foo</A>

**Closed by ianhong** 2015-03-02 18:50 UTC
Labels: 0 - Backlog
