### ISSUE TITLE
DefaultViewComponentHelper SelectComponent method performance

### ISSUE THREAD

**Issue by ivaylokenov** [aspnet/Mvc#5203] opened 2016-08-30 19:50 UTC
While looking through the code I noticed that the `DefaultViewComponentHelper` caches the view component descriptors when using the `InvokeAsync(string name, object arguments)` overload of the `InvokeAsync` method. It calls the `IViewComponentSelector.SelectComponent` which stores the descriptors in `ILookup` data structures. On the other hand the `InvokeAsync(Type componentType, object arguments)` overload iterates all descriptors every time it is called.

If I have a lot of components and use only the `Type` overload in my views, it would be a lot more slower that the `string` alternative. I believe it will be better to just call `_selector.SelectComponent(componentType.FullName);` (or have its own cache) instead of the iteration.

I can provide measurements, if you require them, but I do not see any valid reason why the `string` method caches the descriptors and the `Type` one does not.

**Comment by rynowak** [comment] 2016-08-31 16:21
It would be great to see some data indicating that there is a measurable impact to this. How many VC types is "a lot" to you?

The fix for this would involve introducing another cache and another constructor to DVCH - (because DCVH is scoped not singleton).

=================

As far as why it's this way? Not sure if it was an oversight or if we measured it and determined that the cost wasn't significant. It seems unlikely that we tested this with a large number of VC types in the application, so I'm curious about what you think a large number of VCs is...

I can say that it's by design that the 'name' selection goes through `IViewComponentSelector` and 'type' selection does not. 'name' selection is intended to support some level of dynamism and can be customized.

**Comment by ivaylokenov** [comment] 2016-08-31 18:26
@rynowak Thank you for your fast answer. The biggest MVC 5 project I have seen had around 800 partial views. Considering this number, I quickly created a simple MVC Core project with 800 simple view components and measured 5000 concurrent invocations iterating over them with `System.Diagnostics.Stopwatch` (it is not the best way to measure but it shows quick results) . The `Type` method overload is more than 100% slower than the `string` one, however, the page loads quite fast. I am attaching the solution.

If you believe the 'Type' method does not worth adding a cache, the issue can be closed. :+1: 

[ManyViewComponents.zip](https://github.com/aspnet/Mvc/files/447998/ManyViewComponents.zip)

**Comment by rynowak** [comment] 2016-08-31 20:33
The question here is, what's the impact of the difference between these two on the site as a whole. 

If using a string is twice as fast when you have 800 VCs, but that part of the code is 00.05% of the time to render a page, it's not going to make much of an impact either way. There's a tradeoff in adding a cache in more memory used and more components we have to maintain.

**Comment by ryanbrandenburg** [comment] 2016-11-08 00:44
I did a little naive stopwatch testing on @ivaylokenov's example before jumping into full blown profiling and I don't think this is a scenario we need to optimize for. The string overload of `InvokeAsync` IS roughly twice as fast as the type overload, but in the given example where we find one of 800 views 5000 times the type overload takes ~70ms vs ~30ms on the string overload. This tells me that individual calls to `InvokeAsync` (of either overload) are taking significantly less than 1ms vs a page load time of ~200ms.

@rynowak do you see any pitfalls with my logic here?

**Comment by rynowak** [comment] 2016-12-14 00:34
Yeah I don't feel especially motivated to change this based on the above data. I think we should close and reconsider if someone finds a case where this is important from a perf POV.

**Comment by ryanbrandenburg** [comment] 2016-12-14 00:38
Closing this, if anyone finds more evidence that this scenario needs attention please re-open.

**Closed by ryanbrandenburg** 2016-12-14 00:38 UTC
Labels: 2 - Working, investigate
