### ISSUE TITLE
Enclose a list of tags (taghelper) by a parent tag

### ISSUE THREAD

**Issue by alansangeeth** [aspnet/Mvc#2909] opened 2015-08-04 06:19 UTC
I need to achieve like below
```
    <MyTagList>
            <MyTag></MyTag>
            <MyTag></MyTag>
    </MyTagList>
```
When ever I use MyTag in design time, it need to be enclosed automaticaly by MyTagList or MyTag should error that it must be enclosed by MyTagList

**Comment by dougbu** [comment] 2015-08-04 14:35
Are you looking for an ability to adjust the HTML schema the editor uses i.e. disallow and don't suggest `<MyTag>` unless immediately within `<MyTagList>`?

**Comment by Eilon** [comment] 2015-08-04 17:17
@DamianEdwards

**Comment by NTaylorMullen** [comment] 2015-08-04 17:45
https://github.com/aspnet/Razor/issues/255 plans to accomplish that. Stay tuned! :smile:

**Comment by NTaylorMullen** [comment] 2015-08-11 23:55
Duplicate of https://github.com/aspnet/Razor/issues/474 and aspnet/Razor#255

**Closed by NTaylorMullen** 2015-08-11 23:55 UTC
Labels: duplicate
