### ISSUE TITLE
Model validation accepts undefined enum values.

### ISSUE THREAD

**Issue by strohhut** [aspnet/Mvc#8012] opened 2018-07-05 06:38 UTC
#### Is this a Bug or Feature request?:
Possibly a bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

```CSharp
public class TestModel
{
    public MyEnum MyEnum { get; set; }
}

public enum MyEnum
{
    A = 1
}


```

```CSharp
public IActionResult MyAction(string json)
{
    var testModel = new TestModel();

    // Assume we got the TestModel instance by deserializing the json action argument manually.

    bool res = TryValidateModel(testModel); // Expected false but is true

    return View();
}
```

#### Description of the problem:
2.1 added checking for Enum.IsDefined during model binding. But when validating manually it is not checked.

#### Version of `Microsoft.AspNetCore.Mvc`
2.1.1

Tags: default value, enums

**Comment by pranavkm** [comment] 2018-07-05 16:48
cc @kichalla

**Comment by mkArtakMSFT** [comment] 2018-07-06 16:37
@kichalla, can you please look into this? Thanks!

**Comment by kichalla** [comment] 2018-07-10 19:16
I can reproduce this. Currently we check if a value for a enum is defined or not during the model binding process and not during validation. I am unable to recall the reason we decided it to be a model binding stage rather than validation(cc @dougbu , do you remember why?), but based on comment in the original bug here: https://github.com/aspnet/Mvc/issues/6329#issuecomment-328238584, using `EnumDataTypeAttribute` should be able to resolve the issue.

**Comment by dougbu** [comment] 2018-07-10 19:47
> we decided it to be a model binding stage rather than validation

&hellip; because it's a better fit with other things we do during model binding. Type conversions and their failures are all handled during model binding.

In addition, users can add `[EnumDataType]` to change the validations (in a more granular fashion than changing `MvcOptions.SuppressBindingUndefinedValueToEnumType` or (worse) `MvcCompatibilityOptions.CompatibilityVersion`).

**Comment by kichalla** [comment] 2018-07-10 20:58
Thanks @dougbu 

Closing this as by design.

**Closed by kichalla** 2018-07-10 20:58 UTC
Labels: by design, cost: XS, investigate
