### ISSUE TITLE
Action attribute should not be added automatically when using FormTagHelper

### ISSUE THREAD

**Issue by andreas-cloudnine** [aspnet/Mvc#2606] opened 2015-05-24 10:55 UTC
See this StackOverflow question:
http://stackoverflow.com/questions/30387136/how-to-prevent-auto-adding-of-action-and-method-attributes-into-form-element-in/30389917

The issue is that forms without an action attribute automatically get an action attribute and a anti forgery hidden field. Forms shouldn't be modified by the FormTagHelper at all if no asp- attributes are present. This also follows how runat="server" works in WebForms.

**Comment by dougbu** [comment] 2015-05-24 20:14
This is a duplicate of #2581 (and a few other duplicates). @NTaylorMullen added the necessary infrastructure to Razor (issue aspnet/Razor#361, commit aspnet/Razor@0e61b49) and also changed the `<a>` and `<form>` tag helpers to use it (@e689863). In nightly Beta 5 builds, these tag helpers are now associated only with elements that have one of their `asp-*` attributes.

Workaround in earlier releases is to add an exclamation mark to the element name e.g. `<!form>...`.

**Closed by dougbu** 2015-05-24 20:14 UTC
