### ISSUE TITLE
Non-deterministic behavior for model in PartialView

### ISSUE THREAD

**Issue by topguss** [aspnet/Mvc#4106] opened 2016-02-16 14:11 UTC
**Background**
We have view model with items :

    public class PaymentViewModel
    {
	  public decimal? Payment { get; set; }
	  public string Description { get; set; }
	
	  public List<SplittedPaymentViewModel> SplittedPayment { get; set; } = new List<SplittedPaymentViewModel>();
    }

    public class SplittedPaymentViewModel
    {
	  public short SplittedPaymentId { get; set; }
	  public decimal? Payment { get; set; }
	  public string Description { get; set; }
    }

For rendering html, we have this two views, one regular: **CreatePayment**

    @model ZevApp.ViewModels.Record.PaymentViewModel
    ...
    <input class="form-control" asp-for="Payment" type="number" />
    <input class="form-control" asp-for="Description" />
    ...
    <div class="panel-body" id="SplittedPayments">
	@foreach (var spItem in Model.SplittedPayment)
	{
	  @Html.Partial("SplittedPaymentPartial", spItem);
	}
    ...
    </div>

And the other Partial: **SplittedPaymentPartial**

    @model ZevApp.ViewModels.Record.SplittedPaymentViewModel
    ...
    <input class="form-control" asp-for="Payment" type="number" />
    <input class="form-control" asp-for="Description" />
    ...

As you can see, from the first view, we call partial view and pass them item by item form the *SplittedPayment* list.

Each view define model at the beginning of the file.

**Use case 1**
From a controller we return view with name *CreatePayment* and pass initialized object of *PaymentViewModel*, initialized with three *SplittedPaymentViewModel*s. 

We run the code, but unexpectedly behavior is occur:
Each partial view bind *Payment* and *Description* form the CreatePayment's model *PaymentViewModel* - not from a passed item?

**Use case 2**
From a controller we return partial view and pass initialized object of SplittedPaymentViewModel. Binding is as expected - partial view bind *Payment* and *Description* form the passed model.

When we are editing partial view by VisualStudio 2015, IntelliSense recognizes _SplittedPaymentViewModel_ as model for partial page.

It seems to us that when we call partial view from regular view, than the partial view use model from the original view, not the model we pass.

**Comment by dougbu** [comment] 2016-02-16 19:30
Could you please add the code initializing the `PaymentViewModel` and `SplittedPaymentViewModel` instances in the two cases? The generated HTML would also help understand this issue.

**Comment by topguss** [comment] 2016-02-17 08:35
Here is test project and use case steps:

[https://drive.google.com/file/d/0B5bsSH-06GTYSU1kaDQxQS02NUU/view?usp=sharing](https://drive.google.com/file/d/0B5bsSH-06GTYSU1kaDQxQS02NUU/view?usp=sharing)

1. Run the project, click on the link "CreatePayment".

2. You can see initialized data and in this case they are well binding .

3. Click Submit button.

- If you put break point on debug mode on _public IActionResult CreatePayment(PaymentViewModel model)_ you can see that model is OK - it contains 2 items

- After rendering the page, you can see that for each SplittedPayment, Payment and Description were binded from PaymentViewModel.

**Comment by dougbu** [comment] 2016-02-17 17:41
I'm unable to view those files online. And the downloaded `.rar` file is flagged as containing a virus on my machine. Please upload the files to a personal GitHub repo instead.

**Comment by danroth27** [comment] 2016-02-17 22:04
@dougbu Could you try to reproduce this issue manually? I.e. create the same views, partial views and model types and see what happens.

**Comment by zhaparoff** [comment] 2016-02-18 00:56
@topguss, 

You need to specify prefix for your partial view fileds by providing ViewDataDictionary parameter to 
`@Html.Partial("SplittedPaymentPartial", spItem, new ViewDataDictionary(ViewData, spItem) { TemplateInfo = new TemplateInfo() { HtmlFieldPrefix = "SplittedPaymentPartial" } })`
instead of hardcoding them to vpartial view.
But in MVC 6 TemplateInfo property seems to be read-only.

Or you can try to consume EditorFor helper
`@Html.EditorFor(model => spItem)`

**Comment by topguss** [comment] 2016-02-18 07:45
Here is public git repo with code: [https://github.com/topguss/TestPartialViewBinding-MVC6](https://github.com/topguss/TestPartialViewBinding-MVC6)

**Comment by dougbu** [comment] 2016-02-18 18:34
@topguss much appreciated. Having a look now...

**Comment by dougbu** [comment] 2016-02-19 22:00
@topguss, as @zhaparoff implied, the system is working as intended. The expressions in `SplittedPaymentPartial.cshtml` (e.g. `@(Model.SplittedPaymentId)` work as you expect. However the helpers look first in the `ModelStateDictionary` e.g.  `asp-for="Payment"` leads to a lookup with the key `"Payment"`. This is required to round trip the submitted values in the case where the submission included invalid data.

The problem is `CreatePayment.cshtml` doesn't provide any information about the `spItem` expression when invoking the partial. I suggest the following variant of @zhaparoff's workaround:
```c#
        var savePrefix = ViewData.TemplateInfo.HtmlFieldPrefix;
        for (var i = 0; i < Model.SplittedPayment.Count; i++)
        {
            ViewData.TemplateInfo.HtmlFieldPrefix = Html.NameFor(m => m.SplittedPayment[i]);

            var spItem = Model.SplittedPayment[i];
            @Html.Partial("SplittedPaymentPartial", spItem);

            ViewData.TemplateInfo.HtmlFieldPrefix = savePrefix;
        }
```

The above also allows you to simplify `SplittedPaymentPartial.cshtml`.

Side note: "Regular 321" is invalid (too long) for `Payment.Description`. So, in your repro, the submission does indeed include invalid data.

**Comment by dougbu** [comment] 2016-02-23 20:11
Closing since root cause is primarily around ease of use and discovering properties like `HtmlFieldPrefix`. Have filed #4132 and #4134 to cover most of that.

**Closed by dougbu** 2016-02-23 20:11 UTC
Labels: 2 - Working, investigate
