### ISSUE TITLE
Attribute Routing Unexpected 404 on HttpPost

### ISSUE THREAD

**Issue by jhigh2000** [aspnet/Mvc#6066] opened 2017-04-03 21:03 UTC
Reporting a scenario where the Attribute Routing behavior in ASP.NET Core does not match the behavior in ASP.NET MVC 5.

## Impact
Unexpected 404 when using attribute routing

### ASP.NET Core Project Setup
- File...New Project
- Web \ ASP.NET Core Web Application (.NET Core)
- Template: Web Application
- Authentication: No Authentication

### Code
- Add a New Controller named CustomerController.cs with the following code:

```
using Microsoft.AspNetCore.Mvc;

namespace Test.Controllers
{
    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class CustomerController : Controller
    {
        [HttpGet("Customer/Edit/{id:int}")]
        public IActionResult Edit(int id)
        {
            var vm = new Customer
            {
                Id = id,
                Name = "Test Customer"
            };
            return View(vm);
        }

        [HttpPost("Customer/Edit")]
        public ActionResult Edit(Customer customer) => RedirectToAction(nameof(HomeController.Index), "Home");
    }
}
```

- Add a New View to Views/Customer named Edit.cshtml with the following razor (default scaffolded edit view) :

```
@model Test.Controllers.Customer

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Id" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

```

### ASP.NET MVC 5 Project Setup
- File...New Project
- Web \ ASP.NET Web Application (.NET Framework)
- ASP.NET 4.6.2 Template: MVC
- Authentication: No Authentication

- Add a New Controller named CustomerController.cs with the following code:

```
using System.Web.Mvc;

namespace Test.Controllers
{
    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class CustomerController : Controller
    {
        [HttpGet]
        [Route("Customer/Edit/{id:int}")]
        public ActionResult Edit(int id)
        {
            var vm = new Customer
            {
                Id = id,
                Name = "Test Customer"
            };
            return View(vm);
        }

        [Route("Customer/Edit")]
        [HttpPost]
        public ActionResult Edit(Customer customer) => RedirectToAction(nameof(HomeController.Index), "Home");
    }
}
```

- Add a New View to Views/Customer named Edit.cshtml with the following razor (default scaffolded edit view):

```
@model Test.Controllers.Customer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
```

## Test Scenario

- Launch both sites, navigate to /customer/edit/1

![image](https://cloud.githubusercontent.com/assets/138398/24631430/da0992c6-1885-11e7-834a-2f6232f86ef4.png)

- Click Save

## Expected Result

- HttpPost to ```public ActionResult Edit(Customer customer) (...)```
is successful.

### ASP.NET MVC 5

- HttpPost is successful

### ASP.NET Core

- HttpPost results in a 404 Not Found

![image](https://cloud.githubusercontent.com/assets/138398/24631610/92f89958-1886-11e7-92c2-d408b6a1fba0.png)

**Comment by khellang** [comment] 2017-04-04 00:10
Why didn't you include a screenshot of the successful case? My gut feeling says you're not actually POST'ing to the same URL, cause I simply can't see how that would match a route in either MVC 5 or Core. Granted, it should probably have returned a 405 instead of 404 (I think this is configurable), but there's definitely no combination of method and URL that matches `POST /Customer/Edit/1` :smile:

**Comment by khellang** [comment] 2017-04-04 00:19
What happens of you're more specific about what values you bind to? I.e. add `[FromRoute]` to the `id` parameter?

**Comment by rynowak** [comment] 2017-04-04 00:50
The `Customer/Edit/{id}` entry is considered more specific for link generation because it has a parameter `id` in addition to the `controller` and `action` values. It will be tried 'first' because it's considered a more specific - since you have the following route values in your *ambient values* `{ controller = "Customer", action = "Edit", id = "5" } and these satisfy the requirements, then that template is used and it generates the path `Customer/Edit/5`.

If you want this to behave differently, you have a few options (in order of simplicity):
1. Use the template `Customer/Edit/{id}` for your `POST`-handling actions. Then you don't have the requirement to place a hidden field in your form.
2. Give your `HttpPost` and `HttpGet` actions different names (via method name or the `[ActionName]` attribute. This will allow you to refer to them unambiguously
3. Give one (or both) of your routes a route name via `Name = Foo` in your attributes. This will allow you to refer to them unambiguously.
4. Use `@Html.BeginForm(  ... new { id = (string)null })` to wipe out the `id` value in the ambient values.

Of these 1). is the choice that will reduce boilerplate and most closely follows the typical convention for a CRUD form.

**Comment by jhigh2000** [comment] 2017-04-04 01:58
@khellang The screenshot of the MVC 5 success case is a redirect to /home/index and looks like this:

![image](https://cloud.githubusercontent.com/assets/138398/24638602/667d8496-18af-11e7-8ffc-dffe39a5168f.png)
and
![image](https://cloud.githubusercontent.com/assets/138398/24638616/7fd4e308-18af-11e7-9439-0d2fc45f8784.png)

@rynowak Agreed that 1. is the best approach and follows convention (and the way that I normally handle the post actions), however my reason for submitting this issue was to illustrate the differences in behavior between MVC 5 and ASP.NET Core.  Some team members are migrating legacy core and unexpectedly saw the routes fail (unexpectedly in the sense that they routes resolve correctly in "classic" MVC 5).

**Comment by rynowak** [comment] 2017-04-04 02:05
Thanks for the report then. This was an intentional behavior change from MVC5.

See the relevant code here: https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/Template/RoutePrecedence.cs

Note that there's both 'inbound precedence' and 'outbound precedence'

In the past attribute routing had one kind of precedence, which was the same as what we call 'inbound precedence'. It usually did the wrong thing for URL generation, which is why we came up with a different algorithm for URL generation.

**Comment by rynowak** [comment] 2017-04-04 02:11
```[HttpPost] // This works```

Hmm.. Now **that** might be a bug. Does it generate the URL `/`?

/cc @Eilon - it's worth looking into this. The code in `RoutePrecedence` likely doesn't do the right thing when we have an empty route template.

**Comment by rynowak** [comment] 2017-06-19 08:46
@eilon - we should look at this one for 2.0.0

**Comment by Eilon** [comment] 2017-06-22 19:49
@SteveSandersonMS - can you take a look?

**Comment by SteveSandersonMS** [comment] 2017-06-23 13:38
@rynowak Could you clarify why you think this might be a bug? I might be missing something about the intended design, but the current behaviour does seem reasonable to me.

> [HttpPost] // This works
> Hmm.. Now that might be a bug. Does it generate the URL /?

No, the `asp-action="Edit"` on the `<form>` generates the URL `/Customer/Edit/1`, because the route values match the template on `[HttpGet("Customer/Edit/{id:int}")]` and it doesn't filter by HTTP method. Also if you have the default route `"{controller=Home}/{action=Index}/{id?}"` this makes no difference because whichever route matched, it would produce the same URL outbound.

Then when you submit the form and the browser does a POST to `/Customer/Edit/1`, the result is:

 * If you **don't** have the default route `"{controller=Home}/{action=Index}/{id?}"`, then the only matching route is the `[HttpGet("Customer/Edit/{id:int}")]` one, but that action doesn't accept POST, so we serve a 404 as expected
 * If you **do** have the default route, then the default route will match inbound, and passes the request to the one action satisfying `controller=Customer`, `action=Edit` that also accepts POST, so we run that action and serve its 302 redirection as expected.

So my guess is that this is all as expected, and the only reason for the uncertainty above was the unclarity about whether there's also a default route or not. In @jhigh2000's case, there must have been a default route in order to see the behaviour that they did. But perhaps @rynowak thought this was behaving wrongly because he was describing the expected behaviour for the `[HttpGet("Customer/Edit/{id:int}")]` route alone with no default route.

Or @rynowak am I misinterpreting your concern entirely? Is there something specifically about route precedence that seems wrong here?

**Comment by jhigh2000** [comment] 2017-06-23 14:01
@SteveSandersonMS I can confirm that the File...New Project minimal repro as described above did indeed have the default route in Startup.cs:

![image](https://user-images.githubusercontent.com/138398/27485112-16e4ad2a-57f1-11e7-8c09-2ef687e8098b.png)

I guess I'm still not sure *why* the behavior changed between between MVC5 and MVC6.  Specifically,

```
[HttpGet("Customer/Edit/{id}")]

// matches in MVC5, does not match in MVC6 (404)
[HttpPost("Customer/Edit")]  
```

But given that the behavior did change, what is the recommended/idiomatic attribute route for the matching HttpPost for this type of scenario?

**Comment by rynowak** [comment] 2017-06-23 21:04
> Could you clarify why you think this might be a bug? I might be missing something about the intended design, but the current behaviour does seem reasonable to me.

I wasn't aware that conventional routing was involved. Mixing attribute routing and conventional routing is the same application is going to require some care.

**Comment by SteveSandersonMS** [comment] 2017-06-26 08:34
@rynowak Are you saying then that you agree the described behaviour is correct based on the info we now have, or are you still concerned that there's a bug? (And if so, could you clarify what specifically you think is wrong?)

**Comment by rynowak** [comment] 2017-06-26 11:58
I don't think this is a bug, I had no idea conventional routing was in the picture.

I think I was on mobile when I replied last time, sorry for not being clear, duh-doi.

---------

> But given that the behavior did change, what is the recommended/idiomatic attribute route for the matching HttpPost for this type of scenario?

I'd recommend first using either attribute routing (the attributes) *or* using conventional routing `routes.MapRoute`. If you're using one you don't need the other, and I think it will just add to your confusion.

The idiomatic way to do this is to match `Customer/Edit/{id}` (attribute routing or `{controller}{action}/{id?}` (conventional routing.

Everything you're saying is expected, so I still stand by [my advice from before](https://github.com/aspnet/Mvc/issues/6066#issuecomment-291350705).

**Comment by SteveSandersonMS** [comment] 2017-06-26 12:20
Thanks @rynowak. Sounds like we're OK here then. Closing.

**Closed by SteveSandersonMS** 2017-06-26 12:20 UTC
Labels: 1 - Ready, bug

**Comment by MikePerholtz** [comment] 2017-06-27 11:17
I ran into this same problem when following Sean Wildermuth's Pluralsight course on .net core 1.0 which I started in VS2015 and eventually ported over to VS2017, but kept the 1.0 framework.

Coding along side the course ,which used a single basic conventional route inside startup.cs,  I progressed to the part where a single [httppost] attribute  (no other parameters) was attached to one of the (contact) controller methods.  This caused the route to break, where the basic (Contact )  page would not even load up '404'.

For accuracy, I matched every line of code to that of the course and re-checked it five ways to Kansas.  I tried upgrading all dependencies (still inside VS2017) to core 1.1.  Then I tried porting over to the core 2.0 preview, but the route was still broken.  If I could spare another two hours I would rebuild it all back in 2015 and see if the route worked like it did on Shawn M.'s machine.
