### ISSUE TITLE
InputTagHelper generates text input for decimals and doubles

### ISSUE THREAD

**Issue by andrewlock** [aspnet/Mvc#6024] opened 2017-03-25 14:08 UTC
I suspect this is by design, but I can't see any issues about it. 

Why does the input tag helper generate an `input` with `type="text"` for `decimal` and `double` properties? I would expect it to generate a `type="number"` , given that `double` and `float` do so. Instead, it generates a text field with unobtrusive validation attributes. Is this related to culture differences?

For example, 
```C#
    public class ViewModel
    {
        public double Quantity { get; set; }
        public decimal Price { get; set; }
    }
```

```HTML
@model ViewModel

<input asp-for="Quantity"  />
<input asp-for="Price" />
```

Generates
```HTML
<input type="text" data-val="true" data-val-number="The field Quantity must be a number." data-val-required="The Quantity field is required." id="Quantity" name="Quantity" value="0">
<input type="text" data-val="true" data-val-number="The field Price must be a number." data-val-required="The Price field is required." id="Price" name="Price" value="0.00">
```

where I would expect
```HTML
<input type="number"  id="Quantity" name="Quantity" value="0">
<input type="number"  id="Price" name="Price" value="0">
```

Thanks

**Comment by Muchiachio** [comment] 2017-03-25 15:56
The issue is that you can't enter a decimal number in an input with a type `number`, unless you specify a correct step interval, because default one is 1 (integer). Also it breaks application globalization, by not allowing commas, spaces or other special symbols based on browser's locale. Even though they can be used in some languages.

**Comment by frankabbruzzese** [comment] 2017-03-26 09:31
The main reason is input type number send its input to the server in international format, while accepting input in the browser locale. On the other side if browser doesn't support input type number the input behaves like a text input. As a conclusion since the model binder has non infos about browser support it wouldnt able to deserialize the number. Obviously the problem exists just for decimal/float since for integer numbers international and locale format are the same.

If you would like to change the default behavior, solution is: sending infos on browser support to model binde(in hidden field or cookie)r, writing a custom binder for simple types, and then writing a tag helper that modifies input fields rendering.

**Comment by andrewlock** [comment] 2017-03-26 16:46
Thanks both, that all makes sense, and was as I feared - primarily locale related.

However, it feels like this is something which is going to be a very common problem for people. Surely, wanting to have decimal number inputs is going to be a requirement for a vast number of people - any eCommerce application? I realise it can be handled at the validation level,  but having number fields actually have `type="number"` is especially useful on mobile, where it changes the keyboard etc.

Having to know about the browser locale does sound horrible, so I understand not supporting it, but it seems like that means people are kind of left to themselves to try and implement it (or more likely, just set `type="number"`` directly on the input, thereby breaking in the scenario described).

I wonder if it would be worthwhile to have this functionality baked in somewhere. Based on your solution, I guess this might not really be possible, but I think it would be very desirable...

**Comment by ctolkien** [comment] 2017-03-26 23:27
Chrome seems to be the only browser that handles this "correctly". In my testing on Win10:

* Chrome57 will accept an intl. number format and render with the current users locale.
* Edge14 will accept a intl. number format, render with the intl. format but prevent submitting forms due to validation.
* Firefox50 seems to completely ignore the OS's specified decimal separator and use intl. format only.
![image](https://cloud.githubusercontent.com/assets/515955/24336268/b5a4d516-12d7-11e7-87c5-c617874018e1.png)


http://codepen.io/ctolkien/pen/EWpJeR

**Comment by frankabbruzzese** [comment] 2017-03-27 09:24
@andrewlock ,
if you work with the english locale you should have no problems, just force type='number' in your view, or write a simple taghelper that executes before the built-in one, that sets  type='number' for decimals, floats and doubles.

In case of other culture you may use the [Mvc Controls Toolkit](http://examples.aspnetcore.mvc-controls.com/InputExamples/Number) (I am the author of). It do all needed stuffs: communicate browser infos to the model binder, if browsers do not support an Html5 input it falls back on a bootstrap widgets, and provide also client side localized validation. It uses the last version of the Globalize lbrary, and other js stuffs, so it is not a "lightweight solution", but no lighttweight solution is possible (with current browser support). It contains also other controls, but if you are interested just to Html5 inputs you may choose the "partial installation" at the end of the [installation documentation page](http://documentation.aspnetcore.mvc-controls.com/QuickStart/Installation).

**Comment by andrewlock** [comment] 2017-03-27 18:29
Thanks, yeah just specifying `type="number"` is the route I've been taking, and thanks very much for the Mvc Controls Toolkit! 

I think we can probably close this now - until browser support is better, there's not a better option. Thanks everyone.

**Comment by rynowak** [comment] 2017-07-17 06:38
Closing this since you're happy with the outcome

**Closed by rynowak** 2017-07-17 06:38 UTC

**Comment by veikkoeeva** [comment] 2018-07-22 20:15
I'll link this to https://github.com/aspnet/Mvc/issues/6024 as they're related and I found the threads supplemented each other on what comes to my understanding of the issue.
