### ISSUE TITLE
In default project, updating Microsoft.AspNetCore.Mvc.Core to 1.1.0 takes compilation time from ~1 second to ~6 seconds each and every time

### ISSUE THREAD

**Issue by havremunken** [aspnet/Mvc#5619] opened 2016-12-17 18:35 UTC
I started a new Web API project, with just a single controller for now, and it compiled quickly and all was well. I did check the NuGet package updates and noticed that there were quite a few updates since creating the project from template. After updating, the compile time for the project (no other changes made) increased by 5 seconds, and now takes a little more than 6 seconds no matter how many or few changes are made. 

This is on a relatively new PC, fast CPU, 32GB RAM, SSD etc.

Steps to reproduce:

1. In Visual Studio 2015 (up to date), create a new project (brand new solution). Go with an "ASP.NET Core Web Application (.NET Core). I chose not to add Application Insights, and went with Visual C#. In the template window, I went with "Web API", No Authentication and did not check to Host in the cloud.

2. Once the new project is created and packages restored, press F6 to compile. On my PC, the time reported is always at 00:00:01.0xxxx - so a tad more than a second. I also do some "phantom changes" to the source code (inserting a space and deleting it again) and recompiling again, the time takes is always pretty much in the same ballpark.

3. Manage NuGet packages for the project, go to Updates - at the time of writing, there are 12 updates to be had. At the top of the list is Microsoft.AspNetCore.Mvc. Update this package, and optionally Microsoft.AspNetCore.Routing (which is probably a good idea, it does matter a little to the issue of compilation time).

4. Recompile the project. The compilation time is now always at least 00:00:06.1xxxx on my PC.

If I choose not to upgrade the routing package in step 3 (which might lead to unexpected behavior for all I know), compilation time seems to stay around 5.9 seconds.

I have reproduced this in three projects now, and if this somehow does not happen to anyone else, I am of course willing to do any tested desired to figure out what happens.

Thanks!

**Comment by Eilon** [comment] 2016-12-20 23:02
Super duper weird. I was able to reproduce this on my laptop (not the same timing, but approximately the same scale: from ~2sec on 1.0.0, to about ~11sec on 1.1.0).

It's worth noting that it is not supported to mix & match versions - you have to update all your packages to 1.1.0 (except for NETCore.App, which is at 1.0.1). But even with that change, I still encountered the issue.

I'm moving this to the CLI repo, which is where the compilation magic happens.

**Comment by Eilon** [comment] 2016-12-20 23:03
This issue was moved to dotnet/cli#5107

**Closed by Eilon** 2016-12-20 23:03 UTC
