### ISSUE TITLE
Remove MVC.DNX

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#4525] opened 2016-04-23 20:54 UTC
It doesn't work anymore.

/cc @Eilon @DamianEdwards  RC2

**Comment by javiercn** [comment] 2016-04-23 22:13
I had a PR out for it, ir you guys give the ok, I'll update it and merge it.

**Comment by davidfowl** [comment] 2016-04-23 23:11
@javiercn where is it

**Comment by javiercn** [comment] 2016-04-27 20:03
https://github.com/aspnet/Mvc/pull/4379

**Comment by Eilon** [comment] 2016-05-02 16:47
Ok I give up, let's do this for RC2.

**Comment by javiercn** [comment] 2016-05-02 18:18
Closing this one as it's a dupe of https://github.com/aspnet/mvc/issues/4187

**Closed** 2016-05-02 19:27 UTC
Labels: 2 - Working, task

**Comment by javiercn** [comment] 2016-05-02 19:29
059ec0f3531cbbd04258c6ea5b4951ca27eecc92
