### ISSUE TITLE
Adding @using in _GlobalImports shows squigglies in VS

### ISSUE THREAD

**Issue by rustd** [aspnet/Mvc#2271] opened 2015-03-25 18:34 UTC
I have the following in _GlobalImports.cshtml
```C#
@using NoAut
@using Microsoft.Framework.OptionsModel
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
```

In my View I am using it as 
```C#
@inject IOptions<AppSettings> AppSettings
```

In VS I get squiggles in my Views. It works at runtime. Chatted with Taylor and he will look into this

**Comment by NTaylorMullen** [comment] 2015-03-25 19:56
/cc @danroth27 @Eilon @DamianEdwards Found why this is happening. It's an easy fix and is ultimately caused by the same issue that resulted in the directives `@tagHelperPrefix`, `@addTagHelper` and `@removeTagHelper` no longer working in `_GloblImport.cshtml` during design time: just need to apply the fix in an additional location. 

I'd love to get this one into release - super low impact since it only affects tooling.

**Comment by NTaylorMullen** [comment] 2015-03-25 22:39
Super quick fix to this out for PR now: assigned to beta5, feel free to move milestone if you decide there's enough value in getting it into beta4.

**Comment by Eilon** [comment] 2015-03-26 00:19
Clearing the milestone so we can triage in the morning.

**Comment by NTaylorMullen** [comment] 2015-03-26 22:08
9402f1485ccc245f874d5d530f8c8a1ad54f3ced

**Closed by NTaylorMullen** 2015-03-26 22:08 UTC
Labels: 3 - Done, bug
