### ISSUE TITLE
Consider only monitoring Views folder for `_ViewImports.cshtml` files.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#4605] opened 2016-05-09 22:27 UTC
We currently monitor the root of a users project which ends up triggering OS level file watcher events during restore for things like node_modules. In some cases, even [crashing VS](https://github.com/aspnet/FileSystem/issues/187).

I don't see a whole lot of value in monitoring everything outside of the `Views` folder. I wont make a perf argument since I haven't profiled; however, not monitoring/receiving events for the 1800 files in node_modules alone is bound to increase performance.

/cc @sebastienros since I know he had some different scenarios in Orchard where _ViewImports weren't always in the Views folder.

**Comment by pranavkm** [comment] 2016-05-09 22:54
The other alternative is to poll for individual file change notifications (i.e. use `PollingFileChangeToken`) instead of using the file watcher.

**Comment by nil4** [comment] 2016-05-09 23:02
Would this remove the ability to have [a folder-per-feature structure](https://scottsauber.com/2016/04/25/feature-folder-structure-in-asp-net-core/) as mentioned in the last community standup (the second [Link of the Week](https://blogs.msdn.microsoft.com/webdev/2016/05/09/notes-from-the-asp-net-community-standup-may-3-2016/))? Do you envisage a way to opt-out of this approach? 

I see a lot of value in having the flexibility to group together views with their related code, be it controllers, models or client-side components (e.g. TypeScript/Javascript/CSS files).

**Comment by dougbu** [comment] 2016-05-09 23:37
Have to be careful if we go the "only monitoring Views folder" route because areas.

Would a watcher pattern like `**/*.cshtml` do the Right Thing<sup>:tm:</sup>?

**Comment by scottsauber** [comment] 2016-05-10 02:41
+1 for not breaking feature folder structures or the like (not 100% sure if this would, but seems like it would). 

My blog post got thousands of hits after being on the stand up and the www.asp.net site.  I've never written a blog post before and have no following on Twitter or anything, so people were simply interested in the topic.  So what I'm trying to say is - this seems to be important to people.

**Comment by Eilon** [comment] 2016-05-10 17:00
Yeah the problem is that there's no single "Views" folder... I'm not sure how we can safely do this change.

**Comment by Eilon** [comment] 2016-05-10 17:02
Perhaps, if anything, if performance is a real concern then we could have a Views-exclude list where you could exclude `./node_modules`, `wwwroot`, etc.

But the real question is: what's the actual problem we're trying to solve? If we don't know of any specific perf concern, how do we know there's even a problem?

**Comment by NTaylorMullen** [comment] 2016-05-10 17:10
@Eilon I filed this issue after seeing races caused by monitoring node_modules [here](https://github.com/aspnet/FileSystem/issues/187#issuecomment-218023271).

**Comment by ShadowDancer** [comment] 2016-06-09 11:49
On my machine there are serious performance issues when touching solution explorer in xproj projects.

**Comment by pranavkm** [comment] 2016-06-09 16:43
@ShadowDancer is this with projects containing a large number of cshtml views \ node_modules?

**Comment by ShadowDancer** [comment] 2016-06-09 19:50
@pranavkm Yes. Npm and bower especially. I moved bower_components out of project directory (with .bowerrc) and it helps a bit.

**Comment by Eilon** [comment] 2016-09-29 06:03
@pranavkm assigning to you as part of the various other file monitoring stuff you're looking at. Not sure exactly what we should do here.

**Comment by pranavkm** [comment] 2016-09-29 19:20
There's two levels of file watching involved with Razor views

1. The ViewEngine track view files at runtime to determine files that need to be recompiled. 
2. The RazorHost tracks _ViewImports both at design time and runtime to determine if it needs to reparse these files to gather Razor directives. This is primarily a design time focused cache to prevent additional parsing work on every key stroke.

Using the FSW in the first scenario is likely the better solution in particular when the application is deployed and files don't change frequently. Polling might be better in the latter scenario since it means we wouldn't need to filter cshtml specific changes from the slew of unrelated editing activity and don't have to harden against failures in the FSW's event handlers.

**Comment by Eilon** [comment] 2017-03-22 21:42
@pranavkm @rynowak any more recent thoughts on this?

**Comment by pranavkm** [comment] 2017-03-22 21:54
This work item was motivated by VS issues, but a lot of it is likely to change when we start using the Razor VSIX for tooling. IMO, we can revive this if we start seeing issues with large applications using the vsix.

**Comment by Eilon** [comment] 2017-03-22 22:53
So close this for now?

**Comment by rynowak** [comment] 2017-05-30 18:46
I don't think there's anything to do here so closing. The Razor tooling doesn't use a file watcher, it talks to VS project system.

**Closed by rynowak** 2017-05-30 18:46 UTC
Labels: investigate
