### ISSUE TITLE
I can't get RawUrl.  Request.GetDisplayUrl & Request.Path is bad, any method(I can't find) 

### ISSUE THREAD

**Issue by plosft** [aspnet/Mvc#6892] opened 2017-09-28 09:04 UTC
My request original url: 
http://localhost/2http%3A%2F%2Flocalhost%3A803%2Fhomepage%2F3%2FSignup%3FM49HD59E

RawUrl & Request.GetDisplayUrl & context.Features.Get<IHttpRequestFeature>().RawTarget %2F%2F miss one '/', not is http://(is http:/)

after one day, i can't find  any method. 

follow is good
1:  /2http://localhost:803/homepage/..... 
2:  /2http%3A%2F%2Flocalhost%3A803%2Fhomepage%2F.....

asp.net core 2.0

**Comment by davidfowl** [comment] 2017-09-28 10:51
What are you trying to do?

**Comment by plosft** [comment] 2017-09-28 14:20
I want to create a Web site that can accept any text and generate a QR. I hope it can accept a URL, but I use ASP. NET Core 2.0 is not possible, because when there are 2 escaping '/', you will miss 1 '/'. I want to get the original URI of the escape.

**Comment by khellang** [comment] 2017-09-28 19:38
`context.Features.Get<IHttpRequestFeature>().RawTarget`?

**Comment by plosft** [comment] 2017-09-29 05:53
context.Features.Get<IHttpRequestFeature>().RawTarget is bad too.

**Comment by rynowak** [comment] 2017-09-29 08:43
> (I don't want to use querystring.) 

You're pretty much guaranteed to have issues trying to encode a URL as a path segment.

If you're running behind IIS in this case, I'll bet that's what's munging the path. Different servers have different quirks for this sort of thing.

@Tratcher is the expert on this.

What's your reason for not wanting to use the query string?

**Comment by Tratcher** [comment] 2017-09-29 11:52
Yes, sounds like a known iis/http.sys behaviour. Have you tried running kestrel without IIS?

**Comment by plosft** [comment] 2017-09-30 00:28
thank you, Tratcher. You are right. I use kestrel without IIS, no issue.  @Tratcher

**Comment by Tratcher** [comment] 2017-09-30 00:44
HttpSysServer may also work for you as it uses the raw url to work around the unescaping caused by Http.Sys. In the IIS+Kestrel scenario this isn't possible today because the raw url is lost when proxying to Kestrel.

**Comment by plosft** [comment] 2017-09-30 00:49
Thanks for the response! @rynowak , everyone.

For compatibility reasons. I want to migrate existing project to ASP. NET Core 2.0.
I don't use querystring because I have been using .net framework/iis to do the same thing, and many existing projects depend on it.

**Comment by Eilon** [comment] 2017-11-07 18:59
@Tratcher where should this bug ultimately go? I just want to make sure it's in the right repo, even if we end up just closing it.

**Comment by Tratcher** [comment] 2017-11-07 19:29
Close, this is an IIS issue. We've dealt with it the best we can in the individual servers.

**Closed** 2017-11-07 20:58 UTC
