### ISSUE TITLE
About  Routing  match double slash

### ISSUE THREAD

**Issue by zuosc** [aspnet/Mvc#7849] opened 2018-06-01 08:45 UTC
#### Is this a Bug or Feature request?:

Maybe  it‘s a Feature ~

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):

Same with this  question：  https://stackoverflow.com/questions/50248828/asp-net-core-attribute-routing-and-double-forward-slash?rq=1

#### Description of the problem:
Same as above

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.8" />
<TargetFramework>netcoreapp2.0</TargetFramework>

**Comment by mkArtakMSFT** [comment] 2018-06-01 16:51
Thank you for your feedback.
We're closing this issue as the behavior discussed seems to be by design.

**Closed by mkArtakMSFT** 2018-06-01 16:51 UTC
