### ISSUE TITLE
Integration testing SignOutAsync problem?

### ISSUE THREAD

**Issue by Tealons** [aspnet/Mvc#8021] opened 2018-07-06 13:51 UTC
I have enabled integration testing according to the following docs: [https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1)

Now I want to simulate logging out of the application. The test looks like this:

```
[Fact, TestPriority(3)]
public async Task LogoutFromApplication()
{
        var defaultPage = await _client.GetAsync("/");
        IHtmlDocument responseContent = await HtmlHelpers.GetDocumentAsync(defaultPage);

        var response = await _client.SendAsync(
            (IHtmlFormElement)responseContent.QuerySelector("form[id='logout_form']"));
        var body = await response.Content.ReadAsStringAsync();
}
```

And the logout method like this: 

  ```
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Logout()
{
       await _signInManager.SignOutAsync();
       _logger.LogInformation(4, "User logged out.");
       return RedirectToAction(nameof(HomeController.Index), "Home");
}
```

In the application startup.cs we have the following policy:

```
 services.AddMvc(config =>
            {
                var policy = new AuthorizationPolicyBuilder(JwtBearerDefaults.AuthenticationScheme, IdentityConstants.ApplicationScheme)
                    .RequireAuthenticatedUser()
                    .Build();
                config.Filters.Add(new AuthorizeFilter(policy));
            });
```

The logout method is hit by the test, but the redirect does not cause the login screen to appear, which should because of the mvc policy in our startup.cs.  Instead the normal index page is shown. It looks like the identity cookie is not removed from the client. Does anyone know what is happening here? Or am I missing something completely?

**Comment by mkArtakMSFT** [comment] 2018-07-06 16:04
Thank you for filing this issue. In order for us to investigate this issue, could you please provide a minimalistic repro project that illustrates the problem you're facing?

**Comment by Tealons** [comment] 2018-07-07 19:07
I just created a new project and uploaded the source code: [https://github.com/Tealons/ExampleLogoutTest](https://github.com/Tealons/ExampleLogoutTest)

Steps to reproduce the problem:

1. Build the web application and register an account.
2. Change the username and password in LoginTest.cs to the one just created
3. Run the tests. Test 3 (LogoutFromApplication) should succeed, but it fails....

Please let me know if you need any more information. Thanks for your help!

**Comment by mkArtakMSFT** [comment] 2018-07-09 17:04
Thanks @Tealons.
@javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment] 2018-07-09 19:48
Hi @Tealons thanks for contacting us.

The client created with CreateClient follows redirects and handles cookies automatically. What you are seeing is most likely caused by the fact that the action is producing a redirect and the client is automatically following it.

You can set `ClientOptions.AllowAutomaticRedirects = false` in your custom `WebApplicationFactory` to avoid this behavior and you should see the redirects. Let us know if that is not the case.

Closing this as no further action is needed.

**Comment by Tealons** [comment] 2018-07-09 20:42
@javiercn @mkArtakMSFT : I tried the ClientOptions.AllowAutomaticRedirects = false option, but that just breaks all the tests. I'm testing real application behavior and having redirects is pretty normal when you have a MVC authorization policy...

Honestly, I have the feeling that the client is not destroying the identity cookies because of the redirect. Can something like that be the case?

**Comment by javiercn** [comment] 2018-07-09 20:55
@Tealons I'm looking at it. I saw that your tests were pretty standard, so I assumed the automatic redirects were the cause.

**Comment by javiercn** [comment] 2018-07-09 21:07
@Tealons I took a second look. It seems like the issue is with the second test. The user needs to be registered before you can log in and the password that you are using is not actually valid. I would suggest that you check for the user name in the page to see if there is a valid user logged in.

You can inspect the cookies through looking inside the HttpClient instance within the _client or by creating your own custom client by calling CreateDefaultClient and setting up the httpmessagehandlers yourself as in https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Testing/WebApplicationFactoryClientOptions.cs#L70 (You can provide a cookie container to the handler to inspect the cookies more easily)

**Comment by javiercn** [comment] 2018-07-09 21:08
@Tealons Additionally, what you are trying to do is something like https://github.com/aspnet/Identity/blob/master/test/Identity.FunctionalTests/LoginTests.cs#L27

**Comment by Tealons** [comment] 2018-07-10 08:08
@javiercn I think you missed my instructions for reproducing the problem :) 
Test 2 fails indeed if you do not register an account and change the credentials in test 2.  I did not post the database with the code because I thought that doing a quick setup would be faster.

So after your hint about the cookies, I did some extra research and found that the identity cookie is destroyed properly as you can see in the screenshots of the cookies in test 2 and 3: 

**Test 2:**
![image](https://user-images.githubusercontent.com/7141563/42496461-68613576-8426-11e8-98c9-ae5d0d1fb40d.png)

**Test 3:**
![image](https://user-images.githubusercontent.com/7141563/42496466-6fd50ba2-8426-11e8-929e-53a4305d997e.png)

During debugging I noticed that somehow the MVC policy is not applied when you logout with the _client. In the example repo the user is redirected to the login page, while the _client is just shown the index page. Somehow the client is treated differently than the normal user of the portal? I have no idea where this behavior comes from...

Btw, in the link to the example tests, not a single test is about logging out... 
I would do more debugging if I could. I think this is a middleware problem? I have no idea how I can debug that part of the application.

**Comment by javiercn** [comment] 2018-07-10 18:07
@Tealons Thanks for the thorough response. I've missed that. I'll take another look at the area and see what's going on.

**Comment by javiercn** [comment] 2018-07-19 17:45
@Tealons I've been on vacation. I'm still looking into this.

**Comment by Tealons** [comment] 2018-07-19 20:00
@javiercn No problem! I'm already happy that you are willing to help me.

**Comment by javiercn** [comment] 2018-08-21 23:42
@Tealons Sorry for the late response.

I've dug in and found the actual issue. It's an integration issue between the redirect handler and the cookie container handler. In essence the issue is as follows:
The redirect handler copies the body of the request but not the headers.
The cookie handler adds the appropriate cookies to the request (modifying the headers)
The request is sent and comes back as a redirect
The redirect handler says its a redirect and just emits a new request to the response location (using the modified headers in the request, including the old cookie)
That's why you are seeing the difference between F5 and running the integration test.

I'm working out a fix for this.

**Closed** 2018-08-23 23:47 UTC
Labels: 2 - Working, PRI: 1 - Required, bug

**Comment by Tealons** [comment] 2018-08-29 21:28
@javiercn Sorry for my late reply. I was a little busy the past few days with the birth of my daughter :)
Great to hear that you fixed the issue. I'm going to test it when things get normal again and I can get a normal night of sleep. However, I'm not doubting that your fix will work!

Thanks again!
