### ISSUE TITLE
routeOptions.LowercaseUrls  does not support area

### ISSUE THREAD

**Issue by emailtowalter** [aspnet/Mvc#5072] opened 2016-07-25 01:51 UTC
Hi... when I use area in MVC, routeOptions.LowercaseUrls =true seems do not change the area casing. 

i.e. \Areas\Feature1\Controllers... I have to type //domain/Feature1/... 

Bug?

**Comment by Eilon** [comment] 2016-07-25 16:51
@javiercn can you investigate?

**Comment by ctolkien** [comment] 2016-07-26 00:23
Am not able to reproduce.

Given:
```HTML
<a asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
```

Produces:

```HTML
<a href="/Admin/Products">Products</a>
```

After configuring:

```csharp
services.Configure<RouteOptions>(opts =>
{
    opts.LowercaseUrls = true;
});
```

Produces:
```HTML
<a href="/admin/products">Products</a>
```

Unless OP @emailtowalter  isn't referring to URL generation?

**Comment by Eilon** [comment] 2016-07-26 00:36
Yeah I wouldn't expect this to reproduce. Routing doesn't know anything about areas, so I don't see how it could possibly affect it...

**Comment by emailtowalter** [comment] 2016-07-26 01:49
I was not clear. It is NOT about URL generation, but the routing. I deploy .net core on Cloud foundry (linux) where is case sensitive for the URL ( unlike windows platform). 

I found that controller and view do not care about casing with opts.LowercaseUrls = true; But area still case sensitive. I guess Eilon pointed out that area is not in the routing scope. 

Anyway, thought it would be nice to include area in the scope.

**Comment by Eilon** [comment] 2016-07-26 04:29
@emailtowalter thanks for the extra info. The `routeOptions.LowercaseUrls` option just tells ASP.NET Core's Routing system to always *generate* URLs in all-lowercase. It doesn't affect matching incoming request URLs.

Can you explain what you mean by "area still case sensitive"?

**Comment by javiercn** [comment] 2016-07-26 23:25
I can't repro this behavior:
```C#
    [Area("MyArea")]
    public class HomeController : Controller
    {
        [HttpGet("[area]")]
        public IActionResult Something()
        {
            return Content("Works!");
        }
    }
```
Both /MyArea and /myarea work and route as expected.

**Comment by javiercn** [comment] 2016-07-28 18:15
Closing for now as we couldn't reproduce the issue. Feel free to provide more information or a repro project and reopen the issue if you are still running into it.

**Closed by javiercn** 2016-07-28 18:15 UTC
Labels: no repro
