### ISSUE TITLE
TagBuilder fail with NPE if attribute have null value 

### ISSUE THREAD

**Issue by justdmitry** [aspnet/Mvc#4710] opened 2016-05-22 23:34 UTC
Sample .cshtml code:

```
<html><body>
    @{
        var tb = new TagBuilder("span");
        tb.Attributes.Add("dummy", null);
        tb.InnerHtml.Append("Hello, World!");
    }
    @tb
</body></html>
```

This tag builder will fail with `NullPointerException` while rendering with stacktrace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.Rendering.TagBuilder.AppendAttributes(TextWriter writer, HtmlEncoder encoder)
   at Microsoft.AspNetCore.Mvc.Rendering.TagBuilder.WriteTo(TextWriter writer, HtmlEncoder encoder)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBuffer.<WriteToAsync>d__18.MoveNext()
```

Tested on `Microsoft.AspNetCore.Mvc 1.0.0-rc2-final`.

Investigation: 

[Line 208 of TagBuilder.AppendAttributes](https://github.com/aspnet/Mvc/blob/1.0.0-rc2/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Rendering/TagBuilder.cs#L208) calls for `HtmlEncoder.Encode(writer, attribute.Value)`.

But `TextEncoder.Encode(TextWriter output, string value)` is [overload](https://github.com/dotnet/corefx/blob/v1.0.0-rc2/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/TextEncoder.cs#L211), requesting `value.Length`.

**Comment by Eilon** [comment] 2016-05-23 04:10
Good find! The workaround seems like it would be to just pass in `string.Empty` or `""` in the meantime.

**Comment by ctyar** [comment] 2016-05-23 07:26
if these behaviors are ok, I can send a PR 
```
tagBuilder.Attributes.Add("attribute", "value")
<p attribute="HtmlEncode[[value]]"></p>

tagBuilder.Attributes.Add("attribute", null)
<p attribute></p>

tagBuilder.Attributes.Add("attribute", string.Empty)
<p attribute=""></p>
```

**Comment by justdmitry** [comment] 2016-05-23 09:05
Issue #4078 says:

> In any case TagBuilder does not support minimized attributes, sorts the generated attributes alphabetically by name, and more.

Is this "by design" or not?

**Comment by dougbu** [comment] 2016-05-23 16:32
> Is this (not support minimized attributes) "by design" or not?

All of the quoted points are by design. `TagBuilder` is intended for C# helpers that create entire HTML elements. And it has generated XHTML-compliant syntax forever.

> ```
tagBuilder.Attributes.Add("attribute", null)
<p attribute></p>
```

This is incorrect and not aligned with the rest of the `TagBuilder` class. A minimized attribute is shorthand for `attribute="attribute"` and not `attribute="@null"`. The generated HTML in this case should be identical to that for `tagBuilder.Attributes.Add("attribute", string.Empty)`.

**Comment by Eilon** [comment] 2016-05-23 16:47
@ctyar yes that behavior is by design.

I think a point of comparison is to see what ASP.NET MVC 5.x did, and replicate that behavior.

**Comment by Eilon** [comment] 2016-05-23 17:11
Looks like in MVC 5.x a `null` was treated the same as `""`, which is to render an empty quoted value.

I.e. this:

```c#
    var x = new TagBuilder("myTag");
    x.Attributes["x"] = "v";
    x.Attributes["y"] = "";
    x.Attributes["z"] = null;
```

Renders this:

```html
<myTag x="v" y="" z=""></myTag>
```

So let's preserve that behavior.

**Comment by pranavkm** [comment] 2016-05-26 23:06
Fixed in https://github.com/aspnet/Mvc/commit/42dd4499e0ba395d1ec45ddc549402c9c199b59f.

**Closed by pranavkm** 2016-05-26 23:06 UTC
Labels: 3 - Done, bug, up-for-grabs
