### ISSUE TITLE
BodyModelBinder does not respect ModelMetadata.ConvertEmptyStringToNull property

### ISSUE THREAD

**Issue by nenadvicentic** [aspnet/Mvc#8092] opened 2018-07-16 11:51 UTC
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
(general case, see description bellow)

#### Description of the problem:
If JSON with empty string value is sent to the server, for example:
```
{
    value: 54,
    description: ""
}
```
`BodyModelBinder` will not respect `ModelMetadata.ConvertEmptyStringToNull` property, which is by default `true` and it fills `Description` property with "". This in turn creates problem with validation. For example:

```
public class Item
{
    public int Value { get; set; }

    [StringLength(50, MinimumLength = 3)]
    public string Description { get; set; }
}

```
Even though `Description` property is not required, empty string will always trigger validation.
This is in contract to behavior of `DefaultModelBinder`, which in turn uses `SimpleModelBinder` when posting data to the client as a form. In this case `ModelMetadata.ConvertEmptyStringToNull` defaults to true and is always respected.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.1

**Comment by mkArtakMSFT** [comment] 2018-07-16 16:47
Thanks for contacting us, @nenadvicentic.
@dougbu, can you please look into this? Thanks

**Comment by dougbu** [comment] 2018-07-16 21:21
@nenadvicentic thank you for your feedback. We're closing this issue as the behaviour discussed is by design.

The `BodyModelBinder` marks a transition from model binding (where `ConvertEmptyStringToNull` matters) to input formatting (where the setting is ignored). In this case, input conversions are the responsibility of the serializer and that's a `JsonSerializer`. Json.NET has no similar setting but you may be able to do something similar using a [`JsonConverter`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonConverter.htm`) for `string`s.

**Closed by dougbu** 2018-07-16 21:21 UTC
Labels: investigate

**Comment by nenadvicentic** [comment] 2018-07-16 23:01
@dougbu `BodyModelBinder` is used for the exactly same scenario as default form binder. That is - to send user input data to the server, where it should be validated. It is just that `BodyModelBinder` is suited better for single page applications and JSON format.

Now we have situation that changing of input format (JSON vs form-data) affects behavior of input model validation. I don't understand what kind of transition this is?

Regarding alternatives, I tried both MVC configuration with `AddJsonOptions` and later implementing custom `JsonConveter`. Simple implementation easily breaks things down the chain and, on top of that, this is solution for one specific formatter.

If I render same model later using different formatting (in my case razor HTML), I have to maintain different set of formatting attributes on the model for different formats.

I wonder what were pros for this design decision?

**Comment by dougbu** [comment] 2018-07-16 23:11
@nenadvicentic to be clear: Input formatting in legacy ASP.NET was almost completely separate from model binding. We integrated them to some extent in ASP.NET Core. But, the controlling settings remain completely separate.

**Comment by nenadvicentic** [comment] 2018-07-17 07:44
@dougbu OK, I get it. It's completely different deserialization code path.

I just think you should have at least provided same defaults for both formats, since use case is most of the times identical (send input data to server, bind it to the model and validate).

I managed to find relatively simple workaround, after looking a bit more through JSON.NET source code:

```
    public class EmptyStringToNullJsonConverter : JsonConverter
    {
        public override bool CanRead => true;
        public override bool CanWrite => false;

        public override bool CanConvert(Type objectType)
        {
            return typeof(string) == objectType;
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            string value = (string)reader.Value;
            return string.IsNullOrWhiteSpace(value) ? null : value.Trim();
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new NotImplementedException("Unnecessary because CanWrite is false. The type will skip the converter.");
        }
    }

```
And register it globally:
```
services
    .AddMvc(.....)
    .AddJsonOptions(options => options.SerializerSettings.Converters.Add(new EmptyStringToNullJsonConverter()))
```

Or on class property, directly:
```
    public class Item
    {
        public int Value { get; set; }

        [StringLength(50, MinimumLength = 3)]
        [JsonConverter(typeof(EmptyStringToNullJsonConverter))]
        public string Description { get; set; }
    }
```
