### ISSUE TITLE
TempData Attribute on an MVC Controller

### ISSUE THREAD

**Issue by mmillican** [aspnet/Mvc#7130] opened 2017-12-14 03:33 UTC
Is it possible (or can it become possible) to decorate a property on a Controller with the `TempDataAttribute` and read that from the view?  Currently, the following example does not work from my testing.  Setting via `TempData["ErrorMessage"]` does work as expected

**Controller (abbrev)**
```
public class AccountController : Controller
{
    [TempData]
    public string ErrorMessage { get; set; }

    [HttpPost]
    public IActionResult Login(LoginViewModel model)
    {
        // DO some  login stuff

        ErrorMessage = "Sorry, your login failed.";
        return View(model);
    }
}
```

**View**
```
@if (TempData.Peek("ErrorMessage") != null)
{
     <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}
```

**Comment by mmillican** [comment] 2017-12-14 03:34
Note, I see on #6601 Damian indicates it _should_ work on controllers also.  Maybe I'm missing something?

**Comment by rynowak** [comment] 2017-12-14 17:24
This is expected to work, we should investigate this.

**Comment by mmillican** [comment] 2017-12-14 17:29
@rynowak Let me know if you need additional information to repro / debug.

**Comment by mkArtakMSFT** [comment] 2017-12-14 23:22
@mmillican, which version of ASP.NET Core do you have the issue with? Can you please provide a repro (maybe a zipped solution) or the project code hosted somewhere?

**Comment by mmillican** [comment] 2017-12-16 02:37
@mkArtakMSFT sorry for the delay here.  I believe it's 2.0.3 on that machine.  I'll get a repro to you over the weekend.

**Comment by mkArtakMSFT** [comment] 2017-12-27 19:08
@mmillican, any progress regarding providing a repro?

**Comment by rogaps** [comment] 2017-12-28 14:01
Perhaps you should read the value with `@TempData["TempDataProperty-ErrorMessage"]`. But in my [test](https://github.com/rogaps/Mvc/commit/76f7bab8940c891012e8c91e0c1e8847b474ca5f), it won't be available until the next request, which is different from controller's `TempData` property. I am not sure if it is by design or a bug.

**Comment by mmillican** [comment] 2017-12-28 16:21
@mkArtakMSFT Sorry, I haven't been able to yet with the Holidays.  I'll try to get it this week still.

**Comment by jonakirke94** [comment] 2018-01-15 15:13
@rogaps reading the value as @TempData["TempDataProperty-ErrorMessage"] does indeed work. I just tested it. Doesn't seem to be intended having to type "TempDataProperty" though!

**Comment by mkArtakMSFT** [comment] 2018-01-16 17:50
@mmillican, any updates?

**Comment by Franklin89** [comment] 2018-01-17 12:06
@mkArtakMSFT I create a simple project to reproduce this issue. Have a look [here](https://github.com/Franklin89/TempData-Repro)

If you navigate to the page the first time it doesn't show up. Refresh the page and one of the messages gets displayed. If you hit F5 a couple times it sometimes disappears. Hope this helps.

**Comment by mkArtakMSFT** [comment] 2018-01-17 17:55
Thanks for providing a repro project. One of our team members will look into it and get back to you.

**Comment by mkArtakMSFT** [comment] 2018-01-17 17:56
@kichalla, can you please investigate this? Thanks!

**Comment by pranavkm** [comment] 2018-01-17 18:44
@rynowak we serialize the property in a result filter \ when the response is written. Plus the key is specifically mangled with the prefix to avoid collisions with user generated keys. Why do you expect the initial scenario to work?

**Comment by kichalla** [comment] 2018-01-17 19:14
I think this is working as expected by its design, however the user experience might not be clear. As @pranavkm suggested, we [prefix ](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/SaveTempDataPropertyFilterBase.cs#L13)the temp data properties with `TempDataProperty-`. Seems like in our functional tests with views, we funneled the value of tempdata property through ViewData. https://github.com/aspnet/Mvc/blob/dev/test/WebSites/BasicWebSite/Controllers/TempDataPropertyController.cs#L37-L38, that could be a workaround for the issue here rather than depending on some internal prefix that we create.

@pranavkm @rynowak wondering if we should provide an option on TempDataDictionary to fallback to a property based name in case we cannot find the one with the given name. Example: TempData["foo"] was not found and falls back to look for TempData["TempDataProperty-foo"].

**Comment by pranavkm** [comment] 2018-01-17 19:24
There's a couple of issues around making some of these collection backed properties more prevalent (e.g. https://github.com/aspnet/Mvc/issues/6525). Perhaps the fix would be to make `TempData` also work in views when we do the work. For the time being, using `ViewData` would be the best way to go.

**Comment by kichalla** [comment] 2018-01-17 19:28
Ah I see 👍

**Comment by Franklin89** [comment] 2018-01-17 21:35
@kichalla I agree with the `TempDataPropery-` being by design as you showed with the source link. But the Issue also is that sometimes the message just doesn't show at all. For me on every first call the alert message in my example provided is not visible. Do you see that behavior as well? After hitting F5 it shows up again and then after a couple more refreshs it disappears again.

**Comment by pranavkm** [comment] 2018-01-17 21:55
@Franklin89 the value of the property `StatusMessage` property is only written to `TempData` after the view is rendered (i.e. when Mvc's stack is unwinding. This explains why on the first run there's nothing available. If you were to set the property's value to a value that increments on every request, you'll notice that the view always has the stale value from a previous request. It's a limitation of how the property and it's backing filter works.

**Comment by Franklin89** [comment] 2018-01-18 06:13
@pranavkm oh I see. Thanks for clearification!

**Comment by pranavkm** [comment] 2018-01-18 15:35
Out of curiosity, what's your scenario for using `TempData` to pass things to views? The most common scenario I've encountered it being used is the Post-Redirect-Get ones, so typically nothing reads the value in the context of the current request.

**Comment by Franklin89** [comment] 2018-01-18 22:14
@pranavkm Well I saw the TempData attribute in the new project I created for testing something and thought this looks like a nice feature and tried to build a status message / toast message component with that. After it I had the explained issue I search on GitHub and found this issue and thought I will join the conversation ;-)

**Comment by kichalla** [comment] 2018-01-18 23:35
Closing this as there is no action to be taken here. (As @pranavkm mentioned, we have issue https://github.com/aspnet/Mvc/issues/6525 to improve experience of accessing TempData property in views/pages)

**Closed** 2018-01-18 23:35 UTC
Labels: invalid, investigate
