### ISSUE TITLE
JS issue in PartialViews.

### ISSUE THREAD

**Issue by AliCharper** [aspnet/Mvc#3514] opened 2015-11-10 18:23 UTC
Hi,

Everybody knows MVC has a big problem ,when we want to have JS in a partialview and the script should be in the main view or the Layout.Who can report it to Microsoft and ask them to fix it?.

**Comment by Eilon** [comment] 2015-11-20 18:15
@AliCharper we're unable to reproduce this issue. If a partial view wants to add content to the layout page you can use an `@section` to do so.

Check out what the default templates do:

1. The layout page renders a section called `scripts` (you can call it whatever you want, and have as many as you want):
 * https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Views/Shared/_Layout.cshtml#L65
 * This section is marked as `required=false`, which indicates that it doesn't have to exist
2. Other content pages, such as the Login page, define content for that section:
 * https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Views/Account/Login.cshtml#L88-L90
 * In this case the content renders a *partial page* that has script contents: https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Views/Shared/_ValidationScriptsPartial.cshtml

**Closed by Eilon** 2015-11-20 18:15 UTC
