### ISSUE TITLE
Model is not binding with the values in WEB API GET method when data is Json

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#7500] opened 2018-03-19 05:20 UTC
_From @onlyanup on March 17, 2018 16:32_

I have a GET method where I'm passing a JSON object. The object is the stringified value of a List of a POCO. The Model Binder fails to bind to the object in this method. 

```c#
        [HttpGet("Test2")]
        public object Check(List<SearchModel> data)
        {
            //var d = Newtonsoft.Json.JsonConvert.DeserializeObject<List<SearchModel>>(data);
            if (data != null)
            {
                return data;
            }
            return Request.QueryString.Value;
        }

   public class SearchModel
    {
        public string Column { get; set; }
        public object Value { get; set; }
        public Matcher Matcher { get; set; }
    }

    public enum Matcher
    {
        Equals,
        Contains,
        GreaterThan,
        LessThan
    }
```

Here the data is not exactly null either. It's just an empty object
![image](https://user-images.githubusercontent.com/37064591/37557489-408f3ad4-2a2b-11e8-85cf-eed974e2937a.png)

I tried it with FromQuery as well. Still no luck
![image](https://user-images.githubusercontent.com/37064591/37557660-f338b82a-2a2d-11e8-8ad8-d5c087f6f402.png)

When the same method is changed as POST then the binder works perfectly and binds the data to the JSON sent in the body. So Model Binder is not broken but just not working in the case of the GET.

![image](https://user-images.githubusercontent.com/37064591/37557629-6d994568-2a2d-11e8-86b1-4fd6d362b632.png)

When I try with string type, it does come as a JSON and then the DeserializeObject method deserializes it to the required object

![image](https://user-images.githubusercontent.com/37064591/37557551-34d774ee-2a2c-11e8-8d74-86fd56d3d318.png)

_Copied from original issue: aspnet/Home#2971_

**Comment by Eilon** [comment] 2018-03-19 05:20
_From @louislewis2 on March 18, 2018 21:6_

@onlyanup Could you try this

[HttpGet("check2")]
public object Check([FromQuery]List<SearchModel> data)
.....

For your POST method, you have added the FromBody attribute, perhaps adding 
the FromQuery attribute would work for you on the GET method.

**Comment by Eilon** [comment] 2018-03-19 05:20
_From @onlyanup on March 18, 2018 21:17_

@louislewis2 I had tried that. Please see the 2nd Image in the report.

**Comment by onlyanup** [comment] 2018-03-19 09:55
@Eilon Is there any workaround for this?

**Comment by louislewis2** [comment] 2018-03-19 10:05
@onlyanup Sorry, I did miss that second image you are referring too.
I did see in your fourth image that the data variable is actually an array.

I had an issue like this before, where I had to create an special binder that could handle array values.
I am not sure if this is still an issue, but perhaps that could help you in the mean time while the ASP.NET team check into your issue.

Just google / bing ;) something like asp.net core query string array binder.

I hope it helps

**Comment by onlyanup** [comment] 2018-03-19 10:17
@lajones Thanks for the suggestion. Even I was thinking of creating a custom ModelBinder but after seeing that POST method (Image 3) does bind to the model correctly, I didn't think to re-invent the wheel. I mean a binder must be there which does the work in POST but is not employed in the GET method. I was looking for some workaround to reuse the existing binder by, maybe, making some changes in startup class like adding some JsonOption or something else.

**Comment by Eilon** [comment] 2018-03-19 16:10
@onlyanup sorry I'm not sure, but I'll let the experts in this repo have a look and they will get back to you with an answer.

**Comment by mkArtakMSFT** [comment] 2018-03-19 16:14
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment] 2018-03-19 16:58
> When I try with string type, it does come as a JSON and then the DeserializeObject method deserializes it to the required object

This is the recommended approach to deserializing JSON in the query string. `[FromBody]` is the _only_ way to perform JSON deserialization inside the model binding system.

**Comment by dougbu** [comment] 2018-03-19 17:01
Thank you for your feedback. We're closing this issue as the behaviour discussed is by design.

**Closed by dougbu** 2018-03-19 17:01 UTC

**Comment by onlyanup** [comment] 2018-03-19 17:33
Hmmm. Interesting design choice. Thanks for letting me know.
