### ISSUE TITLE
custom error handling

### ISSUE THREAD

**Issue by omuleanu** [aspnet/Mvc#4442] opened 2016-04-11 06:59 UTC
hi,
I'm trying to get custom error handling in mvc 6, 
I found that I need to do this in Startup.cs
`app.UseExceptionHandler("/Home/Error");`

and have this action
```
public IActionResult Error()
{
     return View("~/Views/Shared/Error.cshtml");
}
```
but I would also need the exception object, so I could get the error message;
another problem is that it's not being used all the time, for example I'm doing an ajax post that should return a partialview and getting "HTTP Error 502.3 - Bad Gateway" error (InvalidCastException in a custom helper), and this exception is not being handled by the above code

**Comment by danroth27** [comment] 2016-04-12 16:39
@Tratcher Can you help out here?

**Comment by Tratcher** [comment] 2016-04-12 16:53
This sample shows how to get the original exception:
https://github.com/aspnet/Diagnostics/blob/dev/samples/ExceptionHandlerSample/Startup.cs#L26-L31

Note the exception handler only works if the response body has not started. Errors that occur during the response body require closing the connection.

**Comment by omuleanu** [comment] 2016-04-12 17:59
@Tratcher thank you I can get the error message now, but not all errors are handled, 
how do you close the connection on error ?

**Comment by omuleanu** [comment] 2016-04-12 17:59
@Tratcher thank you I can get the error message now, but not all errors are handled, 
how do you close the connection on error ?

**Comment by Tratcher** [comment] 2016-04-12 18:09
https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L50-L54
If middleware sees that the response has already started it will re-throw the original exception. The server (Kestrel) will  catch this exception, abort the request, and close the socket.  IIS may display the above error if it hasn't received the start of the response before noticing the connection was closed. Otherwise you should get an error from the browser about an incomplete response.

**Comment by omuleanu** [comment] 2016-04-12 18:29
ok, I'm using the code from here now: https://github.com/aspnet/Diagnostics/blob/dev/samples/ExceptionHandlerSample/Startup.cs#L26-L31
and it's working good,
but in case of 404 I get an empty result
so if I go to http://localhost:40701/unexistentpage
I get a blank white page
I would like to be able to handle this as well and show my 404 page ( with my _Layout.cshtml, as usual )

**Comment by Tratcher** [comment] 2016-04-12 18:33
404s are not exceptions. See the following example for handling status codes: https://github.com/aspnet/Diagnostics/blob/dev/samples/StatusCodePagesSample/Startup.cs#L29

**Comment by omuleanu** [comment] 2016-04-12 19:48
thanks, what I needed was this:
app.UseStatusCodePagesWithReExecute("/Error/Index/{0}");
strange behavior though 
the above line works but this line:
app.UseStatusCodePagesWithReExecute("/Error/Index?id={0}");
will not, even though if I type in the browser mylocalhostapp/Error/Index?id=123 it works ok

**Comment by Tratcher** [comment] 2016-04-12 21:07
@rynowak would model binding get confused if processed the same request twice?

**Comment by rynowak** [comment] 2016-04-12 21:16
Model binding doesn't attach any state to the HTTP context, however routing does, but it looks like it will overwrite it every time https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/RouterMiddleware.cs#L43

**Comment by Tratcher** [comment] 2016-04-13 17:20
@ryanbrandenburg can you repro this?

**Comment by ryanbrandenburg** [comment] 2016-04-13 19:58
@omuleanu can I get you to clarify what exactly is happening? When you do `/Error/Index/{0}` it generates the expected error page, but when you do `/Error/Index?id={0}` what does it do? Do you get a 500 without any content?

It would also be helpful if you could push a full reproduction repo to github so that we can be sure we're testing under the same conditions as you.

**Comment by omuleanu** [comment] 2016-04-13 20:03
@ryanbrandenburg when I do `/Error/Index?id={0}` it gives a blank/empty page ( no html at all)

all you need to test this is to put 
app.UseStatusCodePagesWithReExecute("/Error/Index?id={0}");
and for success have a controller like this:
```
    public class ErrorController : Controller
    {
        public ActionResult Index(string id)
```

**Comment by omuleanu** [comment] 2016-04-13 20:12
another interesting thing is that I also get a blank page if i put the line:
`app.UseStatusCodePagesWithReExecute("/Error/Index/{0}");` 
after 
'app.UseMvc`
so before `app.UseMvc` it works, after blank page

I tried this because `app.UseRequestLocalization` has the same problem, if you put it after it does nothing

here's the whole of my working Configure method, just in case, you can modify it as explained up ^ to break it:
```
 public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseRequestLocalization(new RequestLocalizationOptions()
            {
                SupportedCultures = new List<CultureInfo>
                {
                    new CultureInfo("en"),
                    new CultureInfo("de"),
                    new CultureInfo("fr"),
                    new CultureInfo("ro"),
                }
            }, new RequestCulture("en"));


            app.UseExceptionHandler("/Error/Index");
            
            app.UseIISPlatformHandler(options => options.AuthenticationDescriptions.Clear());
            app.UseStaticFiles();

            app.UseStatusCodePagesWithReExecute("/Error/Index/{0}");

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```

**Comment by Tratcher** [comment] 2016-04-13 20:40
@omuleanu That makes sense, you're building a request processing pipeline, it's very order dependent. Requests go down, responses and exceptions go back up.

**Comment by ryanbrandenburg** [comment] 2016-04-14 00:01
@omuleanu that is as expected. The parameter for UseStatusCodePagesWithReExecute is `pathFormat`, and is not designed to pass query strings. The routing middleware interprets it like you're looking for the path `/Error/Index?id=404` rather than the path `/Error/Index` with query string `?id=404`.

For now use the `/Error/Index/{0}` format, but if you feel strongly about using a query string there check out aspnet/Diagnostics#268.

Closing this now as a dupe of aspnet/Diagnostics#268.

**Closed by ryanbrandenburg** 2016-04-14 00:01 UTC
Labels: question
