### ISSUE TITLE
Add empty attributes to TagHelpers

### ISSUE THREAD

**Issue by evorine** [aspnet/Mvc#2733] opened 2015-06-24 08:40 UTC
In HTML5, empty attributes are valid and are boolean types. It is here: http://www.w3.org/html/wg/drafts/html/master/infrastructure.html#boolean-attributes

But currently in MVC, it is not supported.
```html
<a href="#" data-is-blue>...</a>
```
So we can wait `data-is-blue` attribute's value as a boolean type in TagHelper class.

**Comment by dougbu** [comment] 2015-06-24 15:00
Dupe of aspnet/Razor#431

But this works today: Your `TagHelper` could _not_ bind the `bool` attribute. Instead check whether it appears in `TagHelperOutput.Attributes`. Check `TagHelperAttribute.Minimized` to differentiate that case from `data-is-blue="data-is-blue"` for some reason.

Separately Razor does not allow bound attributes with names starting with `data-`.

**Closed by dougbu** 2015-06-24 15:00 UTC
Labels: duplicate
