### ISSUE TITLE
`NullReferenceException` in `DefaultPageLoader.Load` if ContentRoot starts with '\\?\'

### ISSUE THREAD

**Issue by ericwj** [aspnet/Mvc#7622] opened 2018-04-09 22:54 UTC
I'm creating a 2.1-preview1 project and doing some non-standard configuration.

I found some API's will return directory names starting with `\\?\` and Mvc doesn't eat them.

```PS
cd C:\
mkdir razor | Out-Null
cd razor
dotnet new razor
(gc .\Program.cs) -join [System.Environment]::NewLine `
    -replace "\.UseStartup", ".UseContentRoot(@`"\\?\C:\razor`").UseStartup" | 
    Out-File .\Program.cs -Encoding utf8
start https://localhost:5001
dotnet run
```

```
Hosting environment: Development
Content root path: \\?\C:\razor
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET https://localhost:5001/
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.DefaultPageLoader.Load(PageActionDescriptor actionDescriptor)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler.<>c__DisplayClass12_0.<RouteAsync>b__0(HttpContext c)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 228.8637ms 500 text/html; charset=utf-8
```

**Comment by Eilon** [comment] 2018-04-09 23:44
Just curious: Is there a reason that `\\?\`-style paths are being used? Is it to get past MAX_PATH?

**Comment by ericwj** [comment] 2018-04-10 00:25
No, they magically appear when running behind IIS.

**Comment by mkArtakMSFT** [comment] 2018-04-10 02:06
Hi @ericwj. Can you please share a repro project?

**Comment by ericwj** [comment] 2018-04-10 06:45
"ancmHostingModel": "InProcess" in `launchSettings.json` is the offender.

```JSON
{
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_HTTPS_PORT": "44393"
      },
      "ancmHostingModel": "InProcess"
    }
}
```

The screenshot will hopefully do the trick, if not - let me know. Not quite the whole scoop because in my original project I get `\\?\` for `Directory.GetCurrentDirectory()` even. And I seem to be completely unable to produce any stdout logs running under IIS after publishing, although IIS Express writes them happily.

If you hand any directory derived from `Assembly.GetEntryAssembly().Location` to `UseContentRoot` without stripping the `\\?\` you should get the `NullReferenceException` I reported. E.g. `new DirectoryInfo(...).Parent.Parent.FullName` - which is essentially what I was doing, looking for `web.config` and `appconfig.json`.

I also had a very odd crash with a `NullReferenceException` using Assembly.Location in an initializer for a static readonly field in a Razor Page. Could be related.

Startup was Hello world but I had a full Pages folder running `dotnet new razor`, a VS 15.7 update 3 glitch hopefully...sorry for the design ;)
![image](https://user-images.githubusercontent.com/9473119/38539606-2982c25e-3c99-11e8-9bb7-f7c267d0e93a.png)

**Comment by Tratcher** [comment] 2018-04-10 16:29
Likely a duplicate of https://github.com/aspnet/IISIntegration/issues/725

**Comment by Eilon** [comment] 2018-04-10 16:30
Yup, looks exactly the same.

**Comment by mkArtakMSFT** [comment] 2018-04-10 16:51
Thanks folks. Closing this one as a dupe.

**Closed by mkArtakMSFT** 2018-04-10 16:51 UTC
