### ISSUE TITLE
Build fails when %userprofile% contains space

### ISSUE THREAD

**Issue by HamletHakobyan** [aspnet/Mvc#7847] opened 2018-05-31 22:05 UTC
Build fails when trying to install .NET Core Runtime (x64) 2.0.0

**Comment by mkArtakMSFT** [comment] 2018-05-31 22:28
Thanks for contacting us, @HamletHakobyan.
Trying to understand the issue you're facing here.
Are you having issues with building an app targeting .NET Core runtime 2.0?
Would be great if you could provide a sample repro project emphasizing the issue.

**Comment by HamletHakobyan** [comment] 2018-06-01 00:36
The issue is  related to the asp.net core mvc project. When I try to run `build.com /t:Restore` it fails with error

> C:\Users\aaa bbb\\.dotnet\buildtools\korebuild\2.2.0-preview1-17064\modules\KoreBuild.Tasks\module.targets(53,5): error : dotnet-install failed on .NET Core Runtime (x64) 2.0.0. [C:\Users\aaa bbb\\.dotnet\buildtools\korebuild\2.2.0-preview1-17064\KoreBuild.proj]

it because of space in profile name "aaa bbb". When I thy to print `InstallDir` and `Channel` arguments of "scripts\dotnet-install.ps1" they are
`InstallDir = "c:\Users\aaa"`
`Channel= "bbb\.dotnet\x64"`

**Comment by pranavkm** [comment] 2018-06-01 00:51
cc @natemcmaster \ @ryanbrandenburg

**Comment by mkArtakMSFT** [comment] 2018-06-01 00:58
Thanks for the details, @HamletHakobyan.
@ryanbrandenburg looks like this is related to our build scripts.
Can you please look into this?

**Comment by natemcmaster** [comment] 2018-06-01 00:59
This looks like a duplicate of https://github.com/aspnet/BuildTools/issues/666

**Comment by HamletHakobyan** [comment] 2018-06-01 01:11
I found out, that the problem is in msbuild task `InstallDotNet`. The procmon shows that the InstallDir arguemnt passed to the "dotnet-install.ps1" is double quoted. So in powershell, the double quoted argument with space is separated to the 2 arguments by the space.

**Comment by HamletHakobyan** [comment] 2018-06-01 01:13
@natemcmaster yes, it is.

**Comment by mkArtakMSFT** [comment] 2018-06-01 01:46
Thanks @natemcmaster. Closing this one in favor of the earlier reported issue referenced above.

**Closed by mkArtakMSFT** 2018-06-01 01:46 UTC
Labels: investigate
