### ISSUE TITLE
Under certain condition TagHelper raise namespace name could not be found

### ISSUE THREAD

**Issue by Azaret** [aspnet/Mvc#2595] opened 2015-05-21 16:33 UTC
I work on an internal web app with an important UI, which I want to migrate to MVC6 soon. Because you guys have done an amazing work and it looks very cool. Anyway.

The basic architect looks as follow : 

*Index.cshtml*
```cshtml
@{
    Layout = "~/Views/Shared/Layout";
}
<h2>title</h2>
<p>Hello vNext!</p>
```

*Layout.cshtml*
```cshtml
@{
    Layout = "~/Views/Shared/MainLayout";
}
@RenderBody()
@section GlobalMenu
{
    <ul class="nav navbar-nav">
        <li class="active">
            <a asp-controller="Home" asp-action="Index">Index</a>
        </li>
    </ul>
}
```

*MainLayout.cshtml*
```cshtml
<!DOCTYPE html>
<html>
<head>
...
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation" id="global-navbar">
        ...
        @RenderSection("GlobalMenu", false)
        ...
   </div>
   ...
   @RenderBody()
   ...
</body>
</html>
```

In this specific configuration, an exception is raised (full stack at the end) : 
```
An unhandled exception occurred while processing the request.

CompilationFailedException: One or more compilation failures occured:
...\Views\Shared\Layout.cshtml(15,17): error CS0246: The type or namespace name 'TagHelperContent' could not be found (are you missing a using directive or an assembly reference?)
at Microsoft.AspNet.Mvc.Razor.CompilationResult.EnsureSuccessful()
```

Note that:
- if `<a asp-controller="Home" asp-action="Index">Index</a>` is removed from the section the exception is not raised anymore.
- `<a asp-controller="Home" asp-action="Index">Index</a>` works perfectly when in `Index.cshtml`, `Layout.cshtml` out of the section, and `MainLayout.cshtml`.
- Also, if `<a asp-controller="Home" asp-action="Index">Index</a>` is added in `Layout.cshtml` both out and in the section, no exception is raised and both link are generated. ie : 
```cshtml
@{
    Layout = "~/Views/Shared/MainLayout";
}
<a asp-controller="Home" asp-action="Index">Index</a>
@RenderBody()

@section GlobalMenu
{
    <ul class="nav navbar-nav">
        <li class="active">
            <a asp-controller="Home" asp-action="Index">Index</a>
        </li>
    </ul>
}
```

I also tried with only 1 layout and 1 index, and it looks like right, but not with the sub-layout + section thingy.

Tell me if you need more info.

Full Stack : 
```
CompilationFailedException: One or more compilation failures occured:
 ...\Views\Shared\Layout.cshtml(15,17): error CS0246: The type or namespace name 'TagHelperContent' could not be found (are you missing a using directive or an assembly reference?)
à Microsoft.AspNet.Mvc.Razor.CompilationResult.EnsureSuccessful()
à Microsoft.AspNet.Mvc.Razor.CompilerCache.OnCacheMiss(RelativeFileInfo file, String normalizedPath, Func`2 compile)
à Microsoft.AspNet.Mvc.Razor.CompilerCache.GetOrAddCore(String relativePath, Func`2 compile)
à Microsoft.AspNet.Mvc.Razor.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
à Microsoft.AspNet.Mvc.Razor.VirtualPathRazorPageFactory.CreateInstance(String relativePath)
à Microsoft.AspNet.Mvc.Razor.RazorViewEngine.GetRazorPageResult(ActionContext context, String pageName, Boolean isPartial)
à Microsoft.AspNet.Mvc.Razor.RazorViewEngine.FindPage(ActionContext context, String pageName)
à Microsoft.AspNet.Mvc.Razor.RazorView.GetLayoutPage(ViewContext context, String layoutPath)
à Microsoft.AspNet.Mvc.Razor.RazorView.<RenderLayoutAsync>d__19.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
à Microsoft.AspNet.Mvc.Razor.RazorView.<RenderAsync>d__15.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
à Microsoft.AspNet.Mvc.ViewExecutor.<ExecuteAsync>d__2.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
à Microsoft.AspNet.Mvc.ViewResult.<ExecuteResultAsync>d__20.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
à Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeResultAsync>d__44.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
à Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeResultFilterAsync>d__43.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
à Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__42.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
à Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeResourceFilterAsync>d__37.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
à Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
à Microsoft.AspNet.Mvc.MvcRouteHandler.<InvokeActionAsync>d__3.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
à Microsoft.AspNet.Mvc.MvcRouteHandler.<RouteAsync>d__2.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
à Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__25.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
à Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__10.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
à Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
à Microsoft.AspNet.Diagnostics.ErrorPageMiddleware.<Invoke>d__4.MoveNext()
```

**Comment by dougbu** [comment] 2015-05-21 16:47
@Azaret where are you including the `@addTagHelper` directive?

**Comment by Azaret** [comment] 2015-05-22 08:58
In `_GlobalImport.cshtml`

**Comment by danroth27** [comment] 2015-05-22 16:54
@dougbu Could you please try to reproduce this issue?

**Comment by dougbu** [comment] 2015-05-22 17:09
sure

**Comment by NTaylorMullen** [comment] 2015-05-22 18:19
Workarounds are:

- Place an `@using Microsoft.AspNet.Razor.Runtime.TagHelpers` in your layout.
- :trollface: workaround = Use an additional `TagHelper` outside of the section. :smile:

**Comment by dougbu** [comment] 2015-05-26 22:06
The `Exception` does not reproduce with Beta 5 bits. I needed to back up to Beta 4 to get that exact behaviour.

However the problem is not fixed at all in Beta 5; the symptoms are just different. In particular `<a asp-controller="Home" asp-action="Index">Index</a>` is passed through into the generated HTML. In some ways this silent failure is worse than the previous exception.

Fix is relatively simple: We have a few visitors that need to consistently recurse into sections.

**Comment by dougbu** [comment] 2015-05-26 22:06
Clearing milestone so this confirmed bug can be triaged.

**Comment by dougbu** [comment] 2015-05-30 19:09
Closing because newer aspnet/Razor#412 issue is in the correct repo.

**Closed** 2015-05-30 19:10 UTC
Labels: bug, duplicate
