### ISSUE TITLE
Validation occurs against declared type rather than real type

### ISSUE THREAD

**Issue by Materix** [aspnet/Mvc#7952] opened 2018-06-21 12:52 UTC
#### Is this a Bug or Feature request?:

Bug - Probably regression

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

Repo with example project on: https://github.com/Materix/ValidationInterface

Send POST request on `api/fruit` with `{"type":"orange"}` as body and `Content-Type: application/json`

Expected result: ModelState.IsValid = false
Result: ModelState.IsValid = true

CompatibilityVersion is set to Version_2_1. 
Without setting all works correctly
On 2.0.0. all works correctly.

#### Description of the problem:

I have interface of model class (`IFruit`) from which two class derived (`Apple`, `Orange`). I have custom JsonConventer which determine proper type bases on one value from json. All validation attributes were in individual implementation. When I bind to `IFruit` ModelState.IsValid always returns true.

#### Images:
![obraz](https://user-images.githubusercontent.com/6151485/41720214-a563989c-7562-11e8-9a80-8bb8dda000f5.png)
![obraz](https://user-images.githubusercontent.com/6151485/41720221-a9fd32dc-7562-11e8-8893-30d59c7bf494.png)
![obraz](https://user-images.githubusercontent.com/6151485/41720226-acd7e286-7562-11e8-8aae-67ba140be7af.png)

**Comment by pranavkm** [comment] 2018-06-21 23:51
Looks like this is a result of the validation changes in 2.1. Specifically, with a 2.0 compatibility setting, `ModelMetadata` is calculated over the actual model type - 
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ObjectModelValidator.cs#L59

In 2.1, we pass the `ModelMetadata` of the declared model type - 
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ParameterBinder.cs#L296-L301

Not entirely sure what the intended behavior needs to be. A previous issue suggested that we are meant to look at the declared model type - https://github.com/aspnet/Mvc/issues/6466#issuecomment-312703146. @dougbu thoughts?

@Materix you should be able to retain the older behavior by turning off validation for top level nodes `MvcOptions.AllowValidatingTopLevelNodes`. It does mean validation attributes on top level properties and controller parameters will not apply, but it does unblock this specific scenario in your case.

**Comment by dougbu** [comment] 2018-06-22 05:06
@pranavkm this looks like an exception to the overall declared type behaviour of the validation system. Unfortunately, removing this exception -- whether intended or not -- introduced a regression.

**Comment by Materix** [comment] 2018-06-22 11:07
So, the second option is to write own ModelBinder f.e. (already used to bind from json-formatted form field as `[FromForm(Name = "name"), ModelBinder(typeof(JsonModelBinder))]`)

```c#
    public class JsonModelBinder : IModelBinder
    {
        private readonly IOptions<MvcJsonOptions> _jsonOptions;

        public JsonModelBinder(IOptions<MvcJsonOptions> jsonOptions)
        {
            _jsonOptions = jsonOptions;
        }

        public async Task BindModelAsync(ModelBindingContext bindingContext)
        {
            var name = bindingContext.ModelName ?? bindingContext.FieldName;
            var valueProviderResult = bindingContext.ValueProvider.GetValue(name);
            if (valueProviderResult == ValueProviderResult.None)
            {
                return;
            }

            bindingContext.ModelState.SetModelValue(name, valueProviderResult);

            var value = await Task.Factory.StartNew(
                            () => JsonConvert.DeserializeObject(valueProviderResult.FirstValue, bindingContext.ModelType, _jsonOptions.Value.SerializerSettings));

            
            bindingContext.Result = ModelBindingResult.Success(value);
        }
    }
```

and update field `bindingContext.ModelMetadata` by creating new for real type?

**Comment by pranavkm** [comment] 2018-06-22 13:16
@Materix haven't tried your suggested change, but I don't think it'd work. `ParameterBinder` does not use `ModelBindingContext.ModelMetadata` during validation (it uses the original value passed in to the `BindAsync` method). Seeing this is a regression, I'll see if we can get a fix for this in an upcoming patch.

**Comment by pranavkm** [comment] 2018-07-02 18:30
@Materix I'm working on porting the fix to an upcoming patch release. https://github.com/aspnet/Mvc/issues/7968 is the tracking issue. In the meanwhile, I'd recommend using the `MvcOptions.AllowValidatingTopLevelNodes` switch to continue getting the 2.0 existing behavior.

**Comment by pranavkm** [comment] 2018-07-02 18:30
Fixed in https://github.com/aspnet/Mvc/commit/335500ab0ed76e073514130068aab43a40ebba3e

**Closed by pranavkm** 2018-07-02 18:30 UTC
Labels: 3 - Done, breaking-change, bug, cost: M

**Comment by mathiasbl** [comment] 2018-08-01 08:02
This fix will only work when the type is a top level object? What if it's defined as a property on another type?

**Comment by dougbu** [comment] 2018-08-01 14:07
@mathiasbl nothing changed in the validation of non-top-level objects.
