### ISSUE TITLE
Add a filter attribute for setting request form size limits

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#5020] opened 2016-07-14 12:37 UTC
Currently user has to do something like https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Filters/RequestFormSizeLimitAttribute.cs ...would be good to provide this out of the box...

From @davidfowl 

cc @rynowak

**Comment by rynowak** [comment] 2016-07-14 14:46
Just to make it clear, is this for the case where you a fairly restrictive limit applied site-wide, but then need to relax that limit for an action?

It's not a **bad** idea, but how common is this? My worry about this is that it's not a knob most users will need to fiddle with, we don't want to put it in everyone's face by default - our defaults need to be "good enough" for the vast majority of applications.

**Comment by davidfowl** [comment] 2016-07-16 08:44
I think we should provide a filter that lets you tweak all of the `FormOptions`, not just the value limit. Large uploads being one of the major scenarios. Providing a filter as a convenient way to target a particular action method doing this kinda thing.

**Comment by danroth27** [comment] 2016-08-17 23:29
Duplicate of #5128

**Closed by danroth27** 2016-08-17 23:29 UTC
Labels: enhancement
