### ISSUE TITLE
Model Not Binding to Subtype with Collection 

### ISSUE THREAD

**Issue by saddlebear** [aspnet/Mvc#8446] opened 2018-09-11 21:26 UTC
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

https://github.com/saddlebear/AspNetCoreModelBindingIssue.git

Issue concerns ArticleController.cs, Models/Article.cs, Models/Image.cs and Create.cshtml.

Article class has an Image class property.   
Image class contains a  List<IFormFile> field.

#### Description of the problem:

When uploading a file, if Create.cshtml does not contain a field in Image (Image.Caption) other than a collection (Image.FormFiles) then FormFiles will not receive the uploaded form.    If you comment out the form group containing Image.Caption, run the project and attempt to upload a file the file will not be uploaded.  If you uncomment the form group containing Image.Caption, run the program, upload a file, the file will be uploaded into Image.FormFiles.   The Image.Caption field has to be on the form for the uploaded files to be stored in Image.FormFiles.

**Comment by mkArtakMSFT** [comment] 2018-09-11 23:34
Thanks for contacting us, @saddlebear.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment] 2018-09-12 19:02
@saddlebear there's actually two issues here:
1. The model binding system checks whether any property of a complex model has data in the request. If not, it does not bind the model -- avoiding useless recursion. In this case, the binding source for the `List<IFormFile>` property is not correctly inferred i.e. the checks don't look in the right place. So, without `Caption` data, the system does not bind the `Image`.
  This part is similar to #7770 though unrelated to `[ApiController]`. The fix for that (in `2.2.0-preview1`) fixes this as well.
2. The model binding system special-cases complex types with _all_ properties having "greedy" binding sources e.g. those coming `FromFile`. But, it will not bind models with properties mixing greedy and non-greedy binding sources unless the non-greedy properties (like `Caption`) have data in the request.

**Comment by dougbu** [comment] 2018-09-12 19:11
@saddlebear the workaround is to provide information for another property, as you did for `Caption`. If you prefer nothing be shown to users, add a hidden field:
``` html
<input asp-for="Image.Caption" type="hidden" />
```

**Comment by dougbu** [comment] 2018-09-13 16:12
@danroth27 @mkArtakMSFT I discussed this issue offline with @rynowak. We agree part 2 in my comment [back here](https://github.com/aspnet/Mvc/issues/8446#issuecomment-420761645) should be treated as a bug. I'm labeling this issue as such but leaving the milestone and priority to you two.

**Comment by mkArtakMSFT** [comment] 2018-09-13 16:15
I would like to resolve this in current milestone, so we don't have any model-binding (or at least reduce as much as possible) issues. It's kind of a can of worms.

**Comment by dougbu** [comment] 2018-09-14 18:59
Turns out the outstanding issue, now that @pranavkm fixed #7770, is a duplicate of #7562. Will use that bug to track updating the `ComplexTypeModelBinder`.

**Closed** 2018-09-14 19:00 UTC
Labels: 1 - Ready, PRI: 1 - Required, bug, cost: S, duplicate
