### ISSUE TITLE
Broken Razor Views with DNX beta6-12005 and last aspnet packages

### ISSUE THREAD

**Issue by IsaacSee** [aspnet/Mvc#2682] opened 2015-06-10 15:20 UTC
Hello, 

Since our last dnx upgrade, it seems that razor views are broken.
We upgraded everything this morning (dnx & aspnet packages) to last versions.
Our Startup only configure mvc services and use default mvc, with a simple controller/action.

We end up with the following exception without much informations.
If someone has a clue on this, thanks by advance.

```
An unhandled exception occurred while processing the request.

InvalidOperationException: Operation is not valid due to the current state of the object.
Microsoft.Framework.Runtime.DesignTimeHostCompiler.<Compile>d__6.MoveNext()

AggregateException: One or more errors occurred.
System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)


InvalidOperationException: Operation is not valid due to the current state of the object.
Microsoft.Framework.Runtime.DesignTimeHostCompiler.<Compile>d__6.MoveNext()
AggregateException: One or more errors occurred.
System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
System.Threading.Tasks.Task`1.get_Result()
Microsoft.Framework.Runtime.DesignTimeHostProjectCompiler.CompileProject(ICompilationProject project, ILibraryKey target, Func`1 referenceResolver, Func`1 resourcesResolver)
Microsoft.Framework.Runtime.ProjectLibraryExportProvider.<>c__DisplayClass5_0.<GetLibraryExport>b__0(CacheContext ctx)
Microsoft.Framework.Runtime.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
Microsoft.Framework.Runtime.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
Microsoft.Framework.Runtime.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
System.Lazy`1.CreateValue()
System.Lazy`1.LazyInitValue()
System.Lazy`1.get_Value()
Microsoft.Framework.Runtime.Caching.Cache.Get(Object key, Func`2 factory)
Microsoft.Framework.Runtime.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
Microsoft.Framework.Runtime.ProjectLibraryExportProvider.GetLibraryExport(ILibraryKey target)
Microsoft.Framework.Runtime.CompositeLibraryExportProvider.<>c__DisplayClass2_0.<GetLibraryExport>b__0(ILibraryExportProvider r)
System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
Microsoft.Framework.Runtime.CompositeLibraryExportProvider.GetLibraryExport(ILibraryKey target)
Microsoft.Framework.Runtime.ProjectExportProviderHelper.GetExportsRecursive(ICache cache, ILibraryManager manager, ILibraryExportProvider libraryExportProvider, ILibraryKey target, Func`2 include)
Microsoft.Framework.Runtime.ProjectExportProviderHelper.GetExportsRecursive(ICache cache, ILibraryManager manager, ILibraryExportProvider libraryExportProvider, ILibraryKey target, Boolean dependenciesOnly)
Microsoft.Framework.Runtime.LibraryManager.<>c__DisplayClass23_0.<GetAllExports>b__0(CacheContext ctx)
Microsoft.Framework.Runtime.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
Microsoft.Framework.Runtime.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
Microsoft.Framework.Runtime.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
System.Lazy`1.CreateValue()
System.Lazy`1.LazyInitValue()
System.Lazy`1.get_Value()
Microsoft.Framework.Runtime.Caching.Cache.Get(Object key, Func`2 factory)
Microsoft.Framework.Runtime.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
Microsoft.Framework.Runtime.LibraryManager.GetAllExports(String name, String aspect)
Microsoft.Framework.Runtime.LibraryManager.GetAllExports(String name)
Microsoft.AspNet.Mvc.Razor.Compilation.RoslynCompilationService.GetApplicationReferences()
System.Lazy`1.CreateValue()
System.Lazy`1.LazyInitValue()
System.Lazy`1.get_Value()
Microsoft.AspNet.Mvc.Razor.Compilation.RoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
Microsoft.AspNet.Mvc.Razor.Compilation.RazorCompilationService.Compile(RelativeFileInfo file)
Microsoft.AspNet.Mvc.Razor.Compilation.CompilerCache.OnCacheMiss(RelativeFileInfo file, String normalizedPath, Func`2 compile)
Microsoft.AspNet.Mvc.Razor.Compilation.CompilerCache.GetOrAddCore(String relativePath, Func`2 compile)
Microsoft.AspNet.Mvc.Razor.Compilation.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
Microsoft.AspNet.Mvc.Razor.VirtualPathRazorPageFactory.CreateInstance(String relativePath)
Microsoft.AspNet.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext context, String pageName, Boolean isPartial)
Microsoft.AspNet.Mvc.Razor.RazorViewEngine.GetRazorPageResult(ActionContext context, String pageName, Boolean isPartial)
Microsoft.AspNet.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName)
Microsoft.AspNet.Mvc.Rendering.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean partial)
Microsoft.AspNet.Mvc.Rendering.CompositeViewEngine.FindView(ActionContext context, String viewName)
Microsoft.AspNet.Mvc.ViewResult.<ExecuteResultAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeResultAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeResultFilterAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeResourceFilterAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Mvc.MvcRouteHandler.<InvokeActionAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Mvc.MvcRouteHandler.<RouteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute.<RouteAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNet.Diagnostics.ErrorPageMiddleware.<Invoke>d__4.MoveNext()
```

**Comment by davidfowl** [comment] 2015-06-10 15:24
Can you reproduce this in a simple project?

**Comment by IsaacSee** [comment] 2015-06-10 15:26
First step was to clean out everything in our Startup and only setup default Mvc.
I am now trying to repro with the default vnext template.
I'll confirm in few minutes.

**Comment by IsaacSee** [comment] 2015-06-10 15:40
It works with a very simple project (startup with only mvc, one controller, one action & one view).

We will continue to investigate what would cause it in our project, when our Startup only set up mvc with defaults. Do you have any clue on what could cause that (any hidden auto-discovery processus or   reference problem) ?

**Comment by davidfowl** [comment] 2015-06-10 15:43
From the stack trace I would say it looks like 2 different projects using 2 different versions if the runtime. Basically each of them has a `global.json` that specifies an SDK version and each project's `global.json` specifies a different SDK version.

**Comment by IsaacSee** [comment] 2015-06-10 15:45
Thanks for the clue.

Here is our global.json, the one and only existing on our filesystem.
Could an external package influence this ?

```
{
    "projects": [
        "src",
        "test"
    ]
}
```

**Comment by davidfowl** [comment] 2015-06-10 15:47
@IsaacSee how many projects in the solution?

**Comment by IsaacSee** [comment] 2015-06-10 16:22
We have 16 projects in the solution.

**Comment by IsaacSee** [comment] 2015-06-10 16:28
Well, your question lead me to the culprit !

In the solution we have an unloaded project containing only js files (without any compilable file).
It is included to the website references to be included in the publication process.
When I remove it from references, our views works again.
I guess, since there is not compilable file, it does not generate any assembly causing the view rendering process to fail.

**Comment by IsaacSee** [comment] 2015-06-10 16:41
We need to find a solution since we'd like to keep this project included in the publication.

Another interesting thing is that when I launch the project with "dnx . web" views works, but as soon as we launch it from visual studio (IIS Express or AspNet.Hosting) views stop working.

**Comment by IsaacSee** [comment] 2015-06-10 16:50
We tried to add a dummy class to the "X" project so that the compilation generate something but even with that, as soon as we include it in the website, views stops working.

"X" project real name is "Evencity.Clients".

**Comment by branciat** [comment] 2015-06-11 09:47
Hello,

I have the same issue today, without change important into the projects.
The solution contain the git repositories dev of entity framework 7, npgsql dev  and my project.
Yesterday run is ok with the sql server connector, today is crash on the same error during the compilation of the view razor.

**Comment by IsaacSee** [comment] 2015-06-11 12:26
So to summarize, it seems to have a link with the way visual studio is launching projects (thought it had no impact and simply launched the host).

---------------------



It **works** when starting the project without visual studio with a **dnx . web** command as : 
```
Microsoft.AspNet.Hosting  --ASPNET_ENV production --server Microsoft.AspNet.Server.WebListener --server.urls http://*:5000 
```
We tryed with development and production env, it does not seem to impact the issue.

---------------------

But it **does not  work** when we start the website from visual studio (with or without debugging).
Our website reference a vnext project containing a lot of client files, freezing visual studio, so we keep this project unloaded. Nevertheless this project must be included in the publish result, so we reference it from the website project.json file.

Interesting thing is that - without doing any other modification - if we load the project, then restart visual studio, views start working again. And as soon as we unload the project, then restart visual studio, it broke views again.

---------------------

Are we missing something ? Is there a place to find more information about this issue if it happend again ?

Our target is to have a folder, containing client scripts, included in the publication process of multiple website. This folder can not be loaded in visual studio (since we can not find a way to exlude folder in Visual Studio 2015, causing big freezes walking all thooses files). We also tried to include this folder using the "content" option of project.json but it does not work due to file locking issues during publication process.

**Comment by IsaacSee** [comment] 2015-06-11 12:41
Also, we have the same exception in our functionnal test (in tests, the bug does not seem dependant on the inclusion of an unloaded project). When we use the Microsoft.AspNet.TestHost.TestServer to request razor backed pages, we have the same exception result, everytime. Right now we have not figured out why.

**Comment by danroth27** [comment] 2015-06-11 16:12
Can you share with us your project so that we can investigate?

**Comment by IsaacSee** [comment] 2015-06-12 08:36
Unfortunatly I can not share the project but I will try to extract the problem in an simplier & anonymous repro project. During this time, if you have any lead we could dig up, it would be great.

**Comment by IsaacSee** [comment] 2015-06-12 09:26
You will find a reproduction solution here : http://gitlab.fivetouch.net/isaac.duplan/aspnet-brokenviews-reproduction/tree/master

It contains only two projects 
- A minimal Mvc Website using razor for its single action
- A reference project "DisabledProject" witch cause the reported error when referenced by the website and disabled

If you disable the "DisabledProject", restart visual studio then run the website using visual studio (Ctrl + F5 for example), you should have the same exception.

If you enable the "DisabledProject", restart visual studio then run the website, it should be all right.

As I stated above, we had the same exception when requesting a razor page using TestHost.TestServer in functional tests, there might be a correlation, I'll try to repro this too in a later commit.

**Comment by IsaacSee** [comment] 2015-06-12 09:38
Just added a single tests witch fails when "DisabledProject" is disabled.

**Comment by dougbu** [comment] 2015-06-14 19:10
Using `TestServer` example from the [repo](http://gitlab.fivetouch.net/isaac.duplan/aspnet-brokenviews-reproduction.git) and latest `dev` bits, DTH `throw`s this `InvalidOperationException` when attempting to compile `DisabledProject`. That project is not in its `_projectContext` dictionary. DTH gets that context in a message from VS. When a project is disabled, VS doesn't build it and does not provide information about the project in its `"ProjectContexts"` message.

I'll talk to the tooling team tomorrow.

Note disabling (aka unloading) a project only changes the `.suo` file, nothing that is used from the command line. So doing anything from the command line continues to work. In addition removing the reference from the main project to `DisableProject` works because DTH will not attempt to resolve the reference.

Stack trace on receipt of the `"ProjectContexts"` message:
```
Microsoft.Framework.Runtime.Compilation.DesignTime.dll!Microsoft.Framework.Runtime.DesignTimeHostCompiler.ProjectContextsInitialized(System.Collections.Generic.Dictionary<string, int> projectContexts) Line 104	C#
Microsoft.Framework.Runtime.Compilation.DesignTime.dll!Microsoft.Framework.Runtime.ProcessingQueue.ReceiveMessages() Line 116	C#
mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	Unknown
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()	Unknown
```

Stack trace at the `throw` when `DisabledProject` is not loaded in VS is:
```
Microsoft.Framework.Runtime.Compilation.DesignTime.dll!Microsoft.Framework.Runtime.DesignTimeHostCompiler.Compile(string projectPath, Microsoft.Framework.Runtime.ILibraryKey library) Line 78	C#
Microsoft.Framework.Runtime.Compilation.DesignTime.dll!Microsoft.Framework.Runtime.DesignTimeHostProjectCompiler.CompileProject(Microsoft.Framework.Runtime.Compilation.ICompilationProject project, Microsoft.Framework.Runtime.ILibraryKey target, System.Func<Microsoft.Framework.Runtime.Compilation.ILibraryExport> referenceResolver, System.Func<System.Collections.Generic.IList<Microsoft.Framework.Runtime.Compilation.ResourceDescriptor>> resourcesResolver) Line 36	C#
Microsoft.Framework.Runtime.dll!Microsoft.Framework.Runtime.ProjectLibraryExportProvider.GetLibraryExport.AnonymousMethod__0(Microsoft.Framework.Runtime.Caching.CacheContext ctx) Line 113	C#
Microsoft.Framework.Runtime.Abstractions.dll!Microsoft.Framework.Runtime.Caching.CacheExtensions.Get.AnonymousMethod__0(Microsoft.Framework.Runtime.Caching.CacheContext ctx) Line 9	C#
Microsoft.Framework.Runtime.Caching.dll!Microsoft.Framework.Runtime.Caching.Cache.CreateEntry(object k, System.Func<Microsoft.Framework.Runtime.Caching.CacheContext, object> acquire) Line 102	C#
Microsoft.Framework.Runtime.Caching.dll!Microsoft.Framework.Runtime.Caching.Cache.AddEntry.AnonymousMethod__0() Line 40	C#
mscorlib.dll!System.Lazy<Microsoft.Framework.Runtime.Caching.Cache.CacheEntry>.CreateValue()	Unknown
mscorlib.dll!System.Lazy<Microsoft.Framework.Runtime.Caching.Cache.CacheEntry>.LazyInitValue()	Unknown
mscorlib.dll!System.Lazy<Microsoft.Framework.Runtime.Caching.Cache.CacheEntry>.Value.get()	Unknown
Microsoft.Framework.Runtime.Caching.dll!Microsoft.Framework.Runtime.Caching.Cache.Get(object key, System.Func<Microsoft.Framework.Runtime.Caching.CacheContext, object> factory) Line 24	C#
Microsoft.Framework.Runtime.Abstractions.dll!Microsoft.Framework.Runtime.Caching.CacheExtensions.Get<Microsoft.Framework.Runtime.Compilation.ILibraryExport>(Microsoft.Framework.Runtime.Caching.ICache cache, object key, System.Func<Microsoft.Framework.Runtime.Caching.CacheContext, Microsoft.Framework.Runtime.Compilation.ILibraryExport> factory) Line 9	C#
Microsoft.Framework.Runtime.dll!Microsoft.Framework.Runtime.ProjectLibraryExportProvider.GetLibraryExport(Microsoft.Framework.Runtime.ILibraryKey target) Line 64	C#
Microsoft.Framework.Runtime.dll!Microsoft.Framework.Runtime.CompositeLibraryExportProvider.GetLibraryExport.AnonymousMethod__0(Microsoft.Framework.Runtime.Compilation.ILibraryExportProvider r) Line 21	C#
System.Core.dll!System.Linq.Enumerable.WhereSelectArrayIterator<System.__Canon, System.__Canon>.MoveNext()	Unknown
System.Core.dll!System.Linq.Enumerable.FirstOrDefault<Microsoft.Framework.Runtime.Compilation.ILibraryExport>(System.Collections.Generic.IEnumerable<Microsoft.Framework.Runtime.Compilation.ILibraryExport> source, System.Func<Microsoft.Framework.Runtime.Compilation.ILibraryExport, bool> predicate)	Unknown
Microsoft.Framework.Runtime.dll!Microsoft.Framework.Runtime.CompositeLibraryExportProvider.GetLibraryExport(Microsoft.Framework.Runtime.ILibraryKey target) Line 21	C#
Microsoft.Framework.Runtime.dll!Microsoft.Framework.Runtime.ProjectExportProviderHelper.GetExportsRecursive(Microsoft.Framework.Runtime.Caching.ICache cache, Microsoft.Framework.Runtime.ILibraryManager manager, Microsoft.Framework.Runtime.Compilation.ILibraryExportProvider libraryExportProvider, Microsoft.Framework.Runtime.ILibraryKey target, System.Func<Microsoft.Framework.Runtime.ILibraryInformation, bool> include) Line 69	C#
Microsoft.Framework.Runtime.dll!Microsoft.Framework.Runtime.ProjectExportProviderHelper.GetExportsRecursive(Microsoft.Framework.Runtime.Caching.ICache cache, Microsoft.Framework.Runtime.ILibraryManager manager, Microsoft.Framework.Runtime.Compilation.ILibraryExportProvider libraryExportProvider, Microsoft.Framework.Runtime.ILibraryKey target, bool dependenciesOnly) Line 22	C#
Microsoft.Framework.Runtime.dll!Microsoft.Framework.Runtime.LibraryManager.GetAllExports.AnonymousMethod__0(Microsoft.Framework.Runtime.Caching.CacheContext ctx) Line 138	C#
Microsoft.Framework.Runtime.Abstractions.dll!Microsoft.Framework.Runtime.Caching.CacheExtensions.Get.AnonymousMethod__0(Microsoft.Framework.Runtime.Caching.CacheContext ctx) Line 9	C#
Microsoft.Framework.Runtime.Caching.dll!Microsoft.Framework.Runtime.Caching.Cache.CreateEntry(object k, System.Func<Microsoft.Framework.Runtime.Caching.CacheContext, object> acquire) Line 102	C#
Microsoft.Framework.Runtime.Caching.dll!Microsoft.Framework.Runtime.Caching.Cache.AddEntry.AnonymousMethod__0() Line 40	C#
mscorlib.dll!System.Lazy<Microsoft.Framework.Runtime.Caching.Cache.CacheEntry>.CreateValue()	Unknown
mscorlib.dll!System.Lazy<Microsoft.Framework.Runtime.Caching.Cache.CacheEntry>.LazyInitValue()	Unknown
mscorlib.dll!System.Lazy<Microsoft.Framework.Runtime.Caching.Cache.CacheEntry>.Value.get()	Unknown
Microsoft.Framework.Runtime.Caching.dll!Microsoft.Framework.Runtime.Caching.Cache.Get(object key, System.Func<Microsoft.Framework.Runtime.Caching.CacheContext, object> factory) Line 24	C#
Microsoft.Framework.Runtime.Abstractions.dll!Microsoft.Framework.Runtime.Caching.CacheExtensions.Get<Microsoft.Framework.Runtime.Compilation.ILibraryExport>(Microsoft.Framework.Runtime.Caching.ICache cache, object key, System.Func<Microsoft.Framework.Runtime.Caching.CacheContext, Microsoft.Framework.Runtime.Compilation.ILibraryExport> factory) Line 9	C#
Microsoft.Framework.Runtime.dll!Microsoft.Framework.Runtime.LibraryManager.GetAllExports(string name, string aspect) Line 137	C#
Microsoft.Framework.Runtime.dll!Microsoft.Framework.Runtime.LibraryManager.GetAllExports(string name) Line 76	C#
Microsoft.AspNet.Mvc.Razor.dll!Microsoft.AspNet.Mvc.Razor.Compilation.RoslynCompilationService.GetApplicationReferences() Line 200	C#
mscorlib.dll!System.Lazy<System.Collections.Generic.List<Microsoft.CodeAnalysis.MetadataReference>>.CreateValue()	Unknown
mscorlib.dll!System.Lazy<System.Collections.Generic.List<Microsoft.CodeAnalysis.MetadataReference>>.LazyInitValue()	Unknown
mscorlib.dll!System.Lazy<System.Collections.Generic.List<Microsoft.CodeAnalysis.MetadataReference>>.Value.get()	Unknown
Microsoft.AspNet.Mvc.Razor.dll!Microsoft.AspNet.Mvc.Razor.Compilation.RoslynCompilationService.Compile(Microsoft.AspNet.Mvc.Razor.Compilation.RelativeFileInfo fileInfo, string compilationContent) Line 73	C#
Microsoft.AspNet.Mvc.Razor.dll!Microsoft.AspNet.Mvc.Razor.Compilation.RazorCompilationService.Compile(Microsoft.AspNet.Mvc.Razor.Compilation.RelativeFileInfo file) Line 48	C#
Microsoft.AspNet.Mvc.Razor.dll!Microsoft.AspNet.Mvc.Razor.Compilation.CompilerCache.OnCacheMiss(Microsoft.AspNet.Mvc.Razor.Compilation.RelativeFileInfo file, string normalizedPath, System.Func<Microsoft.AspNet.Mvc.Razor.Compilation.RelativeFileInfo, Microsoft.AspNet.Mvc.Razor.Compilation.CompilationResult> compile) Line 188	C#
Microsoft.AspNet.Mvc.Razor.dll!Microsoft.AspNet.Mvc.Razor.Compilation.CompilerCache.GetOrAddCore(string relativePath, System.Func<Microsoft.AspNet.Mvc.Razor.Compilation.RelativeFileInfo, Microsoft.AspNet.Mvc.Razor.Compilation.CompilationResult> compile) Line 115	C#
Microsoft.AspNet.Mvc.Razor.dll!Microsoft.AspNet.Mvc.Razor.Compilation.CompilerCache.GetOrAdd(string relativePath, System.Func<Microsoft.AspNet.Mvc.Razor.Compilation.RelativeFileInfo, Microsoft.AspNet.Mvc.Razor.Compilation.CompilationResult> compile) Line 92	C#
Microsoft.AspNet.Mvc.Razor.dll!Microsoft.AspNet.Mvc.Razor.VirtualPathRazorPageFactory.CreateInstance(string relativePath) Line 53	C#
Microsoft.AspNet.Mvc.Razor.dll!Microsoft.AspNet.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(Microsoft.AspNet.Mvc.ActionContext context, string pageName, bool isPartial) Line 272	C#
Microsoft.AspNet.Mvc.Razor.dll!Microsoft.AspNet.Mvc.Razor.RazorViewEngine.GetRazorPageResult(Microsoft.AspNet.Mvc.ActionContext context, string pageName, bool isPartial) Line 215	C#
Microsoft.AspNet.Mvc.Razor.dll!Microsoft.AspNet.Mvc.Razor.RazorViewEngine.FindView(Microsoft.AspNet.Mvc.ActionContext context, string viewName) Line 108	C#
Microsoft.AspNet.Mvc.Extensions.dll!Microsoft.AspNet.Mvc.Rendering.CompositeViewEngine.FindView(Microsoft.AspNet.Mvc.ActionContext context, string viewName, bool partial) Line 75	C#
Microsoft.AspNet.Mvc.Extensions.dll!Microsoft.AspNet.Mvc.Rendering.CompositeViewEngine.FindView(Microsoft.AspNet.Mvc.ActionContext context, string viewName) Line 65	C#
Microsoft.AspNet.Mvc.Extensions.dll!Microsoft.AspNet.Mvc.ViewResult.ExecuteResultAsync(Microsoft.AspNet.Mvc.ActionContext context) Line 65	C#
Microsoft.AspNet.Mvc.Core.dll!Microsoft.AspNet.Mvc.Core.FilterActionInvoker.InvokeResultAsync() Line 723	C#
Microsoft.AspNet.Mvc.Core.dll!Microsoft.AspNet.Mvc.Core.FilterActionInvoker.InvokeResultFilterAsync() Line 688	C#
Microsoft.AspNet.Mvc.Core.dll!Microsoft.AspNet.Mvc.Core.FilterActionInvoker.InvokeAllResultFiltersAsync(Microsoft.AspNet.Mvc.IActionResult result) Line 591	C#
Microsoft.AspNet.Mvc.Core.dll!Microsoft.AspNet.Mvc.Core.FilterActionInvoker.InvokeResourceFilterAsync() Line 359	C#
Microsoft.AspNet.Mvc.Core.dll!Microsoft.AspNet.Mvc.Core.FilterActionInvoker.InvokeAllResourceFiltersAsync() Line 247	C#
Microsoft.AspNet.Mvc.Core.dll!Microsoft.AspNet.Mvc.Core.FilterActionInvoker.InvokeAsync() Line 136	C#
Microsoft.AspNet.Mvc.Core.dll!Microsoft.AspNet.Mvc.MvcRouteHandler.InvokeActionAsync(Microsoft.AspNet.Routing.RouteContext context, Microsoft.AspNet.Mvc.ActionDescriptor actionDescriptor) Line 111	C#
Microsoft.AspNet.Mvc.Core.dll!Microsoft.AspNet.Mvc.MvcRouteHandler.RouteAsync(Microsoft.AspNet.Routing.RouteContext context) Line 85	C#
Microsoft.AspNet.Routing.dll!Microsoft.AspNet.Routing.Template.TemplateRoute.RouteAsync(Microsoft.AspNet.Routing.RouteContext context) Line 149	C#
Microsoft.AspNet.Routing.dll!Microsoft.AspNet.Routing.RouteCollection.RouteAsync(Microsoft.AspNet.Routing.RouteContext context) Line 70	C#
Microsoft.AspNet.Routing.dll!Microsoft.AspNet.Builder.RouterMiddleware.Invoke(Microsoft.AspNet.Http.HttpContext httpContext) Line 36	C#
Microsoft.AspNet.Hosting.dll!Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(Microsoft.AspNet.Http.HttpContext httpContext) Line 26	C#
Microsoft.AspNet.Hosting.dll!Microsoft.AspNet.Hosting.Internal.HostingEngine.Start.AnonymousMethod__0(Microsoft.AspNet.FeatureModel.IFeatureCollection features) Line 78	C#
Microsoft.AspNet.TestHost.dll!Microsoft.AspNet.TestHost.TestServer.Invoke(Microsoft.AspNet.FeatureModel.IFeatureCollection featureCollection) Line 134	C#
Microsoft.AspNet.TestHost.dll!Microsoft.AspNet.TestHost.ClientHandler.SendAsync.AnonymousMethod__0() Line 73	C#
mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task>.InnerInvoke()	Unknown
mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown
```

**Comment by dougbu** [comment] 2015-06-14 19:31
Another workaround is to skip the project (un-check it in VS's Configuration Manager) rather than disabling it entirely (unloading it from the solution). This works because VS lets DTH know the disabled project exists and that's enough for DTH to compile everything.

**Comment by dougbu** [comment] 2015-06-14 19:51
Same scenario works fine in MVC 5.

**Comment by IsaacSee** [comment] 2015-06-15 08:16
Thanks for the investigations.

Just a precision about the workaround you posted : the reason for the "DisabledProject" to be unloaded is that it contains a lot of client files. All theses files make visual studio freeze for minutes at start or when we manipulation solution explorer. So we use another IDE to work with theses files, but we still need the project to be included in our main website so that the "DisabledProject" folder stays included during the publication process. 

So : we need a way to have a project included in our website, without loading it in visual studio, or a way to prevent visual studio to ignore (completely, also from search) all the file from the "DisabledProject". Right now we could not find a good way to do it. 

Is there a way to prevent VS project auto inclusion when it is listed as a dependancy ?

**Comment by IsaacSee** [comment] 2015-06-15 08:34
By the way thanks for the workaroud, the following process works : 
- Loading the project
- Unchecking it from Configuration Manager
- Then unload the project again
The project stays included in publication process.

**Comment by dougbu** [comment] 2015-07-17 22:09
Removed Investigate label. Main design question is whether a fix for this issue should be implemented in Visual Studio (Web Tools Extensions in particular) or Design Time Host (i.e. the aspnet/dnx repo).

**Comment by dougbu** [comment] 2015-07-27 18:28
Will track as a Visual Studio issue: aspnet/Tooling-Internal#430. That issue also describes a simpler repro using a console application.

**Closed by dougbu** 2015-07-27 18:28 UTC
Labels: 2 - Working, needs design

**Comment by IsaacSee** [comment] 2015-08-06 11:56
Hello, 
Since I can not access to Tooling-Internal repository, do you have any news or workaround on this ?

**Comment by dougbu** [comment] 2015-08-06 16:34
No news but the above discussion includes two workarounds:
- Execute the project outside Visual Studio.
- As you said:

> Loading the project
Unchecking it from Configuration Manager
Then unload the project again The project stays included in publication process.

**Comment by IsaacSee** [comment] 2015-08-25 13:12
Thanks for your answer. But as I edited my post, the last workaround does not work after restarting Visual Studio. Is there a way to simply exlude folders from visual studio (vNext Library Project) so that they are not loaded in the IDE ?
