### ISSUE TITLE
Move OnActionExecuting from Controller to ControllerBase

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/Mvc#7949] opened 2018-06-21 11:30 UTC
The [`Controller`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Controller.cs) class contains the methods `OnActionExecuted`, `OnActionExecuting`, and `OnActionExecutionAsync`.

These methods are not only useful in the context of a MVC application with views, they are also useful for a Web API. When using a Web API there is a practice of inheritering from [`ControllerBase`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs) rather than `Controller` as per the Microsoft documentation.
https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1#derive-class-from-controllerbase

Perhaps it should be considered to move the  `OnActionExecuted`, `OnActionExecuting`, and `OnActionExecutionAsync` methods from `Controller` to `ControllerBase`.

**Comment by rynowak** [comment] 2018-06-21 18:30
These methods exist on controller for legacy reasons and to make sure that developers can migrate existing code. If you want this functionality on `ControllerBase` - just implement the appropriate filter for your use case on your controller type - there's nothing special about these methods being built it, controllers can implement filter interfaces.

**Comment by pranavkm** [comment] 2018-06-21 18:49
Closing as by design.

**Closed by pranavkm** 2018-06-21 18:49 UTC
Labels: by design
