### ISSUE TITLE
Uploading formfile I have to set [FromForm(Name="formfile"]

### ISSUE THREAD

**Issue by johnkwaters** [aspnet/Mvc#7867] opened 2018-06-04 20:50 UTC
It used to match the name of the variable in the method with the name of the form...but now I have to explicitly spell it out with the Name attribute.
This is after upgrading to 2.1 and adding ApiController attribute.
I thought this was less work not more? Why do I have to tell the binding that the name of the form upload is the SAME as the name of the method variable?

`public async Task<int> UploadTenantLogoAsync([FromForm(Name = "formfile")] IFormFile formfile)`

**Comment by mkArtakMSFT** [comment] 2018-06-04 21:29
Thanks for contacting us, @johnkwaters.
@pranavkm, can you please answer the question here?

**Comment by pranavkm** [comment] 2018-06-04 23:22
This is yet another manifestation of https://github.com/aspnet/Mvc/issues/7609. We're addressing this in 2.1.1. Unfortunately short of adding adding the `[FromForm(Name = "formfile")]` attribute or not using `ApiController`, there isn't a very good resolution for this in 2.1.0

**Comment by mkArtakMSFT** [comment] 2018-06-05 17:06
Closing this issue as a dupe of the referenced #7609.

**Closed by mkArtakMSFT** 2018-06-05 17:06 UTC
Labels: investigate

**Comment by johnkwaters** [comment] 2018-06-19 03:17
Looks like it was not fixed in 2.1.1?
