### ISSUE TITLE
Look into DI for ViewComponents/TagHelpers

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#2716] opened 2015-06-18 17:58 UTC
We've got a very streamlined experience today for registering controllers with DI and allowing you to use advanced DI features there. We should look into providing the same for ViewComponents and TagHelpers.

**Comment by danroth27** [comment] 2016-02-12 18:35
Duplicate of https://github.com/aspnet/Mvc/issues/4087

**Closed by danroth27** 2016-02-12 18:35 UTC
Labels: 1 - Ready, enhancement
