### ISSUE TITLE
Bug in Razor Page Model

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#7554] opened 2018-03-27 00:11 UTC
_From @rishabhack on March 26, 2018 21:22_

```C#
public  JsonResult GetResult(){
    return Json();
}
```

Will  give error the name 'Json' does not exist in current context in razor page modal while working fine when page is drives from controller
I can't use razor page model due to this serious issue and need to move to MVC approach instead of page modal. Please Resolve this Bug.

_Copied from original issue: aspnet/Home#3003_

**Comment by Eilon** [comment] 2018-03-27 00:13
I believe this is by-design because the `Json` helper is meant for APIs, not pages.

There are some historical notes in https://github.com/aspnet/Mvc/issues/5846 under the "Methods Pages Don't Need" section.

**Comment by pranavkm** [comment] 2018-03-27 16:22
You could always new up an instance of `JsonResult`:

```C#
public  IActionResult OnPost(){
    return new JsonResult(...);
}
```

**Comment by mkArtakMSFT** [comment] 2018-03-27 16:53
Thank you for your feedback.
We're closing this issue as the behavior discussed seems to be by design.

**Closed by mkArtakMSFT** 2018-03-27 16:53 UTC

**Comment by rishabhack** [comment] 2018-06-14 04:24
thanks @Eilon ,@pranavkm
