### ISSUE TITLE
Using Attribute and Convention Based Routing Together

### ISSUE THREAD

**Issue by oruchreis** [aspnet/Mvc#4742] opened 2016-05-25 08:19 UTC
We can combine  attribute routing with convention-based routing as mentioned here: [Attribute Routing in ASP.NET MVC 5](https://blogs.msdn.microsoft.com/webdev/2013/10/17/attribute-routing-in-asp-net-mvc-5/#enabling-attribute-routing)
And for using both we should use MapMvcAttributeRoutes method before convention routing implementations:

``` c#
    public static void RegisterRoutes(RouteCollection routes)
    {
        routes.IgnoreRoute(“{resource}.axd/{*pathInfo}”);

        routes.MapMvcAttributeRoutes();

        routes.MapRoute(
            name: “Default”,
            url: “{controller}/{action}/{id}”,
            defaults: new { controller = “Home”, action = “Index”, id = UrlParameter.Optional }
        );
    }
```

But the `MapMvcAttributeRoutes` removes action methods from `StandardRouteMethods` which the convetion-based routing uses. So we can't use convetion-based routing if we define a routing like that:

``` c#
    [RoutePrefix("d")]
    [Route("{action=index}")]
    public class DefaultController : Controller
    {
        [Route]
        public ActionResult Index()
        {
            return View();
        }

        [Route("f")]
        public ActionResult Foo()
        {
            return View();
        }
    }
```

If we want to reach the url: "/Default/Foo" which is proper for "{controller}/{action}/{id}" convention route, an exception occures like that `A public action method 'Foo' was not found on controller 'Namespace...DefaultController'.`. 

There is an explanation in the source code of ActionMethodSelectorBase:

``` c#
        protected void Initialize(Type controllerType)
        {
            //////
            // The attribute routing mapper will remove methods from this set as they are mapped.
            // The lookup tables are initialized lazily to ensure that direct routing's changes are respected.
            StandardRouteMethods = new HashSet<MethodInfo>(ActionMethods);
        }
```

If we can combine both, why this is happening? Is this a bug or an intentionally behaviour? Are there any workaround to use both at same time

**Comment by davidfowl** [comment] 2016-05-25 08:23
Is this an MVC Core bug?

**Comment by oruchreis** [comment] 2016-05-25 08:31
alack! sorry my bad, I didn't read the description at readme.md when I saw "aspnet/Mvc" at the address bar :(

**Comment by Eilon** [comment] 2016-05-25 16:55
@rynowak I believe with MVC 5.x this was by design, right?

**Comment by rynowak** [comment] 2016-05-25 17:07
This is by default in 5.x as well as MVC Core. Routing for an individual action is either/or - you can't do both styles for the same action.

**Comment by Eilon** [comment] 2017-06-09 22:08
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by Eilon** 2017-06-09 22:08 UTC
Labels: question
