### ISSUE TITLE
Error: CS1703: System.Runtime, Version=4.1.2.0

### ISSUE THREAD

**Issue by tarekgh** [aspnet/Mvc#7058] opened 2017-11-16 19:42 UTC
_From @Vohuman on November 15, 2017 5:6_

When my MVC.core project tries to open any page, I face with the following error:

> CS1703: An assembly with the same identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported.

I tried to clean Temporary folder and checked about the conflicts within the projects but I found nothing.  

_Copied from original issue: dotnet/corefx#25260_

**Comment by tarekgh** [comment] 2017-11-16 19:42
_From @karelz on November 16, 2017 18:8_

Do you have a (minimal) repro for your failure?
Are you running on .NET Core or on .NET Framework?
Are you able to reproduce the problem outside of MVC? (if not, starting the bug report in MVC repo might be best)

**Comment by egovova11** [comment] 2017-11-21 10:21
Same problem here.

`Compiler Error Message: CS1703: An assembly with the same identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references.`

Detailed compiler output:
```
Microsoft (R) Visual C# Compiler version 4.7.2046.0

for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\project_name\1f41a75d\811b1a5f\assembly\dl3\1a40273d\895bc1cf_9a62d301\System.Runtime.DLL: error CS1703: An assembly with the same identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references.
c:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll: (Location of symbol related to previous error)
```

This occurs only while running application under Local IIS, IIS Express works fine.
ASP.NET MVC4 application is targeting .NET Framework 4.6.1, references several .NET Standard 2.0 projects. 

IIS: 10.0.15063.0
Visual Studio: 15.4.4
.Net Core SDKs: 2.0.0, 2.0.2, 2.0.3 

OS Edition: Windows 10 Enterprise x64
OS Version: 1703
OS Build: 15063.674

**Comment by tarekgh** [comment] 2017-11-21 17:05
CC @joperezr

**Comment by joperezr** [comment] 2017-11-21 18:01
Hello @egovova11 did you add the System.Runtime reference to one of your projects? I would expect this to just come automatically as part of the tooling, so what the error tells me is that you are trying to add a reference manually and the tooling is also trying to add the reference.

**Comment by egovova11** [comment] 2017-11-22 11:24
Hi @joperezr 
No, no project references any version of System.Runtime directly. 
I found that if I reference net standard lib from net framework lib project, which in turn is referenced by MVC app project, everything works fine. 
It looks like when csc.exe is called by inetsrv to compile dynamic assemblies for asp.net, it is provided with all assemblies which ended up in bin/debug, including version of System.Runtime (the one not from GAC) in my case.

**Comment by joperezr** [comment] 2017-11-22 17:27
ok, I see thanks for checking, glad that your scenario is working now.

> However, I was unable to reproduce the same with just MVC4 project + referenced Net Standard library project.

I thought that was your scenario, or are you saying that with your original project you didn't have a project-to-project reference and instead only had references to nuget packages?

**Comment by egovova11** [comment] 2017-11-23 08:21
In my scenario I have project-to-project reference (total around 70 projects in solution plus some third-party non-nuget libraries targeting NET4.0 and NET 4.5), and the issue occured specifically when ASP.NET project directly referenced one of NET Standard library projects + I was debugging application with local IIS:
1. `ASP.NET Project (NET Framework 4.6.1) -> Library Project (NET Standard 2.0)`
I don't encounter abovementioned error if I debug under IIS Express OR if I have references like:
2. `ASP.NET Project (NET Framework 4.6.1) -> Library Project (NET Framework 4.6.1) -> Library Project (NET Standard 2.0)`

What I am unable to do is to reproduce issue with just debugging stripped down version (literally two projects in solution) under local IIS.
`ASP.NET Project (NET Framework 4.6.1) -> Library Project (NET Standard 2.0)`
I tried adding different nuget packages referencing System.Runtime to lib project, but still no luck.

I can provide full list of dlls used in csc.exe call to compile temprorary dll for IIS if it helps.

**Comment by joperezr** [comment] 2017-11-27 17:52
That is very weird I would actually expect the opposite to happen (issue reproing on scenario 2 but not in 1). Yes, could you please provide the csc call for scenario 1 along with the full exception you are hitting at compile time?

**Comment by egovova11** [comment] 2017-11-28 10:47
[IIS error page.txt](https://github.com/aspnet/Mvc/files/1509460/IIS.error.page.txt)
This is what IIS shows when I'm trying to access any page of the application using first scenario. `CompanyName.ProductName.*.dll` and `CommonLibrary.dll` are our projects, `ProductName.dll` is ASP.NET application, others are acquired either from nuget or from GAC.

**Comment by joperezr** [comment] 2017-11-28 18:00
cc @dsplaisted Looks like in here, msbuild extensions is adding a reference to System.Runtime facade from the support package even though it was already referenced, which is causing csc to fail to compile because we are passing in System.Runtime.dll as reference two times. Can you take a look?

**Comment by egovova11** [comment] 2018-01-16 13:27
The issue still persists. Is there any updates on that?

**Comment by mkArtakMSFT** [comment] 2018-01-16 17:59
Hi @dsplaisted. Did you get a chance to look into this issue? Thanks!

**Comment by bencyoung** [comment] 2018-01-22 15:17
I'm also seeing this and it's causing lots of issues. For instance my app.config file contains an assembly redirect:

```
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
```

Which I think is the .NET 4.7.1 version. However if I package up the exe as a NuGet package it doesn't get a dependency on this version, it gets one on 4.1.1.0 and so extracting all the dlls from the dependencies puts a dll with the wrong version into the folder and I get:

```

=== Pre-bind state information ===
LOG: DisplayName = System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///F:/Dev/Deploy/Auth3/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = FIS.Risk.Core.AuthenticatorService.exe
Calling assembly : Microsoft.CodeAnalysis, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: F:\Dev\Deploy\Auth3\FIS.Risk.Core.AuthenticatorService.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 4.0.20.0 redirected to 4.1.2.0.
LOG: Post-policy reference: System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///F:/Dev/Deploy/Auth3/System.Runtime.DLL.
LOG: Assembly download was successful. Attempting setup of file: F:\Dev\Deploy\Auth3\System.Runtime.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

**Comment by bencyoung** [comment] 2018-01-22 15:18
In fact the assembly redirects section is massive, which makes things pretty tricky to manage...

**Comment by mkArtakMSFT** [comment] 2018-01-23 18:01
Hi @tarekgh, this doesn't seem like an MVC issue. Should we move it back to corefx repo?

**Comment by tarekgh** [comment] 2018-01-23 18:04
@joperezr can evaluate and confirm that. 

CC @AlexGhiondea

**Comment by joperezr** [comment] 2018-01-23 18:15
I agree it doesn't seem like an MVC issue but it is not corefx either. This seems to be a tooling bug so probably the right place to put it would be on the dotnet/sdk repo. That said, do you mind checking if your app's app.config on the bin folder have any binding redirects to System.Runtime? Even after having both dlls referenced I would  have expected a binding redirect to be automatically generated by the tooling forcing to use app local one, so that you wouldn't get the issue you are hitting now. Can you try downloading latest VS (15.5.4 at the moment) and try building again and check your app.config?

**Comment by bencyoung** [comment] 2018-01-24 07:40
So this is a bit of an edge case for us. The app runs fine when built and run because somehow the .NET 4.7.1 System.Runtime gets into the bin folder. However if you download the exe as a nuget package, and extract all its dependencies then the wrong System.Runtime ends up used (an earlier version, so that if you deploy the same app.config it still doesn't work, because it's redirected "past" the version deployed).

The huge list of binding redirects is also going to be a pain to manage I think!

**Comment by joperezr** [comment] 2018-01-24 17:16
> because somehow the .NET 4.7.1 System.Runtime gets into the bin folder.

This is because of our tooling, we automatically inject the right shims that will make your app run succesfully.

> However if you download the exe as a nuget package

How are you packaging it? and which TFM are you targeting with your package? Do you have a pointer to the package somewhere so that I can inspect it?

**Comment by mkArtakMSFT** [comment] 2018-01-24 18:04
Hi @nguerrera. According to @joperezr, this belongs to dotnet/sdk repo. Can you please move it over? //cc: @eerhardt

**Comment by bencyoung** [comment] 2018-01-25 07:50
I'm afraid I can't send you the still we have. I'll see if I can some up with a repo.

To extract dlls we have a custom tool called "Unpackd" that downloads a set of NuGet packages (using the 4.0 API) and then extracts all the dlls from them for a particular target. We use this so our builds can flow through TeamCity artifacts as well as NuGet, and so that we can deploy an application defined by a set of packages to a folder. It works great for older .NET but not so much for netstandard/full mixes at the moment!

**Comment by mkArtakMSFT** [comment] 2018-04-05 20:53
Hi everyone. We're closing this issue as it's not related to MVC. Please file an issue in an appropriate repo and reference this one from it.

**Closed by mkArtakMSFT** 2018-04-05 20:53 UTC
Labels: external

**Comment by tarekgh** [comment] 2018-04-05 21:02
@mkArtakMSFT would be nice to move it to dotnet/sdk

**Comment by nguerrera** [comment] 2018-04-05 21:12
@joperezr @alexghiondea @dsplaisted  Is this one of the issues with binding redirects that was already fixed, or one that is already tracked? Do we really need a new bug in dotnet/sdk?
