### ISSUE TITLE
Clientside Validation Attributes not added if rendering same property multiple times

### ISSUE THREAD

**Issue by JeremySkinner** [aspnet/Mvc#7081] opened 2017-11-24 12:38 UTC
// cc @rynowak 

I've run into another issue when working on the .net core integration for [FluentValidation](https://github.com/jeremyskinner/FluentValidation) 

If you render the same field in your view multiple times, validation attributes are only added to the first instance of this field. This is because of an explicit check in the `AddAndCheckValidationAttributes` method in the ValidationHtmlAttributeAdapter: 

https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/ValidationHtmlAttributeProvider.cs#L80-L84

Looking at the tests, this appears to be be by design: https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/test/Microsoft.AspNetCore.Mvc.ViewFeatures.Test/ViewFeatures/DefaultValidationHtmlAttributeProviderTest.cs#L195

...but I'm struggling to understand the reasoning for this. Surely if you render the property twice on the screen and the property is a required field, you'd want the required attribute to be applied to both instances of the field? Or am I missing something?

**Comment by Eilon** [comment] 2017-11-27 19:06
@dougbu do you remember why the code does this?

I do remember that it's been this way for ages, but I can't quite remember why.

**Comment by dougbu** [comment] 2017-11-27 19:44
The feature appears to have been in the code for ages. In fact `FormContext.RenderedFields` and the `FormContext.RenderedField(...)` methods exist only to enable this one-time rendering of validation attributes. Those were part of the initial MVC 4.0.0 publication to https://aspnetwebstack.codeplex.com (now visible at https://github.com/aspnet/AspNetWebStack/commit/0f8c45fe03).

Mostly guessing: I suspect the reasoning was multiple fields with the same name in one form would otherwise cause duplicate messages in a validation summary.  In some cases e.g. `[Required]`, only one field needs a value. And, the jQuery Validation hooks (especially [`onError(...)`](https://github.com/aspnet/jquery-validation-unobtrusive/blob/master/src/jquery.validate.unobtrusive.js#L51-L66) due to the single-element `.attr(...)` call) is only guaranteed to do the **Right Thing:tm:** for the first element with the expected `data-valmsg-for` attribute value.

**Comment by dougbu** [comment] 2017-11-27 19:48
BTW @JeremySkinner in the "render the property twice on the screen" scenario, why use editable fields for additional display purposes?

**Comment by dougbu** [comment] 2017-11-29 17:53
@Eilon we should either close this as "by design" or an the ability (e.g. an option) to opt into rendering the attributes more than once per form. If we do the second, would need to test Unobtrusive jQuery Validation thoroughly and perhaps tweak its design.

I'm not suggesting we change the default approach because that could have unintended consequences.

**Comment by dougbu** [comment] 2017-11-29 17:54
Cleared the `investigate` label.

**Comment by rynowak** [comment] 2017-12-18 16:46
>  this one-time rendering of validation attribute

@JeremySkinner is the problem here that the user wants to render the client side attributes more than once per-form? or more than once per-page?

**Comment by JeremySkinner** [comment] 2017-12-18 16:48
@rynowak in this particular case it appears to be in the same form, but one is inside a partial view and one isn't.

**Comment by rynowak** [comment] 2017-12-18 16:53
AH ok. If this is inside the same form, this this is definitely intended on our part. We can find a way to solve this though, but we block this by default on purpose.

**Comment by JeremySkinner** [comment] 2017-12-18 16:55
Ok, thanks - that's good to know that it is actually intentional.

**Comment by rynowak** [comment] 2017-12-18 16:56
For instance you can use this https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/FormContext.cs#L139 to 'forget' that you rendered a field.

**Comment by mkArtakMSFT** [comment] 2017-12-27 18:47
Hi @JeremySkinner. Do you expect any other actions here?

**Comment by JeremySkinner** [comment] 2017-12-27 19:02
No - please feel free to close. Thanks for the explanations.

**Comment by mkArtakMSFT** [comment] 2017-12-28 21:44
Thanks @JeremySkinner!

**Closed by mkArtakMSFT** 2017-12-28 21:44 UTC
