### ISSUE TITLE
Regression: #4652 again in 2.1.0-preview1-final

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/Mvc#7595] opened 2018-04-04 11:31 UTC
Env:
- VS 15.7.0 Preview 2.0
- ASP.NET Core 2.1 Web Application (MVC)
- `<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview1-final" />`

The same issue #4652 I reported back in 2016 appears again.

```c#
    [ModelBinder(BinderType = typeof(MyModelBinder))]
    public class MyModel {
        public string Foo;
    }

    public class MyModelBinder : IModelBinder {
        public Task BindModelAsync(ModelBindingContext bindingContext) {
            var model = new MyModel {
                Foo = "Bar"
            };
            bindingContext.Result = ModelBindingResult.Success(model);
            return Task.CompletedTask;
        }
    }

    public class HomeController : Controller {
        public IActionResult Index(MyModel model) {
            return View();
        }
    }
```

`BindModelAsync` is not invoked.

/cc @GoshaFighten @San4es

**Comment by dougbu** [comment] 2018-04-04 18:10
Very strange. The tests I added in e63f094a5f should still exist, despite our various refactorings in this area. I'm not aware of any test removals or Preview 1 failures.

Suggest we investigate for realz.

@AlekseyMartynov do you have a new version of https://github.com/AlekseyMartynov/aspnetcore-rc2-modelbinding? That app doesn't exist anymore.

**Comment by AlekseyMartynov** [comment] 2018-04-04 18:57
The code snippet from https://github.com/aspnet/Mvc/issues/7595#issue-311191359 should be enough to demonstrate the problem.

- Create ASP.NET Core 2.1 MVC app in VS
- Replace code in HomeController.cs
- Debug

**Comment by dougbu** [comment] 2018-04-04 20:12
Thanks for reporting this issue. I agree that this is a Preview 1 bug; it also exists in our `dev` branch.

The only workaround I can see when using Preview 1 is to copy the `[ModelBinder(...)]` atrribute to the parameter:
``` c#
public class HomeController : Controller {
    public IActionResult Index([ModelBinder(BinderType = typeof(MyModelBinder))] MyModel model) {
        return View();
    }
}
```

With our nightly builds, you could disable top-level validation in `Startup.ConfigureServices(...)`:
``` c#
services
    .AddMvc(options => options.AllowValidatingTopLevelNodes = false)
    .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
```
Or, stick with `CompatibilityVersion.Version_2_0` for now (again, only with our nightly builds):
``` c#
services
    .AddMvc()
    .SetCompatibilityVersion(CompatibilityVersion.Version_2_0);
```

**Comment by dougbu** [comment] 2018-04-04 20:33
@mkArtakMSFT @danroth27 this is a strong candidate the milestone after Preview 2. By default in 2.1 mode, attributes on a parameter's type e.g. `[Bind]`, `[BindProperty]` or `[ModelBinder]` are no longer reflected in the parameter's `ModelMetadata`. The same goes for any (custom) `[Validation]` and `[Display]` (and similar) attributes.

Will also need to have another look at the tests added in e63f094a5f to make sure they're run with `AllowValidatingTopLevelNodes` enabled.

**Comment by dougbu** [comment] 2018-04-04 20:43
Looks like the problem is here: https://github.com/aspnet/Mvc/blob/8e323a8e1e78b520e9a1c2a5a5f64139d5c210d0/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Metadata/ModelAttributes.cs#L182-L185

**Comment by mkArtakMSFT** [comment] 2018-04-05 16:11
Thanks for looking into this, @doug.  I've assigned this to you as you already have context.

**Comment by dougbu** [comment] 2018-04-15 19:58
> ~~revert changes to `DefaultApplicationModelProvider` in #7628 / d995b0418a~~

Ignore this idea. That fix overlaps this one but isn't actually the root cause of #7350. That is, we need both fixes.

**Comment by dougbu** [comment] 2018-04-17 20:00
- e0e96ce53b in `release/2.1`
- cd6d130a8d merged that into `dev`

**Closed** 2018-04-17 20:02 UTC
Labels: 2 - Working, bug, cost: S
