### ISSUE TITLE
DataAnnotationsClientModelValidator<TAttribute> should localize the ErrorMessage, not the DisplayName

### ISSUE THREAD

**Issue by muratcakir** [aspnet/Mvc#3434] opened 2015-10-28 19:33 UTC
When DataAnnotations localization is active, the `GetErrorMessage` method in class `DataAnnotationsClientModelValidator<TAttribute>` returns the localized display name of the passed ModelMetadata, but it should be the localized value of `Attribute.ErrorMessage`. Exactly like in class `DataAnnotationsModelValidator`:

```c#
string errorMessage = null;
if (_stringLocalizer != null &&
    !string.IsNullOrEmpty(Attribute.ErrorMessage) &&
    string.IsNullOrEmpty(Attribute.ErrorMessageResourceName) &&
    Attribute.ErrorMessageResourceType == null)
{
    errorMessage = _stringLocalizer[Attribute.ErrorMessage]; // CORRECT!
}
```

**Comment by dougbu** [comment] 2015-10-28 21:02
Suspect this is a dupe of #3414.

**Comment by Anderman** [comment] 2015-11-11 09:58
Localized and not localized return display name

```
          Attribute.ErrorMessageResourceType == null)
            {
                return _stringLocalizer[displayName];
            }
            
            return Attribute.FormatErrorMessage(displayName);
```

**Comment by Anderman** [comment] 2015-11-11 14:24
The GetErrorMessage is also called from other attributes. 
From the Maxlength parameter you need to supply both Displayname and length. 
```
return _stringLocalizer[Attribute.ErrorMessage,displayName, Attribute.Length];
```

**Comment by Anderman** [comment] 2015-11-11 14:30
I think you use this `!string.IsNullOrEmpty(Attribute.ErrorMessage)` to check of a custom error message is set. But this is not the case with the Emailaddress attribute. Maybe Attribute.CustomErrorMessageSet to check if a custom error message is set

**Comment by Anderman** [comment] 2015-11-11 16:50
CompareAttribute missing code to localized.
```
 public string FormatErrorMessage(ClientModelValidationContext context)
            {
                var displayName = context.ModelMetadata.GetDisplayName();
                return string.Format(CultureInfo.CurrentCulture,
                                     ErrorMessageString,
                                     displayName,
                                     GetOtherPropertyDisplayName(context));
            }
```

**Comment by dougbu** [comment] 2015-11-11 17:55
Looks like there are a few issues mixed into this one.

1. @muratcakir and @Anderman you're correct that `DataAnnotationsClientModelValidator<TAttribute>.GetErrorMessage(...)` and `DataAnnotationsModelValidator.Validate(...)` are inconsistent. I suspect @Anderman is also correct that the `IStringLocalizer` invocation in both should be `_stringLocalizer[Attribute.ErrorMessage, DisplayName]`. If not, `DataAnnotationsClientModelValidator<TAttribute>` should be changed to match `DataAnnotationsModelValidator`.
2. @Anderman I suggest filing a new issue about using the correct parameters when looking up the error message for some `[Validation]` subclasses e.g. `[Compare]` and `[MaxLength]`. This also applies to both `DataAnnotationsModelValidator` and `DataAnnotationsClientModelValidator<TAttribute>`.
3. @Anderman I suggest also filing a new issue about bringing `CompareAttributeAdapter` into the `IStringLocalizer` fold.

**Closed** 2015-11-30 19:18 UTC
Labels: 2 - Working, bug
