### ISSUE TITLE
Can't create MVC plugins in .NET Core

### ISSUE THREAD

**Issue by livarcocc** [aspnet/Mvc#7825] opened 2018-05-24 16:38 UTC
_From @gordon-matt on May 24, 2018 1:50_

I'm having a very big problem with migrating my plugins system over to .NET Core. I keep getting the following error for any plugins that contain MVC views, controllers, etc:

```
An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
Generated Code
One or more compilation references are missing. Ensure that your project is referencing 'Microsoft.NET.Sdk.Web' and the 'PreserveCompilationContext' property is not set to false.

    Type expected

            [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
            public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
            [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
            public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
            [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
            public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<JQueryFormBuilderBlock> Html { get; private set; }

        }

    }
    #pragma warning restore 1591
	
	//etc...
```

And when I set the project SDK to `<Project Sdk="Microsoft.NET.Sdk.Web">`, then I get the following error instead:

```
System.InvalidOperationException: Cannot find compilation library location for package 'Mantle.Plugins.Messaging.Forums'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.get_CompilationReferences()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.LazyMetadataReferenceFeature.get_References()
   at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
   at Microsoft.AspNetCore.Razor.Language.RazorTemplateEngine.GenerateCode(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CreateCacheEntry(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SaasKit.Multitenancy.Internal.TenantResolutionMiddleware`1.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

After searching around a bit, I tried the following to no avail:

```
<MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
```

I could really use some help here, as it seems that creating plugins in .NET Core is impossible.

Is there anything else you need that would be helpful? This is for a CMS of mine that I am porting from MVC5 to .NET Core 2. I have not yet made the repo public because it is not ready, but I am happy to add individuals here if viewing the source code helps solve the issue.

_Copied from original issue: dotnet/sdk#2268_

**Comment by livarcocc** [comment] 2018-05-24 16:38
_From @svick on May 24, 2018 13:48_

Your issue seems to be specific to ASP.NET Core MVC, so I think you should post it to [the aspnet/Mvc repo](https://github.com/aspnet/Mvc) instead.

**Comment by livarcocc** [comment] 2018-05-24 16:38
I will move this issue to aspnet/mvc. Thanks for the suggestion @svick

**Comment by mkArtakMSFT** [comment] 2018-05-24 17:01
@gordon-matt, could you please share a sample repro project with us to help with investigation?

**Comment by pranavkm** [comment] 2018-05-24 18:03
Runtime compilation of views really doesn't play with the kind of assembly loading mechanism you're trying to achieve here. The recommendation is to compile views at build (https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/sdk?view=aspnetcore-2.1). More pertinently, our recommendation is to use [OrchardCore](https://github.com/OrchardCMS/OrchardCore) rather than hand rolling your plug in system. You're likely going to run in to other issues around building and loading plugins that are solved by OrchardCore.

**Comment by gordon-matt** [comment] 2018-05-24 23:14
Guys, thanks for your responses.

@pranavkm, that link telling me to set the SDK as `<Project SDK="Microsoft.NET.Sdk.Razor">` seems it might do the trick. Unfortunately, when I modify one of the plugins like that I get the following error and the project then refuses to load:

```
LimitedFunctionality
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: catalog
   at Microsoft.Requires.NotNull[T](T value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.GetDebuggerTargets(IPropertyPagesCatalog catalog, IImmutableDictionary`2 dynamicTargets)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.<LinkExternalInput>b__42_2(Tuple`2 bunch)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.ProcessMessage(Func`2 transform, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.<>c__DisplayClass10.<.ctor>b__3(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: catalog
   at Microsoft.Requires.NotNull[T](T value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.GetDebuggerTargets(IPropertyPagesCatalog catalog, IImmutableDictionary`2 dynamicTargets)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.<LinkExternalInput>b__42_2(Tuple`2 bunch)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.ProcessMessage(Func`2 transform, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.<>c__DisplayClass10.<.ctor>b__3(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---
```

And yes, I am using `.NET Core SDK 2.1 RC1 or later` as is required. My version when checking with the **dotnet --version** comand is 2.1.201 and I see that same version installed in `C:\Program Files\dotnet\sdk`.

As for OrchardCore, that's a CMS. As I stated before, my project is also a CMS / framework. Why would I build mine on top of someone else's? Moreover, it's not something new, but rather a project I have built up over a few years on MVC5, which I am now porting to .NET Core.

Anyway, I have added you as a "contributor" to my project, as there seems to be no such thing as a readonly user on a private repo here. Obviously please don't push any changes, but to get started, it's not too difficult, just do the following:

1. Follow the instructions to setup from the README file (but ignore the part about the database, as it's a little bit of a pain to get users and basic data up and ready so I link here to a download (about 450kb) of the database: http://www.mediafire.com/file/icypfp9bt8ta51o/MantleCMS.zip/file

2. Build the app and try run it.. you will get the message about "Cannot find compilation library location for package XYZ".

The system is trying to load plugins from the MantleCMS/Plugins directory... those are files copied via "Post Build Events" from the actual plugins which you can find in the "Plugins" solution folder in Visual Studio. If you open the .csproj files for those, you will see they've been set to use **Microsoft.NET.Sdk.Web**. Not doing so gives the other error I mentioned in the original post.

Hope you can help. Thanks

**Comment by gordon-matt** [comment] 2018-05-25 07:57
OK I migrated to .NET Core 2.1, but now I have a different error... See screenshot below

![capture1](https://user-images.githubusercontent.com/2860937/40533074-b732a4b4-6040-11e8-9b96-d3bc6c0a7f30.PNG)

Basically, the error messages are because the plugins have been setup with `<Project Sdk="Microsoft.NET.Sdk.Razor">` and it's now trying to build the razor views that are present in the **/Plugins** folder in my main app. This folder should be ignored, because I simply copy all DLLs, views and content (JS, CSS, etc) to the **/Plugins** folder for loading those plugins at runtime. At least, that's what I did in MVC5 anyway. I don't actually want razor views compiled at all, but read at runtime, like I had before. What can I do?

If you want, you can see the **feature/SDK2_1** branch of my repo. Just try build it and you'll see that error.

**Comment by gordon-matt** [comment] 2018-05-25 13:54
@pranavkm / @livarcocc OK guys ignore the last issue above, as that was fixed by my excluding the **/Plugins** folder from the main web project, which is what I should have done before. So that error is taken care of. However, I still get the same old error as follows:

```
Cannot find compilation library location for package 'Mantle.Plugins.Messaging.Forums'
```

If you run my app (using the database from the link I provided), you don't need to care about navigating around the app, just paste the following in the address bar:

`/admin/blocks/content-blocks/get-editor-ui/A500591F-86AE-49DB-AB5E-E949B4DF860A`

That will try to load a Razor view from one of the plugins and give that error message.

**Comment by pranavkm** [comment] 2018-05-25 15:51
> This folder should be ignored, because I simply copy all DLLs, views

In general, it's going to be difficult for you to compile views for dynamically loaded views at runtime. You should copy the build time compiled .Views dll from your plugins over and avoid copying both cshtml files and deps files from plugins.

**Comment by gordon-matt** [comment] 2018-05-25 16:02
Sounds like I'm going to have to make a lot of changes to my existing code, but if that's the only way, then so be it. It worked great in MVC5.. I don't know why it's such a hassle in .NET Core. Anyway, could you please point me in the right direction on how to go about what you suggested?

By the way, I would imagine that wanting runtime plugins is a fairly common use case for many projects. I would think some official plugin system for ASP.NET Core would be in order. Ideally, I think some NuGet-based plugin system where packages can be installed/uninstalled from a local directory though some very simple API would be the best thing to do. How about it? Shall I suggest that in this repo or elsewhere? Where's the best place for such a suggestion?

**Comment by sebastienros** [comment] 2018-05-25 17:37
@gordon-matt Use the Orchard Core Framework. It will provide you with plugin support (from Nuget packages also, and custom galleries if you want), dynamically configurable features (coming from plugins), multi-tenancy and theming. You can build any modular app on top of that, like we do to build the Orchard Core CMS. It will save you a lot of work, and probably provide you with features you would not have time to implement by yourself.

We tried to handle dynamic module loading, but there are so many issues to account for. You might get it to work, sure, but what do you do on a deployed site? Do you allow users to install anything from a gallery, and have the site be recycled? What if it's not binary compatible? Do you deploy stuff without testing? What about docker scenarios, where you would lose these files. What about farm scenarios where only one server would get the plugin? We've been there, then decided to stop doing it. In the end even with that feature we would recommend all customer from disabling dynamic loading for all these in production.

**Comment by ckams** [comment] 2018-05-25 18:16
@gordon-matt

I am trying to initiate something [there](https://github.com/aspnet/Mvc/issues/7703).

**Comment by gordon-matt** [comment] 2018-05-26 02:17
@sebastienros Thanks for your response. If the Orchard modules is completely separate from all the other Orchard stuff, then I suppose I might consider it. But if it means having to use their infrastructure for tenants, theming, etc. as you mentioned then it's not so great, because my CMS already has those things and I am quite happy with my setup overall.

**Comment by mkArtakMSFT** [comment] 2018-05-30 16:52
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Closed by mkArtakMSFT** 2018-05-30 16:52 UTC
Labels: investigate

**Comment by gordon-matt** [comment] 2018-05-31 00:31
@mkArtakMSFT Actually, no - it has yet to be resolved. I want to thank @pranavkm for taking the time to look at my code and attempt a solution, but it's still not working. I will continue working on this problem and reopen this issue later if I'm still stuck. Thanks.

**Comment by gordon-matt** [comment] 2018-06-04 02:32
@pranavkm Thanks for the sample. I have forked it and integrated my own architecture and it works well. However, the exact same code in my larger system causes problems. The strangest part is the error **"Can't fnd compilation library for XYZ"** actually shows up in totally unrelated parts of the system...

Here is a screenshot of my solution:

![mantle](https://user-images.githubusercontent.com/2860937/40895498-0bcf4b2a-67ef-11e8-93bb-b94083371e74.PNG)

As you can see, I have the main app, which uses some plugins.. but there are also 4 class libraries that are referenced directly by the main app which are NOT plugins, but have embedded views. When I navigate to one of those views in the class lib, which is totally unrelated to any plugins, then it throws that annoying error about not being able to find the compilation library for the plugins. I can't quite figure out why that is.

**Comment by gordon-matt** [comment] 2018-06-04 05:10
@pranavkm 

OK, I have replicated the problem! You can find my fork here: https://github.com/gordon-matt/PluginApp

Basically, the **master** branch has been modified with my own plugin management code and it works fine. Now look at the **develop** branch, it's based on the master branch, but I added an "Admin" area with a page to install/uninstall plugins. The plugin still works fine if you click the "Plugin Action" link on the home page... but when you try browse to "/admin", then it throws the error about not being able to find the compilation library for the plugin. Hope you can solve this. Thanks!

**Comment by gordon-matt** [comment] 2018-06-07 07:02
@pranavkm Should I open a new issue for this? Since it appears to be some kind of a bug.

**Comment by pranavkm** [comment] 2018-06-07 16:44
In general, you're going to have a difficult time doing runtime compilation when you are dynamically loading assemblies from non-standard locations. By removing the view here - https://github.com/gordon-matt/PluginApp/blob/develop/MainApp/MainApp.csproj#L8, you're forcing it to compile at runtime. 

If you must perform runtime compilation, 

* Consider not generating the deps file from your plugin. You could do this by setting `<GenerateDependencyFile>false</GenerateDependencyFile>` in https://github.com/gordon-matt/PluginApp/blob/develop/PluginApp/PluginApp.csproj

* Use a custom `AssemblyPart` that explicitly implements `ICompilationReferencesProvider` and avoids reading the deps file.

> Since it appears to be some kind of a bug.
This is all by design. The runtime and MVC assumes that you reference binaries \ package that you care about and not load them from arbitrary path.

**Comment by gordon-matt** [comment] 2018-06-08 01:30
@pranavkm Wow, that's weird about the view... I didn't set `<Content Remove=` like that.. at least not intentionally. Anyway, yes, removing that fixes the demo. However, I checked my real app and I don't have any views removed like that. In fact, when running my real app, everything is fine from my own admin dashboard - from the main index page of the dashboard to a few other pages... but as soon as I look at some pages that are coming from embedded views from another assembly, then I get that error again. Using `<GenerateDependencyFile>false</GenerateDependencyFile>` seems to be working now though.. so thank you for that tip. Will this result in any issues? Maybe performance or what?

Also, about loading from an arbitrary path, why not? It certainly is useful and as you can see from my project and others that use runtime plugins, there are use cases for it. Perhaps a request can be made to officially support arbitrary paths like this in the next version?

> Last thing: I still think what I suggested before is best: that Microsoft officially release some NuGet-based plugins solution for .Net Core. We could have our plugin NuGet packages in some folder and some classes to install/uninstall them, so we no longer need to keep reinventing the wheel. Example:

```
using System.ComponentModel.Composition; // <-- My guess as to a good namespace... (like MEF)

PluginManager.PluginsPath = "~/Plugins";
var availablePlugins = PluginManager.GetAvailablePlugins();
PluginManager.Install("MyPlugin");
PluginManager.Uninstall("MyPlugin");
// etc..
```

> Then guys like me only need to care about creating the admin page (Controller and View) for these plugins.

Anyway, thanks again for your help. Hopefully I won't get anymore related errors now.
