### ISSUE TITLE
Compile Razor Views into a .dll Natively

### ISSUE THREAD

**Issue by rudarobson** [aspnet/Mvc#2260] opened 2015-03-25 02:37 UTC
Compile .cshtml files into a single .dll file for deploying views
Would also be nice to support "html pack" automatically handling cache (Not Modified)

for bigger projects would also be nice to distribute the views into different .dlls, and having a file that knows in which .dll that resource is placed

** what I meant about html pack is to just put the html into the .dll and use the .dll creation date to   handle the NotModified for http caching

It enables, and makes easier, to create a UI project, handling only views, and controllers for those views, static content etc... into a completely separate project..

And also is possible to deploy many UI projects into same application (I do it nowadays but uploading lots of files, packing would be much easier)

for example.. creating an 
usual user interface project
and an admin user interface project

**Comment by danroth27** [comment] 2015-03-25 16:56
This definitely something we want to look at improving, but probably not something we will get to for this release. Adding to the backlog.

You can take a look at how we currently do this in our Diagnostics package:
https://github.com/aspnet/Diagnostics/tree/dev/src/Microsoft.AspNet.Diagnostics
https://github.com/aspnet/Diagnostics/tree/dev/src/PageGenerator

**Comment by danroth27** [comment] 2016-08-17 23:14
This is largely a duplicate of #3917.

**Closed by danroth27** 2016-08-17 23:14 UTC
Labels: 0 - Backlog, duplicate, enhancement, feature

**Comment by bjorn-ali-goransson** [comment] 2017-05-16 23:18
@danroth27 care to edit your links? They 404'...

**Comment by danroth27** [comment] 2017-05-17 03:14
@bjorn-ali-goransson I think those are the new links
