### ISSUE TITLE
Error while rendering nullable enum properties

### ISSUE THREAD

**Issue by topguss** [aspnet/Mvc#5627] opened 2016-12-21 10:13 UTC
In version 1.1.0 there is a problem with nullabile enum properties and @Html.DisplayFor().

This exception is rised: InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'System.String', but this ViewDataDictionary instance requires a model item of type 'System.Enum'.

For example: 
Model: 
```
  public class TestViewModel
  {
    public string Note { get; set; }

    [EnumDataType(typeof(TestEnum))]
    public TestEnum? TestEnum { get; set; }
  }

  public enum TestEnum
  {
    TestCase_1,
    TestCase_2,
    TestCase_3,
  }
```

View:
```
@model WebApplication4.Areas.Public.TestViewModel
<p>TestEnum: @Html.DisplayFor(model => model.TestEnum) </p>
```

Enum template:
```
@model Enum

@if (Model != null)
{
  var enumType = Model.GetType();
  string enumValue = Model.ToString();

  string displayName = enumType.Name + "_" + enumValue.ToString();

  @Html.DisplayTextFor(model => displayName)
}
else
{
  @Html.DisplayTextFor(model => model)
}
```

project.json
 ```
 "dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
  },

  "frameworks": {
    "net461": {}
  },
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },
```

**Comment by Eilon** [comment] 2016-12-22 01:35
@ryanbrandenburg is this a dup of that issue you worked on just recently?

**Comment by topguss** [comment] 2016-12-22 08:03
yes

**Comment by ryanbrandenburg** [comment] 2016-12-30 23:18
Yes, this appears to be a dupe of #5547, closing.

**Closed by ryanbrandenburg** 2016-12-30 23:18 UTC
