### ISSUE TITLE
Page routing silently falls back to generic handler when named handler does not exist

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7362] opened 2018-02-13 18:48 UTC
For example, if Index.cshtml contains
``` html
<form method="post" asp-page-handler="Integral">
    <!-- ... -->
    <input type="submit" />
</form>
```
and the corresponding page model contains only
``` c#
public void OnGet(...)
{
    // ...
}

public IActionResult OnPost(...)
{
    // ...
}
```
the `OnPost(...)` handler will execute. I expected a 404 in this scenario.

The behaviour is the same for `@page` and `@page "{handler?}"`.

The chosen handler method is logged. But, there's no mention of failing to find the `OnPostIntegral(...)` handler. Should at least warn for this case because it indicates a developer error.

**Comment by Eilon** [comment] 2018-02-13 18:56
What URL got generated in the rendered `<form ...>` tag?

**Comment by dougbu** [comment] 2018-02-13 19:16
> What URL got generated in the rendered `<form ...>` tag?

With `@page "{handler?}"` in Index.cshtml, `<form>` tag helper generates `action="/Integral"`. With bare `@page`, `<form>` tag helper generates `action="/?handler=Integral"`. I'm more surprised the first does not result in a 404 than the second.

**Comment by rynowak** [comment] 2018-02-13 22:29
This is by design. This is how routing works.

**Comment by mkArtakMSFT** [comment] 2018-02-13 22:51
@danroth27, @DamianEdwards, @Eilon do you think we should change the design here to not silently redirect but to behave exactly as instructed?

**Comment by dougbu** [comment] 2018-02-14 00:34
@rynowak where else do we have fallbacks to a more-generic route (a shorter template, not a template that ends with `/*`). I.e. is your "how routing works" statement specific to pages?

@mkArtakMSFT if this is how page routing works, even when using the `handler` route value option, :ok: (mostly). Suggest we at least need some logging to help users figure out what's going on when the fallback was *not* intended e.g. a typo in the name of the handler method or in the `asp-page-handler` value.

**Comment by mkArtakMSFT** [comment] 2018-02-14 17:54
@dougbu, don't we already have logging where we choose which handler to choose? If not, please file a new issue specifically for that.

**Comment by dougbu** [comment] 2018-02-15 00:08
@mkArtakMSFT we log about the handler chosen but not the handlers considered (that I've seen).

In any case, the larger issue might be documentation, might be a missing feature, or something else. Took a bit of experimentation i.e. perhaps missing documentation, but I've found handlers are 100% optional even in page models containing handlers. For example, a page model containing just `public void OnGet() {}` still accepts POST requests. There's no obvious way to *restrict* the HTTP methods a page accepts i.e. perhaps a missing feature.

To get the behaviour I wanted i.e. to make sure I had all the handlers my page expected, I switched to `@page "{handler=default}"` and changed the page model to
``` c#
public class IndexModel : PageModel
{
    public IActionResult OnGet()
    {
        return new NotFoundObjectResult($"Executing unsupported handler '{RouteData.Values["handler"]}'.");
    }

    public IActionResult OnPost()
    {
        return new NotFoundObjectResult($"Executing unsupported handler '{RouteData.Values["handler"]}'.");
    }

    public IActionResult OnGetDefault([FromHeader, Required] string host)
    {
        // ...
        return Page();
    }

    public IActionResult OnPostDefault([MinLength(6)] string host)
    {
        // ...
        return Page();
    }

    public IActionResult OnPostIntegrals([MinLength(6), Required] int[] ints)
    {
        // ...
        return Page();
    }
}
```
This caught my typo in the `OnPostIntegrals` method name and returned an error message making it easy to see.

**Comment by DamianEdwards** [comment] 2018-02-15 05:50
This is all by design. Nothing here makes me want to change any of it.

**Comment by dougbu** [comment] 2018-02-15 06:19
@DamianEdwards :ok: then should I move this issue to the Docs repo?

**Comment by DamianEdwards** [comment] 2018-02-15 06:32
If you feel something should be added to docs regarding how handler selection works, go for it.

**Comment by mkArtakMSFT** [comment] 2018-02-15 17:58
Thanks folks! Closing by-design.

**Closed by mkArtakMSFT** 2018-02-15 17:58 UTC
