### ISSUE TITLE
Resource file Designer.cs generation fails as resource keys are no longer valid C# identifiers

### ISSUE THREAD

**Issue by drauch** [aspnet/Mvc#6774] opened 2017-09-06 10:00 UTC
We use the @Localizer["Some Text"] localization mechanism. However, as we understand it, foreign languages are still provided as resource files. The key must be the non-localized text (e.g., "Some Text"). However, as soon as we have a space in it, the key is no longer a valid C# identifier and the ResXGenerator cannot re-generate the Designer.cs file anymore.

What's the solution for this? Is this a known problem?

**Comment by Eilon** [comment] 2017-09-06 17:04
Ah yes we've seen this issue before. I'll try to find the previous discussion on it. One workaround to this is to disable VS's default "Single File Generator" that it applies to all RESX files because it disallows generating the CS file when any of the resource identifiers are not valid C#. You can disable it by right-clicking on the RESX file in Solution Explorer in VS and selecting Properties, and then in the Properties window you can clear out the single file generator.

**Comment by Eilon** [comment] 2017-09-06 18:04
Ok looks like it was just an email discussion where this was discussed. The recommended workaround is to disable the single file generator for the files. Another more costly alternative is to use keys that are valid C# identifiers (e.g. `MyStringResource`), which means you also need to have your "neutral language" (the one without a locale specified) be stored in a RESX file.

Ultimately this is a VS issue so if you have additional feedback on that, please log an issue using VS's built-in Feedback tool. I'm closing this issue because there's no further action in ASP.NET Core.

**Closed by Eilon** 2017-09-06 18:04 UTC

**Comment by drauch** [comment] 2017-09-06 18:44
@Eilon : OK, thanks for the clarification!

**Comment by drauch** [comment] 2017-09-07 11:10
@Eilon : I do have a follow-up question though. The ResourceManagerStringLocalizer works only if the Designer class is properly generated. If I delete the Designer.cs file, the resource does no longer work. So it looks like it is a ASP.NET MVC problem?!

**Comment by pranavkm** [comment] 2017-09-07 16:23
@drauch that doesn't seem right. The localizer works with the embedded resource stream, not the code generated designer.

**Comment by Eilon** [comment] 2017-09-07 21:04
Right, the .designer.cs is just for accessing resources directly from your own C# code.

**Comment by drauch** [comment] 2017-09-11 06:21
@Eilon / @pranavkm : I localized the problem: we used `stringLocalizerFactory(typeof(MyResources))` where `MyResources` was the class in the designer file. This seems to be buggy:

MyResources resides in "MyApp.Resources", LocalizationOptions.ResourcesPath is set to "Resources", calling the factory as above looks for the resource file in "MyApp.Resources.Resources.MyResources" (yes, two times "Resources").

Is this intended? We are now using the other overload of the factory to workaround the problem...however, this looks like a bug?

**Comment by Eilon** [comment] 2017-09-11 06:29
@ryanbrandenburg can you comment on this? @hishamco maybe you have some ideas?

**Comment by hishamco** [comment] 2017-09-11 06:41
> I localized the problem: we used stringLocalizerFactory(typeof(MyResources)) where MyResources was the class in the designer file. This seems to be buggy:

Have a look to localization sample [here](https://github.com/aspnet/Localization/blob/dev/samples/LocalizationSample/Startup.cs#L25) `IStringLocalizer<Startup> SR` the `Startup` isn't the .designer.cs

but to understand your issue, please create a repo to reproduce your issue

**Comment by hishamco** [comment] 2017-09-11 06:46
FYI you don't need `stringLocalizerFactory(typeof(MyResources))` a because the localization APIs is already register a generic version for you https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/LocalizationServiceCollectionExtensions.cs#L65

For more details example, refer to https://github.com/aspnet/Entropy/tree/dev/samples/Localization.StarterWeb which have almost of the localization gooness

**Comment by ryanbrandenburg** [comment] 2017-09-11 16:34
Yeah, please review the linked resources and [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization#resource-file-naming). Usually this kind of thing turns out to be a problem related to the namespace of the class, so pay extra attention to that section. If it doesn't answer your question please post a minimal repro project so that we can figure out the exact behavior.
