### ISSUE TITLE
Get tests working on Travis / Linux

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4153] opened 2016-02-25 05:11 UTC
Unlike a few repos, MVC builds have succeeded on Travis / Linux. See success as recently as two days ago. Unfortunately the current builds are not clean.

Main issue appears to be finding web site projects in functional tests. Since many functional tests succeed, problems may be limited to sites containing views or other files that must be found on disk.
```
Microsoft.AspNetCore.Mvc.FunctionalTests.CompilationOptionsTests.CompilationOptions_AreUsedByViewsAndPartials [FAIL]
      System.ArgumentException : The directory name /home/travis/build/aspnet/Mvc/test/Websites/RazorWebSite/ is invalid.
      Parameter name: path
```

See failures in https://s3.amazonaws.com/archive.travis-ci.org/jobs/111588349/log.txt for example. (Log is truncated at https://travis-ci.org/aspnet/Mvc/jobs/111588349 though some failures are visible.)

**Comment by muratg** [comment] 2016-02-25 17:01
@NTaylorMullen Are you able to look into this?

**Comment by NTaylorMullen** [comment] 2016-02-25 18:46
I'm still catching up on work from when I was sick and prepping for the netstandard transition. Does someone else have bandwidth?

**Comment by muratg** [comment] 2016-02-25 20:45
@Eilon Can we find someone to look into this?

**Comment by muratg** [comment] 2016-02-25 21:59
@ryanbrandenburg Could you have a look?

**Comment by ryanbrandenburg** [comment] 2016-02-26 00:42
@muratg I can look at it today and tommorow but FYI I'm out most of next week on vacation so if it's a longer fix it might end up in limbo.

**Comment by muratg** [comment] 2016-02-26 00:50
@ryanbrandenburg Cool, let's have the initial look, and if it's not fixable by EOD tomorrow, we can assign someone else.

**Comment by ryanbrandenburg** [comment] 2016-02-26 17:52
I've got a PR out (#4161) that fixes 2 things, hopefully they're the only ones.

**Comment by muratg** [comment] 2016-02-26 17:57
Travis runs in your branch are in progress. Fingers crossed.

**Comment by ryanbrandenburg** [comment] 2016-02-26 23:52
Blocked by dotnet/cli/issues/1612

**Comment by ryanbrandenburg** [comment] 2016-03-04 23:09
dotnet/cli#1612 was a dupe of dotnet/cli#1613.

**Comment by muratg** [comment] 2016-03-04 23:14
@pakrym the CLI bug seems to be triaged for RTM.  Though per @ryanbrandenburg it blocks Travis runs.  Any workaround, or should be just disable the test on Mono for now?

**Comment by muratg** [comment] 2016-03-04 23:23
@Eilon I just had a chat with Pavel. The dotnet CLI bug (which does not have an easy solution apparently) is the root cause of Razor compilation failure on Mono.  Essentially this means no Mono support for Razor. If you think this is OK, we can disable Mono tests for MVC.

**Comment by muratg** [comment] 2016-03-04 23:32
Had a chat with @DamianEdwards... we will try to tackle the CLI bug if we get some breathing room...

In the meantime, @ryanbrandenburg let's skip MVC tests on Mono for now.  I recommend keeping a bug open to reenable them when the CLI issue is fixed.

**Comment by Eilon** [comment] 2016-03-05 03:14
:+1:

**Comment by ryanbrandenburg** [comment] 2016-03-07 17:51
Tests were disabled in #4234 and tracked in #4238, will close this once they pass on CI.

**Closed** 2016-03-10 01:13 UTC
Labels: 1 - Ready, task
