### ISSUE TITLE
FromQuery parameter binding fails for multi-valued (array) params if a name isn't explicitly given 

### ISSUE THREAD

**Issue by lisardggY** [aspnet/Mvc#8126] opened 2018-07-23 06:33 UTC
#### Is this a Bug or Feature request?:
A bug, it appears.

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
https://github.com/lisardggY/AspNetControllerTest

#### Description of the problem:

I've encountered strange behavior when binding multi-valued controller parameters with [FromQuery] in ASP.NET Core 2.1.1.

For this controller signature:
`public ActionResult<IEnumerable<string>> Get([FromQuery] string[] user)`
I expect to be able to call with
`http://server/api/values?user=a&user=b`

but this will always return an empty array in `user` - even if I only pass a single value.
However, explicitly stating the name of the query parameter *will* work:

`public ActionResult<IEnumerable<string>> Get([FromQuery(Name = "user")] string[] user)`

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Microsoft.AspNetCore.App 2.1.1

**Comment by lisardggY** [comment] 2018-07-23 06:47
#### Is this a Bug or Feature request?:
A bug, it appears.

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
https://github.com/lisardggY/AspNetControllerTest

#### Description of the problem:

I've encountered strange behavior when binding multi-valued controller parameters with [FromQuery] in ASP.NET Core 2.1.1.

For this controller signature:
`public ActionResult<IEnumerable<string>> Get([FromQuery] string[] user)`
I expect to be able to call with
`http://server/api/values?user=a&user=b`

but this will always return an empty array in `user` - even if I only pass a single value.
However, explicitly stating the name of the query parameter *will* work:

`public ActionResult<IEnumerable<string>> Get([FromQuery(Name = "user")] string[] user)`

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Microsoft.AspNetCore.App 2.1.1

**Comment by mkArtakMSFT** [comment] 2018-07-23 15:49
Thanks for contacting us, @lisardggY.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment] 2018-07-23 16:55
@lisardggY is your controller associated with an `[ApiController]` attribute?

If yes, this is a duplicate of #7712. The fix is available in the https://dotnet.myget.org/gallery/aspnetcore-dev feed. I suggest choosing an early 2.2.0 Preview 1 version e.g. https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.Mvc/2.2.0-preview1-34762

**Comment by dougbu** [comment] 2018-07-23 16:57
Oops, missed your repro link. This is indeed a duplicate of #7712.

**Closed by dougbu** 2018-07-23 16:57 UTC
Labels: investigate

**Comment by lisardggY** [comment] 2018-07-24 07:38
Ah, I missed that one when searching the issues list. Glad to see it was fixed. Thanks!
