### ISSUE TITLE
JsonResult executor is logging value contents instead of type for JObject object.

### ISSUE THREAD

**Issue by oofpez** [aspnet/Mvc#7323] opened 2018-02-01 10:01 UTC
First posted this as a comment on Issue [#4604.](https://github.com/aspnet/Mvc/issues/4604#issuecomment-361681903)

 I am having an issue where my entire api response body is logged!

Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor: Information: Executing JsonResult, writing value { ... }

{ ... } containing the entire json model.

how can I turn this off? It only seems to happen where they response is returned like this:
return Json(JsonConvert.DeserializeObject(stringValue));

as opposed to return Json( object) which outputs the type.

to reproduce:  have stringValue be a string respresenting a json object , such as 

> "{\"id\":\"Lwjt7pdibUGFRqh6AKQyXg\",\"href\":\"blahblahblah\" }"

**Comment by oofpez** [comment] 2018-02-02 09:07
I can tell that it is logging using the ToString() of JObject, which is the json itself.

**Comment by mkArtakMSFT** [comment] 2018-02-06 17:41
Hi @oofpez. Thanks for reporting this issue. We agree that this seems to be a bug and we've assigned one of our team members to look into this based on its priority.

**Comment by mkArtakMSFT** [comment] 2018-02-06 17:42
@jbagga, can you please look into this?

**Comment by davenewza** [comment] 2018-02-27 14:30
Yes, this is a bit of a problem for us. Is there an interim solution to prevent this?

**Comment by rynowak** [comment] 2018-03-19 14:58
I'm confused about this. Where's the bug here? https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/Internal/MvcJsonLoggerExtensions.cs#L36

This should have been addressed as part of https://github.com/aspnet/Mvc/commit/db2d9ee56f9a7ca0f1a264821e0608b70047337c

@davenewza and @oofpez - this was fixed for 2.1 - if you're experiencing this on 2.0 or earlier, you will not have the fix. I suggest you edit your logging settings and set the category `Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor` to Warning to hide these messages.

**Comment by oofpez** [comment] 2018-03-19 15:02
ok, nvm.  Waiting on 2.1 to go live then :)

**Comment by rynowak** [comment] 2018-03-19 15:03
I just tried this locally, and it outputs:
```
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method MvcSandbox.Controllers.HomeController.Index (MvcSandbox), returned result Microsoft.AspNetCore.Mvc.JsonResult in 272.4678ms.
info: Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor[1]
      Executing JsonResult, writing value of type 'System.String'.
```

@jbagga were you able to reproduce this in some other way on 2.1?

**Comment by davenewza** [comment] 2018-03-19 15:09
@rynowak Thanks. Will set the logging filter for now and until 2.1 which I believe is scheduled for Q2.

**Comment by jbagga** [comment] 2018-03-19 17:47
With dev I see:

```
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method MvcSandbox.Controllers.HomeController.Index (MvcSandbox), returned result Microsoft.AspNetCore.Mvc.JsonResult in 33082.1549ms.
info: Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor[1]
      Executing JsonResult, writing value of type 'Newtonsoft.Json.Linq.JObject'.
```

When the Action is
```
        [HttpPost]
        public IActionResult Index([FromBody] string body)
        {
            var stringValue = body;
            return Json(JsonConvert.DeserializeObject(stringValue));
        }
```

@oofpez and @davenewza I am closing this for now. Let us know if you run into any issues here when trying 2.1!

**Closed by jbagga** 2018-03-19 17:47 UTC
Labels: 1 - Ready, bug, cost: S
