### ISSUE TITLE
ApiController BindingErrors in 2.1-preview1-final

### ISSUE THREAD

**Issue by Tornhoof** [aspnet/Mvc#7512] opened 2018-03-20 13:50 UTC
The new 2.1 ApiController Attribute is supposed to infer the bindings. This does not work nicely.
The attached repro contains a webapp demonstrating the full problem, the controller looks like this:
```csharp
    [ApiController]
    [Route("api/Test")]
    public class TestController : Controller
    {
        [HttpPost]
        [Route("Working")]
        public Task<IActionResult> Working(HelloWorld helloWorld)

        {
            IActionResult okResult = new OkResult();
            return Task.FromResult(okResult);
        }

        [HttpPost]
        [Route("NotWorking")]
        public Task<IActionResult> Notworking(HelloWorld helloWorld, CancellationToken cancellationToken = default)

        {
            IActionResult okResult = new OkResult();
            return Task.FromResult(okResult);
        }

        [HttpPost]
        [Route("StillNotWorking")]
        public Task<IActionResult> StillNotWorking([FromBody] HelloWorld helloWorld,
            CancellationToken cancellationToken = default)

        {
            IActionResult okResult = new OkResult();
            return Task.FromResult(okResult);
        }
    }
```
The problems are:

1. If you have a cancellationToken in your method definition the binder will warn and the method will not work: 
```
 Microsoft.AspNetCore.Mvc.Internal.ApiBehaviorApplicationModelProvider:Warning: Unable to unambiguously infer binding sources for parameters on 'System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] NotWorking(BodyBindingRepro.HelloWorld, System.Threading.CancellationToken)'. More than one parameter may be inferred to bound from body.
```
The result is Status 400 and
```json
{
    "": [
        "The input was not valid."
    ]
}
``` 

2. Even if I then annotate the parameter I want to be bound with [FromBody] like in asp.net core 2.0 it does not work, the behaviour is the same as in 1.

Either I'm doing something completely wrong or the inferring of the binding sources only works in a happy case scenario (see ``Working`` in the example above).
- I expected that the CancellationToken will be ignored automatically (Does anyone ever bind to a cancellationToken?)
- I expected that I can override the automatic inferring by annotating it manually.
- Does the inferring algorithm take the last parameter if ambiguous? If yes, it probably should rather take the first one, I guess that most developers have the most important parameters first.
- If the inferring algorithm is ambiguous it probably should throw an error instead of an warning.

Repro:
[BodyBindingRepro.zip](https://github.com/aspnet/Mvc/files/1829528/BodyBindingRepro.zip)
Build and invoke the controller methods via Postman or similar and see the effect.

**Comment by rynowak** [comment] 2018-03-20 18:13
Thanks for your feedback. We'll take a look at this and figure it out for preview2

/cc @pranavkm

**Comment by mkArtakMSFT** [comment] 2018-03-20 22:20
@pranavkm, can you please investigate this? Thanks!

**Comment by khellang** [comment] 2018-03-26 18:09
> I expected that the CancellationToken will be ignored automatically (Does anyone ever bind to a cancellationToken?)

This should be solved with #7548.

> I expected that I can override the automatic inferring by annotating it manually.

The problem in this case, is that `helloWorld` is explicitly annotated with `[FromBody]`, while `cancellationToken` is also inferred to `BindingSource.Body`. This leads us to the next point:

> Does the inferring algorithm take the last parameter if ambiguous? If yes, it probably should rather take the first one, I guess that most developers have the most important parameters first.

This isn't really a problem with the inference. The problem is that you have two parameters that both bind to the body. I'm not sure if this has any defined behavior, or if it's just a coincidence that it ends up binding to the last parameter?

> If the inferring algorithm is ambiguous it probably should throw an error instead of an warning.

I think this ties into the previous point as well. After the application model has been created, should MVC detect cases where two arguments bind to the body and throw? Are there other cases where you could end up shooting yourself in the foot like this?

**Comment by Tornhoof** [comment] 2018-03-27 06:56
Another possible improvement, if the http method is get, the infered binding should not be body but  query instead.

**Comment by pranavkm** [comment] 2018-03-27 16:11
@Tornhoof binding sources are statically calculated and not in the context of a request, so that wouldn't work.

> After the application model has been created, should MVC detect cases where two arguments bind to the body and throw?

The error message @Tornhoof produced is while we ensure there aren't duplicate `FromBody` parameters. So I think that's already covered. 

> Are there other cases where you could end up shooting yourself in the foot like this?

Apart from `FromBody` there aren't other built-in sources that only allow binding one instance per request. You could potentially have a user created one, unfortunately there we don't have a way to describe this constraint as yet.

**Comment by khellang** [comment] 2018-03-27 16:24
> The error message @Tornhoof produced is while we ensure there aren't duplicate `FromBody` parameters. So I think that's already covered.

No, the error message is from the inference phase. There could still be ways to end up with multiple parameters with `BindingSource.Body`. Even if a warning is logged, you still get to the action itself, which will probably fail with some weird error because multiple binders are trying to read from the body. If validation had been in place, this can been cought earlier.

**Comment by pranavkm** [comment] 2018-03-27 16:37
Oh right, it's a warning. And yes, you could have a convention that modifies parameter binding sources and lead you to a questionable state.

**Comment by khellang** [comment] 2018-03-27 17:37
Yes, and I'd much rather see a fail-fast scenario than having stuff work/not work by accident. The question is whether such validation would be considered a breaking change? Could there be people out there in the wild running with such configurations?

**Comment by Tornhoof** [comment] 2018-03-27 17:39
It's a new Feature and you need to opt-in. I don't think there are many Users out there yet.

**Comment by Eilon** [comment] 2018-04-02 18:43
@pranavkm / @mkArtakMSFT - is this a must-have for Preview2? If not, let's move to RC1.

**Comment by pranavkm** [comment] 2018-04-02 18:46
This is done. Fixed in https://github.com/aspnet/Mvc/commit/c515cece8ed8a39b8163c3ba35024bcc79716ca0

**Closed by pranavkm** 2018-04-02 18:46 UTC
Labels: 2 - Working, bug, cost: S

**Comment by NickStrupat** [comment] 2018-08-15 03:12
This still happens with `Microsoft.AspNetCore.OData` 7.0.1

**Comment by martinsmith74** [comment] 2018-09-27 10:02
After spending almost all day on this, I had working samples but it wasn't working in my code. Finally, I discovered that if you remove the ApiController attribute it works.

**Comment by pranavkm** [comment] 2018-09-27 15:45
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
