### ISSUE TITLE
By Design? DisplayFor(m=>ienum)  MetaData will resolve to base type instead of actual but will resolve to actual if generating item templates

### ISSUE THREAD

**Issue by Tarig0** [aspnet/Mvc#7274] opened 2018-01-22 18:24 UTC
I have the following interface and classes

```c#
public interface ICollectionRule<out T> 
    {
        IEnumerable<T> Items { get; }
    }

public Class CollectionRule<T>: ICollectionRule<T> {
IEnumerable<T> Items { get; }
}

public partial Class CollectionRule<String>: CollectionRule<String> {}
```

and a view with
```
@model ICollectionRule<object>
@Html.DisplayFor(m => m.Items)
```

I won't be able to create a template for IEnumerable[String] but I am able to create a template for String.

If I change the Displayfor to
```c#
Html.Display("Items")
```

It will then resolve to the actual IEnumerable[String] type.

**Comment by mkArtakMSFT** [comment] 2018-01-23 17:29
@dougbu, any thoughts?

**Comment by dougbu** [comment] 2018-01-23 17:58
> won't be able to create a template for `IEnumerable` but I am able to create an editor for `String`

@Tarig0 what exactly does this mean? Are you saying `DisplayFor(...)` doesn't seem to use a template named `IEnumerable`? `IEnumerable`Object`?

More generally, I'd appreciate more context e.g. the names of the available template files and exactly where they and the view above are located in your application.

**Comment by Tarig0** [comment] 2018-01-23 18:00
Sorry Had html like tags I have edited the post so you can now see IEnumerable[string]

**Comment by dougbu** [comment] 2018-01-23 18:04
@Tarig0 please describe your view files more completely as well as the exact behaviour you're seeing.

**Comment by Tarig0** [comment] 2018-01-23 18:23
The specific case I have is.

**Sample Classes**
```c#
public class CircuitsRule: CollectionRule<CircuitInfo> {}

[ModelMetadataType(typeof(Meta))]
    public partial class MarkingsRule : CollectionRule<SelectedMarking>
    {
        public IEnumerable<string> SelectedMarkings
        {
            get => Items?.Select(m => m.Marking);
            set => Items = value.Select(m => new SelectedMarking() { Marking = m }).ToHashSet();
        }
    }
    public class Meta
    {
        [UIHint(nameof(MarkingsRule.SelectedMarkings))]
        public object Items { get; set; }
    }
```
**Display Templates**
DisplayTemplates/SelectedMarkings.cshtml
DisplayTemplates/CircuitInfo.csHTML

**Root Display**
DisplayTemplates/CollectionRule`1.csHTML
```
@model ICollectionRule<object>
<tr>
    @Html.DisplayFor(m => m.Keys)    
    @Html.Display(nameof(ICollectionRule<object>.Items))
@*
  This can't read the UIhint on the MarkingRule class since the resolved modelmetadata is ICollectionRule<object>.Items instead of ICollectionRule<SelectedMarking>
But this will eventually resolve to the CircuitInfo.cshtml for  CircuitsRule
    @Html.DisplayFor(m=>m.Items)
*@
</tr>
```

**Comment by dougbu** [comment] 2018-02-09 22:50
@Tarig0 you are correct; this behaviour is by design. The HTML helpers that work with Linq expressions have no information about runtime types when they determine `ModelMetadata` of the result. Those helpers do not even evaluate the expression until much later in HTML generation.

On the other hand, `string`-based HTML helpers (those that work with an "expression name") almost-always determine `ModelMetadata` based on runtime information. This is required because indexing into `ViewData` is has precedence over using `Model` and property evaluation has to work on whatever's found in that first step.

To make `Display(nameof(AProperty))` work identically to `DisplayFor(m => m.AProperty)`, declare the most-specific model type you can. For example, use `@model MarkingsRule` in your root view.

**Comment by dougbu** [comment] 2018-02-09 22:50
Closing as `by design`.

**Closed by dougbu** 2018-02-09 22:50 UTC
Labels: by design

**Comment by dougbu** [comment] 2018-02-09 22:52
I should have acknowledged your work @Tarig0: Thank you for your feedback! We're closing this issue as the behaviour discussed is by design.
