### ISSUE TITLE
Add an option to inline css file inside a Razor page

### ISSUE THREAD

**Issue by gdoron** [aspnet/Mvc#5340] opened 2016-09-29 17:56 UTC
Hi,

I just wrote a small TagHelper that inlines css files as it's one of the recommendations of PageSpeed by Google:
https://developers.google.com/speed/docs/insights/InlineCSS 
https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

It would be nice if ASP.NET would have something like that baked into the framework and the existing `LinkTagHelper` which surely will be much more robust than my extremely simple, couple of minutes work:

```
[HtmlTargetElement("embedCss")]
public class EmbedCssTagHelper : TagHelper
{
    private readonly IMemoryCache _memoryCache;
    private readonly IHostingEnvironment _hostingEnvironment;
    private const string CacheKeyPrefix = "EmbedCss_";
    public string Href { get; set; }

    public EmbedCssTagHelper(IMemoryCache memoryCache, IHostingEnvironment hostingEnvironment)
    {
        _memoryCache = memoryCache;
        _hostingEnvironment = hostingEnvironment;
    }

    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        var cacheKey = CacheKeyPrefix + Href;
        output.TagName = "style";
        var content = _memoryCache.GetOrCreate(cacheKey, entry =>
        {
            if (_hostingEnvironment.IsStaging() || _hostingEnvironment.IsProduction())
            {
                Href = Href.Replace(".css", ".min.css");
            }

            var path = _hostingEnvironment.WebRootPath+ Href;
            var result = File.ReadAllText(path);
            // Surely there are other ways, like watching the file system for changes...
            // If you could reference a resource that shows how to do that it would be great!
            entry.SetAbsoluteExpiration(TimeSpan.FromMinutes(1));
            entry.SetValue(result);
            return result;
        });

        output.Content.SetHtmlContent(content);
        output.TagMode = TagMode.StartTagAndEndTag;
    }
}
```

What do you think about it @Eilon?

BTW, while writing the TagHelper was easy, I couldn't find why my TagHelper didn't get fire until I added `[HtmlTargetElement("embedCss")]`, what should be the element name in the HTML if it wasn't specified?

**Comment by Eilon** [comment] 2016-10-25 17:32
@DamianEdwards can you share thoughts on how important a feature like this is? Especially considering HTTP2, where making multiple requests shouldn't be as expensive as it is today from a latency perspective.

**Comment by DamianEdwards** [comment] 2016-10-25 17:35
Still worthwhile. I did it on live.asp.net. HTTP2 is a while away from normal, especially given it requires Windows Server 2016 for IIS.
We should have this built in to both the link and script tag helpers.

**Comment by gdoron** [comment] 2016-10-25 17:36
@DamianEdwards  Awesome, thanks!

**Comment by Eilon** [comment] 2016-10-25 17:39
One of the big problems we're concerned about is that embedding CSS is tricky when you have URLs inside the CSS (e.g. to images). The URLs have to be re-pathed based on the *current request's* URL.

The code would have to parse the CSS and re-path every URL inside it. This would affect the ability to cache the CSS because there can't be one canonical copy of it - there would have to be a copy for every URL where it's used (or at least for every "group" of similar URLs).

**Comment by DamianEdwards** [comment] 2016-10-25 17:48
That's a very good point. We could simply say "not supported" in that case, but I agree it's less than ideal. There are many cases when this would still be useful, as plenty of CSS doesn't contain URLs to images or fonts, but it's not clear what the correct behavior here should be.

**Comment by gdoron** [comment] 2016-10-25 18:48
@Eilon @DamianEdwards 

It's easily solved with having only URI "absolute relative" (totally made this term up right now) paths in the CSS files:

<h3>Good:</h3>

	/static/images/kitchen.jpeg
	@font-face {
	  font-family: 'MyWebFont';
	  src: url('/static/fonts/webfont.woff2') format('woff2')
	}
	
<h3>Bad:</h3>

	../images/kitchen.jpeg
	@font-face {
	  font-family: 'MyWebFont';
	  src: url('../fonts/webfont.woff2') format('woff2')
	}
	
In fact, this is how we currently use CSS on our website.
We create the website in a very components fashion, like a SPA, with tons of partial views, and each partial view has its own independent SCSS file. So it's impossible to have tons of HTTP requests for css files for each and every partial view in a page (can be a dozen for a page).

The only drawback of this is every request for the page, all the CSS needs to be included in the HTML and can't be cached locally on the client browser.

I thought about ways to solve it: every page loads the global css file (all the SCSS files, combined) **asynchronously** and set a cookie with the last time it was received / ETAG. 
When rendering the page, using `<embedCss>`, we'll check the cookie, if its ETAG is the newest, we won't include inline CSS but rely on the external CSS file.
<sub>We didn't implement it yet as we are busy with writing our entire client side from scratch, but that's the idea.</sub>

**Comment by Eilon** [comment] 2016-10-26 01:49
@gdoron using only absolute URLs is a "restriction," not a "solution" 😄 Using relative paths in CSS is extremely common because in "normal" CSS files it's the safest to use. It's quite normal for the author of the CSS file to require some of their own images, yet not know the final path where the CSS file and related images will be placed. For example, Bootstrap.css has tons of relative `url()` values.

But anyway, we're definitely not saying this is a bad feature - as @DamianEdwards said it's quite interesting. The concern is that there's a lot of work required to call it "done". Not the least of which is doing actual browser perf measurements to see whether this feature even improves performance in several common scenarios. (We all know that just making various "site optimization" checklists happy is not necessarily actually good for the site.)

**Comment by gdoron** [comment] 2016-10-26 14:33
@Eilon @DamianEdwards
I agree, using relative paths in CSS is extremely common and useful **BUT** only for external resources (like bootstrap you mentioned).
This is because the authors of the CSS framework can't enforce a specific website, application and folders structure, so they must use relative paths to link the fonts and images.
Inline large chuck for CSS file is actually a bad pattern and discouraged by page speed:

> Be careful when inlining data URIs in CSS files. While selective use of small data URIs in your CSS may make sense, inlining large data URIs can cause the size of your above-the-fold CSS to be larger, which will slow down page render time.

So It really only makes sense to inline homemade CSS, which doesn't benefit at all from using relative paths, and sometimes it's even more resilient to use absolute paths since you can move the CSS file around and it work break anything (for example, serving from a CDN or moving the `.min.css` to a different folder).

> Not the least of which is doing actual browser perf measurements to see whether this feature even improves performance in several common scenarios.

Make sure to test on mobile devices and slow networks, inline resources on these have a huge impact, because of browsers' parallel request limitation and TCP [(HTTP) slow start](https://en.wikipedia.org/wiki/TCP_congestion_control#Slow_start)

See more on performance and mobile:
[Presentation](https://docs.google.com/presentation/d/1wAxB5DPN-rcelwbGO6lCOus_S1rP24LMqA8m1eXEDRo/present?slide=id.g11c1373c5_5_35) [YouTube lecture](https://youtu.be/I4vX-twze9I) both of **Ilya Grigorik**, a web performance engineer at Google, co-chair of the W3C Web Performance Working group.

**Comment by gdoron** [comment] 2016-10-31 11:40
@Eilon Curious to know whether you agree with the the above or not.

**Comment by Eilon** [comment] 2016-10-31 21:21
@gdoron those are all good points, but still no plans to have this feature built-in. If you end up building this tag helper you can release a package on NuGet, and we'd be happy to link to it.

**Comment by gdoron** [comment] 2016-10-31 22:43
@Eilon Problem is, I think it shouldn't really be a new tagHelper but a boolean property on LinkTagHelper.
Should I really copy paste the entire code (with great features) from `LinkTagHelper`?
That's bad practice.

Is there a DRY way of extending TagHelpers in MVC Core?

**Comment by Eilon** [comment] 2016-10-31 23:45
To include this in the framework I think we'd want to try resolving some of the issues mentioned earlier. As of right now I think some of these issues are a "pit of failure" where it's very easy to lead a user into doing things that won't work.

As far as extending the current tag helpers, it's a matter of whether the tag helper in question was designed to support any particular extensibility, and in this case what's being discussed is a whole new feature, so I'm not surprised that it doesn't have that extensibility.

**Comment by gdoron** [comment] 2016-11-01 08:50
@Eilon So what do you suggest? It seems like the community is blocked by the framework, unless we are going to copy paste the entire `LinkTagHelper` class (and its dependencies) which is really bad for maintenance.

Thanks.

**Comment by Eilon** [comment] 2016-11-02 07:07
@gdoron I looked at `LinkTagHelper` and I'm not sure this is a good fit for the existing tag helper. The existing tag helper is all about doing file globbing (not very useful here) and resource/CDN fallback (clearly not applicable here).

So this sounds to me like it fits best as a separate tag helper.

If this tag helper requires some core pieces of functionality from some existing tag helper we would certainly be open to exposing some of that functionality somewhere - it's a matter of identifying what should be made reusable. Do you have thoughts on that?

**Comment by gdoron** [comment] 2016-11-02 08:58
@Eilon I think you're probably right regarding LinkTagHelper not fitting to embeding css, but that's (at least from my understanding) is the only way we can still use the known HTML element `<link>` and just having a flag to embed the content.

Regarding something common, I guess the only the thing that might be common is the `FileVersionProvider` which is in a separate class anyway.

BTW, do you think it's a good idea storing the CSS file content in the MemoryCache and invalidate it when the content changes?
Or is it better reading it from disk every time?

**Comment by Eilon** [comment] 2016-11-02 22:14
@gdoron you can have multiple tag helpers targeting the same element, though you're right that it wouldn't be the same as having just one extra switch.

Regarding loading from disk vs. using a memory cache, the best way to answer that is to not implement caching, use a profiler to measure the behavior, and then optimize whatever the slowest part is, and then finally measure again to see that the behavior improved in the expected way. Then repeat.

**Comment by mkArtakMSFT** [comment] 2018-09-12 21:12
Closing this as we have no plans to do this.

**Closed by mkArtakMSFT** 2018-09-12 21:12 UTC
Labels: enhancement, feature-Tag-Helpers, needs design
