### ISSUE TITLE
Anchor tag helper not working or working bad

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Mvc#8639] opened 2018-10-24 16:36 UTC
_From @spzvtbg on Wednesday, 24 October 2018 09:31:18_

### I'm still new and learning, but I think the links should go wherever they are pointed no matter where they are

_Copied from original issue: aspnet/AspNetCore#3710_

**Comment by mkArtakMSFT** [comment] 2018-10-24 16:36
_From @mkArtakMSFT on Wednesday, 24 October 2018 16:34:59_

Thanks for contacting us, @spzvtbg.
@dougbu, can you please investigate this? Thanks!

**Comment by spzvtbg** [comment] 2018-10-25 08:15
So I want to have a web application with 2 languages. For this purpose I use localizations. As I mentioned for each role I will have the area and for each area I will use a separate layout but with the same [_LoginPartial](https://github.com/spzvtbg/Csharp-Web/blob/master/TheacherDiary/TheacherDiary.Web/Views/Shared/_LoginPartial.cshtml). For this purpose, I use a list of links for changing languages. 
    1. I tried with a separate  _LoginPartial, but the result was the same but in all cases the list itself works and shows the options but there is nothing going on when choosing.    
    2. When there is no user entered everything works fine, when someone joins the exchange links do not working:
         a. Initially, I make the language-changing method  in the [HomeController](https://github.com/spzvtbg/Csharp-Web/blob/master/TheacherDiary/TheacherDiary.Web/Controllers/HomeController.cs), but the links did not going there.
         b. Then I moved the method to a [separate page](https://github.com/spzvtbg/Csharp-Web/blob/master/TheacherDiary/TheacherDiary.Web/Areas/Identity/Pages/SetLangueage.cshtml.cs) so it worked, but by debugging the application does not enter the method.


That is pretty all, the Point is that that links not working and I use <a asp-area="" asp-controller="Home" asp-action="Index" …. - because I showing Images, that I can not do with a @Html.Action that is why  I did not try this Option. I suppose the problem comes either from the logout form or localization process or both together

**Comment by dougbu** [comment] 2018-10-25 18:45
@spzvtbg the problem is in your `Startup.Configure(...)` method. You're creating two MVC middleware instances that know nothing about each other and that confuses many things, especially routing.

Instead of
``` c#
app.UseMvc(routes =>
    {
        routes.MapRoute(
            name: "areas",
            template: "{area:exists}/{controller}/{action}/{id?}"
        );
    });
app.UseMvc(routes =>
    {
        routes.MapRoute(
            name: "default",
            template: "{controller=Home}/{action=Index}/{id?}");
        );
    });
```
it should be
``` c#
app.UseMvc(routes =>
{
    routes
        .MapRoute(
            name: "areas",
            template: "{area:exists}/{controller}/{action}/{id?}")
        .MapRoute(
            name: "default",
            template: "{controller=Home}/{action=Index}/{id?}");
});
```

**Comment by dougbu** [comment] 2018-10-25 18:46
Thank you for your feedback. We're closing this issue as the questions asked here have been answered.

**Closed by dougbu** 2018-10-25 18:46 UTC
Labels: investigate

**Comment by spzvtbg** [comment] 2018-10-26 06:46
@dougbu, а very stupid mistake on my part, I do not know how to apologize for the lost time, really sorry for that. The next time I will be carefuly.
I apologize once again to you and all those who committed this mistake, with best regards.
