### ISSUE TITLE
Add 'expression' action link helpers to MVC

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#544] opened 2014-05-19 18:06 UTC
We should consider adding helpers like this:

`@Html.ActionLink<HomeController>(c => c.Index(5))`

We shipped these in the past in Microsoft.Web.Mvc, and some 3rd party packages shipped them for webapi.

**Comment by danroth27** [comment] 2016-08-18 16:40
Duplicate of #2646

**Closed by danroth27** 2016-08-18 16:40 UTC
Labels: 0 - Backlog, enhancement
