### ISSUE TITLE
RenderSection is rendering incorrectly inside tag attribute

### ISSUE THREAD

**Issue by CoderProject** [aspnet/Mvc#6343] opened 2017-05-31 16:31 UTC
To reproduce the issue write the RenderSection inside a tag attribute in your Layout in Shared folder:
Exp: `<body class="@RenderSection("cls",false)">`

Set the section content in a view:
`@section cls{login}`

The result is rendered as following:
`<bodylogin class>`

**Comment by Eilon** [comment] 2017-06-05 22:10
@NTaylorMullen / @rynowak / @pranavkm - this looks pretty weird. Assigning to @NTaylorMullen to investigate.

**Comment by NTaylorMullen** [comment] 2017-06-05 22:58
This is a duplicate of: https://github.com/aspnet/Razor/issues/677

**Comment by Eilon** [comment] 2017-06-06 16:31
Indeed it is, and we have decided not to fix it. The linked bug has suggested alternatives.

**Closed by Eilon** 2017-06-06 16:31 UTC
Labels: 1 - Ready, bug
