### ISSUE TITLE
Conneg: Add diagnostics for better debugging.

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#708] opened 2014-06-26 16:12 UTC
we consistently see folks struggling to understand the content negotiation process and why a certain format was chosen. This feature should probably take a cue from route debugging and enable some sort of tracing, understanding without having to debug through the MVC source code

**Comment by yishaigalatzer** [comment] 2015-01-14 23:32
Duplicate of logging

**Closed by yishaigalatzer** 2015-01-14 23:32 UTC
