### ISSUE TITLE
Support calling HtmlHelper methods from within tag helpers for nested models

### ISSUE THREAD

**Issue by fschmied** [aspnet/Mvc#6645] opened 2017-08-11 10:04 UTC
The `ModelExpression` used by tag helpers only provides the expression in string form, not in `LambdaExpression` form. Due to #6639 (resp. #4821), calling `IHtmlHelper` methods such as `Editor` and `Display` with this string expression fails for nested models.

Please provide a fix to this.

A simple way would be to expose the protected `HtmlHelper.Generate...` methods (which take a `ModelExplorer`), e.g.,  either on `IHtmlHelper` or on `IHtmlGenerator`.

**Comment by dougbu** [comment] 2017-08-11 15:43
@fschmied what should be fixed other than #4821? That is, if we fixed #4821, what additional changes would you like to see in this area?

**Comment by fschmied** [comment] 2017-08-12 07:30
@dougbu In principle, I just want a supported way of rendering editor templates etc. from within a tag helper. Fixing #4821 is one way to make this work.

Exposing GenerateEditor(ModelExplorer, ...) etc. is another one, with the added benefit of avoiding the roundtrip ModelExpression -> string -> ModelExplorer.

So, to answer your question: If you fix #4821, that's an okay solution to my problem. If you don't fix that, please expose the corresponding APIs.

**Comment by dougbu** [comment] 2017-09-07 21:46
Duplicate of #6512.

**Closed by dougbu** 2017-09-07 21:46 UTC
Labels: duplicate
