### ISSUE TITLE
Response.WriteAsync causes "The connection was reset"

### ISSUE THREAD

**Issue by ruchanb** [aspnet/Mvc#6809] opened 2017-09-12 08:14 UTC
I have following code
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {        
        public async Task<IActionResult> Test()
        {
            await Response.WriteAsync("Hello");
            return Ok();
        }
    }
}
```
When i try to view `Home\Test` in browser, I get the error 
```
This site can’t be reached

The connection was reset.
```
Steps to Reproduce
- Create new Asp.net Core project
- In home controller add the above method

Project file
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.2" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.1" />
  </ItemGroup>

</Project>

```

Removing the `Response.WriteAsync` causes no issue. What is causing the issue?

**Comment by Eilon** [comment] 2017-09-12 17:13
Are you running this directly in Kestrel (default when launching from command line), in IIS Express (default when launching from Visual Studio on Windows), or something else?

**Comment by Eilon** [comment] 2017-09-12 17:14
cc @halter73 @Tratcher in case you guys have any thoughts.

**Comment by Tratcher** [comment] 2017-09-12 17:51
`OK()` sets the status code, correct? That can't be done after you call Write. I expect there to be an invalid operation exception in the logs for this request.

**Comment by Tratcher** [comment] 2017-09-12 17:52
Can you change the return type from `Task<IActionResult>` to `Task`?

**Comment by davidfowl** [comment] 2017-09-12 18:38
It's strange this causes a connection reset (at first glance)

**Comment by Tratcher** [comment] 2017-09-12 18:40
An unhandled exception after the first write causes a connection reset because it's too late to send a 500.

**Comment by halter73** [comment] 2017-09-13 00:47
@Tratcher is right. Some browsers like IE/Edge will show the partial chunked content written to the response body before the connection was closed, but I know Chrome won't without a chunked terminator.

Normally you wouldn't get a connection reset since Kestrel normally waits for whatever has been written to the response to body flush given an application error. It doesn't try to consume the request body prior to closing the connection though, so maybe that's the cause of the reset.

**Comment by ruchanb** [comment] 2017-09-13 05:29
@Eilon I used IISExpress which had the mentioned error. Using CLI gives 
```localhost unexpectedly closed the connection.
ERR_INCOMPLETE_CHUNKED_ENCODING
```
Here is the stack trace
```info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action WebApplication1.Controllers.HomeController.Test (WebApplication1) in 156.8609ms
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.InvalidOperationException: StatusCode cannot be set, response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.set_StatusCode(Int32 value)
   at Microsoft.AspNetCore.Mvc.ActionResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware.<ExecuteWithFilter>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      The response has already started, the error page middleware will not be executed.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL7QCVMHJR7N": An unhandled exception was thrown by the application.
System.InvalidOperationException: StatusCode cannot be set, response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.set_StatusCode(Int32 value)
   at Microsoft.AspNetCore.Mvc.ActionResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by ruchanb** [comment] 2017-09-13 05:38
changing the code to
```
public async Task Test()
        {
            await Response.WriteAsync("Hello");           
        }
````
it gives the desired result.
From the discussion above, should I assume, it is by design? Doesn't feel like it though.

**Comment by Tratcher** [comment] 2017-09-13 10:58
Yes it is by design. Normally in MVC you don't write directly to the response, you return some sort of ActionResult that does it for you. Doing both causes a conflict, you can't return two responses for one request.

**Comment by Eilon** [comment] 2017-09-13 15:49
Closing because this issue is by-design for the reasons mentioned above.

**Closed by Eilon** 2017-09-13 15:49 UTC

**Comment by davidfowl** [comment] 2017-09-14 15:38
MVC needs a InlineActionResult that just exposes the lambda.

**Comment by Tratcher** [comment] 2017-09-14 15:59
Wouldn't that do the same thing as returning void?

**Comment by davidfowl** [comment] 2017-09-14 16:02
> Wouldn't that do the same thing as returning void?

That's an EmptyResult.

I should have been clearer with a code sample.

```C#
public IActionResult Foo()
{
  return Result(context => context.HttpContext.Response.WriteAsync("Hello World"));
}
```

**Comment by Tratcher** [comment] 2017-09-14 16:04
How is that different from this?
```
public async Task Foo()
{
  await HttpContext.Response.WriteAsync("Hello World");
}
```

**Comment by davidfowl** [comment] 2017-09-14 16:05
For all the same reasons that returning action results exists today. Filters can look at the results, make decisions based on it, short circuit etc.

**Comment by Tratcher** [comment] 2017-09-14 16:08
Ah, seems useful. Not sure how you communicate that usefulness in the API names though.

**Comment by Eilon** [comment] 2017-09-14 17:13
Clearly it would be `ActionActionResult` 😄
