### ISSUE TITLE
Array or List in query string does not get parsed

### ISSUE THREAD

**Issue by ZsoltBendes** [aspnet/Mvc#7712] opened 2018-04-26 13:42 UTC
I have a controller with and end point that accepts a list of integers in a GET method. The In version 2.1 preview1 the method is working as expected. But in 2.1 preview2 the parameter is an empty list.

### Functional impact
The end point parameter does not get parsed.

### Minimal repro steps

1. Create an end point that can be called with an array of items like: 
/api/v1/Tags/getByIds?ids=1&ids=2

2.  Call the end point.

### Expected result
The ids should be in the parameter list.

### Actual result
The list is empty

The sample that I tried: 
[HttpGet]
        [Route("getByIds")]
        public async Task<IActionResult> GetTagsByIds([FromQuery]List<int> ids)
        {
            var result = await _repository.GetTagsByIdsAsync(ids);
            return Ok(result);
        }

This code works fine in preview1 and 2.0. In preview2 the ids list is empty.

**Comment by mkArtakMSFT** [comment] 2018-04-26 17:30
Thanks for contacting us, @ZsoltBendes.
@dougbu, I remember we made some changes in this area during preview2. Is this an expected result of those changes/

**Comment by dougbu** [comment] 2018-04-26 18:02
@mkArtakMSFT I reviewed what went into that milestone and the only thing I can think of is the ability to enable / disable new features using `CompatibilityVersion.Version_2_1` or `CompatibilityVersion.Version_2_0`. But, none of those new features should affect this scenario. On the other hand, this may relate to one of the model binding regressions found in Preview 1 but not fixed until RC1.

@ZsoltBendes what you're describing is covered in a number of Mvc tests which were not failing in Preview 2. I suspect there's something more going on in your test case. Do you have a small repro project, preferably in a GitHub repo?

**Comment by mkArtakMSFT** [comment] 2018-05-10 17:49
@dougbu, @ZsoltBendes has provided a repro now. Please advise on what's wrong with the usage he has (assuming that's the case).

**Comment by ZsoltBendes** [comment] 2018-05-14 10:47
@mkArtakMSFT in the RC1 I noticed that this issue is not present anymore.

**Comment by dougbu** [comment] 2018-05-15 05:27
>  in the RC1 I noticed that this issue is not present anymore.

Upgrading your repro project to RC1 doesn't change the behaviour in my testing. I _think_ I understand what's going on but not if the problem has gone away in your environment.

**Comment by dougbu** [comment] 2018-05-15 05:40
FYI in `dev`, this problem is likely at https://github.com/aspnet/Mvc/blob/d9f035ad7c4693c314e293f21bfef7ed002dc8e2/src/Microsoft.AspNetCore.Mvc.Core/Internal/ApiBehaviorApplicationModelProvider.cs#L258-L260

Put another way, the app model provider is treating `List<int>` as a complex type and unconditionally setting the parameter's `BinderModelName` to `string.Empty` instead of `"ids"`. (Should almost-always exclude collections when using `IsComplexType`.)

**Comment by mkArtakMSFT** [comment] 2018-05-15 16:55
Thanks @dougbu. Then I don't understand how is this possible:

> @mkArtakMSFT in the RC1 I noticed that this issue is not present anymore.

@ZsoltBendes, can you also share your `RC1` upgraded project?

**Comment by ZsoltBendes** [comment] 2018-05-18 13:34
@mkArtakMSFT @dougbu I took one more look on the RC1 project that uses this code, and fails. Looks like I made a mistake when testing this on RC1. Sorry about the that and the confusion it may caused.

**So the bug is still in the repository** :(

**Comment by springy76** [comment] 2018-06-05 13:44
I'm on final 2.1 and an action having a `[FromQuery] string[] parts` parameter which has been working since 2012 (there it was `[FromUri]`) now stops working as soon as I add the `[ApiController]` attribute to the controller class.

Then in the log I see the following lines:
```
[Debug]  54.257  60 Debug| Attempting to bind parameter 'parts' of type 'System.String[]' ... (AsyncTaskMethodBuilder`1.Start => <BindModelAsync>d__11.MoveNext => MvcCoreLoggerExtensions.AttemptingToBindParameterOrProperty) [Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder] ****
[Debug]  54.263  60 Debug| Attempting to bind parameter 'parts' of type 'System.String[]' using the name '' in request data ... (AsyncTaskMethodBuilder.Start => <BindModelAsync>d__10.MoveNext => MvcCoreLoggerExtensions.AttemptingToBindModel) [Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinder] ****
[Debug]  54.272  60 Debug| Could not bind to collection using a format like =value1&=value2 (AsyncTaskMethodBuilder.Start => <BindModelAsync>d__10.MoveNext => MvcCoreLoggerExtensions.NoNonIndexBasedFormatFoundForCollection) [Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinder] ****
[Debug]  54.277  60 Debug| Attempting to bind model using indices. Example formats include: [0]=value1&[1]=value2, [0]=value1&[1]=value2, .index=zero&.index=one&[zero]=value1&[one]=value2 (<BindModelAsync>d__10.MoveNext => CollectionModelBinder`1.BindComplexCollection => MvcCoreLoggerExtensions.AttemptingToBindCollectionUsingIndices) [Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinder] ****
[Debug]  54.287  60 Debug| Could not find a value in the request with name '[0]' of type 'System.String'. (<BindComplexCollectionFromIndexes>d__16.MoveNext => SimpleTypeModelBinder.BindModelAsync => MvcCoreLoggerExtensions.FoundNoValueInRequest) [Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinder] ****
[Debug]  54.287  60 Debug| Done attempting to bind model of type 'System.String' using the name '[0]'. (<BindComplexCollectionFromIndexes>d__16.MoveNext => SimpleTypeModelBinder.BindModelAsync => MvcCoreLoggerExtensions.DoneAttemptingToBindModel) [Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinder] ****
[Debug]  54.289  60 Debug| Done attempting to bind parameter 'parts' of type 'System.String[]'. (AsyncTaskMethodBuilder.Start => <BindModelAsync>d__10.MoveNext => MvcCoreLoggerExtensions.DoneAttemptingToBindModel) [Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinder] ****
[Debug]  54.289  60 Debug| Done attempting to bind parameter 'parts' of type 'System.String[]'. (AsyncTaskMethodBuilder`1.Start => <BindModelAsync>d__11.MoveNext => MvcCoreLoggerExtensions.DoneAttemptingToBindParameterOrProperty) [Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder] ****
[Debug]  54.290  60 Debug| Attempting to validate the bound parameter 'parts' of type 'System.String[]' ... (AsyncTaskMethodBuilder`1.Start => <BindModelAsync>d__11.MoveNext => MvcCoreLoggerExtensions.AttemptingToValidateParameterOrProperty) [Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder] ****
[Debug]  54.303  60 Debug| Done attempting to validate the bound parameter 'parts' of type 'System.String[]'. (AsyncTaskMethodBuilder`1.Start => <BindModelAsync>d__11.MoveNext => MvcCoreLoggerExtensions.DoneAttemptingToValidateParameterOrProperty) [Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder] ****
```

And the array is always **EMPTY**!

Usage is (and has been since years): `?parts=p1&parts=p2`

I also tried `?parts=p1,p2` and `?parts[0]=p1&parts[1]=p2` but no change, not even `?[0]=p1&[1]=p2` as the log lines suggest.

**HELP**

**Comment by kishanAnem** [comment] 2018-06-10 14:51
Hi @mkArtakMSFT and @dougbu,

Please let me know is this right way to fix. I got expected results.

![image](https://user-images.githubusercontent.com/8208927/41202662-217f28a0-6cea-11e8-8c89-f57ed8989aa2.png)

And all test cases are passed.

![image](https://user-images.githubusercontent.com/8208927/41202677-5d04e4d2-6cea-11e8-85f2-3753a4a99a90.png)
If I'm not wrong modelBinder is picking CollectionModelBinder<int>.

![image](https://user-images.githubusercontent.com/8208927/41202781-74a230b2-6ceb-11e8-90b3-24a8d64cb96a.png)
ParameterModelName has to set explicitly, always use that as the prefix. With this check it has fixed.
[9811cff](https://github.com/kishanAnem/Mvc/commit/9811cffedb8f6efdd5553fa1385049c79aaa52d1)

**Comment by dougbu** [comment] 2018-06-10 19:03
@kishanAnem the problem is not in `ParameterBinder` at all. The fix I'll implement will be in `ApiBehaviorApplicationModelProvider`.

**Comment by KLuuKer** [comment] 2018-06-13 08:51
Would it be possible to get this in a 2.1.x patch?
This is completely blocking us from using ApiExplorer

**Comment by BladeWise** [comment] 2018-06-13 15:01
Is there an official workaround in the meantime?

**Comment by dougbu** [comment] 2018-06-13 15:36
The main workaround is to remove `[ApiController]` from any controllers containing actions with collection parameters.

**Comment by BladeWise** [comment] 2018-06-13 16:08
Uhmmmm, not really a fan of this workaround, which can cause more problems (in our codebase) than the ones it can solve.
I suppose the best way at the moment would be to explicitly set a ModelBinder on the collection parameter, am I wrong?

**Comment by dougbu** [comment] 2018-06-13 16:33
@BladeWise what `[ApiController]` changes is the binder model name. So, `[FromQuery(Name="ids")]` _should_ work in this particular case.

**Comment by BladeWise** [comment] 2018-06-13 17:48
@dougbu  Thanks for the hint, I'll try it and report my findings.

**Comment by BladeWise** [comment] 2018-06-14 08:16
I can confirm that the workaround works (at least in my case).
The multiple values (e.g.`ids=1&ids=2`) are properly bound to the collection once the Name property is specified in the FromQuery attribute.

@dougbu Thanks a lot for your support! :)

**Comment by springy76** [comment] 2018-06-14 15:23
As written 9 days ago, for some reason this `FromQuery.Name` property did not work for me.

**Comment by mkArtakMSFT** [comment] 2018-06-19 15:39
> Would it be possible to get this in a 2.1.x patch?

Not really @KLuuKer, given the simple workaround is available.

**Comment by dougbu** [comment] 2018-06-19 17:51
> is it right way?

Yes, this is the correct approach. A few points:
- Need to also fix the block here: https://github.com/aspnet/Mvc/blob/58aa16ee696a00fb40d91a4011c2c5f890ea983d/src/Microsoft.AspNetCore.Mvc.Core/Internal/ApiBehaviorApplicationModelProvider.cs#L211-L217
- Need a better name than `isComplexTypeParameter`. I suggest `parameterMetadata` or just `metadata`.
- Need tests 😸

**Comment by kishanAnem** [comment] 2018-06-19 18:06
👍. will add tests.

**Comment by kishanAnem** [comment] 2018-06-23 01:03
Hi @dougbu,

Is that PR is fine correct?

**Comment by dougbu** [comment] 2018-06-23 01:28
> Is that PR is fine correct?

@kishanAnem I have a few PRs to review and should get to yours before Monday.

**Comment by kishanAnem** [comment] 2018-06-23 01:34
thank you very much @dougbu. ☺️

**Comment by CliffordSimak** [comment] 2018-06-23 12:18
I have the same issue. I hope you fix it 🙏

```
>dotnet --info
 Version:   2.1.301
 Commit:    59524873d6

 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by dougbu** [comment] 2018-06-26 18:46
e1af5b8b6d

Thanks again @kishanAnem

**Closed by dougbu** 2018-06-26 18:46 UTC
Labels: 1 - Ready, PRI: 2 - Preferred, bug, cost: S
