### ISSUE TITLE
Simplify Mvc.Testing usage

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7620] opened 2018-04-09 19:16 UTC
The current Mvc.Testing API has a few quirks that make it less usable / understandable:
- `WebApplicationFactory<TEntryPoint>` exposes a `ClientOptions` property that
  - is only used when calling `CreateClient()` i.e. it's ignored when calling `CreateDefaultClient()`. This is documented but not at all intuitive
  - duplicates the `CreateClient(WebApplicationFactoryClientOptions)` feature. Why do both approaches exist?
- The `WebApplicationFactory<TEntryPoint>.CreateDefaultClient(Uri baseAddress, ...)` makes it simple to specify the base address of the created `HttpClient`. No similar `WebApplicationFactory<TEntryPoint>.CreateClient(...)` overload exists; users must either instantiate a `WebApplicationFactoryClientOptions` instance or change ``WebApplicationFactory<TEntryPoint>.ClientOptions.BaseAddress` to do the same thing.

**Comment by mkArtakMSFT** [comment] 2018-04-10 17:12
@danroth27, would be great to hear your opinion about this

**Comment by danroth27** [comment] 2018-04-11 07:38
I think these are by design, but @javiercn can say for sure.

**Comment by javiercn** [comment] 2018-04-11 14:31
@dougbu what is your proposal here?

**Comment by dougbu** [comment] 2018-04-11 15:57
@javiercn I suggest
1. remove the `ClientOptions` property because `CreateClient(WebApplicationFactoryClientOptions)` is clearer
  - perhaps leave a `static` `_clientOptions` or `_defaultClientOptions` field for `CreateClient()`'s use
2. add a `CreateClient(Uri baseAddress)` overload

**Comment by javiercn** [comment] 2018-04-12 21:11
> remove the ClientOptions property because CreateClient(WebApplicationFactoryClientOptions) is clearer

The most common use case for this class is to call CreateClient(). ClientOptions is there so that you can configure how the clients are created by default for all your tests.

For tests where you need to customize something (like avoid autoredirects, or use a different base Uri) you can pass in the client options directly to get the client you want instead of the default one configured for the factory.

For tests where you need complete control (very few) you have CreateDefaultClient which will allow you to explicitly configure the list of handlers applied to your client (useful for scenarios that involve authentication for example).

As a convenience, in that method you get an overload to set the base address along with the list of handlers to apply to the client.

Testing in most real applications requires both, handling cookies and redirects automatically to make the tests bearable. Which is why CreateClient exists and why it's considered the main API.

CreateDefaultClient is there for the 5% scenarios where you need absolute control over the list of handlers+address applied to the request.

**Comment by dougbu** [comment] 2018-04-12 21:55
> For tests where you need complete control (very few) &hellip;

This is very strange. `CreateClient(WebApplicationFactoryClientOptions)` gives you some extra control. But, you need to switch to `CreateDefaultClient(...)` for "complete" control?

> CreateDefaultClient is there for the 5% scenarios where you need absolute control over the list of handlers+address applied to the request.

Why is the "default" the one that doesn't work like a real client and is supposedly for the 5% case?

**Comment by javiercn** [comment] 2018-04-12 21:58
@dougbu Because I wanted a different name and @Eilon preferred default. Default in this context means "Empty/No additional behavior"

**Comment by dougbu** [comment] 2018-04-12 22:07
@javiercn if that's the case, then the following overloads would make more sense:
- `CreateClient(params DelegatingHandler[])`
- `CreateClient(Uri, params DelegatingHandler[])`
- `CreateClient(WebApplicationFactoryClientOptions)`
- `CreateDefaultClient()`
- `CreateDefaultClient(Uri)`

Actually, do we have an example of anyone / anything except `WebApplicationFactoryClientOptions` using `DelegatingHandler`s? It's not clear why the `handlers` parameters are publicly exposed.

**Comment by dougbu** [comment] 2018-04-12 22:34
Hmm, #7638 and #7637 are interesting given a user's `WebApplicationFactory<T>` subclass is _never_ returned from `WithWebHostBuilder(...)`. See issue #7541 and the fix in #7542 / 51784bb2d6. Can't down-cast what `WithWebHostBuilder(...)` returns to a user type.

That is, neither PR composes well with other parts of the Mvc.Testing package. Maybe we should switch the #7541 fix to a `protected virtual Clone()` approach to enable these requested features end-to-end?

**Comment by dougbu** [comment] 2018-04-12 23:05
> We would pass in a delegate in the same way we do for other methods for the webhostbuilder factory, so no need to switch the approach.

Pass delegates into what? `WithWebHostBuilder(...)` is not `virtual`.

**Comment by mkArtakMSFT** [comment] 2018-04-19 18:04
Closing this issue as some of the aspects of the `WebApplicationFactory` class have been improved already. Also, we'll look forward for customer feedback going forward and make sure that subsequent feedback is address in future releases.

**Closed by mkArtakMSFT** 2018-04-19 18:04 UTC
Labels: investigate
