### ISSUE TITLE
Razor Pages do not pick up changes to _ViewImports.cshml outside of the Pages directory

### ISSUE THREAD

**Issue by halter73** [aspnet/Mvc#6428] opened 2017-06-21 23:45 UTC
#### /_ViewImports.cshtml
```
@namespace TestNamespace
```

#### /Pages/TestPage.cshtml
```
@page

@GetType()
```

#### /Views/Home/Index.html
```
@{
    Layout = null;
}

@GetType()
```

To reproduce this issue, take the following steps:

- Ensure all the files listed above are in your MVC 2.0.0-preview2 project.
- Launch the web project from VS. I was debugging the app while doing the following steps, but I don't think debugging is necessary to repro the issue.
- Verify that the initial response for `http://example/` is `TestNamespace.Views.Home.Index_View` and the initial output for `http://example/TestPage` is `TestNamespace.Pages.TestPage_Page`.
- Without stopping the app, edit the namespace to `/_ViewImports.cshtml` to something other than `TestNamespace` like `NewNamespace`.
- Verify that the initial response for `http://example/` has now changed to `NewNamespace.Views.Home.Index_View` as expected.
- Note that the response for `http://example/TestPage` has **not** changed to `NewNamespace.Pages.TestPage_Page`. Instead it's still `TestNamespace.Pages.TestPage_Page`

If you restart the app or modify TestPage.cshtml, the namespace changes will be picked up.

**Comment by pranavkm** [comment] 2017-06-21 23:59
Dupe of https://github.com/aspnet/Mvc/issues/6308

**Comment by pranavkm** [comment] 2017-06-21 23:59
Actually no, this is different 👍

**Closed** 2017-06-27 16:30 UTC
Labels: 2 - Working, bug
