### ISSUE TITLE
Cannot resolve custom TagHelper when running on Mono or Core CLR (using docker)

### ISSUE THREAD

**Issue by christiansparre** [aspnet/Mvc#3234] opened 2015-09-30 11:54 UTC
I have an issue with a very simple site I'm trying to get running on Linux with Mono/Core CLR on docker. I get the following error:

```Cannot resolve TagHelper containing assembly 'TagHelperTest'. Error: Could not load file or assembly 'TagHelperTest, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.```

It works on windows using both IISExpress and WebListener.

I have put up the simplest project that for me reproduces the error here: https://github.com/christiansparre/aspnettaghelperissue

I have tried asking in the Jabbr channel, but no luck. I'm unsure how to proceed resolving this issue, so I hope someone here can help :)

**Comment by NTaylorMullen** [comment] 2015-09-30 15:17
@dougbu you got the `TagHelper` tests working on CoreCLR right?

**Comment by dougbu** [comment] 2015-09-30 15:35
@NTaylorMullen yes and no. `TagHelper`s are covered in our functional tests, those are enabled for Core CLR, and they worked fine at the Beta 7 release. However our `TagHelper` unit tests are not enabled for Core CLR.

**Comment by dougbu** [comment] 2015-09-30 15:37
@christiansparre which DNX version are you using? Even better, what is the output of `dnu --version`?

**Comment by Eilon** [comment] 2015-09-30 16:09
@dougbu putting on your plate to investigate.

**Comment by christiansparre** [comment] 2015-09-30 16:13
@dougbu I have only tested using docker at the moment so right now totally based on the https://github.com/aspnet/aspnet-docker/blob/master/1.0.0-beta7-coreclr/Dockerfile and https://github.com/aspnet/aspnet-docker/blob/master/1.0.0-beta7/Dockerfile files. So unless there is an issue with the docker files my guess would be beta7

**Comment by christiansparre** [comment] 2015-09-30 16:32
This is the output from ```dnu --version```

```
root@4c87f14a74b8:/app# dnu --version
Microsoft .NET Development Utility
 Version:      1.0.0-beta7-15532
 Type:         CoreCLR
 Architecture: x64
 OS Name:      Linux
```

and

```
root@9c20b8e8b71a:/app# dnu --version
Microsoft .NET Development Utility
 Version:      1.0.0-beta7-15532
 Type:         Mono
 Architecture: x64
 OS Name:      Linux

**Comment by dougbu** [comment] 2015-10-07 04:24
@christiansparre I am unable to reproduce your issue. Are you still seeing it?

`dnu restore` brought down slightly newer packages for me. The https://api.nuget.org/v3/index.json feed may have been updated since your last attempt.

If the problem continues after you run `dnu restore` again, it may be OS-specific. Please provide the output from the following commands in that case.
```
uname -a
lsb_release
cat /etc/lsb-release
cat /etc/os-release
```

**Comment by christiansparre** [comment] 2015-10-07 06:06
@dougbu thank you for looking into it. I did a rebuild of the docker container and also did a ```dnu restore``` with no success. This is the output from the above commands.

```
root@7ca9c9c8c9a9:/app# uname -a
Linux 7ca9c9c8c9a9 4.0.9-boot2docker #1 SMP Thu Sep 10 20:39:20 UTC 2015 x86_64 GNU/Linux
root@7ca9c9c8c9a9:/app# lsb_release
bash: lsb_release: command not found
root@7ca9c9c8c9a9:/app# cat /ect/lsb_release
cat: /ect/lsb_release: No such file or directory
root@7ca9c9c8c9a9:/app# cat /etc/os_release
cat: /etc/os_release: No such file or directory
```

So something is clearly missing, I'm not that familiar with Linux :) Hope it helps

The above test was done with docker-machine on windows with boot2docker in VirtualBox. I have hade the same error on DigitalOcean with their docker image. I have not tried installing a Linux distribution including Mono/CoreCLR etc. myself. I'm only experimenting with docker.

**Comment by dougbu** [comment] 2015-10-08 06:48
@christiansparre I remain unable to reproduce this issue, even within the Docker image. I suspect the difference is in the kernels since Docker uses the host's kernel. In either my host or within a Docker image, I see
```
> uname -r
3.19.0-30-generic
```
I'm unsure of the kernel in boot2docker 4.0.9 but suspect it's not 3.19.0-30. Note boot2docker has also recently been deprecated. Pages such as https://github.com/boot2docker/osx-installer/releases point to https://www.docker.com/toolbox instead.

Detailed steps...
```
> docker run -it microsoft/aspnet:1.0.0-beta7-coreclr bash
> apt-get install git
> git clone https://github.com/christiansparre/aspnettaghelperissue
> cd aspnettaghelperissue/TagHelperTest/src/TagHelperTest/
> dnu restore
> dnx kestrel &
> curl http://localhost:5004

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Home Page</title>
</head>
<body>
<div>Hello world</div>
<div>Test from TagHelper</div>
</body>
</html>
```

**Comment by dougbu** [comment] 2015-10-14 04:13
@christiansparre is this still an issue for you?

**Comment by christiansparre** [comment] 2015-10-14 05:58
@dougbu I just tried your example above using docker-machine and still boot2docker as it is still the image that Docker Toolbox and docker-machine uses and it works. 

```uname -a``` gives kernel version 4.0.9, but if 3.19.0 is the one you support i'll find a way to use that.

You can close this if you do not need to do further investigation. Thank you for your help :)

**Comment by dougbu** [comment] 2015-10-14 06:29
Well, I wasn't saying 3.19.0 is the only kernel on Earth that works :smiley: but I'm glad you found a combination that works.

Closing. Please reopen or file a new issue if you encounter issues with your new setup.

**Closed by dougbu** 2015-10-14 06:29 UTC
Labels: investigate

**Comment by kbok** [comment] 2016-04-13 23:12
I'm confused. Is the bug still present? I'm having the same issue with a recent installation of Docker Toolbox: boot2docker 1.11.0, kernel 4.1.19. 

uname -a is `Linux f4a3481b56a6 4.1.19-boot2docker #1 SMP Thu Apr 7 02:41:05 UTC 2016 x86_64 GNU/Linux` (no lsb)

I'm using the vanilla aspnet images 1.0.0-rc1-update1 and the issue appears with both the coreclr and the mono images.

Boot2docker with kernel versions <4 are over one year old now, so that's impractical to just rollback to ISO. (FTR boot2docker hasn't been deprecated, but you're not supposed to use it directly, and use docker-machine instead).

I can update the repro if you need (it got a bit old).

**Comment by christiansparre** [comment] 2016-04-14 06:01
@kbok I have not really looked at this since October, feel free to mess with the repro if you like :)

I'm not really working with docker and aspnet core at the moment so have no idea if it is still a problem.

**Comment by kbok** [comment] 2016-04-14 20:15
I updated the repro, the problem is still here indeed: https://github.com/kbok/aspnettaghelperissue

@dougbu Could we reopen the issue?

**Comment by Eilon** [comment] 2016-04-14 22:30
Does this only repro on Mono? Or does it repro on CoreCLR?

**Comment by kbok** [comment] 2016-04-15 06:12
@eilon On both, though the dockerfile is configured for coreclr.
