### ISSUE TITLE
No way to specify default value for optional parameter action in attribute Route

### ISSUE THREAD

**Issue by kulmugdha** [aspnet/Mvc#1219] opened 2014-10-02 20:44 UTC
Scenario: I want to specify simple controller/action route using attribute route. In MVC5, you could specify:
[Route("home/{action=Index}")]

In K world, there is no equivalent of that
[Route("home/[action=Index]")] doesn’t work. I'd be great if we could specify this.

**Comment by danroth27** [comment] 2016-08-18 20:30
Duplicate of #3286

**Closed by danroth27** 2016-08-18 20:30 UTC
Labels: 0 - Backlog, enhancement
