### ISSUE TITLE
Sometimes Get 404 Error or another Action

### ISSUE THREAD

**Issue by EricPing** [aspnet/Mvc#3401] opened 2015-10-23 08:33 UTC
(My English is not very well)

I found a problem about ASP.NET 5 Beta 8 

Below is my code:
``` csharp
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.Json(this.ModelState.ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToArray()
                ));
            }

            return this.Json(new { });
        }
```

When I use ajax to Login Method (POST) very quickly send request

It will response JSON to me, 

However, after third requests, it will become HTML Page~

And, I put [HttpGet] before first line ** public IActionResult Login() **
After third requests, it will return 404~

Below is part code I put in Startup.cs

```csharp
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                        name: "default",
                        template: "{action}/{id?}",
                        defaults: new { controller = "Home", action = "Index" });
            });
```

Oh, I found, I forgot to put [FromBody] before LoginViewModel, but I think the response must be the same result ~~

Thank you for your help, Thanks!

**Comment by EricPing** [comment] 2015-10-23 08:35
Below is the code I put in Startup.cs

```csharp
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                        name: "default",
                        template: "{action}/{id?}",
                        defaults: new { controller = "Home", action = "Index" });
            });
```

**Comment by EricPing** [comment] 2015-10-23 08:42
Oh, I found, I forgot to put [FromBody] before LoginViewModel,  but I think the response must be the same result ~~ Thanks you very much

**Comment by dougbu** [comment] 2015-10-23 15:45
@EricPing are you running on Kestrel? If so this may be a duplicate of aspnet/KestrelHttpServer#270. Suggest trying WebListener (if you're running on Windows) and seeing if the issue goes away.

**Comment by dimaaan** [comment] 2015-10-23 16:59
Having this trouble too. 
Repeating a same post request to stateless controller give te 404 time to time.
My config (i use dev environment) is:

```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            // Add the platform handler to the request pipeline.
            app.UseIISPlatformHandler();

            // Configure the HTTP request pipeline.
            app.UseStaticFiles();

            if(env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

           // my stateless middleware here

            // Add MVC to the request pipeline.
            app.UseMvc();
```

**Comment by EricPing** [comment] 2015-10-24 13:29
@dougbu  I use Visual Studio 2015 with IIS Express ( just pressCtrl + F5 to run the site),
I will give a try on WebListener on Windows after weekend, thank you for your reply

**Closed** 2015-10-25 05:53 UTC
