### ISSUE TITLE
Microsoft.AspNetCore.Mvc.WebApiCompatShimTest currently does not build \ run tests on net461

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7049] opened 2017-11-13 20:45 UTC
Looks like we stopped compiling \ testing it on desktop. Adding `net461` TFM back causes builds to fail.

**Comment by kichalla** [comment] 2017-12-12 23:31
Duplicate of https://github.com/aspnet/Mvc/issues/5822

cc @dougbu @pranavkm

**Closed by kichalla** 2017-12-12 23:31 UTC
Labels: duplicate, task
