### ISSUE TITLE
IStringLocalizer<T> where T is part of library assembly and not web application assembly

### ISSUE THREAD

**Issue by xandhen** [aspnet/Mvc#5816] opened 2017-02-16 12:59 UTC
Hi,

I am having some serious issue setting up localization for our new web application and am forced to admit that this has gotten the best of me.

## Background

I have multiple web applications and multiple libraries, all which needs to support localisation. The idea is to inject IStringLocalizer instances into classes located in the libraries from a web application. A lot of string resources will be shared between the UI layer in the web applications and the business logic in the libraries. Therefor it is desired to share resource files and the idea is to use IStringLocalizer<ASharedClass> where ASharedClass is defined in a library.

Now, when I try to setup a simple solution to support this, I can't get the IStringLocalizer instances to use the correct resources files unless I override the ResourceManagerStringLocalizerFactory and clean it from "assembly.Resources". Interestingly, using ResourceManager works, although it picks resource files from unexpected locations.

## Demo
I have a simple demo repo for this, in which the web application is setup for localisation and setup to use the "Resources" folder for resource files. It has a vast amount of resource files in various places with various namings to try to get a resource loaded. Each resource file have a different value for the string "Test".

Repo URL: https://github.com/xandhen/NetCoreLocalizationPlayground

### Current output

IStringLocalizer (Class1): Test
Culture: sv:sv
ResourceManager: Localized string for value "Test" classlibrary root (en)
IStringLocalizer (LocalClass): Test

### Expected output

IStringLocalizer (Class1): Localized string for value "Test" web resource folder Namespace.class (sv)
Culture: sv:sv
ResourceManager: Localized string for value "Test" web resource folder Namespace.class (sv)
IStringLocalizer (LocalClass): Localized string for value "Test" web resource folder assembly local (sv)

### Analysis

As one can se, no resource file is used for looking up the string except for in the case where the ResourceManager class is used directly, but then it picks the resource file from the root of the library, not the resource folder of the library or the web application.

It is also visible the even though the default culture is set to Swedish, the UI culture gets set to English. This is also the case when the Accept-Language request header includes sv as the first language in the list.

**Comment by Eilon** [comment] 2017-02-17 21:18
@ryanbrandenburg can you take a look at this? I think this is an area where others have run into problems. Assuming this all works, but is tricky, do we have a sample for this? Or missing docs?

**Comment by xandhen** [comment] 2017-02-19 21:17
As an update, I noticed that there seems to be some connection with the assembly name and the root namespace of the library project. If I rename the project (only .csproj file, directory doesn't matter) to be the same as the root namespace of the library project, then it can successfully load the rest file from the Resources directory of the library project. If this is also done for the web application, then the assembly local res file can be found.

Output with .csproj files renamed to be equal to the root namespace.

IStringLocalizer (Class1): Localized string for value "Test" classlibrary resource dir (en)
Culture: sv:en
ResourceManager: Localized string for value "Test" classlibrary root (en)
IStringLocalizer (LocalClass): Localized string for value "Test" web resource folder assembly local (en)

**Comment by ryanbrandenburg** [comment] 2017-02-21 22:42
You are correct, renaming your csproj files fixes the issue. I've filed dotnet/sdk#895 to find out if this is expected behavior. If it is we'll update the documentation to reflect that.

**Comment by Eilon** [comment] 2017-02-22 17:40
@ryanbrandenburg I'm putting this on your plate for tracking until we get final confirmation from the SDK team.

**Comment by ryanbrandenburg** [comment] 2017-02-22 17:57
In the mean time @xandhen you can work around this if you set both AssemblyName and RootNamespace to the same value and use that value as the root of your class names.

**Comment by xandhen** [comment] 2017-02-23 08:09
@ryanbrandenburg Thanks for the tip. Explicitly setting the AssemblyName removes the need for renaming the csproj file and enables a "logical" naming of the project, not tied to the output assembly name.

I'm still puzzled about the culture since only CurrentCulture is set to Swedish while CurrentUiCulture is being set to English. The default request culture is set to "sv-SE" in the application startup and even though the HTTP Accept-Language request header has sv as the first language it is ignored for the UiCulture. This is really blocking me as the web application in development is a primarily Swedish application. I would like UiCulture to be set to english only if Swedish is completely missing from the localisation cookie, query string and request header.

Some additional food for thought though.

1. When injecting resources through IStringLocalizer<Class1> the resource directory within the class library is dictated by the localisation service configuration `services.AddLocalization((LocalizationOptions options) => options.ResourcesPath = ResourcePath);`
2. When getting resources through the ResourceManager the resources are expected to be located in the assembly root folder `new ResourceManager(typeof(Class1)).GetString("Test")`

I'm not sure this should be aligned or even how, but it could be worth mentioning this in the docs as it forces an alignment of resource file location within all the assemblies of an application.
A potential mitigation for this, which could be very useful in general, is to allow the executable assembly to override resource files in the referenced assemblies. This would allow one to place resource files in a directory of choice in the executable assembly therefor not be dependent on location in the referenced libraries (even though you have to copy all the resource files with a scoped file name). It would also allow an application to override resources in referenced libraries and provide more application tailored resources.

With this approach, the resource location would be resolved in this order

1. Resource directory in executable assembly (full namespace naming of resource files)
2. Resource directory in the assembly that owns the class

**Comment by xandhen** [comment] 2017-02-24 10:06
Another issue seems to be that the csproj file name can not include '.'. 
For example a library project with a project file named x.y.csproj and assembly and root namespace name of 'x.y' will not work. 
But a library project with a project file named xy.csproj and assembly and root namespace name of 'x.y' will work.

**Comment by ryanbrandenburg** [comment] 2017-02-24 21:31
I'm not sure I entirely follow your scenario in the second paragraph, maybe you could clarify with expected vs actual examples? But I do note that your SupportedCulture objects are different from eachother [here](https://github.com/xandhen/NetCoreLocalizationPlayground/blob/master/web/Startup.cs#L27) and that supportedCulture only has the Culture "se", which is the code for "Sami", not swedish.

We don't advise that people manually create instances of `ResourceManager` (if you know of somewhere where we do please let me know so we can fix it) and the behavior of a raw `ResourceManager` is not within the scope of the localization project or its documentation. If you DO create one then you'll have to learn the intricacies of how Resources are generated and retrieved. You can learn some about that by reading the code for `ResourceManagerStringLocalizer`.

Your second comment seems worth noting on dotnet/sdk#895 since it creates a limit on Resource names. I'll bring it up there.

**Comment by xandhen** [comment] 2017-02-24 22:06
@ryanbrandenburg Thanks for the tip and forwarding the resource name limits.

I tried however aligning the  SupportedCulture objects to the following

```
protected static List<CultureInfo> supportedCultures = new List<CultureInfo>
{
	new CultureInfo("sv-SE")
};
protected static List<CultureInfo> supportedUICultures = new List<CultureInfo>
{
	new CultureInfo("sv-SE"),
	new CultureInfo("en-US"),
	new CultureInfo("nn-NO")
};
```

This doesn't change anything however and the CurrentUICulture is still set to english. The only way to get Swedish UICulture is to provide an empty list of RequestCultureProviders to the RequestLocalizationOptions instance that is supplied as an argument to the app.UseRequestLocalization() call.

As this is my AcceptLanguage header, I would assume that the AcceptLanguageHeaderRequestCultureProvider provider would set Swedish as the UI language.

Accept-Language:sv,en-US;q=0.8,en;q=0.6,el;q=0.4

The expected outcome, for any request where a language cookie is not set and a query string parameter is not supplied, would be that if Swedish "sv" is supplied in the Accept-Language header property or if neither any of the supported UI cultures ("sv", "nn" or "en") are supplied in the Accept-Language header, that the CurrentUICulture is set to Swedish.
I would also expect that "en" or "nn" would only be set as the CurrentUICulture if they are supplied in the the Accept-Language header and "sv" is not supplied therein.

The current outcome is that the English is always set as the CurrentUICulture if it is present in the Accept-Language header, even if it is specified with a lower priority than other supported UI cultures. I've fiddled around with some combinations of RequestCultureProviders and Accept-Language header values and found that the core issue seems to be a bug in the prioritisation in the AcceptLanguageHeaderRequestCultureProvider class. It can be noted that my system (OS X) is set to English so maybe the AcceptLanguageHeaderRequestCultureProvider ranks the system culture higher than the language list supplied in the Accept-Language header value?

**Comment by ryanbrandenburg** [comment] 2017-02-24 23:26
You're welcome. Sorry for the confusion but I requested a little more information regarding the csproj "." stuff in an edit (I accidentally pressed comment while still composing my response).

You're requesting "general" swedish in your acceptLanguage, but you've told your program that you only accept Sweden swedish. Since your headers only accept the more general `sv` it won't give you the more specific `sv-SE`. The reverse would work (If your AcceptLanguage is `sv-SE` and your supportedUICultures includes `sv` you would be returned `sv`) but you can only go from more specific locals to less specific.

One way to solve this is to include `sv` in supportedUICultures, but the "correct" course depends on the specifics of that language tree, which I'll leave to you.

**Comment by xandhen** [comment] 2017-02-26 19:17
I'm a bit puzzled about the relationship between SupportedCulture and SupportedUICulture in this case. To my understanding, the UICulture is for language purposes, while Culture is mainly for formatting etc. I would therefor believe that language would be the primary selector and one could therefor go from less to more specifics. In my case I also only have a single supported culture, so regardless of the specifics of the header value, it will always be set to "sv-SE". 
Unfortunately to go form more to less doesn't work well with modern browsers sine e.g. adding an extra language in Chrome most of the time only gives you a less specific choice, unless the language selected comes in many cultures. In my case I only want to support multiple languages, but not cultures so being less specific in the SupportedUICulture list will not be a problem.

E.g. English has 7 different options in Chrome while Swedish only have one option, which does not include culture ("sv"). On OS X Safari is even worse, it will only send the primary OS language.

Perhaps these details of the AcceptLanguageHeaderRequestCultureProvider could be added to the docs?

**Comment by xandhen** [comment] 2017-02-26 19:19
@ryanbrandenburg regarding the csproj "." stuff I think you can ignore that for now. I had that issue in two applications in different repositories and now I can't reproduce it in any off them.

**Comment by ryanbrandenburg** [comment] 2017-02-27 18:23
You understand the difference between SupportedCulture and SupportedUICulture correctly, but I think your suggestion to go from less specific to more specific Cultures would be more confusing than helpful. If your application supported both es-ES and es-MX, and the AcceptHeader of a request was for "es" which one would be chosen under your system? Under the current system in this scenario if you wanted to return es-MX in this scenario you can simply create two resource sets, "es" which would be returned for a request of either es or es-MX and es-ES. @DamianEdwards does that all sound right?

That said, you're correct that we don't talk about this in the docs, I filed aspnet/Docs#2846.

**Comment by ryanbrandenburg** [comment] 2017-03-03 19:53
Seems like this is wrapped up so I'm closing it out.

**Closed by ryanbrandenburg** 2017-03-03 19:53 UTC
Labels: investigate
