### ISSUE TITLE
Bring back associated metadata type (buddy type) from MVC

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#1476] opened 2014-10-29 20:56 UTC
Desktop CLR had a mechanism where a one type could specify another type to be used as it's 'metadata type' for things like model metadata and validation.

We want to bring back this mechanism to support easier authoring of viewmodels.

See: http://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.metadatatypeattribute(v=vs.110).aspx

**Comment by yishaigalatzer** [comment] 2015-01-13 18:16
Duplicate of #1654

**Closed by yishaigalatzer** 2015-01-13 18:16 UTC
Labels: 2 - Sprint Backlog, enhancement
