### ISSUE TITLE
Mvc.Testing incompatible with current Razor application

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7615] opened 2018-04-08 20:56 UTC
## Repro Steps
The following is similar to the [Preview 1 functional testing instructions](https://blogs.msdn.microsoft.com/webdev/2018/03/05/asp-net-core-2-1-0-preview1-functional-testing-of-mvc-applications/) but done In Visual Studio using Preview 2 bits:
1. Create new ASP.NET Core Web Application
    - Later steps make more sense if "Create directory for solution" is enabled
2. Choose Web Application i.e. a Razor app and your favourite authentication scheme
3. Hit F5 or Ctrl-F5 to confirm app works fine
4. Add an xUnit Test Project (.NET Core) to the solution
5. Edit test project file to bump up the target framework: `<TargetFramework>netcoreapp2.1</TargetFramework>`
    - current Microsoft.AspNetCore.App package used in web application project is not compatible with a lower TFM
6. Add a reference from the test project to the web application project
7. Use Manage NuGet Packages to add a Microsoft.AspNetCore.Mvc.Testing package dependency to the test project
    - choose same version e.g. `2.1.0-preview2-30552` as Microsoft.AspNetCore.App package in the web application project
8. Edit UnitTest1 to perform a simple test:
    ``` c#
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc.Testing;
    using RazorApp1;
    using Xunit;

    namespace FunctionalTest
    {
        public class UnitTest1 : IClassFixture<WebApplicationFactory<Startup>>
        {
            private readonly HttpClient _client;

            public UnitTest1(WebApplicationFactory<Startup> factory)
            {
                _client = factory.CreateDefaultClient();
            }

            [Fact]
            public async Task Test1()
            {
                // Arrange & Act
                var response = await _client.GetAsync("https://localhost/");

                // Assert
                Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            }
        }
    }
    ```
    - use "http://localhost" if you chose _not_ to include HTTPS support when creating the web application project
9. Use Test Explorer to Run All tests

### Expected
The one test succeeds.
### Actual
Test fails, apparently due to a failed attempt to re-compile the Index.cshtml Razor page. Note the test project's bin includes the {app}.Views.dll assembly.
```
...
Result StackTrace:	
at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.DefaultPageLoader.Load(PageActionDescriptor actionDescriptor)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler.<>c__DisplayClass12_0.<RouteAsync>b__0(HttpContext c)
...
Result Message:	
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException : One or more compilation failures occurred:
umzefeie.bog(4,41): error CS0234: The type or namespace name 'Razor' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
umzefeie.bog(5,44): error CS0234: The type or namespace name 'RazorPages' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
umzefeie.bog(4,82): error CS0518: Predefined type 'System.Type' is not defined or imported
umzefeie.bog(4,119): error CS0518: Predefined type 'System.String' is not defined or imported
umzefeie.bog(4,142): error CS0518: Predefined type 'System.String' is not defined or imported
umzefeie.bog(5,89): error CS0518: Predefined type 'System.String' is not defined or imported
...
```

## Suspects
The attempt to re-compile a Razor page and its failure are likely separate problems. Probably have an incompatibility between the MSBuild pre-compilation approach and the MSBuild side of the Testing package.

## Versions
Microsoft Visual Studio Enterprise 2017: `15.7.0 Preview 3.0 [27604.0.d15.7]`
.NET Core SDK: `2.1.300-preview2-008523`
Microsoft.NETCore.App: `2.1.0-preview2-26403-06`
Microsoft.AspNetCore.App: `2.1.0-preview2-30552`
Microsoft.AspNetCore.Mvc.Testing: `2.1.0-preview2-30552`

**Comment by dougbu** [comment] 2018-04-09 05:15
Similar scenario using .NET Framework 4.6.1 succeeds. Major differences in successful case are the TFM and use of .NET Framework-compatible packages (not Microsoft.AspNetCore.App).

**Comment by dougbu** [comment] 2018-04-09 05:16
Found while verifying aspnet/Release#257.

**Comment by mkArtakMSFT** [comment] 2018-04-09 16:54
@javiercn, can you please look into this? Thanks!

**Comment by pranavkm** [comment] 2018-04-10 20:14
Investigated and this has the same root cause as https://github.com/aspnet/Mvc/issues/7617 although the presentation is different. Here's what happens:

1) Mvc does not discover RazorApp1 as an Mvc referencing library and consequently does not discover the compiled view either.
2) No parts returning requisite reference assemblies is registered, so runtime compilation of the Razor Page also fails.

Addressing, https://github.com/aspnet/Mvc/issues/7617 fixes both of these issues. Closing this as dup.

**Closed by pranavkm** 2018-04-10 20:14 UTC
Labels: 1 - Ready, bug
