### ISSUE TITLE
Add existing MVC applications as perf tests

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#7668] opened 2018-04-17 02:03 UTC
We should add our two existing (simple) test apps as workloads for the aspnet/benchmarks system

https://github.com/aspnet/Performance/tree/dev/testapp/BasicViews
https://github.com/aspnet/Performance/tree/dev/testapp/BasicApi

/cc @sebastienros

**Comment by mkArtakMSFT** [comment] 2018-05-24 16:59
Closing this as a dupe of https://github.com/aspnet/Mvc/issues/7805

**Closed by mkArtakMSFT** 2018-05-24 16:59 UTC
Labels: 1 - Ready, task
