### ISSUE TITLE
Nested TagHelpers of same Type cause ArgumentException (Key problem)

### ISSUE THREAD

**Issue by AvogadroSG1** [aspnet/Mvc#7606] opened 2018-04-06 12:54 UTC
**Nested Tag Helpers of the same type will cause an Argument Exception (Key Problem)**

**System**
.NET Core 2.1

**Description**
Using a TagHelper to create a Bootstrap 3.3.6 Panel:
```
    public class PanelContext
    {
        public IHtmlContent Body { get; set; }
        public IHtmlContent Footer { get; set; }
    }

    [RestrictChildren("panel-body", "panel-footer")]
    public class PanelTagHelper : TagHelper
    {
        public string PanelTitle { get; set; }
        public string PanelIcon { get; set; }
        public string PanelID { get; set; }
        public string PanelCSS { get; set; }

        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
            var panelContext = new PanelContext();
            context.Items.Add(typeof(PanelTagHelper), panelContext);

            await output.GetChildContentAsync();

            PanelCSS = string.IsNullOrEmpty(PanelCSS) ? "" : PanelCSS;

            string template = $@"<div class='panel-heading'>
                                        <div class='panel-title'><i class='{PanelIcon}'></i>&nbsp;{PanelTitle}
                                        </div>
                                    </div>
                                    ";
            

             

            //Set the TagHelper's Tag to a Div.
            output.TagName = "div";

            //Set the Tag's ID attribute.
            output.Attributes.SetAttribute("id", $@"{PanelID}");

            //Set the Tag's class attribute.
            output.Attributes.SetAttribute("class", $@"panel {PanelCSS}");

            //Add the Templated HTML
            output.Content.AppendHtml(template);

            if (panelContext.Body != null)
            {
                output.Content.AppendHtml(panelContext.Body);
            }
            if(panelContext.Footer != null)
            {
                output.Content.AppendHtml(panelContext.Footer);
            }
        }
    }
```

Nesting a panel like:
```
<panel panel-css="panel-default">
     <panel-body>
     @* Do some other stuff*@
          <panel panel-css="panel-default>
               <panel-body>
               @*Stuff*@
               </panel-body>
           </panel>
    </panel-body>
</panel>
```

This will generate:
```
ArgumentException: An item with the same key has already been added. Key: <Namespaceremoved>.TagHelpers.PanelTagHelper

Pertinent Trace Error: context.Items.Add(typeof(PanelTagHelper), panelContext);
```

I believe it's because there is already a context injected into the system and there is no unique identifier for these context.

Is this an error in my programming, or a bug with nesting taghelpers?

I can provide the Child TagHelpers if needed.

Thank you very much for your time.

**Comment by mkArtakMSFT** [comment] 2018-04-10 19:14
Thanks for contacting us, @AvogadroSG1. It would be great if you could share a sample project with a repro with us.

**Comment by AvogadroSG1** [comment] 2018-04-11 14:46
No problem!
Here you go!
[https://github.com/AvogadroSG1/taghelperbug](url)
Also Download attached.

[TagHelperBug.zip](https://github.com/aspnet/Mvc/files/1899297/TagHelperBug.zip)

**Comment by kishan3034** [comment] 2018-05-13 08:28
Hi @mkArtakMSFT and @AvogadroSG1,
I reproduce this bug. I felt there is no bug.  

**Root cause:**
key was added first time panel tag helper get called Process method .  when inner Panel tag helper get called same method again trying to add same key.

i changed your project. and please go through repository **[TagHelperBug](https://github.com/kishan3034/TagHelperBug)**

**Output:**
![image](https://user-images.githubusercontent.com/8208927/39964944-188f2db0-56ad-11e8-9e48-a88dd852a328.png)

**Comment by mkArtakMSFT** [comment] 2018-05-14 20:53
Thanks @kishan3034.

@AvogadroSG1, seems like this is an issue with your code, so we're closing this now.

**Closed by mkArtakMSFT** 2018-05-14 20:53 UTC
Labels: 1 - Ready, bug
