### ISSUE TITLE
Need support for specifying custom error message for type safety server validation 

### ISSUE THREAD

**Issue by apoorvg** [aspnet/Mvc#3662] opened 2015-11-30 11:25 UTC
There are some type safety validations applied during model binding. These validations result  into messages like "The value 'value' is not valid for fieldName". E.g. The value 'abc' is not valid for Age. 

Currently these message are coming from the MVC codebase itself. 

Is there a way to customize these message?

**Comment by dougbu** [comment] 2015-11-30 16:56
@apoorvg MVC supports customization of those messages through `IModelBindingMessageProvider`. The easiest way to change the delegates is in your `Startup` class: Update `MvcOptions.ModelBindingMessageProvider` e.g.
``` c#
    services.AddMvc(
        options => options.ModelBindingMessageProvider.MissingBindRequiredValueAccessor = Resources.FormatModelBinding_MissingBindRequiredMember);
```

**Comment by apoorvg** [comment] 2015-11-30 17:35
Thanks for the reply. 

I have already customized all the properties as provided by ModelBindingMessageProvider but still see few validation messages showing up as "The value 'abc' is not valid for Age", which is different from my customization. 

My scenario is:

    public class ModelName
    {
       public double PropertyName { get; set; }
 }

This property is bound to a text box using TagHelpers. If user enters a value as 'abc' in this textbox and on submitting (no client side validations) I get a validation message as "The value 'abc' is not valid for PropertyName". 

On further looking into MVC code, it seems the message is as per below resource string
/// <summary>
        /// The value '{0}' is not valid for {1}.
        /// </summary>
        internal static string FormatModelError_InvalidValue_MessageWithModelValue(object p0, object p1)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("ModelError_InvalidValue_MessageWithModelValue"), p0, p1);
        }

This message is applied in class SimpleTypeModelBinder while trying to do a ConvertTo operation. 

Assuming my understanding is correct, I was unable to find a way to customize this message. 

Let me know if I am missing something.

**Comment by dougbu** [comment] 2015-11-30 17:59
@apoorvg you're not missing anything. This report is a duplicate of #3215. That issue specifically calls out the message mentioned in your detailed comments.

**Comment by Eilon** [comment] 2015-11-30 20:06
Indeed, looks like a dup of https://github.com/aspnet/Mvc/issues/3215.

**Closed by Eilon** 2015-11-30 20:07 UTC
