### ISSUE TITLE
Unit Test Razor Pages PageModel, ModelState threw NullReferenceException

### ISSUE THREAD

**Issue by hinault** [aspnet/Mvc#7061] opened 2017-11-17 15:59 UTC
I want to write Uni test for my PageModel. Here is the method I want to test.

```cs
public class CreateModel : PageModel
    {
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            _context.Student.Add(Student);
            await _context.SaveChangesAsync();
            return RedirectToPage("./Index");
        }
    }

```
Here is my test code

```cs
  [TestMethod]
        public async Task OnPostAsync_ReturnPageResult()
        {
            //Arrange
            var createModel = new CreateModel(Context);
            createModel.Student = new RazorDemo.Models.Student();
            createModel.ModelState.AddModelError("FirstName", "Required");
            //Act
            var page = await createModel.OnPostAsync() as PageResult;
            //Assert
            Assert.IsNotNull(page);
        }
```

In MVC when I initialize a new Controller in my test method, the ModelState isn't not null, i can add ModelError like controller.ModelState.AddModelError("Email", "Required"). It isn't possible with Razor ModelPage because ModelState threw an exception .

![mock](https://user-images.githubusercontent.com/15146271/32955955-7fa0594c-cb85-11e7-80a2-ae542e5e4b72.png)

What is the best way to avoid this exception in my unit test?

**Comment by DamianEdwards** [comment] 2017-11-17 16:05
This is a duplicate of #6943 

We've fixed this for the next minor release, but for now you'll need to initialize the property value yourself in the unit test.

**Closed by DamianEdwards** 2017-11-17 16:05 UTC

**Comment by hinault** [comment] 2017-11-17 16:59
Thanks for your quick answer.

**Comment by jacqueskang** [comment] 2018-02-19 12:31
@DamianEdwards How can we initialize the ModelState please? It has no public setter.
