### ISSUE TITLE
Consider improving the syntax for FlushPoints

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#1080] opened 2014-08-29 16:54 UTC
Right now using FlushPoints look like this:

```HTML
</head>
@{ await FlushAsync(); }
...
```

The suggestion is to make it look nicer

```HTML
</head>
@await FlushAsync()
...
```

This would require returning a no-op value (`null` / empty `HelperResult`) from `FlushAsync`

**Comment by yishaigalatzer** [comment] 2015-01-12 21:58
Duplicate of #1547

**Closed** 2015-01-12 21:58 UTC
Labels: duplicate
