### ISSUE TITLE
Required Attribute ErrorMessage Property on Select tags

### ISSUE THREAD

**Issue by cdwlighting** [aspnet/Mvc#4169] opened 2016-02-26 19:03 UTC
I think I have a bug, although, it's possible it in my code as well... This is MVC 6.0.0-rc1-final.

I have a a Field with the Attribute [Required("Please select a Value to add to cart")], When I set an asp-for property on the select box for that field, the data-val-required property has a value of the name of the field, in this Amount.  I am not sure what I am doing wrong or if someone can recommend a work around.

Thanks,

**Comment by dougbu** [comment] 2016-02-26 20:11
@cdwlighting please describe your scenario a bit more. What platform are you seeing this on? If you're using Mono, which version?

If possible please the relevant snippets from your `.cshtml` file and the generated HTML.

**Comment by cdwlighting** [comment] 2016-02-26 20:27
@dougbu I have a field in my model marked:

```
   class model {
      [Required(ErrorMessage="Please Select Value")]
       public string Amount {get; set;}
      public IEnumerable<SelectListItem> Amounts { get; set; } 
    }
```
```
<select asp-for="Amount" asp-items="Amounts"></select>
```
 Rendered HTML
```
<select placeholder="Amount" class="form-control" data-val="true" data-val-required="Amount" id="cost" name="cost">
	<option value="" selected="" hidden="" disabled="">AMOUNT</option>
	<option value="$10{p:10}">$10.00</option>
</select>
```
Expected HTML
```
<select placeholder="Amount" class="form-control" data-val="true" data-val-required="Please Select Value" id="cost" name="cost">
	<option value="" selected="" hidden="" disabled="">AMOUNT</option>
	<option value="$10{p:10}">$10.00</option>
</select>
```
I have Created a Tag Helper, and have been following the construction of the client validation rules, and I think I have identified where the values are missing.

```
	var validationContext = new ClientModelValidationContext(				For.ModelExplorer.Metadata, _metadataProvider, ViewContext.HttpContext.RequestServices);			var validatorProviderContext = new ClientValidatorProviderContext(For.ModelExplorer.Metadata);
_clientModelValidatorProvider.GetValidators(validatorProviderContext);
var validators = validatorProviderContext.Validators;
/* This appears to be where things go side ways, v.GetClientValidationRules(validationContext).*/	
var validatorList = validators.SelectMany(v => v.GetClientValidationRules(validationContext));
```
validators has the ErrorMessage on it, and something is happening in GetclientValidationRules.  Again Not sure if it's something I have done in correctly, but that is where things appear to go sideways.


Thanks.

**Comment by dougbu** [comment] 2016-02-26 21:17
Does the problem you're describing occur when using the MVC `<select>` tag helper and not your custom one?

Separately where does `name="cost"` come from? Might not be related to this issue but looks a bit strange. Depending on how that's done, could lead to problems model binding or when the framework looks up errors.

**Comment by cdwlighting** [comment] 2016-02-26 21:20
I have tried both tag helpers.  It behaves the same way.  My tag helper is a copy of the regular tag helper.  Again, I have isolated the issue to that location I mentioned.

**Comment by dougbu** [comment] 2016-06-01 19:12
I'm not able to reproduce this with current `dev` code nor with `1.0.0-rc2-final`. With either version, the `<select>` tag helper generates
``` html
<select data-val="true" data-val-required="Please select value" id="Amount" name="Amount"><option value="">Amount</option>
<option value="$10.00{p:10}">$10.00</option>
<option value="$20.00{p:20}">$20.00</option>
<option value="$30.00{p:30}">$30.00</option>
</select>
```

The `GetClientValidationRules()` method went away between RC1 and RC2 (see aspnet/Announcements#179) and it's possible we fixed something in this area. But I suspect something else is going on. (For example MVC won't generate validation attributes if HTML fields for a particular property have already been generated within the current `<form>`.)

@cdwlighting please create a GitHub repo containing a simple project that reproduces your issue. Best if it's an RC2 project and does _not_ use your custom `<select>` tag helper (because you said that isn't relevant to this issue).

**Comment by dougbu** [comment] 2016-06-06 19:33
Closing for now. We have not received similar reports nor been able to reproduce this issue. Please reopen if you're still hitting it with RC2.

**Closed by dougbu** 2016-06-06 19:33 UTC
Labels: 2 - Working, investigate
