### ISSUE TITLE
Error of strong type parameter for custom taghelper

### ISSUE THREAD

**Issue by CN-jaycee** [aspnet/Mvc#3976] opened 2016-01-23 03:13 UTC
```
    <h1 editable-options="new EditableOptions {
    Placement =enumPlacementType.right,
    Title ="请输入专栏名"
         }"></h1>
```

An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.

```
/Views/Shared/Components/Header/Default.cshtml

Invalid expression term ';'
    Title ="请输入专栏名"
} expected
    Title ="请输入专栏名"
```

**Comment by NTaylorMullen** [comment] 2016-01-25 20:10
Hey @CN-jaycee, this is working as intended. What you're encountering is Razor's purposeful minimal  knowledge about C#. What's happening is it sees your `Title ="` and it thinks the `"` is ending your attribute. You can fix your problem by changing the attribute quotes to be single quoted `'`.

**Comment by Eilon** [comment] 2016-01-25 22:43
@NTaylorMullen where are you seeing extra double-quotes?

**Comment by NTaylorMullen** [comment] 2016-01-25 22:44
The `Title` value: `"请输入专栏名"`

**Comment by NTaylorMullen** [comment] 2016-01-25 23:19
Closing as by design. By the way you can also surround your attribute value in `@(...)` if you don't want to use single quotes :smile:

**Closed by NTaylorMullen** 2016-01-25 23:19 UTC
Labels: by design
