### ISSUE TITLE
Is RazorPages suposed to be detected by FileProviders on RazorViewEngineOptions?

### ISSUE THREAD

**Issue by bang75** [aspnet/Mvc#6489] opened 2017-07-03 21:29 UTC
I've tried to add an EmbeddedFileProvider but it doesn't seem to work...

**Comment by pranavkm** [comment] 2017-07-03 21:57
Do you have a repro application handy? Embedded FileProviders registerd with `RazorViewEngineOptions` should work with Razor Pages, but we don't have any test coverage for it.

**Comment by bang75** [comment] 2017-07-04 08:37
Hmm, just a thought: Maybe the EmbeddedFileProvider works and the problem is how MVC "detects" and routes to the razor pages?

Because putting a razor page in an external lib and embedding it + adding embeddedfileprovider doesn't work.

How are MVC discovering razor pages? And how are they routed, because it doesn't seems to happen in the normal router...

**Comment by pranavkm** [comment] 2017-07-04 14:49
I specifically added a test to verify if things work with an external lib and it does. A limitation of `EmbeddedFileProvider` is that it does not support directories. By default, Razor Pages scans for files under the `/Pages` directory so it never finds any files to compile. My guess is you're likely running in to this limitation. That said, I wouldn't have to guess if I had a repro app 😄

**Comment by bang75** [comment] 2017-07-04 15:31
Not sure I'm following here... 
When I use EmbeddedFileProvider with MVC views, folders works great.
Do you mean that all razor pages should be put in the root namespace of the lib with the embedded cshtml files? In that case it will not be possible to create an hierachy, of pages.

With repro app, do you mean if I have a sample of my problem on git hub :) ?

**Comment by bang75** [comment] 2017-07-05 08:42
Here is a sample app:
https://github.com/bang75/RazorPagesTest

**Comment by pranavkm** [comment] 2017-07-05 18:10
@bang75 - like I mentioned earlier, `EmbeddedFileProvider` does not support directories. Putting the files in a folder named `Pages` basically results in a file named `Pages.Index.cshtml` (not a file named `Index.cshtml` under the `Pages` directory). There are some solutions in https://github.com/aspnet/FileSystem/issues/184 that might help in this case. https://www.nuget.org/packages/Dazinator.AspNet.Extensions.FileProviders has an `InMemoryFileProvider` which also lets you construct a file provider from an arbitrary set of inputs.

**Comment by bang75** [comment] 2017-07-05 18:49
I'm aware of that the embedded directories results in "namespaces" instead of hiearchy, but I still don't understand why the EmbeddedFileProvider works perfectly with MVC views organized in folders but not razor pages.

**Comment by pranavkm** [comment] 2017-07-05 19:00
For views, Mvc requests for files `/Views/Home/Index.cshtml`. The `EmbeddedFileProvider` converts that to `View.Home.Index.cshtml` and can return it.
For Razor Pages, we have to perform a directory scan to look for all cshtml files with the `@page` directive for routing. For one, `EmbeddedFileProvider` does not support any directories other than `/`. We look for files under the `/Pages` directory which results in not finding any files to route to. 

I'd recommend looking at the couple of options I linked to above. Precompilation (https://github.com/aspnet/MvcPrecompilation#enabling-view-compilation) works with Razor Pages and you should be able to use that as an alternative to embedding files.

**Comment by bang75** [comment] 2017-07-05 20:02
Ok. Now I think I get it...
It's the GetDirectoryContents method thats causing trouble for the razor pages since it needs to get a list of available pages and EmbeddedFileProvider don't handle this, while MVC Views tries to find specific files when resolving a view and that works fine even with "folders" (/ will translate to .).

Right?

**Comment by pranavkm** [comment] 2017-07-05 21:16
@bang75 - yup that summarizes it correctly. Closing this work item since we've understood the root cause of the issue.

**Closed by pranavkm** 2017-07-05 21:16 UTC
Labels: investigate
