### ISSUE TITLE
TagHelper Intellisense not working in Area Views folder

### ISSUE THREAD

**Issue by svdoever** [aspnet/Mvc#6266] opened 2017-05-13 15:55 UTC
Using Visual Studio 2017, TagHelper intellisense works in the default Views folder, but it does not work in the Vieuws folder in an Area. See also: http://stackoverflow.com/questions/43269184/areas-view-tag-helper-intellisense-no-use-in-asp-net-core-vs2017#

**Comment by Eilon** [comment] 2017-05-13 22:48
@svdoever - are you using VS2017 RTM, or do you have Update 1, Update 2, or Update 3 Preview 1 installed? If you could show what's in VS's "Help/About" dialog that would be helpful!

@NTaylorMullen @rynowak - any ideas?

**Comment by rynowak** [comment] 2017-05-14 00:59
No idea off the cuff, we need to try this out and see if we can reproduce it.

**Comment by jingliancui** [comment] 2017-05-15 07:27
resolve is by just add this code at the top of the cshtml file:

    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

**Comment by svdoever** [comment] 2017-05-15 20:03
Don't know what changed, but the intellisense works now as advertised. Sorry for my mistake.

**Comment by wgutierrezr** [comment] 2017-06-07 11:34
I have the same problem. Reading this post it means I have to add "@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers" to all my .cshtml files within the Areas folder? OMG!
(It comes already in _ViewImport.cshtml by default in ASP.Net Core 1.1).

**Comment by Eilon** [comment] 2017-06-07 15:25
@wgutierrezr I don't think that's the intended behavior, but there might be a bug that we fixed in that scenario that perhaps isn't available publicly yet.

@rynowak - thoughts?

**Comment by NTaylorMullen** [comment] 2017-06-07 18:13
If you have a `_ViewImports.cshtml` file within your Areas folder that has the `@addTagHelper`, that should work.

**Comment by rynowak** [comment] 2017-06-26 00:07
There should be no change here to how this behaves in 2.0.0. You need to have an `@addTagHelper` in scope in your views. 

I'm going to close this issue again since it's not clear what exactly it's tracking. If anyone is having a similar problem please open a new issue and provide a clear description of what is happening.

**Closed by rynowak** 2017-06-26 00:07 UTC
Labels: investigate
