### ISSUE TITLE
dotnet myAspNetCoreApp.dll fails with no error message

### ISSUE THREAD

**Issue by LeslieMurphy** [aspnet/Mvc#8122] opened 2018-07-20 18:22 UTC
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
I deployed an ASP.NET Core 2.0 app (using EF) to a user's desktop for testing, using Folder deploy to create a framework dependent set of files.

Edited the appsettings.json to change our DB connection string.  I mistakenly placed in code like this:

"ConnectionStrings": {
    "DefaultConnection": "Server=(.\SQLEXPRESS;Database=xxx;Trusted_Connection=True;MultipleActiveResultSets=true",
  },

The use of a single backslash in the default connection string caused asp.net core to fail to start up and not issue any error messages.  use of  two slashes \ \SQLEXPRESS allowed the app to startup just fine

I was using **dotnet myApp.dll** from the commandline

No log files were generated

#### Description of the problem:

Invalid entry in appsettings.json causes dotnet command to fail without any error message

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

Microsoft.AspNetCore.All 2.0.0
Microsoft.EntityFrameworkCore.Toolsl 2.0.0

**Comment by Eilon** [comment] 2018-07-20 18:36
Hi @LeslieMurphy , can you show what the Program.cs and Startup.cs look like? Then we can try to reproduce this and get to the bottom of it. Thanks!

**Comment by LeslieMurphy** [comment] 2018-07-20 18:44
Sure, thanks! 

 

Program.cs

 

using System;

using Microsoft.AspNetCore;

using Microsoft.AspNetCore.Hosting;

using Microsoft.Extensions.Configuration;

using Microsoft.Extensions.DependencyInjection;

using HCM_Xpert.Data;

using Microsoft.AspNetCore.Identity;

using HCM_Xpert.Models;

using NLog.Web;

 

namespace HCM_Xpert

{

    public class Program

    {

       

        public static void Main(string[] args)

        {

            // NLog: setup the logger first to catch all errors

            var logger = NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();

            try

            {

                var host = BuildWebHost(args);

                using (var scope = host.Services.CreateScope())

                {

                    var services = scope.ServiceProvider;

                    try

                    {

                        var appDBcontext = services.GetRequiredService<ApplicationDbContext>();

                        DbInitializer.Initialize(appDBcontext, services.GetRequiredService<UserManager<ApplicationUser>>());

                    }

                    catch (Exception ex)

                    {

                        logger.Error(ex, "An error occurred while seeding the database.");

                    }

                }

                host.Run();

                logger.Debug("Host stated");

            }catch (Exception e)

            {

                logger.Error(e, "Startup failed with fatal error: " + e.Message);

            }

        }

 

        public static IWebHost BuildWebHost(string[] args) =>

            WebHost.CreateDefaultBuilder(args)

                .UseStartup<Startup>()

             .ConfigureAppConfiguration((builderContext, config) =>

             {

                 IHostingEnvironment env = builderContext.HostingEnvironment;

 

                 config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)

                     .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);

             })

               .UseNLog()

                .Build();

    }

}

 

Startup.cs

 

using System;

using Microsoft.AspNetCore.Builder;

using Microsoft.AspNetCore.Identity;

using Microsoft.EntityFrameworkCore;

using Microsoft.AspNetCore.Hosting;

using Microsoft.Extensions.Configuration;

using Microsoft.Extensions.DependencyInjection;

using HCM_Xpert.Data;

using HCM_Xpert.Models;

using HCM_Xpert.Services;

using Newtonsoft.Json.Serialization;

 

namespace HCM_Xpert

{

    public class Startup

    {

        public Startup(IConfiguration configuration)

        {

            Configuration = configuration;

        }

 

        public IConfiguration Configuration { get; }

 

        // This method gets called by the runtime. Use this method to add services to the container.

        public void ConfigureServices(IServiceCollection services)

        {

            //Configure Email sender

            services.Configure<EmailSettings>(Configuration.GetSection("EmailSettings"));

            services.AddDbContext<ApplicationDbContext>(options =>

                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

 

            services.AddIdentity<ApplicationUser, IdentityRole>()

                .AddEntityFrameworkStores<ApplicationDbContext>()

                .AddDefaultTokenProviders();

 

            // Add application services.

            services.AddTransient<IEmailSender, EmailSender>();

            services.AddTransient<IProjectActivityLogger, ProjectActivityLogger>();

            services.AddTransient<IProjectDBManager,ProjectMSSDBManager>();

            services.AddTransient<IHCMEngineServices, HCMEngineServices>();

            services.AddMvc().AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());

            // Adds a default in-memory implementation of IDistributedCache.

            services.AddDistributedMemoryCache();

 

            services.AddSession(options =>

            {

                options.IdleTimeout = TimeSpan.FromMinutes(20);

                options.Cookie.HttpOnly = true;

            });

            services.AddAuthentication().Services.ConfigureApplicationCookie(options =>

            {

            options.SlidingExpiration = true;

            options.ExpireTimeSpan = TimeSpan.FromMinutes(20);

 

            });

 

        }

 

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)

        {

         

            if (env.IsDevelopment())

            {

                app.UseDeveloperExceptionPage();

                app.UseBrowserLink();

                app.UseDatabaseErrorPage();

            }

            else

            {

                app.UseExceptionHandler("/Home/Error");

            }

 

            app.UseSession();

 

            app.UseStaticFiles();

 

            app.UseAuthentication();

 

            app.UseMvc(routes =>

            {

                routes.MapRoute(

                    name: "default",

                    template: "{controller=Home}/{action=Index}/{id?}");

            });

        }

    }

}

 

nlog.config

 

<?xml version="1.0" encoding="utf-8" ?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"

      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

      autoReload="true"

      internalLogLevel="info"

      throwExceptions="true"

      internalLogFile="c:\logs\internal-nlog.txt">

  

  <extensions>

    <add assembly="NLog.MailKit"/>

</extensions>

  

    

    

    <targets async="true">

       

    <target xsi:type="File" name="alllogs" fileName="c:\logs\microsoftLogs-${shortdate}.log"

            layout="${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|${message} ${exception}" />

 

    

    <target xsi:type="File" name="hcmxpert" fileName="c:\logs\hcmexpertLogs-${shortdate}.log"

            layout="${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|${message} ${exception}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}| user: ${aspnet-user-identity:}" />

      

      <target name="supportMail" xsi:type="Mail"

            smtpServer="smtp.gmail.com"

            smtpPort="465"

            enableSsl="true"

            smtpAuthentication="Basic"

            smtpUserName="xxxxx@xxx.com"

            smtpPassword="xxxxxx"

            from="xxx@xxx.com"

            to="xxxxxx@outlook.com"

            subject="xxxx Critical Error"

            body="

                    Time: ${longdate}${newline}

                    EventID: ${event-properties:item=EventId.Id}${newline}

                    url: ${aspnet-request-url}${newline}

                    action: ${aspnet-mvc-action}${newline}

                    user: ${aspnet-user-identity:}

                    Level: ${uppercase:${level}}${newline}

                    Message:${message} ${exception}${newline}             

             "

          />

      

 

    

    <target xsi:type="Null" name="blackhole" />

  </targets>

 

  

  <rules>

    

    <logger name="*" minlevel="Trace" writeTo="alllogs" />

 

    

    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />

    <logger name="*" minlevel="Trace" writeTo="hcmxpert" />

    

  </rules>  

 

  </nlog>

**Comment by Eilon** [comment] 2018-07-20 20:18
Thank you @LeslieMurphy .

@divega / @ajcvickers - do you know if calling EF's `options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));` with some slightly invalid data for the ConnectionString would cause some fatal exception at startup time?

@LeslieMurphy - perhaps you can also help try to debug this by wrapping that line of code in a try/catch and see if that throws an exception? (E.g. print it out to the console.)

**Comment by LeslieMurphy** [comment] 2018-07-20 20:53
Thanks.

 

Adding that try/catch does not catch anything.

 

But running in the debugger, I can now see that the issue is related somehow to flushing logger buffers.  The “Startup failed with fatal” message does not get logged when I use dotnet xxx.dll:

 

The message that is generated is actually a very good one – it just never made it to the console, grrrr:

 

"Could not parse the JSON file. Error on line number '3': '\"ConnectionStrings\": {\r\n\"DefaultConnection\": \"Server=(localdb)\\mssqllocaldb;Database=aspnet-HCM_Xpert-116458AF-DBAC-4175-BECB-CAEED9AC23FF;Trusted_Connection=True;MultipleActiveResultSets=true\ <file:///\\mssqllocaldb;Database=aspnet-HCM_Xpert-116458AF-DBAC-4175-BECB-CAEED9AC23FF;Trusted_Connection=True;MultipleActiveResultSets=true\> ",'."

 

 

try

            {

                var host = BuildWebHost(args);

                using (var scope = host.Services.CreateScope())

                {

                    var services = scope.ServiceProvider;

                    try

                    {

                        var appDBcontext = services.GetRequiredService<ApplicationDbContext>();

                        DbInitializer.Initialize(appDBcontext, services.GetRequiredService<UserManager<ApplicationUser>>());

                    }

                    catch (Exception ex)

                    {

                        logger.Error(ex, "An error occurred while seeding the database.");

                    }

                }

                host.Run();

                logger.Debug("Host stated");

            }catch (Exception e)

            {

                logger.Error(e, "Startup failed with fatal error: " + e.Message);

            }

**Comment by Eilon** [comment] 2018-07-21 00:02
Ah, interesting. Any chance you can paste the full stack trace for it? That will help me redirect this issue to the right part of the team.

**Comment by Eilon** [comment] 2018-07-21 00:02
Tagging @HaoK because this might end up for you to investigate.

**Comment by mkArtakMSFT** [comment] 2018-07-23 16:37
Moving this to the `aspnet/hosting` repo to find out why no exceptions are logged before crashing the app.

**Comment by mkArtakMSFT** [comment] 2018-07-23 16:38
This issue was moved to aspnet/Hosting#1500

**Closed by mkArtakMSFT** 2018-07-23 16:38 UTC
Labels: investigate
