### ISSUE TITLE
Complex types implementing IValidatableObject is not being validated correctly

### ISSUE THREAD

**Issue by dopare** [aspnet/Mvc#7443] opened 2018-03-06 07:09 UTC
I have following models and action in my test application based on 2.1.0-preview-final1.

`SuppressModelStateInvalidFilter` is `true`

``` C#
public class Parent : IValidatableObject
{
    public string ParentName { get; set; }

    public Child Child { get; set; }

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (ParentName == null)
        {
            yield return new ValidationResult("ParentName is null");
        }
    }
}

public class Child : IValidatableObject
{
    public string ChildName { get; set; }

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (ChildName == null)
        {
            yield return new ValidationResult("ChildName is null");
        }
    }
}

[HttpPost("~/validate")]
public ActionResult Index([FromBody]Parent parent)
{
    return Json(new
    {
        IsValid = ModelState.IsValid,
        Errors = ModelState.Select(s => s.Value)
    });
}
```
If I post following JSON payload:
```
{
	"ParentName1": "parent",
	"Child": {
		"ChildName1": "child",
	}
}
```
result is 
```
{
    "isValid": false,
    "errors": [
        {
            "childNodes": null,
            "children": null,
            "key": "Child",
            "subKey": {
                "buffer": "Child",
                "offset": 0,
                "length": 5,
                "value": "Child",
                "hasValue": true
            },
            "isContainerNode": false,
            "rawValue": null,
            "attemptedValue": null,
            "errors": [
                {
                    "exception": null,
                    "errorMessage": "ChildName is null"
                }
            ],
            "validationState": 1
        }
    ]
}
```
But if I remove `IValidatableObject` and add `[Required]` attributes to string properties then I'm getting following repsonse on same JSON payload:
```
{
    "isValid": false,
    "errors": [
        {
            "childNodes": null,
            "children": null,
            "key": "ParentName",
            "subKey": {
                "buffer": "ParentName",
                "offset": 0,
                "length": 10,
                "value": "ParentName",
                "hasValue": true
            },
            "isContainerNode": false,
            "rawValue": null,
            "attemptedValue": null,
            "errors": [
                {
                    "exception": null,
                    "errorMessage": "The ParentName field is required."
                }
            ],
            "validationState": 1
        },
        {
            "childNodes": null,
            "children": null,
            "key": "Child.ChildName",
            "subKey": {
                "buffer": "Child.ChildName",
                "offset": 6,
                "length": 9,
                "value": "ChildName",
                "hasValue": true
            },
            "isContainerNode": false,
            "rawValue": null,
            "attemptedValue": null,
            "errors": [
                {
                    "exception": null,
                    "errorMessage": "The ChildName field is required."
                }
            ],
            "validationState": 1
        }
    ]
}
```
## My little investigation

Issue #7014 was fixed by #7075 PR which added new [`ValidateComplexTypesIfChildValidationFails`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Validation/ValidationVisitor.cs#L76) property to `ValidationVisitor` class to allow [validate parent](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Validation/ValidationVisitor.cs#L243-L244) even if one of children has failed. 
Code in PR was designed to solve issue by allowing to create custom class implementing `IObjectModelValidator` and by setting this new property to true. But `ParameterBinder` class which was using `IObjectModelValidator` to validate model has marked `IObjectModelValidator` as [obsolete](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ParameterBinder.cs#L82-L84) and now directly [uses](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ParameterBinder.cs#L324) `ValidationVisitor`. This [code](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L245) shows that framework stopped using obsolete constructors to create `ParameterBinder`.

**Comment by dougbu** [comment] 2018-03-06 16:52
>  `ParameterBinder` class which was using `IObjectModelValidator` to validate model has marked `IObjectModelValidator` as [obsolete](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ParameterBinder.cs#L82-L84) and now directly [uses](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ParameterBinder.cs#L324) `ValidationVisitor`. This [code](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L245) shows that framework stopped using obsolete constructors to create `ParameterBinder`.

This is #7413. @dopare is there anything in this issue that won't go away once we fix #7413?

**Comment by dopare** [comment] 2018-03-06 17:01
@dougbu I am not sure about it.
I have injected custom instance of `ParameterBinder` with my custom `IObjectModelValidator` into DI and my action returned result with duplicate errors:

```
{
    "isValid": false,
    "errors": [
        {
            "childNodes": [
                {
                    "childNodes": null,
                    "children": null,
                    "key": "Child",
                    "subKey": {
                        "buffer": "Child",
                        "offset": 0,
                        "length": 5,
                        "value": "Child",
                        "hasValue": true
                    },
                    "isContainerNode": false,
                    "rawValue": null,
                    "attemptedValue": null,
                    "errors": [
                        {
                            "exception": null,
                            "errorMessage": "ChildName is null"
                        }
                    ],
                    "validationState": 1
                }
            ],
            "children": [
                {
                    "childNodes": null,
                    "children": null,
                    "key": "Child",
                    "subKey": {
                        "buffer": "Child",
                        "offset": 0,
                        "length": 5,
                        "value": "Child",
                        "hasValue": true
                    },
                    "isContainerNode": false,
                    "rawValue": null,
                    "attemptedValue": null,
                    "errors": [
                        {
                            "exception": null,
                            "errorMessage": "ChildName is null"
                        }
                    ],
                    "validationState": 1
                }
            ],
            "key": "",
            "subKey": {
                "buffer": "",
                "offset": 0,
                "length": 0,
                "value": "",
                "hasValue": true
            },
            "isContainerNode": false,
            "rawValue": null,
            "attemptedValue": null,
            "errors": [
                {
                    "exception": null,
                    "errorMessage": "ParentName is null"
                }
            ],
            "validationState": 1
        },
        {
            "childNodes": null,
            "children": null,
            "key": "Child",
            "subKey": {
                "buffer": "Child",
                "offset": 0,
                "length": 5,
                "value": "Child",
                "hasValue": true
            },
            "isContainerNode": false,
            "rawValue": null,
            "attemptedValue": null,
            "errors": [
                {
                    "exception": null,
                    "errorMessage": "ChildName is null"
                }
            ],
            "validationState": 1
        }
    ]
}
```

**Comment by dougbu** [comment] 2018-03-06 17:20
@dopare your replacement `ParameterBinder` is doing something wrong with the `ModelState` keys. Should be no `""` or `"Child"` keys, just `"ParentName"` and `"Child.ChildName"`.

**Comment by dopare** [comment] 2018-03-06 17:25
@dougbu I'm using `CustomObjectValidator` class used in unit test of #7075 PR

``` C#
public class CustomObjectValidator : IObjectModelValidator
{
    private readonly IModelMetadataProvider _modelMetadataProvider;
    private readonly IList<IModelValidatorProvider> _validatorProviders;
    private ValidatorCache _validatorCache;
    private CompositeModelValidatorProvider _validatorProvider;

    public CustomObjectValidator(IModelMetadataProvider modelMetadataProvider, IList<IModelValidatorProvider> validatorProviders)
    {
        _modelMetadataProvider = modelMetadataProvider;
        _validatorProviders = validatorProviders;
        _validatorCache = new ValidatorCache();
        _validatorProvider = new CompositeModelValidatorProvider(validatorProviders);
    }

    public void Validate(ActionContext actionContext, ValidationStateDictionary validationState, string prefix, object model)
    {
        var visitor = new ValidationVisitor(
            actionContext,
            _validatorProvider,
            _validatorCache,
            _modelMetadataProvider,
            validationState);

        var metadata = model == null ? null : _modelMetadataProvider.GetMetadataForType(model.GetType());
        visitor.ValidateComplexTypesIfChildValidationFails = ValidateComplexTypesIfChildValidationFails;
        visitor.Validate(metadata, prefix, model);
    }
  
    public bool ValidateComplexTypesIfChildValidationFails { get; set; }
}
```
Injection setup:
``` C#
services.AddSingleton(s =>
{
    var options = s.GetRequiredService<IOptions<MvcOptions>>().Value;
    var loggerFactory = s.GetRequiredService<ILoggerFactory>();
    var metadataProvider = s.GetRequiredService<IModelMetadataProvider>();
    var modelBinderFactory = s.GetRequiredService<IModelBinderFactory>();
    var modelValidatorProvider = new CompositeModelValidatorProvider(options.ModelValidatorProviders);
    return new ParameterBinder(metadataProvider, modelBinderFactory, new CustomObjectValidator(metadataProvider, options.ModelValidatorProviders)
    {
        ValidateComplexTypesIfChildValidationFails = true
    });
});
```

**Comment by dougbu** [comment] 2018-03-06 17:50
@dopare I wouldn't read to much into that unit test's `CustomObjectValidator` nor what `ParameterBinder` does when you use its `[Obsolete]` constructor. Our intent in #7413 is to restore the previous `IObjectModelValidator` workings.

**Comment by dopare** [comment] 2018-03-06 18:54
I think the core issue is still valid even if we forget that `IObjectModelValidator` exists.

**Comment by mkArtakMSFT** [comment] 2018-03-12 17:26
Hi @dopare. Thanks for reaching out to us. We're closing this issue as it seems the referenced fix we're working on will fix this too. If the behavior you're observing won't be fixed after our fix, please file a new issue or just reopen this issue, so we can investigate further.

**Closed by mkArtakMSFT** 2018-03-12 17:27 UTC

**Comment by dougbu** [comment] 2018-03-12 23:39
Ooops, my apologies. This is a duplicate of #7412, not #7413. #7412 is about `IObjectModelValidator` and how it's used.
