### ISSUE TITLE
Add a File method overload on controller and pages.

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#7232] opened 2018-01-11 17:28 UTC
This method (and its associated action result) will perform content negotiation, serialize the object with a formatter and set the content disposition header.

This is useful when the object being sent to the client is the in memory representation of a document and you want the client to download the document.

**Comment by mkArtakMSFT** [comment] 2018-01-11 17:41
@javiercn, we need more details on this. Isn't this what you get with standard action methods - which by-default get content negotiation enabled?

**Comment by javiercn** [comment] 2018-01-11 17:51
@mkArtakMSFT With standard action methods you only get content-negotiation, but you still have to set the content-disposition header yourself on the response. This overload streamlines that.

```charp
FileResult(object file, string fileName, string contentType)
```

```charp
public class ObjectFileResult : ObjectResult
{
    public string FileName { get; set; }
    public string ContentType { get; set; }

    public void override OnFormatting(ActionContext context)
    {
        SetStatusCode();
        SetContentType();
        SetContentDispositionHeader();
    }
}

**Comment by rynowak** [comment] 2018-01-11 21:57
@javiercn is this a dupe of https://github.com/aspnet/Mvc/issues/6260 ?

**Comment by javiercn** [comment] 2018-01-11 23:01
@rynowak Nope. The moral equivalent of that without the json convert https://github.com/aspnet/Identity/pull/1559/files#diff-c797f826e471413030a3cace8d328ee8R38

**Comment by mkArtakMSFT** [comment] 2018-05-14 21:36
Closing this issue as there was no community ask for this.

**Closed by mkArtakMSFT** 2018-05-14 21:36 UTC
Labels: 1 - Ready, enhancement
