### ISSUE TITLE
Razor Page Paramaters pick up other pages route data 

### ISSUE THREAD

**Issue by ghstahl** [aspnet/Mvc#7857] opened 2018-06-02 19:36 UTC
#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):
[buildable project](https://github.com/ghstahl/AspNet-Core2-Page-Route-Problem/tree/master/src/PageRouteIssue)  

1. Out-of-the-box asp.net core2.1 WebApplication
2. Add the following to contacts.cshtml and about.cshtml
```
@page "{id?}"
```
3. Route to;
```
https://localhost:44306/About/hello
```
4. Now click on "Contacts" in the NavBar.

You will be routed to 
```
https://localhost:44306/Contact/hello
```
The link in _layout.cshtml was not changed and is as follows;
```
 <li><a asp-page="/Contact">Contact</a></li>
```

Why is it picking up an url parameter that was never explicitly asked for.
i.e what is that /hello doing there?

#### Description of the problem:
Adding the following;
```
@page "{id?}"
```
to the top of a page causes it to pick up the route of other pages.

#### Version of  

'Microsoft.NETCore.App': 2.1
'Microsoft.AspNetCore.App': 2.1

**Comment by mkArtakMSFT** [comment] 2018-06-04 16:50
Thanks for contacting us, @ghstahl.
@kichalla, can you please look into this?

**Comment by kichalla** [comment] 2018-06-04 17:36
@ghstahl What you are seeing is the use of 'ambient' route values when links are generated. Here 'About' and 'Contact' pages both have the same route parameter name 'id', so when you visit 'Contact' page with 'id=100', the generated link for 'About' also looks like 'About/100'. This works well in scenarios for example if you have a Create, Details, Edit and Delete pages for a Customer model where when you visit a 'Customers/Details/100' you also get links like 'Customers/Edit/100' and 'Customers/Delete/100'. 

So to conclude, what you are seeing is by design.

**Comment by ghstahl** [comment] 2018-06-04 20:18
I think that this design is taking a pretty liberal approach that is sweeping up pages that have nothing to do with each other.  Just because they look like each other doesn't make them part of the same group.

I would argue that the example you gave is too magical in its assumptions.  I personally would even push back on the Customer/Details/100, etc. effect.

btw: 
I changed the contacts.cshtml to 
```
@page "{contactId?}"  // I hope nobody else on my team uses {contactId}!
```
but that isn't what I should have to do to indicate isolation of pages.  I can't be telling developers to make sure their pages don't look like other pages.  It will become a real headache to track down issues.

**Comment by kichalla** [comment] 2018-06-07 17:16
Thanks @ghstahl. We are considering your feedback for our next release's work on Dispatcher. Tracking item: https://github.com/aspnet/Routing/issues/531#issuecomment-395497757

**Comment by kichalla** [comment] 2018-06-07 17:19
Closing this issue. The work related to this can be tracked using https://github.com/aspnet/Routing/issues/531

**Closed by kichalla** 2018-06-07 17:19 UTC
Labels: cost: XS, investigate, needs design
