### ISSUE TITLE
Assembly with same name is already loaded, but the Assemblies have different names

### ISSUE THREAD

**Issue by rschaar** [aspnet/Mvc#5177] opened 2016-08-23 10:45 UTC
Hello everybody,

i have the following issue.

My Project "AspNetCoreApplicationParts" is modulary. Now i'm loading the modulary classlibary "AspNetCoreApplicationParts.Core" dynamically into my project with a AssemblyLoadContext.Default.LoadFromAssemblyPath(path).

```
        Assembly newAssembly = null;
        try
        {
            newAssembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(path);
        }
        catch (FileLoadException myE)
        {
            Console.WriteLine(myE.Message);
        }
```

That's okay, but when i loading another different classlibary "AspNetCoreApplicationParts.Module.Core", the system says into a exception "Assembly with same name is already loaded". the first classlibary has a different namespaces and the DLL has already different filename opposite to the second classlibary.

I'm using the dependencies "Microsoft.AspNetCore.Mvc.**" with version 1.1.0-**

is this issue known? How can i solving this issue?

best regards Robert.

**Comment by Eilon** [comment] 2016-09-29 06:38
@rschaar can you provide a bit more detail on what your app's structure is? Can you upload a repro project to GitHub for us to look at?

**Comment by Eilon** [comment] 2016-11-28 07:51
Closing because we don't have enough information to reproduce this.

**Closed by Eilon** 2016-11-28 07:51 UTC
