### ISSUE TITLE
Component.InvokeAsync add <b> tag

### ISSUE THREAD

**Issue by toben** [aspnet/Mvc#6625] opened 2017-08-03 13:50 UTC
Hello,

I am using Bootstrap for my web application. All was working until I added ViewComponent.
When I use it like that :
`@await Component.InvokeAsync(nameof(Plan), new { tenantId = Model.Id })`

It adds a lots of `<b>` tag everywhere in my DOM...

For example, before my viewcomponents, I have my <script> tags before <body>.
After adding ViewComponents, I have this :

```html
<b>
     <script src="/lib/jquery/dist/jquery.min.js"></script>
     <script src="/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/lib/fastclick/lib/fastclick.js"></script>
    ...
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
        <script src="/lib/gentelella/build/js/custom.js"></script>
        <script src="/js/site.js?v=ZV_DPK5Ua3OKyHELSc4meZGKSEncbBSrL2mEJIUmxh4"></script>
<script type="text/javascript">
</script>
</b>
```

I need help to remove that `<b>` tags because I can't use the Tab feature from Bootstrap for example because my DOM is not "normal".

**Comment by pranavkm** [comment] 2017-08-03 16:18
Could you share your application or a minimal repro with us?

**Comment by rynowak** [comment] 2017-08-03 17:25
This looks like a view that your view component is running is pulling in your layout.

**Comment by Eilon** [comment] 2017-08-04 16:49
@toben please share a repro app on GitHub that demonstrates this and we will investigate.

**Comment by Eilon** [comment] 2017-08-15 20:32
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2017-08-15 20:32 UTC
