### ISSUE TITLE
Error on response rc1

### ISSUE THREAD

**Issue by gvx111** [aspnet/Mvc#3253] opened 2015-10-04 00:36 UTC
on running controller /home/index showing this error
<pre>ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'.
Parameter name: bytes
System.Text.Encoding.ThrowBytesOverflow()</pre>

Error 2
<pre>Unhandled Exception: System.InvalidOperationException: A LeasedArraySegment was
collected without being returned to the pool. This is a memory leak.
   at Microsoft.Framework.MemoryPool.DefaultArraySegmentPool`1.DefaultLeasedArra
ySegment.Finalize()</pre>

**Comment by rynowak** [comment] 2015-10-04 04:45
Closing as dupe of #3252

**Closed by rynowak** 2015-10-04 04:45 UTC
