### ISSUE TITLE
Bootstrap Checkbox does not work well with input Tag Helper

### ISSUE THREAD

**Issue by johnciliberti** [aspnet/Mvc#2642] opened 2015-06-02 03:48 UTC
Here is the standard example checkbox from the Bootstrap website
```
<div class="checkbox">
  <label>
    <input type="checkbox" value="">
    Option one
  </label>
</div>
```

If a have a model name Contact as shown below
```
public class Contact
 {
        [Required]
        [EmailAddress]
        [StringLength(maximumLength: 50, MinimumLength = 5)]
        public string Email { get; set; }

        [Display(Name="Allow Us to send you SPAM?")]
        public bool AllowContactAboutOffers { get; set; }

 }
```
In my view I have the following which emulates what is on the bootstrap sample page but uses the Input Tag Helper `asp-for` attribute.

```
<div class="checkbox">
        <label asp-for="AllowContactAboutOffers">
            <input asp-for="AllowContactAboutOffers"  />
        </label>
</div>
```

What I think most developers would expect from this markup is content rendered as follows:

```
<div class="checkbox">
        <label for="AllowContactAboutOffers">
            <input id="AllowContactAboutOffers" name="AllowContactAboutOffers" type="checkbox" value="true" /><input name="AllowContactAboutOffers" type="hidden" value="false" />
Allow Us to send you SPAM?
        </label>
    </div>

```

But instead you get the following. Note that the text for the label is missing.
```
<div class="checkbox">
        <label for="AllowContactAboutOffers">
            <input id="AllowContactAboutOffers" name="AllowContactAboutOffers" type="checkbox" value="true" /><input name="AllowContactAboutOffers" type="hidden" value="false" />
        </label>
    </div>

```
It seems like the issue only occurs when you nest the input inside the label as they do on the Bootstrap example website. If you change the markup like below it works Ok.
 ```
<div class="checkbox">
        <label asp-for="AllowContactAboutOffers">
        </label>
       <input asp-for="AllowContactAboutOffers"  />
</div>
```

**Comment by dougbu** [comment] 2015-06-02 03:57
Thanks @johnciliberti for the additional information on #2369 and the inspiration to update the title of that issue. This one is a duplicate of that earlier issue so I'm closing it.

**Closed by dougbu** 2015-06-02 03:57 UTC
